### ISSUE TITLE
pgbouncer config raises error  connection problem: pq: SET failed

### ISSUE THREAD

**Issue by seadba** [cybertec-postgresql/pgwatch2#102]
Hello - i am running pgwatch2 on docker v17.05  on rh7  - everything works perfectly for my db's - when i try to configure pgbouncer  monitoring i get the following message in the log

2018/08/17 16:49:49 ERRO main: could not start metric gathering for DB "pgbouncer11_pgbouncer" due to connection problem: pq: SET failed

versions

pgbouncer version 1.9.0

{"pgwatch2_git_version": "9eb5ac699df9873d2138f94dc35e1ba509dd82a6",
 "grafana": "Version 5.2.2 (commit: aeaf7b2)", 
"postgres": "PostgreSQL 9.5.13 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit",
 "influxdb": "InfluxDB v1.6.0 (git: 1.6 62ab18a0f43ee342b84debaaae5486b8b2d8682c)"}

this is not a huge issue, and probably a configuration problem on my end - so no urgency at all - this is a fantastic tool. 

thanks

**Comment by seadba** [comment]
also preset config is set to pgbouncer

**Comment by kmoppel** [comment]
Hi!
Not 100% sure what is the real cause (have not tried it with the new 1.9.0 version also)...but only SET command going to pgbouncer is "SET statement_timeout"...which is actually not needed...so turned it off now. Please re-try with the lastest image and let me know if it helped.

**Comment by kmoppel** [comment]
Also make sure that you set the "DB dbname" field correctly - it should contain the pgbouncer pool name you want statistics for!

**Comment by seadba** [comment]
ok, thanks for the quick response - i assume not setting the db name was why it generated multiple connectors   - will try with latest versin - thanks again  - will update asap

**Comment by seadba** [comment]
ok, i grabbed the latest version - looks like its working correctly - still created multiple targets but it seems ok - i assume it either takes that from the # of db's defined? it doesnt read pgbouncer config files correct?

**Comment by kmoppel** [comment]
@seadba good, some progress :) didn't get the "multiple targets" part though...did pgwatch create many entries with one click??  and correct, pgwatch  doesn't read any config files, it doesn't have access to machines also - all communication happens over the postgres protocol.

**Comment by seadba** [comment]
ok, here was my problem - 2 actually - i used the pgbouncer host/port to create the first reference, and did not add a dbname - thats when i get  Warning! Some DBs not added as already under monitoring: btpg10, btpg11, btpg113, btpg96   - and 3 more collectors were created - i misread your post above and the info button about the dbname field( "NB! if left empty for 'postgres' , all db's from the cluster will be added,prefixed with the "Unique Name")   - the other mistake was using the port/host of the pgbouncer, not the db server - so i now have 4 pgbouncer collectors for 6 instances - i think its working as expected - the error was on my end - i really apprecate the help - great tool - thanks again
