### ISSUE TITLE
Collect data on disk I/O

### ISSUE THREAD

**Issue by vitabaks** [cybertec-postgresql/pgwatch2#105]
**Thank you for these metric fetching helpers:**
psutil_cpu.sql
psutil_mem.sql
psutil_disk.sql

I would like to also collect data on disk I/O. For each disk in my system (or data_directory/tablespaces).

**read_bytes**: number of bytes read
**write_bytes**: number of bytes written
**read_time**:  time spent reading from disk (in milliseconds)
**write_time**:  time spent writing to disk (in milliseconds)
**busy_time**:  time spent doing actual I/Os (in milliseconds)

https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters

**Comment by kmoppel** [comment]
You're welcome:) About the IO topic - I looked into this a bit also...but found that it would need quite some code if one does not want to include disks that are not part of PG setup.  So any help / PR-s would be very welcome on how to match the paths and info from psutil...

**Comment by kmoppel** [comment]
In [2]: **psutil.disk_io_counters(perdisk=True)**
Out[2]: 
{'dm-0': sdiskio(read_count=301455, write_count=442043, read_bytes=21665231872, write_bytes=808486400000, read_time=491288, write_time=39884064, read_merged_count=0, write_merged_count=0, busy_time=333924),
 'dm-1': sdiskio(read_count=301203, write_count=432227, read_bytes=21659898880, write_bytes=808485867520, read_time=491960, write_time=39852320, read_merged_count=0, write_merged_count=0, busy_time=334844),
 'dm-2': sdiskio(read_count=120, write_count=130, read_bytes=2412544, write_bytes=532480, read_time=100, write_time=32924, read_merged_count=0, write_merged_count=0, busy_time=11848),
 'loop0': sdiskio(read_count=11551, write_count=0, read_bytes=12860416, write_bytes=0, read_time=2824, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=124),
 'loop1': sdiskio(read_count=52, write_count=0, read_bytes=355328, write_bytes=0, read_time=20, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop10': sdiskio(read_count=442, write_count=0, read_bytes=751616, write_bytes=0, read_time=20, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop11': sdiskio(read_count=45, write_count=0, read_bytes=122880, write_bytes=0, read_time=92, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop12': sdiskio(read_count=1723, write_count=0, read_bytes=1841152, write_bytes=0, read_time=660, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=20),
 'loop13': sdiskio(read_count=40, write_count=0, read_bytes=343040, write_bytes=0, read_time=12, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop14': sdiskio(read_count=40, write_count=0, read_bytes=343040, write_bytes=0, read_time=4, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop2': sdiskio(read_count=51, write_count=0, read_bytes=354304, write_bytes=0, read_time=32, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop3': sdiskio(read_count=49, write_count=0, read_bytes=367616, write_bytes=0, read_time=4, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=0),
 'loop4': sdiskio(read_count=7536, write_count=0, read_bytes=8018944, write_bytes=0, read_time=592, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=64),
 'loop5': sdiskio(read_count=152, write_count=0, read_bytes=1192960, write_bytes=0, read_time=32, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=4),
 'loop6': sdiskio(read_count=64013, write_count=0, read_bytes=66567168, write_bytes=0, read_time=18912, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=536),
 'loop7': sdiskio(read_count=40, write_count=0, read_bytes=117760, write_bytes=0, read_time=28, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=4),
 'loop8': sdiskio(read_count=17542, write_count=0, read_bytes=19004416, write_bytes=0, read_time=8480, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=368),
 'loop9': sdiskio(read_count=45, write_count=0, read_bytes=122880, write_bytes=0, read_time=44, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=8),
 'sda1': sdiskio(read_count=603, write_count=967, read_bytes=21843968, write_bytes=594513920, read_time=360, write_time=2568, read_merged_count=21, write_merged_count=1780, busy_time=2808),
 'sda2': sdiskio(read_count=4, write_count=0, read_bytes=4096, write_bytes=0, read_time=16, write_time=0, read_merged_count=0, write_merged_count=0, busy_time=16),
 'sda5': sdiskio(read_count=294262, write_count=270168, read_bytes=21670526464, write_bytes=808486400000, read_time=245948, write_time=13234520, read_merged_count=7196, write_merged_count=194961, busy_time=290436)}

In [3]: **psutil.disk_io_counters(perdisk=False)**
Out[3]: sdiskio(read_count=1000968, write_count=1145673, read_bytes=65132281344, write_bytes=2426054914048, read_time=1261428, write_time=93006412, read_merged_count=7217, write_merged_count=196756, busy_time=975020)

In [5]: **os.stat('/var/lib/postgresql/10/main')**
Out[5]: posix.stat_result(st_mode=16832, st_ino=39988134, st_dev=64769, st_nlink=20, st_uid=122, st_gid=127, st_size=4096, st_atime=1535017573, st_mtime=1535352188, st_ctime=1535352188)

**Comment by vitabaks** [comment]
`dc = disk_io_counters(perdisk=False)`
Thus, we get the total data for all the disks.

I want to get data for each disk in the system --> (psutil.disk_io_counters(perdisk=True) )

**Comment by kmoppel** [comment]
Yes, currently all disks summarized...that I understood would be already a start for you too based on https://github.com/cybertec-postgresql/pgwatch2/issues/105#issuecomment-416581544. Waiting on help still on this "real per disk" part then...
