### ISSUE TITLE
metric table_bloat_approx_summary timeout

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#107]
Hello,
i often have this kind of message : 
metric 'table_bloat_approx_summary': pq: canceling statement due to statement timeout

and when i execute the qry manually, i can see that it take quite long time to execute (12 min), with high cpu consumming.
For information, there is 89 tables in this monitored db.
Have you ever seen anything about that ? 
Thanks

**Comment by kmoppel** [comment]
Hi! yes sadly it's quite a common issue for bigger DBs, has to do with the visibility map...and only way to get rid of it is to increase the timeout a lot (12min in your case). Or removing this metrics if bloat is under control by some other means:)
