### ISSUE TITLE
Cleaning out component logs periodically

### ISSUE THREAD

**Issue by lyhistory** [cybertec-postgresql/pgwatch2#109]
is there a way to clear all the old logs and data periodically, for example by setting last 3 days somewhere, every 3 days, the data date before 3 days will be cleaned

**Comment by kmoppel** [comment]
Hi! I assume you're talking about the default Docker setup. Currently logs will be cleaned up automatically only for Postgres after a week. Other component (Influx, Grafana, Web UI, Gatherer) log levels are not verbose though...so in theory it shouldn't be a huge problem (Web UI will also show only 200 last lines). But true, would probably make sense for them also.

**Comment by kmoppel** [comment]
As of v3.0 supervisord automatically also cleans the component logs, so we get it for free basically. Max 500MB per component, thus max 2Gb for the pgwatch2 image.
