### ISSUE TITLE
docker database user/password incorrect

### ISSUE THREAD

**Issue by jwh5566** [cybertec-postgresql/pgwatch2#11]
default user/pw  postgres/pgwatch2admin can't login the database!

and  I install the plpythonu extension, why dashboard don't display the query runtime!

thanks!

**Comment by merrill-oakland** [comment]
It's actually pgwatch2/pgwatch2admin. The docs need to be updated.

**Comment by jwh5566** [comment]
@merrill-oakland 
thanks for your reply!
the database can login, and the cpu_load  value in the influxdb and show normal.
but the Avg. query runtime in the influxdb don't have value 
I check the logs:
MetricsFetcher: failed to fetch metrics for  XXXX stat_statements pq: column "queryid" does not exist 

is this reason? how resolve the problem, thanks a lot!

                                                                                                                        Looking forward to your reply

**Comment by merrill-oakland** [comment]
That would be unrelated. It sounds like a problem with prepared statement for stat_statements or the postgres version. Not sure what's causing that - I didn't run into any problems with it.

**Comment by jwh5566** [comment]
I check my db the pg_stat_statements view, all data is there, ,my pg version is 9.3.10, is that the problem course the question.

**Comment by jwh5566** [comment]
thanks a lot!
 I have resolve the problem. it's the  problem about the get_stat_statement function  permission.
I hope you can offer some doc about custom monitor metric.
thanks again.

**Comment by jwh5566** [comment]
thanks a lot!
 I have resolve the problem. it's the  problem about the get_stat_statement function  permission.
I hope you can offer some doc about custom monitor metrc.
thanks agagin.

**Comment by kmoppel** [comment]
I've now updated the README on DB user/password. The stat_statements problem cannot sadly be solved easily as "queryid" is just plain not there for versions <9.4 and there's no other reasonable column to graph on in Grafana. So I've just added 9.4+ remark to the README on that. Thanks for reporting the issue!

**Comment by jwh5566** [comment]
thanks
I have remove the queryid  in the metrc table, it's ok now.
but i have an other question, it's about the session graph, the idle value is not right, but the sql in the metrc is right, and the value in the influxdb is not right, i don't know why this happen.

**Comment by kmoppel** [comment]
@jwh5566 I think your image upload failed, could you try again? Don't quite get currently what the problem is about..
