### ISSUE TITLE
No new dashboards after upgrade to v1.4.0

### ISSUE THREAD

**Issue by ced75** [cybertec-postgresql/pgwatch2#110]
Hi,

I have upgraded pgwatch2 to the last 1.4.0 version.
I use the docker version and upgraded by removing the old container and recreate a new container with the same volumes as the preceding one. Then, I executed the two SQL scripts associated to the new version (in pgwatch2/sql/datastore_setup/migrations).
I restarted the container.
Everything went right, except that, in the dashboard lists, I can't see the new "system stats" dashboard, nor the other new dashboards.

Did I miss something in the upgrade process?
Thanks in advance for your help,

Cedric

**Comment by kmoppel** [comment]
Hi! The good news - you did all correct! The bad - new dashboards are not automatically inserted:) For new ones it would be actually possible (naming collisions still possible)...but as we cannot change for sure the existing ones (would  break user changes  or alerting)...wouldn't want to do that actually also for new ones. One would just have to import them from [JSON](https://github.com/cybertec-postgresql/pgwatch2/tree/master/grafana_dashboards/v5). But you're right - there is nothing about that in the README - will add a hint:) Thanks for the input!

**Comment by ced75** [comment]
Hi!
Thanks for you answer.
Could you please explain me how import new dashboards from JSON?
I don't see any "import" button from Grafana top menu.
I also executed pgwatch2/bootstrap/set_up_grafana_dashboards.sh script in my docker container, but new dashboards still don't appear.
Sorry for the disturbance, but I don't see what to do.

Thanks again,
Cedric

**Comment by kmoppel** [comment]
No worries, here's how I do it (there a 2 other ways also): 
1) log in as admin
2) hover on the plus sign, in left top corner, with "create" label
3) choose "import" and copy there the json from "grafana_dashboards" folder - e.g. from https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/v5/db-overview-developer/dashboard.json

It's described also in Grafana docus [here](http://docs.grafana.org/reference/export_import/) with screenshots

**Comment by ced75** [comment]
That did it!
I could update old dashboards and import new ones.
Thanks a lot for your help.

Regards,
Cedric

**Comment by ced75** [comment]
OK.
I have all the new dashboards in Grafana now.
But I'm facing a new problem: system dashboards remain empty.
I executed sql scripts names psutil_* on the target database, but nothing is displayed on dashboards.
I'm sure I forgot one other thing... but?

**Comment by kmoppel** [comment]
@ced75 hmm...maybe the "psutil" Python package and the "plpythonu" extension?

**Comment by ced75** [comment]
psutil Python package is installed on server, plpythonu extension is in the database.
In the target database, if I do the following SQL query:
SELECT * FROM get_psutil_mem();
I get the following error:
ERREUR:  AttributeError: 'svmem' object has no attribute 'shared'
CONTEXTE : Traceback (most recent call last):
  PL/Python function "get_psutil_mem", line 5, in <module>
    return vm.total, vm.used, vm.free, vm.shared, vm.buffers + vm.cached, vm.available, vm.percent, sw.total, sw.used, sw.free, sw.percent
fonction PL/python « get_psutil_mem »

**Comment by ced75** [comment]
Hi,
Thanks for the issue.
For get_psutil_mem(), the OS is Linux Debian 8.11 (Jessie).
Could it be related to python version? But I suppose that, when installing psutil package, dependencies are correctly resolved...

I have investigated the different functions calls:
* get_psutil_cpu() works fine;
* get_psutil_disk_io_total() works fine;
The two other functions have the problem described above.

**Comment by Rakshitha-BR** [comment]
Hi Ced,

What is the fix for  get_psutil_mem() issue?

ERROR:  AttributeError: 'svmem' object has no attribute 'shared'
CONTEXT:  Traceback (most recent call last):
  PL/Python function "get_psutil_mem", line 5, in <module>
    return vm.total, vm.used, vm.free, vm.shared, vm.buffers + vm.cached, vm.available, vm.percent, sw.total, sw.used, sw.free, sw.percent
PL/Python function "get_psutil_mem"
