### ISSUE TITLE
Collect xmin stats

### ISSUE THREAD

**Issue by ants** [cybertec-postgresql/pgwatch2#111]
Long running queries on master or on standby with hot_standby_feedback and forgotten replication slots can hold up xmin and cause bloat. Would be good to collect stats about `age(pg_replication_slots.xmin)`, `age(pg_stat_replication.backend_xmin)` and `max(age(pg_stat_activity.backend_xmin))` so they can be monitored and alerted on.

**Comment by kmoppel** [comment]
Changed existing "replication_slots" and "backends" metrics to include pg_replication_slots.xmin and pg_stat_activity.backend_xmin ages. pg_stat_replication one doesn't make too much sense in my opinion as it cannot be relied on - when replica is offline we don't have any info.
pg_replication_slots based info also added to a panel on the "Replicacation" dash - let me know if you see some other places where we could display it by default, closing for now.
