### ISSUE TITLE
openshift config crashes with incorrect certificate perms

### ISSUE THREAD

**Issue by atman9** [cybertec-postgresql/pgwatch2#112]
I keep getting these in the openshift/non-root version

waiting for server to start....2018-09-21 23:37:43 UTC [13-1] FATAL:  private key file "/pgwatch2/persistent-config/self-signed-ssl.key" must be owned by the database user or root
 stopped waiting
pg_ctl: could not start server

I can see in the dockerfile that it runs as:
...
USER 10001

CMD ["/pgwatch2/docker-launcher-nonroot.sh"]
...
and in that file it creates the keys here:
...
if [ ! -f /pgwatch2/persistent-config/self-signed-ssl.key -o ! -f /pgwatch2/persistent-config/self-signed-ssl.pem ] ; then
    openssl req -x509 -newkey rsa:4096 -keyout /pgwatch2/persistent-config/self-signed-ssl.key -out /pgwatch2/persistent-config/self-signed-ssl.pem -days 3650 -nodes -sha256 -subj '/CN=pw2'
    chmod 0600 /pgwatch2/persistent-config/self-signed-ssl.*
fi
...
So I think within the pod, the certs are owned by a UID which is neither root or postgres. 
I hope I am not doing something incorrect, but I just imported the template.
Perhaps the version on dockerhub is not a current as the github version?

**Comment by kmoppel** [comment]
Hi @atman9!  
I booted up minishift (latest version) now...but can't replicate the issue:/ Tried both with v1.3.7 and v1.4.0. 
Could you specify your setup? Or maybe do a fresh run?


```krl@e5470:~$ minishift version
minishift v1.25.0+90fb23e
krl@e5470:~$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.99.100:8443
openshift v3.10.0+fd501dd-48
kubernetes v1.10.0+b81c8f8
```

```krl@e5470:~$ oc exec -it pgwatch2-2-qrnx6 bash
groups: cannot find name for group ID 1000120000
pgwatch2@pgwatch2-2-qrnx6:/$ 
pgwatch2@pgwatch2-2-qrnx6:/$ PGSSLMODE=require psql -h localhost -U postgres
psql (9.5.14)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
```

**Comment by atman9** [comment]
Kaarel, thanks you can close the issue. We were pulling the wrong image , needed to point to `cybertec/pgwatch2-openshift` 
Thanks for looking into it!
