### ISSUE TITLE
Filter stat statement per user

### ISSUE THREAD

**Issue by vincehawk59** [cybertec-postgresql/pgwatch2#114]
I wish I could filter the queries sql available in the stat_statement part. Can not filter by user. Is it possible to change the queries in the tool to add user filter ?

Thank you

**Comment by kmoppel** [comment]
Yes grouping by users would be technically possible...but not so easily. You would have to:
* redefine the "get_stat_statements" helper, joining the pg_roles view
* roll out the new helper on all monitored DBs
* redefine the "stat_statements" metric, adding the new "username" column.
* redefine the Grafana dashboard.

Also this would in many cases multiply the amount of metric data stored so I originally decided to leave it out. Good luck!
