### ISSUE TITLE
change_tracking doesn't support older postgres versions (at least not 9.3)

### ISSUE THREAD

**Issue by markwort** [cybertec-postgresql/pgwatch2#115]
On a database with postgres 9.3, I got the following error messages:

`<user=pg_watch2 db=m7cltrsimucob host=10.139.59.254 time=2018-10-16 00:00:03.658 CEST pid=53381 > ERROR: column "pending_restart" does not exist at character 152 <user=pg_watch2 db=m7cltrsimucob host=10.139.59.254 time=2018-10-16 00:00:03.658 CEST pid=53381 > STATEMENT: select (extract(epoch from now()) * 1e9)::int8 as epoch_ns, name as tag_setting, coalesce(reset_val, '') as value from pg_settings where not pending_restart;`

`<user=pg_watch2 db=m7cltrsimucob host=10.139.59.254 time=2018-10-16 00:00:03.715 CEST pid=53390 > ERROR: schema "monitoring" does not exist <user=pg_watch2 db=m7cltrsimucob host=10.139.59.254 time=2018-10-16 00:00:03.715 CEST pid=53390 > STATEMENT: with sa_snapshot as ( select * from monitoring.get_stat_activity() where pid != pg_backend_pid() and not query like 'autovacuum:%' ) select (extract(epoch from now()) * 1e9)::int8 as epoch_ns, (select count(*) from sa_snapshot) as total, (select count(*) from sa_snapshot where state = 'active') as active, (select count(*) from sa_snapshot where state = 'idle') as idle, (select count(*) from sa_snapshot where state = 'idle in transaction') as idleintransaction, (select count(*) from sa_snapshot where waiting) as waiting, (select extract(epoch from (now() - backend_start))::int from sa_snapshot order by backend_start limit 1) as longest_session_seconds, (select extract(epoch from (now() - xact_start))::int from sa_snapshot where xact_start is not null order by xact_start limit 1) as longest_tx_seconds, (select extract(epoch from max(now() - query_start))::int from sa_snapshot where state = 'active') as longest_query_seconds;`

**Comment by kmoppel** [comment]
Actually seems that the metric was fixed some time ago - you should update the metric definitions. Or maybe just for that one: https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/configuration_hashes/9.0/metric.sql
