### ISSUE TITLE
9.6 pg_stat_activity doesn't have waiting column, breaks kpi metrics gathering

### ISSUE THREAD

**Issue by voiprodrigo** [cybertec-postgresql/pgwatch2#116]
Hi,

This workaround  for kpi metrics seems to do the trick:

- copy metrics/kpi/9.0 to metrics/kpi/9.6
- replace "where waiting" with "where wait_event_type is not null"

Thanks for pgwatch2!

**Comment by kmoppel** [comment]
@voiprodrigo Thanks for reporting! Corrected:)
