### ISSUE TITLE
Question regarding requirements for multi-db unprivileged monitoring

### ISSUE THREAD

**Issue by voiprodrigo** [cybertec-postgresql/pgwatch2#117]
Hi,

First of all, thanks for you work on this project, I think it's a really nice and useful implementation.

Today I started experimenting with it, and using just standalone gatherer, yaml config and JSON output for now. I want to collect the most complete set of metrics (the "full" preset, I assume) from two separate servers, each with multiple logical db's, and always using an unprivileged user. And I have a few questions:

1. If using discovery, is it possible somehow to have one tag for the server name, and another separate tag for the database name? Instead of a concatenation of unique_name and the discovered db name.
2. I believe some metrics are "global" to the server instance, and some are db specific? If this assumption is correct, how to avoid metric duplication when querying more than one logical database per server? 
3. Is it required to grant connect to the pgwatch2 role for all logical db's?
4. Do all the  SQL helpers as well as the extensions (plpythonu, pg_stat_statements) need to be added to all the monitored logical db's?
5. Does it make sense to have a empty pgwatch2 db to connect to just to gather "global" metrics?
6. Would there be any advantage (other than not needing the plpython extension + helpers) to running the gathered locally on each server, and accessing with privileged user instead?

Thanks!

**Comment by kmoppel** [comment]
Glad that you're giving it a try! Feedback is also very welcome. To answer your questions:

1. Currently sadly no such feature...but this would be relatively easy to add. Just didn't have a use case for it so far as there might be a lot of duplicates for the real DB names like "postgres". But please do open a new feature request issue if this would make sense for you.
2. There are no "local" metrics actually - only "global" with another dimensions of Postgres version, so there shouldn't be much duplication.
3. Yes connect is required on all DB-s...as some metrics cannot be extracted from global (per instance) statistics views - the "auto-discovery" feature only get's the DB names and from thereon they'll be handled as independent ones.
4. Yes
5.  Hmm an interesting feature idea...but again not really sure if this makes sense. Currently for the "config file" based deployments one can use automation (Ansible) to keep configs up to date if running a gatherer on all instance hosts.
6. No there is no advantage in feature-wise. Everything is gathered via SQL anyways. It just comes down to what is possible and what makes sense in a concrete organization

Let me know if something was left unclear.
