### ISSUE TITLE
Starting webui only

### ISSUE THREAD

**Issue by thomasboussekey** [cybertec-postgresql/pgwatch2#119]
Hello all,

Thank you for this wonderful tool.

# Context description

I'm trying to upgrade an old pgwatch2 configuration, to create 2 containers, one for pgwatch2-daemon, one for pgwatch2-webui.
All other components are already running on other containers or machines.

# pgwatch2-daemon creation

I managed to create a pgwatch2-daemon container using [dockerfile](https://github.com/cybertec-postgresql/pgwatch2/blob/master/docker/Dockerfile-daemon) and setting the environnement variables:
```
PW2_GRAFANA_BASEURL= https=//..../
PW2_IDATABASE= aaa
PW2_IHOST= xxx.yyy.zz.ddd
PW2_IPASSWORD= xxxxx
PW2_IPORT= '1234'
PW2_IUSER= yyyy
PW2_PGDATABASE= pgwatch2
PW2_PGHOST= xxx.yyy.zz.ddd
PW2_PGPASSWORD= xxx
PW2_PGPORT= '1234'
PW2_PGUSER= yyy
```
# pgwatch2-webui creation

I tried to create a pgwatch2-webui container using [dockerfile](https://github.com/cybertec-postgresql/pgwatch2/blob/master/docker/Dockerfile-webui) and setting the environnement variables:
```
PW2_GRAFANA_BASEURL= https=//..../
PW2_IDATABASE= aaa
PW2_IHOST= xxx.yyy.zz.ddd
PW2_IPASSWORD= xxxxx
PW2_IPORT= '1234'
PW2_IUSER= yyyy
PW2_PGDATABASE= pgwatch2
PW2_PGHOST= xxx.yyy.zz.ddd
PW2_PGPASSWORD= xxx
PW2_PGPORT= '1234'
PW2_PGUSER= yyy
PW2_WEBHOST='0.0.0.0'
PW2_WEBPORT=8080
PW2_WEBUSER=pgwatch2
PW2_WEBPASSWORD=zzz
PW2_VERBOSE='vv'
```

Yet, the container startup always log the **help message**.

```
Generating a 4096 bit RSA private key
....................................................++
...........................................++
unable to write 'random state'
writing new private key to '/pgwatch2/self-signed-ssl.key'
-----
/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
usage: web.py [-h] [--socket-host SOCKET_HOST] [--socket-port SOCKET_PORT]
              [--ssl SSL] [--ssl-cert SSL_CERT] [--ssl-key SSL_KEY]
              [--ssl-certificate-chain SSL_CERTIFICATE_CHAIN] [-v]
              [--no-anonymous-access] [--admin-user ADMIN_USER]
              [--admin-password ADMIN_PASSWORD] [--no-component-logs]
              [-H HOST] [-p PORT] [-d DATABASE] [-U USER]
              [--password PASSWORD] [--pg-require-ssl]
              [--influx-host INFLUX_HOST] [--influx-port INFLUX_PORT]
              [--influx-user INFLUX_USER] [--influx-password INFLUX_PASSWORD]
              [--influx-database INFLUX_DATABASE] [--influx-require-ssl]
              [--grafana_baseurl GRAFANA_BASEURL]

pgwatch2 Web UI

optional arguments:
  -h, --help            show this help message and exit
  --socket-host SOCKET_HOST
                        Webserver Listen Address
  --socket-port SOCKET_PORT
                        Webserver Listen Port
  --ssl SSL             Enable Webserver SSL (Self-signed Cert)
  --ssl-cert SSL_CERT   Path to SSL certificate
  --ssl-key SSL_KEY     Path to SSL private key
  --ssl-certificate-chain SSL_CERTIFICATE_CHAIN
                        Path to certificate chain file
  -v, --verbose         Chat level. none(default)|-v|-vv [$VERBOSE=[0|1|2]]
  --no-anonymous-access
                        If set no login required to configure
                        monitoring/metrics
  --admin-user ADMIN_USER
                        Username for login
  --admin-password ADMIN_PASSWORD
                        Password for login to read and configure monitoring
  --no-component-logs   Dont expose component logs via the Web UI
  -H HOST, --host HOST  Pgwatch2 Config DB host
  -p PORT, --port PORT  Pgwatch2 Config DB port
  -d DATABASE, --database DATABASE
                        Pgwatch2 Config DB name
  -U USER, --user USER  Pgwatch2 Config DB username
  --password PASSWORD   Pgwatch2 Config DB password
  --pg-require-ssl      Pgwatch2 Config DB SSL connection only
  --influx-host INFLUX_HOST
                        InfluxDB host
  --influx-port INFLUX_PORT
                        InfluxDB port
  --influx-user INFLUX_USER
                        InfluxDB username
  --influx-password INFLUX_PASSWORD
                        InfluxDB password
  --influx-database INFLUX_DATABASE
                        InfluxDB database
  --influx-require-ssl  Use SSL for InfluxDB
  --grafana_baseurl GRAFANA_BASEURL
                        For linking to Grafana "Query details" dashboard
```
Inspecting the [web.py](https://github.com/cybertec-postgresql/pgwatch2/blob/master/webpy/web.py) python script, I discovered that it uses the **logging API**.

And I tried to locate the log file where logs can be written.

I found one configuration for logging API into python script [phwatch2.py](https://github.com/cybertec-postgresql/pgwatch2/blob/master/webpy/pgwatch2.py), but it defines a `log_root` variable for webui set to folder: **/var/log/supervisor/** and this folder doesn't exist into my container.

> Are some parameters missing?

> How can I investigate further on?

Thanks in advance for your help,
Regards,
Thomas

**Comment by kmoppel** [comment]
Hi, @thomasboussekey! Glad that you're trying out pgwatch. And it should work now also, I've pushed a new image! That component hasn't gotten any love recently and was yes not up to date :) Let me know if having any other issue.

**Comment by kmoppel** [comment]
hmmm...this is weird. When I specify a wrong port for the config DB I get a normal error...thus it has something to do with the network config of Docker daemon itself. Maybe try with host networking directly? i.e. `docker run ... --network=host ...`

---
2018-11-22 12:48:44,764 WARNING 1 config DB connection test failed: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 32434?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 32434?

[22/Nov/2018:12:48:44] ENGINE Listening for SIGTERM.
2018-11-22 12:48:44,765 INFO 1 [22/Nov/2018:12:48:44] ENGINE Listening for SIGTERM.
[22/Nov/2018:12:48:44] ENGINE Listening for SIGHUP.
2018-11-22 12:48:44,765 INFO 1 [22/Nov/2018:12:48:44] ENGINE Listening for SIGHUP.
[22/Nov/2018:12:48:44] ENGINE Listening for SIGUSR1.
2018-11-22 12:48:44,765 INFO 1 [22/Nov/2018:12:48:44] ENGINE Listening for SIGUSR1.
[22/Nov/2018:12:48:44] ENGINE Bus STARTING
2018-11-22 12:48:44,766 INFO 1 [22/Nov/2018:12:48:44] ENGINE Bus STARTING
[22/Nov/2018:12:48:44] ENGINE Started monitor thread 'Autoreloader'.
2018-11-22 12:48:44,766 INFO 1 [22/Nov/2018:12:48:44] ENGINE Started monitor thread 'Autoreloader'.
[22/Nov/2018:12:48:44] ENGINE Serving on http://0.0.0.0:8080
2018-11-22 12:48:44,868 INFO 1 [22/Nov/2018:12:48:44] ENGINE Serving on http://0.0.0.0:8080
[22/Nov/2018:12:48:44] ENGINE Bus STARTED

**Comment by thomasboussekey** [comment]
I identified the problem, once agin, a single quote problem...

When I modified:
PW2_WEBHOST='0.0.0.0'
by
PW2_WEBHOST=0.0.0.0

It started...

Many thanks for your help @kmoppel 

Thomas
