### ISSUE TITLE
Backends count for multiple DBs mixed together

### ISSUE THREAD

**Issue by merrill-oakland** [cybertec-postgresql/pgwatch2#12]
The Backends + Deadlocks + Temp bytes panel, the SQL for the backends report is missing the dbname filter, so it mixes all the DBs together, and makes a sawtooth pattern. I fixed it in my install by modifying the query SQL from:
`SELECT mean("numbackends") FROM "db_stats" WHERE $timeFilter GROUP BY time($interval) fill(none)`
to
`SELECT mean("numbackends") FROM "db_stats" WHERE "dbname" =~ /^$dbname$/ AND $timeFilter GROUP BY time($interval) fill(none)`

**Comment by kmoppel** [comment]
Thanks for sharing the fix! https://github.com/cybertec-postgresql/pgwatch2/commit/dfe95a44d3f6ff2ae4ebbd3f56c7971cde37cf50
