### ISSUE TITLE
Question - metrics database

### ISSUE THREAD

**Issue by jacks33** [cybertec-postgresql/pgwatch2#121]
Hello,

Just a question about database to store metrics(time-series): do you plan to use a posgresql 11 as well as for config ? 

Thank you.

**Comment by kmoppel** [comment]
Hi,
The schema already is PG 11 compatible. Just some tables and data, no special features so should work with all versions. 
At some point would yes probably make sense to update the default Docker image also but there are no problems (that I know of) currently so no real need for it. And some query tools don't even support 11 yet.
Cheers
