### ISSUE TITLE
Connection leak from pgwatch2

### ISSUE THREAD

**Issue by flaviogurgel** [cybertec-postgresql/pgwatch2#122]
Hello

After downloading latest docker version, I see that pgwatch2 gatherer opens lots of connections to each monitored database. In some of them, it oppenned tens of connections until max_connections was reached.

Looking to the latest commits, I saw that a limit of 2 connections per database was put in place but it's not being effective.

As a temporary solution, I recompiled pgwatch2 with PG_CONN_RECYCLE_SECONDS = 5 and then connections are closed after values are gathered.

I'm not a go developer but I think that the logic in the "if" that controls the number of connections is broken.

Best,
Flavio Gurgel

**Comment by kmoppel** [comment]
Hi! 
Hmm, doesn't sound good...haven't noticed such behaviour myself. As quick fix one could also set a session limit for the monitoring role, .e.g. `ALTER USER pgwatch2 CONNECTION LIMIT 10;` or to disable keeping open of sessions with `PW2_CONN_POOLING=off` or with `--conn-pooling=off` when running the gatherer directly.

Could you maybe describe your setup a bit more?

**Comment by flaviogurgel** [comment]
Hello

Thanks for your reply.

I'll try the PW2_CONN_POOLING=off since I'm running on docker.

My setup is pretty basic, I'm currently using your docker image fetched last friday 23th november. The problem didn't happen before with an image downloaded several months ago, surely before your patches for persistent connections.

I have 97 databases amongst around 30 servers configured to monitor. The only custom setting I've made was to change the schema name of the pg_stat_statements wrapper function because we have a naming convention in place. It works as expected.

My docker command specifies 4 custom directories for Postgres, Grafana, InfluxDB and persistent, so we don't lose data when we prune docker. Unfortunately upgrades on InfluxDB are hard in this setup, so I cleaned up all persistent directories upon latest fetch, so you can count on a fresh install.

The connections leaked by pgwatch2 gatherer stay on idle state. After reaching the connection limit of the server, pgwatch2 stops gathering stats.

I'll try to enforce the connection limit in the monitored databases, it's doable because everything is automated, but turning off the pooling seems to be more of a reasonable choice for now, because after recompiling the gatherer with the 5 seconds timeout, I can confirm that I had a full weekend without issues in my production. Obviously, I have now a custom image that is working for us, but that's the only change in code I've made.

Regards,
Flavio Gurgel

**Comment by kmoppel** [comment]
Thanks for the extra info! Your setup seems quite standard indeed...only the amount of servers is a lot above the average, so will try to replicate this scenario. Until it's sorted out I've disabled the "conn pooling" by default to be on the safe side. Cheers

**Comment by flaviogurgel** [comment]
Sorry for this late reply.
I could use an up-to-date container this week. I can confirm that the issue is gone after your changes.
Thanks!
