### ISSUE TITLE
Permission denied and AttributeError

### ISSUE THREAD

**Issue by DelphF** [cybertec-postgresql/pgwatch2#123]
Hello,

First, many thanks for this tool pgwatch2. It's well documented, easy to install/configure and easy to use. Good job ;-)!

I'm using pgwatch2 without Docker and I'm facing this error message : 

2018/11/26 12:52:32 WARN MetricsFetcher: Failed to get SQL for metric 'wal_size', version '9.6'
2018/11/26 12:54:32 ERRO MetricsFetcher: failed to fetch metrics for 'db_blabla', metric 'table_io_stats': pq: permission denied for relation pg_statio_user_tables
2018/11/26 12:54:32 ERRO MetricsFetcher: failed to fetch metrics for 'db_blabla', metric 'psutil_mem': pq: AttributeError: 'svmem' object has no attribute 'shared'

The PG version is 9.6 and the Python version is 3.4.
OS : RedHat7

Could you tell me what I add to do to correct these errors ?

Many thanks,
Have a nice day,
Delphine.

**Comment by kmoppel** [comment]
Hi, glad that you're giving pgwatch a try!
I've now "fixed" the first and last issue now and pushed a new image. The first one was just a notification though, but the last one is some Redhat "anomaly" where "psutil" does not play according to documentation there.
The 2nd issue is some privilege issue on your side though, maybe try: `grant SELECT on pg_statio_user_tables to pgwatch2 ;`
Let me know if having some other issues, cheers.

**Comment by DelphF** [comment]
Hello,

Many thanks for the new image! It works fine.
For information, I had to adapt this script also : pgwatch2-master\pgwatch2\sql\metric_fetching_helpers\psutil_mem.sql. I don't know if it's because I used it without Docker. 

Just a question : the warning is now an error. May I do something to solve it ? 
2018/11/29 10:45:39 ERRO MetricsFetcher: failed to fetch metrics for 'a4btb', metric 'wal_size': empty SQL

Many thanks for your help.
Cheers,
Delphine.

**Comment by kmoppel** [comment]
@DelphF ah, you're right about changing the "metric_fetching_helpers\psutil_mem.sql"...I overlooked that but added now. 
But hmm interesting, the "empty SQL" error should appear only as INFO level according to that [code](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/pgwatch2.go#L1332). I only see something like that in verbose mode (not enabled by default) :
```
2018/11/30 12:10:46 INFO MetricsFetcher: Ignoring fetch message - got an empty/dummy SQL string for [test:wal_size]
```
Maybe you have some other hints?

**Comment by DelphF** [comment]
Hello,
My fault, I forgot to compile again the gatherer daemon "build_gatherer.sh" to generate the new executable pgwatch2. 

Now it's working!

Many thanks for your help.
Delphine.
