### ISSUE TITLE
Execution Time spikes Alert I am using 

### ISSUE THREAD

**Issue by sbholla** [cybertec-postgresql/pgwatch2#124]
using the below query I was able to calculate the spikes in execution times  such that it would alert us when there is a query which ran for more than 5 seconds and the execution time is 100% more than the avg execution time for that Query in that hour .
It uses the data which is already being collected from stat_statements metric 
Added the metric in graph dashboard and created alert to run for every 30 min to check for last 2 hours .
Query: 
"select max(MaximumExecutionTimeInLasthour) from (select mean(non_negative_derivative_non_negative_derivative) as AverageExecutionTimeLasthour,max(non_negative_derivative_non_negative_derivative) as MaximumExecutionTimeInLasthour,((((max(non_negative_derivative_non_negative_derivative)+0.0000000001)-mean(non_negative_derivative_non_negative_derivative))/mean(non_negative_derivative_non_negative_derivative))*100) as "PercentageGrowthComparingMaxAndAverage" from (SELECT non_negative_derivative(mean("total_time")) / non_negative_derivative(mean("calls")) FROM "stat_statements" WHERE dbname='dbname' and $timeFilter GROUP BY time(2s), "queryid" fill(null)) WHERE non_negative_derivative_non_negative_derivative<>0 GROUP BY time(1h),"queryid","query","rolname" fill(null)) WHERE  MaximumExecutionTimeInLasthour>5000 AND PercentageGrowthComparingMaxAndAverage>100 group by time(1h),"queryid","query","rolname""

let me know your comments

**Comment by kmoppel** [comment]
Hi @sbholla, thanks for sharing the code/idea! And I tried it out (with lowered limits)....but could not get any rows...which might be ok for my metrics though. So not sure what to do with the query...so was thinking maybe just to create a "alerting_samples" folder to the project so that people could get some ideas. Would you be ready to create a PR for that?

**Comment by sbholla** [comment]
My idea was that to add this as a new graph dashboard type called Execution Time spikes which would be a single place to check all the execution times spikes occurred for all the functions and queries 
and provide users to change the time and percentage growth parameters
some thing like below attached image 


![image](https://user-images.githubusercontent.com/40368732/49547574-ab7b9f80-f8a8-11e8-8b50-4177b8395720.png)

**Comment by kmoppel** [comment]
@sbholla aha now I see the idea, image already makes sense. will try to generate some proper test data and implement it in a similar way.
