### ISSUE TITLE
use client certificates in postgres connection string

### ISSUE THREAD

**Issue by menacher** [cybertec-postgresql/pgwatch2#125]
Our postgresdb installation has authentication that requires the use of client certificates, I dont see an option to provide these in the /dbs configuration. Is there some way it can be done?

**Comment by kmoppel** [comment]
Hi! Currently sadly not possible :(...but would be nice indeed. Hopefully can fit it in for the next feature pack. PR-s welcome also of course. 
One should and upload form to the Web UI that stores the files somewhere in /pgwatch2/persistent-config and 2nd option would be to specify them in any location when in "config based" mode.

**Comment by kmoppel** [comment]
@menacher, I've now added support for client certificates. One needs to use a custom setup though as certs need to be physically available for the gatherer. With docker one should then use volumes and the "/pgwatch2/persistent-config" folder. Let me know if you're having any problems. Cheers
![pw2_certs](https://user-images.githubusercontent.com/346788/50083841-b4039c80-01fd-11e9-9def-dedc93c57353.png)

**Comment by menacher** [comment]
Thank you! I will check this out.
