### ISSUE TITLE
How to determine Blocking Queries

### ISSUE THREAD

**Issue by peterneave** [cybertec-postgresql/pgwatch2#129]
I'm trying to find the source of database performance issues. I can see with pgWatch2 that we have frequent medium duration queries. I feel like they are being blocked by locks and I would like to find out which queries are causing the blocks.

I noticed that there is a 'blocking_locks' metrics. Is there an existing Grafana board to display this information? Also, I noticed it uses PIDs. Could I determine the actual statement based on the PID somehow - or would a custom metric be better for my requirement to determine blocking statements? (based on 'blocking locks' but connected to pg_stat_activity to get the exact statements).

**Comment by sbholla** [comment]
I use below monitor metric to capture the blocking 
inserted the metric query in the metric table in pgwatch2 database in postgresql
and then in grafana created table  with query  **SELECT  *  FROM "blockinglocks2"  WHERE "blocked_user"<>'x' and dbname='dbname' and $timeFilter**  

**Metric Query:**
with x as(SELECT                                                                                                                    
   ((extract(epoch from now()) * 1e9)::int8)row_number() over () AS epoch_ns,                                                        
              blocked_locks.pid                  AS tag_blocked_pid,                                                                  
              blocked_activity.usename::text         AS tag_blocked_user,                                                             
              blocking_locks.pid               AS tag_blocking_pid,                                                                   
              blocking_activity.usename::text         AS tag_blocking_user,                                                           
              left(blocked_activity.query,100)           AS tag_blocked_statement,                                                    
              left(blocking_activity.query,100)           AS tag_blocking_statement,                                                  
             blocked_activity.application_name AS tag_blocked_application_name,                                                       
             blocking_activity.application_name AS tag_blocking_application_name,1 as count                                           
       FROM  pg_catalog.pg_locks         blocked_locks                                                                                
       JOIN public.get_stat_activity() blocked_activity  ON blocked_activity.pid = blocked_locks.pid                                  
       JOIN pg_catalog.pg_locks         blocking_locks                                                                                
            ON blocking_locks.locktype = blocked_locks.locktype                                                                       
            AND blocking_locks.DATABASE      IS NOT DISTINCT FROM blocked_locks.DATABASE                                              
            AND blocking_locks.relation      IS NOT DISTINCT FROM blocked_locks.relation                                              
            AND blocking_locks.page          IS NOT DISTINCT FROM blocked_locks.page                                                  
            AND blocking_locks.tuple         IS NOT DISTINCT FROM blocked_locks.tuple                                                 
            AND blocking_locks.virtualxid    IS NOT DISTINCT FROM blocked_locks.virtualxid                                            
            AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid                                         
            AND blocking_locks.classid       IS NOT DISTINCT FROM blocked_locks.classid                                               
            AND blocking_locks.objid         IS NOT DISTINCT FROM blocked_locks.objid                                                 
            AND blocking_locks.objsubid      IS NOT DISTINCT FROM blocked_locks.objsubid                                              
            AND blocking_locks.pid != blocked_locks.pid                                                                               
        JOIN public.get_stat_activity() blocking_activity ON blocking_activity.pid = blocking_locks.pid                               
       WHERE NOT blocked_locks.GRANTED and blocked_activity.datname = current_database()                                              
     union                                                                                                                            
 SELECT 0,0,'x',0,'','','','','',0 )                                                                                                  
     select (extract(epoch from now()) * 1e9)::int8 as epoch_ns,                                                                      
     (select array_to_string(ARRAY(select tag_blocked_pid from x ),',')) as tag_blocked_pid,                                          
     (select array_to_string(ARRAY(select tag_blocked_user from x ),',')) as tag_blocked_user,                                        
     (select array_to_string(ARRAY(select tag_blocking_pid from x ),',')) as tag_blocking_pid,                                        
     (select array_to_string(ARRAY(select tag_blocking_user from x ),',')) as tag_blocking_user,                                      
     (select array_to_string(ARRAY(select tag_blocked_statement from x ),',')) as tag_blocked_statement,                              
     (select array_to_string(ARRAY(select tag_blocking_statement from x ),',')) as tag_blocking_statement,                            
     (select array_to_string(ARRAY(select tag_blocked_application_name from x ),',')) as tag_blocked_application_name,                
     (select array_to_string(ARRAY(select tag_blocking_application_name from x ),',')) as tag_blocking_application_name,0 as count    
     from x limit 1;

**Comment by kmoppel** [comment]
@peterneave  yes, currently there is no preset dashboard for the "blocking_locks"...as it's not also part of any "preset" configs. The reason is that locking metrics need to be called very frequently and they generate a lot of data that could cause high CPU load on Influx / Grafana side, so it's hard to come up with safe but informative queries. All dashboard suggestions are welcome though.
But actually in the "blocking_locks" there are also the queries - "other_query" and "waiting_query"?

**Comment by kmoppel** [comment]
@sbholla  was wondering, are those "IS NOT DISTINCT"-s really needed? Wouldn't a simple "=" work?

**Comment by sbholla** [comment]
"=" should work ,I was actually observing these NOT DISTINCT now

**Comment by peterneave** [comment]
Thanks @kmoppel and @sbholla for the feedback.

The locks that I can see might be 20 seconds but with pgWatch I would only call the block_locks metric every 60 seconds - so, we are likely to miss them without putting strain on the system as a whole. So, given that locking happens to infrequently and it would probably get out of phase with the monitoring.  I've decided to monitor the Postgres logs directly for lock notifications and to call into the blocking_locks script immediately afterwards.

Enable in Postgres Config
`log_lock_waits = on`

Use the blocking_locks sql in pgWatch2 and call it blocking_locks.sql

Leave this code running in a terminal. When it sees a lock in the logs then it will immediately append the blocking logs query into a CSV file that I can use later to analyse. 
```bash
#!/usr/bin/env bash
query=$(cat blocking_locks.sql | sed -e "s/;$//")
psql -U user -d database -c "COPY ( $query ) TO STDOUT WITH CSV HEADER " --pset="footer=off" > locks.csv

tail -fn0 /var/log/postgresql/postgresql-10-main.log | \
  while read line ; do
        echo "$line" | grep --color -E "^.*LOG:.*\w*Lock\b.*$"
        if [ $? = 0 ]; then
         psql -U user -d database -c "COPY ( $query ) TO STDOUT WITH CSV" --pset="footer=off" >> locks.csv
        fi
done
```

**Comment by kmoppel** [comment]
@peterneave Nice idea, to select only after the "trigger". Just pure SQL queries yes are not the best with that use case. Thanks for sharing!
