### ISSUE TITLE
"WAL ratio" doesn't make any sense

### ISSUE THREAD

**Issue by merrill-oakland** [cybertec-postgresql/pgwatch2#13]
The item "WAL Ratio" doesn't make any sense. I had to check the code, and it is actually getting the derivative, which would be the "WAL Rate", which makes a lot more sense.

**Comment by kmoppel** [comment]
Indeed, somehow mixed up the different r-concepts as a non-native speaker:) Corrected in https://github.com/cybertec-postgresql/pgwatch2/commit/715e3b1436ee67e791cbbca97642d80a11bd98ba
