### ISSUE TITLE
psutil_cpu.sql

### ISSUE THREAD

**Issue by Patze66** [cybertec-postgresql/pgwatch2#131]
First, many thanks for this tool pgwatch2. I have little problem when I'm trying to get cpu information. It gives error...

ef_car_production=> SELECT * FROM get_psutil_cpu();
ERROR:  ImportError: cannot import name cpu_times_percent
CONTEXT:  Traceback (most recent call last):
  PL/Python function "get_psutil_cpu", line 4, in <module>
    from psutil import cpu_times_percent, cpu_percent, cpu_count
PL/Python function "get_psutil_cpu"

What I'm doing wrong?

**Comment by kmoppel** [comment]
Hi @Patze66, thank for trying it out! But yes with this "psutil" there have been some other people also getting errors...has to do with the fact that the module has different implementations across versions / operating systems so you need to modify the template to your needs. I've now added a comment also about it to `get_psutil_cpu` source code. It works at least on Ubuntu 16.04/18.04 as this is what we use for the Docker images.

```
/*  Pre-requisites: PL/Pythonu and "psutil" Python package (e.g. pip install psutil)
    NB! "psutil" is known to behave differently depending on the used version and operating system, so if getting
    errors please adjust to your needs. "psutil" documentation here: https://psutil.readthedocs.io/en/latest/
*/
```

**Comment by kmoppel** [comment]
And if you can think of a nice way how to maybe make it more generic, I'm all ears:)
