### ISSUE TITLE
pgwatch is not capturing killed queries 

### ISSUE THREAD

**Issue by sbholla** [cybertec-postgresql/pgwatch2#132]
our applications kills few functions if they take more than 10 seconds to execute 
I am observing that those queries which got killed are not being recorded in  pgwatch 
is this known issue ? is there a way I can overcome this ?

**Comment by kmoppel** [comment]
@sbholla do you mean some pgwatch2 metric queries are killed or your normal user queries? For user queries I'm afraid it's not really possible to do detect "killing" without parsing logs...

**Comment by sbholla** [comment]
thanks I need to parse logs then , that would be an interesting report for pgwatch, if we can have the list of killed transactions 

would share if I could somehow get that data in to pgwatch

**Comment by kmoppel** [comment]
Yes, I'm thinking of something similar also for some time [already](https://github.com/cybertec-postgresql/pgwatch2/issues/32). There are quite some log parsing options out there but good would be to have something that knows Postgres, is light-weight and can configured in a simple way. If you find a nice solution please post to the mentioned issue #32.
