### ISSUE TITLE
Feature request - a Kubernetes Helm chart for deployment

### ISSUE THREAD

**Issue by rafaelsisweb** [cybertec-postgresql/pgwatch2#133]
Hey there, 

I'm needing to deploy pgwatch2 only pw2+confg postgres into a kubernetes cluster.. It will collect metrics from multiples RDS Postgres deployments for multiples environemts , and persist to a sigle and external Influxdb alerady running.

Is there any one using some Helm charts to deploy pw2?

**Comment by kmoppel** [comment]
Hi @rafaelsisweb! Currently not...there's only a sample Deployment config [here](https://github.com/cybertec-postgresql/pgwatch2/tree/master/openshift).
But a Helm support would be a nice feature though...not sure how much work is involved. But I'll leave the ticket open as a "feature request" and please ping back if you get any progress. Thanks!

**Comment by rafaelsisweb** [comment]
Thanks for that.
