### ISSUE TITLE
port already in use error

### ISSUE THREAD

**Issue by MichaelDBA** [cybertec-postgresql/pgwatch2#134]
docker run -d -p 3000:3000 -p 8080:8080 --name pw2 cybertec/pgwatch2

-->
docker: Error response from daemon: driver failed programming external connectivity on endpoint pw2 (6216707b96e33f24b1892bbf28b43e29d26e39b90c81c99cf4a028d0d21dcd7c): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.

**Comment by kmoppel** [comment]
Hmm, seems like a pure Docker issue...maybe just some other application is holding the port. For me the following command identifies the guilty process: `lsof -i :8080`
