### ISSUE TITLE
File based config.

### ISSUE THREAD

**Issue by rafaelsisweb** [cybertec-postgresql/pgwatch2#135]
Hey there, 

It's possible use pgwatch without an config postgresql, just using files to setup monitoring databases and metrics?

**Comment by kmoppel** [comment]
Hi! Yes, there's a "file based" mode with YAML configs: https://github.com/cybertec-postgresql/pgwatch2#file-based-operation

**Comment by rafaelsisweb** [comment]
Hi @kmoppel,

Have you any tip how can I cleanup metrics from influx db in case off rename a dbname?
I'm trying to keep only pgwatch2 daemon with filebased config, without UI/Postgres/Influxdb/Grafana.
Grafana and Influxdb are external resources in this case.

**Comment by kmoppel** [comment]
@rafaelsisweb Simplest cleanup would be probably with "DROP SERIES WHERE dbname = 'X'`. And if still wanting to keep the metrics gathered with the old name, one could also do a scripted update, i.e. a small Python script or something to reinsert (there's no UPDATE) the data with a new name.

Influx docus: https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#delete-a-database-with-drop-database
