### ISSUE TITLE
[Docker] Grafana not re-configured from env. when using an external metrics DB

### ISSUE THREAD

**Issue by debellabre** [cybertec-postgresql/pgwatch2#136]
Hi Kaarel,
I would love to use an external databse postgres for config and metrics. I make a pg_dump_all in the conteneur and restore on the host srisvm-pocpostgre.isocel.info in an instance postgresql 11.1
Then i launched my containeur docker.

here is my order : 
docker run -d -p 3000:3000 -p 8080:8080 -p 5432:5432 -e PW2_PGHOST="srisvm-pocpostgre.isocel.info" -e PW2_PGPORT="5434" -e PW2_PGDATABASE="pgwatch2" -e PW2_PGUSER="pgwatch2" -e PW2_PGPASSWORD="pgwatch2admin" -e PW2_DATASTORE="postgres" -e PW2_PG_METRIC_STORE_CONN_STR="postgresql://pgwatch2:pgwatch2admin@srisvm-pocpostgre.isocel.info:5434/pgwatch2_metrics" --name retouch-pw2 cybertec/pgwatch2-postgres

I verify my PW2 variables : 

docker inspect 2cf4a678e57a  |  grep PW2
                "PW2_PGHOST=srisvm-pocpostgre.isocel.info",
                "PW2_PGPORT=5434",
                "PW2_PGDATABASE=pgwatch2",
                "PW2_PGUSER=pgwatch2",
                "PW2_PGPASSWORD=pgwatch2admin",
                "PW2_DATASTORE=postgres",
                "PW2_PG_METRIC_STORE_CONN_STR=postgresql://pgwatch2:pgwatch2admin@srisvm-pocpostgre.isocel.info:5434/pgwatch2_metrics",
                "PW2_PG_SCHEMA_TYPE=metric-time"

From the container I access the external base. the user pgwatch2 is superuser

docker exec -it 2cf4a678e57a /bin/bash
root@2cf4a678e57a:/# psql -h srisvm-pocpostgre.isocel.info -p 5434 -U pgwatch2 pgwatch2_metrics
psql (11.1 (Ubuntu 11.1-1.pgdg18.04+1))
Type "help" for help.

pgwatch2_metrics=# ^C
pgwatch2_metrics=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 pgwatch2  | Superuser                                                  | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

But The base used ibty pgwatch2 is that of the container.
For check I destroyed the pgwatch2_metrics base of the container instance and I had an error in the Grafana : pq: database "pgwatch2_metrics" does not exist

Can you explian me where I have the error ? 
Thank you for this great product!!
Yves

**Comment by kmoppel** [comment]
Hi @debellabre, thanks for the problem report! I've now tried to do the same thing (use an external DB, not the one in the container), setting the same env. variables...and everything worked, except Grafana - there one needs to edit the data source manually indeed, it's not configured from env. vars currently. Will see if it can be fixed easily...

**Comment by debellabre** [comment]
I changed the data source in grafana and it's good now. 
thanks for the information. 
I will follow the fix
