### ISSUE TITLE
Security Risk on PLPython - Question

### ISSUE THREAD

**Issue by sasadangelo** [cybertec-postgresql/pgwatch2#139]
Hi,

If my understanding is correct pgwatch2 collector written in go grather information from helper scripts written in PLPython a sort of SQL mixed with Python. 
Looking at the documentation https://www.postgresql.org/docs/10/plpython.html I read:

> PL/Python is only available as an “untrusted” language, meaning it does not offer any way of restricting what users can do in it and is therefore named plpythonu. A trusted variant plpython might become available in the future if a secure execution mechanism is developed in Python. The writer of a function in untrusted PL/Python must take care that the function cannot be used to do anything unwanted, since it will be able to do anything that could be done by a user logged in as the database administrator. Only superusers can create functions in untrusted languages such as plpythonu.

Suppose I want use pgwatch2 to monitor a database cluster in production (future development with Patroni support will be appreciate) and I created a role pgwatch2 (so I don't have to change the sql helpers) for it in my database. What is the risk I can have in this configuration?

**Comment by kmoppel** [comment]
Hi! Well the risk would be quite managed. If the created "pgwatch2" role is a normal login role with no extra privileges, then someone would have to find a security hole in the way Postgres manages SECURITY DEFINER in stored procedures to abuse the setup. But as finding a security hole in Postgres is quite hard...I would say risk is minimal :)

**Comment by kmoppel** [comment]
FYI - Patroni support is also planned for the next future version

**Comment by sasadangelo** [comment]
thanks
