### ISSUE TITLE
Expose or document data data storage locations

### ISSUE THREAD

**Issue by merrill-oakland** [cybertec-postgresql/pgwatch2#14]
It would be very helpful if the locations for the various configs and data stores (postgres, Influx, Grafana) were exposed in docker (or at least their paths documented) so we can save setups between container reloads.

**Comment by kmoppel** [comment]
Hi! @merrill-oakland I've created a branch for updating documentation on that, please take a look [here] -(https://github.com/cybertec-postgresql/pgwatch2/tree/better_readme). Especially the last section. Does it already make things clearer?

**Comment by merrill-oakland** [comment]
Yes, that helps a lot!

**Comment by kmoppel** [comment]
Good. In master now:)
