### ISSUE TITLE
How to install PLPython in not standard way - Question

### ISSUE THREAD

**Issue by sasadangelo** [cybertec-postgresql/pgwatch2#140]
Hi,

Currently, I am involved in a project where we are investigating possible monitor tools to sunset the one we are using based on Grafana e in house tool. For monitoring our cluster we are evaluating pgwatch2 and I am investigating how to use it properly. I know several metrics we are interested in are managed through plpython. This language is easy to install on a machine like Redhat/Ubuntu with standard apt-get/yum. However, we currently are using Cloud Foundry Postgres release that is installed in a custom way under a special folder. How I can install PLPython in a custom way so that I have pgwatch2 metrics working? I know this is more a PLPython question than pgwatch2 but after some search, I am unable to find a doc that allow doing that.
Any suggestion?

**Comment by kmoppel** [comment]
Hi,
You're right...it's a question more for the cloudfoundry/postgres-release project. I took a quick look there though and only saw only a couple of extensions mentioned...so not so good chances that "plpythonu" is allowed. To make sure though, please raise an issue with the project...
