### ISSUE TITLE
is it working with aws 10.6 database

### ISSUE THREAD

**Issue by hpolonskaya** [cybertec-postgresql/pgwatch2#141]
does it work with AWS

**Comment by kmoppel** [comment]
Hi, yes it does. All modern PG versions can be used. But with AWS RDS you can't use Python helpers so some out-of-the-box dashboards have some empty panels. With some work (adding AWS Cloudwatch datasource and changing panel definitions) this can be overcome though - see the AWS panel ![AWS](https://raw.githubusercontent.com/cybertec-postgresql/pgwatch2/master/screenshots/aws_rds_cloudwatch_overview.png)
