### ISSUE TITLE
custom metric Not working 

### ISSUE THREAD

**Issue by darshansh** [cybertec-postgresql/pgwatch2#142]
Hi Kmoppel, 

I have installed docker in ubuntu and install latest pgwatch2. I have added one custom metric to add new dashboard to monitor what is running currently. 
I used below query in localhost:8080 for new metric. 

![image](https://user-images.githubusercontent.com/14271741/53478486-f28ac280-3a9c-11e9-926c-bcebeab53708.png)

![image](https://user-images.githubusercontent.com/14271741/53478467-e141b600-3a9c-11e9-8b6d-d9abd9e3d14a.png)

The issue is I get the list of this metric in grafana. However I can show all columns from my query so I can not show all columns on dashboard. I'm good in SQL only. I'm not getting what is the issue. Could you please let me know what I missed ? 

![image](https://user-images.githubusercontent.com/14271741/53478716-7c3a9000-3a9d-11e9-83c0-f08bd623d1c3.png)

**Comment by kmoppel** [comment]
Ahha yes, this is because Grafana can only show "normal" InfluxDB columns, not "tagged" columns.
Tags are meant to be used for filtering (fast search) and grouping (group by) so just remove the "tag_" prefixes you don't plan to use for filtering / grouping.

**Comment by darshansh** [comment]
Hi Kmoppel, 
I'm still getting error in pgwatch2 error log.  And now I can not select the new metric in grafana. 

![image](https://user-images.githubusercontent.com/14271741/53491378-43f67a00-3abc-11e9-947f-7bad38e5c47a.png)

**Comment by kmoppel** [comment]
@darshansh this is cause by the fact that your query is returning some datatypes internal to postgres, which are not recognized by Influx. Influx only eats integer, float, text and boolean. So just add some casts:```
SELECT (extract(epoch from now()) * 1e9)::int8 as epoch_ns, datname::text, state::text, usename::text, pid::text as pid from pg_stat_activity           where datid>0 order by datid;```

**Comment by darshansh** [comment]
Thank you so much Kmoppel. Now I can see the metric in grafana and also columns as well. 

Could you please share any document using which I can learn how to write queries in grafana+influxdb while storing and fetching data from influxdb.

One more thing here  , I want to remove some queries from the query output using NOT like '%epoch_ns%' (this is in SQL). How can I do this in grafana ?  I tried to use Regex expression but no luck.

Thanks for your quick response. Your answers have given me good guidelines to make  and use custom metrics.

**Comment by kmoppel** [comment]
@darshansh Glad that you got it to work!
About writing Influxdb queries for Grafana...the official [docus](https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-basic-select-statement) would be starting place nr 1 I think. Also you could take a look at existing Dashboard queries [here](https://github.com/cybertec-postgresql/pgwatch2/tree/master/grafana_dashboards/v5).

And to exclude queries generated by pgwatch2 itself I've used something like that:
```
... AND "query" !~ /(?i)::int8[\s+]as[\s]+epoch_ns/ ...
```
