### ISSUE TITLE
How to monitor pgbouncer statistics - Question

### ISSUE THREAD

**Issue by sasadangelo** [cybertec-postgresql/pgwatch2#143]
Hi,

I have a PostgreSQL cluster and I am evaluating pgwatch2 for cluster monitoring. Currently, I am connecting to a pgbouncer and try to understand how to monitor pgbouncer statistics for my database.

From my understanding, looking at the code the pgbouncer plugin simply run a show stats and use this data to monitor pgbouncer statistics for a given database. I have only one database called "appcloud" and doing show stats on pgbouncer database I see data for pgbouncer db (all to 0) and the one for appcloud (with given value).

Connection to localhost:8080 it's not clear to me how to declare my connection to see data.

I configured:
hostname: ip
port: 5432
dbname: appcloud
user: myuser
pwd: mypwd
Auto-create helpers: enabled
Preset config=pgbouncer

The problem is that I do not know if this way to configure the connection is correct. Can you help me on this? However, what does Preset config mean?

**Comment by kmoppel** [comment]
Hi,
For PgBouncer pool monitoring you just need to note 3 things:
1) Set "DB type" to "pgbouncer"
2) To "DB dbbname" field add the name of the pgbouncer.ini configured pool name you wish to get statistics on
3) Set "Preset config" to "pbouncer" or configure the "pgbouncer_stats" metric with your own interval under "Custom config". Preset configs are just a bunch of metrics and intervals bundled together. You can change them also on "Metric definitons" tab.

Also it does not make sense to tick the "auto create helpers" flag as helpers can only be created for normal Postgres DB and it will just generate some errors in the log (i've fixed it in master branch though, not to even try creating for pgbouncer).

**Comment by sasadangelo** [comment]
Hi,

It does not work. I want to monitor on Grafana both my db and pgbouncer.
Here what I did:

Configured a connection for pgbouncer:
Unique name: pgbouncer
DB type: pgbouncer
Host: my ip
Port: 5432
DB dbname: <pool name in pgbouncer.ini [pgbouncer]>
DB user: <user with authority to access pgbouncer>
DB password: <pasword of user with authority to access pgbouncer>
Auto create helpers?: unchecked
Preset config: pgbouncer

Then I create another connection for my postgres db that I want to monitor too:
Unique name: appcloud
DB type: postgres
Host: my ip
Port: 5432
DB dbname: appcloud
DB user: <user with authority to access appcloud>
DB password: <pasword of user with authority to access appcloud>
Auto create helpers?: checked
Preset config: full

Now if I do "show stats" on pgbouncer machine I see:
 database  | total_requests | total_received | total_sent | total_query_time | avg_req | avg_recv | avg_sent | avg_query 
-----------+----------------+----------------+------------+------------------+---------+----------+----------+-----------
 appcloud  |            247 |          36129 |     332374 |          1832347 |       0 |       62 |       92 |      2141
 pgbouncer |             10 |              0 |          0 |                0 |       0 |        0 |        0 |         0

However, on Grafana for pgbouncer stats I only see two db: pgbouncer and appcloud. It's not clear to why I do not see only appcloud. I know pgbouncer is only a fake db.

If I select pgbouncer I see statistics only for Incoming and Outgoing traffic rate. If I select appcloud I see nothing. This does not match with what I see with "show stats". As you can see in the snapshot above, appcloud contains data for each column but I do not see them. For pgbouncer I see 0 only for Incoming traffic rate (the field total_received) that is 0 and Outgoing traffic rate (the field total_sent) that is 0.

Can you explain to me how this is supposed to work?

**Comment by sasadangelo** [comment]
@kmoppel ^^^

**Comment by kmoppel** [comment]
@sasadangelo Hi, I guess it could be just a Grafana display issue? Seems currently for the "Pgbouncer" dashboard also normal (DB type = postgres) "DB uniques" were displayed. Could you reload the dash from [here](https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/v5/pgbouncer-stats/dashboard.json)?
Otherwise the metrics gathering looks Ok to me, did a small test setup locally.
