### ISSUE TITLE
Which Postgres version is supported as a metrics store?

### ISSUE THREAD

**Issue by imsky** [cybertec-postgresql/pgwatch2#144]
On Postgres 10, we get "cannot create index on partitioned table" when running `EnsureMetricDummy`. On Postgres 9.6 we get "pq: syntax error at or near "PARTITION"" when doing the same. Is there something that has to be tweaked in order to get a Postgres metrics store working, or are 9.6-10 unsupported versions for a metrics store?

**Comment by kmoppel** [comment]
Hi, yes it's possible to use lesser versions than PG11 with "metric" and "custom" schema types. See the "metric_store" [README](https://github.com/cybertec-postgresql/pgwatch2/tree/master/pgwatch2/sql/metric_store) for more

**Comment by imsky** [comment]
I see, we're using metric-time, which the README states is for PG11+ only.
