### ISSUE TITLE
How to filter some queries which are for collecting data for pgwatch2 metric. 

### ISSUE THREAD

**Issue by darshansh** [cybertec-postgresql/pgwatch2#145]
Hi , 

As shown in the picture, these are some statements which are executed due to metric collection in pgwatch2. How we can exclude these data ?  
![image](https://user-images.githubusercontent.com/14271741/53545216-b44ddb80-3b4e-11e9-9899-c10c0ab7ec61.png)

**Comment by kmoppel** [comment]
Some pre-configured (Influx) dashboards are using something like that:
 `... AND "query" !~ /(?i)::int8[\s+]as[\s]+epoch_ns/ ...`
It assumes of course that there are no other / normal queries with SQL containing "::int8 as epoch"
