### ISSUE TITLE
About the monitoring template "System Stats"

### ISSUE THREAD

**Issue by hp521yu** [cybertec-postgresql/pgwatch2#147]
About the monitoring template "System Stats"
System version "Centos 6.5"
Database version "9.4.6"

I have executed "pip3 install psutil"

> [postgres@L~]$pip3 install psutil 
Requirement already satisfied: psutil in /postgres/python3/lib/python3.6/site-packages (5.6.0)
[postgres@L~]$python3
Python 3.6.5 (default, Mar  7 2019, 11:38:04) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
import psutil
 psutil.cpu_count()
4
psutil.cpu_times()
scputimes(user=924.57, nice=0.0, system=313.53, idle=34389.5, iowait=75.35, irq=9.02, softirq=53.68, steal=0.0, guest=0.0)

Monitoring template prompt "No data points"
The log error message is as follows:

> 2019/03/09 18:54:48 ERRO MetricGathererLoop: Failed to fetch metric data for [L_185_postgres:psutil_disk_io_total]: pq: ImportError: No module named psutil
2019/03/09 18:54:48 ERRO MetricGathererLoop: Total failed fetches for [L_185_postgres:psutil_disk_io_total]: 107
2019/03/09 18:54:48 ERRO MetricGathererLoop: Failed to fetch metric data for [L_185_postgres:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/03/09 18:54:48 ERRO MetricGathererLoop: Total failed fetches for [L_185_postgres:psutil_cpu]: 107

Other monitoring templates are normal
Is it my database configuration file, what parameters are missing?
Please help, thank you very much.

**Comment by kmoppel** [comment]
I think the issue is that you only installed "psutil" for python3. So basically you need to decide if you want the "helpers" in pyton 3 or 2. With 2 it would be easier as the default [helpers](https://github.com/cybertec-postgresql/pgwatch2/tree/master/pgwatch2/sql/metric_fetching_helpers) are for python2, so for 3 you would need to change the `LANGUAGE plpythonu` part. More on creating helpers in the [README](https://github.com/cybertec-postgresql/pgwatch2#steps-to-configure-your-database-for-monitoring)

**Comment by hp521yu** [comment]
Thank you very much for your reply!
As you said, this is the case.
In order to run the "web.py" script. I deliberately compiled Python3
Python3 has "psutil" installed. However, Python 2 that comes with this machine does not have "psutil" installed.
I think pgwatch2 is currently the best monitoring solution for PostgreSQL.
But the deployment documentation on GitHub. Some configuration about the template, there is still a little rough. Will there be more in-depth configuration documentation in the future?
Maybe because I am a rookie.
Thank you very much for your help!

**Comment by hp521yu** [comment]
Configuring ‘pstuil’ again today.
If you find that this module needs to obtain part of the data of the cpu, the system needs to meet the kernel version greater than 3.2.
Otherwise some parameters will not be available.

> [postgres@L~]$python3
> Python 3.6.5 (default, Mar 7 2019, 11:38:04)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
> psutil.cpu_times()
> scputimes(user=924.57, nice=0.0, system=313.53, idle=34389.5, iowait=75.35, irq=9.02, softirq=53.68, steal=0.0, guest=0.0)

> psutil.cpu_times()
> scputimes(user=8.28, nice=0.0, system=7.44, idle=390.28, iowait=1.19, irq=0.0, softirq=0.49, steal=0.0, guest=0.0, guest_nice=0.0)

guest_nice=0.0 （Need kernel > 3.2）

Finally, the "System Statistics" monitoring template will prompt "cpu no data points"

**Comment by kmoppel** [comment]
@hp521yu Thanks a lot for the info on psutil min requirements! I've add a notice to the README on [that](https://github.com/cybertec-postgresql/pgwatch2#warning--notice-on-using-metric-fetching-helpers).
And you're probably right about current documentation insufficiencies....a lot could be improved so to somehow start I've opened a new [issue](https://github.com/cybertec-postgresql/pgwatch2/issues/148) for that purpose...please highlight your pet peeves again there. Thanks!
