### ISSUE TITLE
Documentation improvement ideas

### ISSUE THREAD

**Issue by kmoppel** [cybertec-postgresql/pgwatch2#148]
This ticket is meant to log user feedback on current documentation insufficiencies and ideas for improvements. All ideas welcome, please add a comment if you find something illogical or missing. Thank you!

**Comment by ALTELMA** [comment]
How to edit Grafana.ini when I use docker option? I try to search, but not found.
Please suggest to me.

**Comment by kmoppel** [comment]
> How to edit grafana.ini when I use docker option? I try to search, but not found.
> Please suggest to me.

Hi, Grafana config is in /etc/grafana/grafana.ini (mostly all at defaults)...so something like that
```
vim /etc/grafana/grafana.ini
/etc/init.d/grafana-server restart
```

**Comment by ALTELMA** [comment]
I use docker if I did like you mention. It will disappear after run docker next time, right?

**Comment by kmoppel** [comment]
@ALTELMA it will persist on normal stop / restart...but when you want it to be really persistent, also when updating to a newer pgwatch2 Docker image, then yes you should declare an explicit volume yourself for the config file or set up Grafana without Docker.

**Comment by ALTELMA** [comment]
OK, thank you :)

**Comment by atkaiser** [comment]
Just want to note that `/etc/init.d/grafana-server restart` didn't work for me and I had to run `supervisorctl restart grafana` instead to get grafana to restart correctly

**Comment by rostamiani** [comment]
When installing with Config DB, I had to add some other environments to the `pgwatch2-webui.service` to make it work:

```text
[Service]
Environment="PW2_WEBPORT=8081"
Environment="PW2_PGHOST=localhost"
Environment="PW2_DATASTORE=postgres"
Environment="PW2_PG_METRIC_STORE_CONN_STR= dbname=pgwatch2_metrics user=pgwatch2"
Environment="PW2_PGPASSWORD=yourpass"
```

Beside that, there is no documentation about parameters like `PW2_PGPASSWORD`. I had to look in the code for this param.

**Comment by rostamiani** [comment]
I didn't find any documentation for PGBouncer configuration.

**Comment by kmoppel** [comment]
@rostamiani Thanks for the input! It's sadly impossible to configure or document all possible different input parameter configurations as it's specific to used environment. But `PW2_PGPASSWORD` is actually listed in the ENV file - https://github.com/cybertec-postgresql/pgwatch2/blob/master/ENV_VARIABLES.md#web-ui

PgBouncer usage has some documentation lines here: https://pgwatch2.readthedocs.io/en/latest/advanced_features.html#pgbouncer-support

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.
