### ISSUE TITLE
[documentation] Ability to disable default built-in metrics

### ISSUE THREAD

**Issue by DavidPavlicek** [cybertec-postgresql/pgwatch2#149]
It would be nice to have the option to cleanly disable default builtin metrics (bloat, hashes). I can disable metric definitions, but that produces errors in log like these:

> 2019/03/27 05:17:01 ERRO GetMetricVersionProperties: metric table_hashes not found
> 2019/03/27 05:17:01 ERRO DetectTableChanges: could not get table_hashes sql: metric SQL not found

These metrics are pretty expensive (thus long running) in large databases and can block out DDL statements in other sessions.

In fact, I'm a big fan of transparent approach -> do nothing in the background if there is no preset or custom configuration specified for a database.

**Comment by kmoppel** [comment]
Hi! @DavidPavlicek  are you sure you removed built-in metrics also from the active configs? "table_hashes" should be only used when the special "change_events" (keeps some state unlike others) metric is active...

**Comment by DavidPavlicek** [comment]
Thanks, @kmoppel, as you wrote, I didn't remove change_events from my configs! I just spotted problematic metric SQL in our logs, didn't find them in server configs, so I simply disable corresponding metrics. My fault, but maybe it will be helpful to have a hint on these metrics that they are related to each other...

**Comment by kmoppel** [comment]
ok good, then there's no immediate bug at least...but you're right, it's not explicitly documented :))

**Comment by kmoppel** [comment]
Added some info to README now https://github.com/cybertec-postgresql/pgwatch2/commit/c6cce4fd63d6c0dfa5fe075b2c792cb7c0c6ad4a
