### ISSUE TITLE
Feature request - Metrics change_events - add Grant events

### ISSUE THREAD

**Issue by nicolas-lutic** [cybertec-postgresql/pgwatch2#150]
Hello, 
In addition to events (`create`,`drop` and `update`),  the `grant` event would be interesting.
What do you think about that?
Thanks.

Nicolas.

**Comment by kmoppel** [comment]
@nicolas-lutic That could be useful indeed from a security perspective...backlogged :)

**Comment by kmoppel** [comment]
Implemented in master, will be released next weeks with v1.8
