### ISSUE TITLE
upgarde from 1.4.0 to 1.5.1

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#151]
Hello, i have upgraded the docker image from 1.4.0 to 1.5.1
i face this error ERROR: column "m_master_only" does not exist LINE 4: ...cond', m_last_modified_on) as m_last_modified_on, m_master_o... ^

Do i have to execute some sql script in the pgwatch db itself ?

thx

**Comment by kmoppel** [comment]
Yes, exactly. Please look into the SQL migrations [folder](https://github.com/cybertec-postgresql/pgwatch2/tree/master/pgwatch2/sql/config_store/migrations).

It's noted in the CHANGELOG also btw:
 ```
NB! When migrating old "config DB" based setups, all previous schema migration diffs with bigger version numbers need to be applied first from the "pgwatch2/sql/config_store/migrations/" folder.```

**Comment by pmpetit** [comment]
thx
