### ISSUE TITLE
Question python version

### ISSUE THREAD

**Issue by jacks33** [cybertec-postgresql/pgwatch2#155]
Hello,

I have a question about a python version.

In the server of the web api python 3 is required (there is one postgreSQL instance as well).

In monitored postgres instances it seems possible to use python 2.7.

My question is about the behaviour of package postgresqlXX-plpython-X.X.Y-1PGDG.rhel7

It seems it is not directly linked  to python version package will this package works if python 2.7 and python 3 are installed ? Which version postgres will use ?

Thanks you very much
Tiago ANASTACIO

**Comment by kmoppel** [comment]
Hi!
Yes, in monitored instances there's no big difference if to use version 2 or 3 for the helpers - you might need to only adjust the "LANGUAGE plpython3u" part.  And yes plpython itself is not directly linked to some specific minor python version so you don't need to worry about X.X.Y matching.
Hope it answered your question.
