### ISSUE TITLE
dbname filter dropdown either empty or only shows "All"

### ISSUE THREAD

**Issue by jf912** [cybertec-postgresql/pgwatch2#158]
I am running the docker image and have manually added 3 databases (from one server) from the admin screen on port 8080.  Statistics are being collected.  However, on any of the Grafana dashboards, the dbname filter dropdown box is either empty or shows "All".  There does not appear to be a way to filter my results to a single database.

**Comment by kmoppel** [comment]
Hmm, for me seems to work fine.. @jf912 could you please specify exactly what image are you using (influx or postgres based and which version / image hash). Usually this type of stuff happens when the default data source is changed to something else as it was out-of-the-box.

**Comment by jf912** [comment]
It's an influx image hash: cybertec/pgwatch2@sha256:4c35f818ac409efb10be6c99ef99440a896dafca5e6d9cfa85086aacbd42463b

I did not change the data source. I deleted the image and tried again several times but each time I got the same results.

Thanks for checking this out!

Jeff

**Comment by kmoppel** [comment]
@jf912 still works for me...must be a setup issue then...do logs have some errors?

**Comment by jf912** [comment]
2019/05/14 14:15:03 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2019/05/14 14:15:08 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2019/05/14 14:15:13 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2019/05/14 14:15:18 CRIT main: Could not initialize InfluxDB Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused

Port 8086 is in LISTENING state in the container:
tcp    LISTEN     0      128    :::8086                 :::*

**Comment by kmoppel** [comment]
hmm seems something went wrong when starting influxdb....previously I've seen it happen one time on weak hardware (influx is a bit resource hungry)...could you maybe try again? or exec into the docker image and do `supervisorctl start influxdb` ? or also if it's not really important if metrics are stored in influx you can try the postgres image: `cybertec/pgwatch2-postgres`

**Comment by jf912** [comment]
2019/05/14 14:15:03 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2019/05/14 14:15:08 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2019/05/14 14:15:13 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2019/05/14 14:15:18 CRIT main: Could not initialize InfluxDB Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused

Port 8086 is in LISTENING state in the container:
tcp    LISTEN     0      128    :::8086                 :::*

**Comment by jf912** [comment]
I switch to the postgres image.  Now, I can't view the statistics page on port 8080. When I try, I get "ERROR - Could not connect to InfluxDB".  Are metrics collection stats only available with Influx image?  Also, the dashboard database names are still blank or show "None". Not even the test database.  This is straight out of the box. I changed nothing.

**Comment by slimlime** [comment]
Following quick start - out of the box experience does not work...

Would expect the docker containers to work without further configuration when following any of the predefined commands, let alone tuning specific parameters.

No dbnames available for selection in Grafana dashboards (not even the "test" database shown in the demo)
* this was testing the various installations such as default pgwatch2, -postgres, with test flags enabled/disabled

Among the other testing trying different runs I also came across that could not connect or no data source in Grafana when viewing the pre-baked dashboards.

Dashboard tiles showing random stats like A-series with arbitrary rows of float (?) numbers that seem to change when clicking refresh that I did not expect from the demo.

Issue closed prematurely?

Thanks

**Comment by slimlime** [comment]
No timestamps column but maybe the A-series is the intended randomised data from the test config db?

dbname does not show up as "test"
either empty or "All" as @jf912 noted

**Comment by kmoppel** [comment]
@slimlime I'm guessing that something went wrong in the initialization step - there are some timeouts built-in into the bootup scripts. Usually this happens only on very low-end hardware...so maybe just try again a couple of times. For me it seems to work - on a fresh VM after executing the command from the quick-start section I get this from Grafana:
![Screenshot from 2020-11-26 13-05-52](https://user-images.githubusercontent.com/346788/100343777-7d894b80-2fe8-11eb-98d6-92415f826b99.png)

**Comment by slimlime** [comment]
Hi @kmoppel

Thank you for following up.


That screenshot shows port 9000 (different?)

could you please share another quick start command?

It works in my (personal) alternative non-corporate environment (looks really good! 🚀  @kmoppel ) ; however, I assumed the major benefits of Docker is that these containers are not beholden to some arbitrary timeouts and should be reproducible ~ one-click.

The non-working environment in a fresh VM has much higher specs (tested 2x 4x vCPU + RAM) than the docs' minimum sizing specification and still shows those dashboards with arbitrary randomising data points (randomness can be seen all changing on every dashboard force refresh - impossible negative numbers) - no testdb, All / empty blank dbname dropdown weirdness in Grafana per this issue. 

Adding/removing database in the pgwatch webGUI has no effect here
( outside of that environment everything seems to _just work_  with no special hacks, though )

**Comment by kmoppel** [comment]
@slimlime I used exactly the same quick-start command actually, just used another port as had on instance already running.
But now I've just run the exact command from the quick-start on a fresh AWS EC2 t3.micro VM (2vCPU, 1GB RAM) and it started up nicely, no problems. So I can't really help much here currently without some error logs for example :/
Those Grafana dashboards with random data points are best ignored though, they're dummy placeholders to visualize what can be done.
