### ISSUE TITLE
Issue with long db name in postgresql metric store

### ISSUE THREAD

**Issue by henriavelabarbe** [cybertec-postgresql/pgwatch2#159]
Hi,
I got an issue with pgwatch2 when using the postgresql metric store (metric-dbname-time).
Partition names created by the function ensure_partition_metric_dbname_time get too long for the standard maximum identifier name in Postgresql.
The result is that no more metrics are collected, making pgwatch unusable.

I'm using continuous-discovery with a prefix named as the clustername.
Due to our naming convention, the DB name can be quite long.

I first tried to modify the metric names as a quick workaround, but I think it should be best to adapt the function so it would work with all situations, based on the name length limits in standard Postgresql distributions.

Regards,
Henri Chapelle

**Comment by henriavelabarbe** [comment]
I added a pull request using md5sum to get shorter partition names, it works for me but need additional testing.

**Comment by kmoppel** [comment]
Adding link to PR for reference https://github.com/cybertec-postgresql/pgwatch2/pull/160

**Comment by kmoppel** [comment]
Implemented in v1.6.0
