### ISSUE TITLE
Not getting alert mail from pgwatch2

### ISSUE THREAD

**Issue by darshansh** [cybertec-postgresql/pgwatch2#161]
Hi , 
I have configured alert in one dashboard however not getting alert mail. Could you please provide any guideline or document available for alerting system in pgwatch2?  

![image](https://user-images.githubusercontent.com/14271741/58098252-c348a500-7bf6-11e9-8769-9a46686c0b20.png)

**Comment by kmoppel** [comment]
Hi @darshansh , pgwatch2 does not do any alerting configuration - it's all about how you use Grafana (docs: https://grafana.com/docs/alerting/rules/), so I don't want to give too much advice here.
But as the error says there are some limitations - one of them being that you cannot use templates so  you'd need to alter the dashboard. Or I'd even recommend to create a separate dashboard for only alerting purposes.
