### ISSUE TITLE
install on server which branche

### ISSUE THREAD

**Issue by jacks33** [cybertec-postgresql/pgwatch2#164]
Hi,

I would like to install latest release of pgwatch2 on servers rhel 7 (metrics DB will be postgreSQL)

So I will follow manual instructions.

But  I don't find a github branch called "1.6.0"

Which branch (in github) should I fetch ?

Thank you

**Comment by kmoppel** [comment]
Hi, for me its there - https://github.com/cybertec-postgresql/pgwatch2/tree/v1.6.0
I usually just use the master branch btw, it's "stable enough" :)
