### ISSUE TITLE
k8s and deployment with ingress

### ISSUE THREAD

**Issue by debellabre** [cybertec-postgresql/pgwatch2#165]
Hello,
I can not get the 2 URLs (webui and grafana) at the same time when I go through an ingress instead of a NodePort. I have a proxy problem that forces me to put / as a path in the ingress for it to work. Is this normal? should I use an external grafana in the case of a depletion on k8s? Or is there a variable to position for the 2 to work at the same time?

INGRESS (webui OK, grafana KO)
"spec": {
    "rules": [
      {
        "host": "infra.isocel.info",
        "http": {
          "paths": [
            {
              "path": "/",
              "backend": {
                "serviceName": "pgwatch2-webui",
                "servicePort": 8080
              }
            }
            {
              **"path": "/grafana"**,
              "backend": {
                "serviceName": "pgwatch2-grafana",
                "servicePort": 3000
              }
            }
          ]
        }
      }
  
L'INGRESS (webui KO, grafana OK)
"spec": {
    "rules": [
      {
        "host": "infra.isocel.info",
        "http": {
          "paths": [
            {
              "path": "/pgwatch2",
              "backend": {
                "serviceName": "pgwatch2-webui",
                "servicePort": 8080
              }
            },
            {
              **"path": "/",**
              "backend": {
                "serviceName": "pgwatch2-grafana",
                "servicePort": 3000
              }
            }
          ]
        }
      }

Extract file yaml  Deployment
containers:
      - image: {{ pgwatch2.image }}
        imagePullPolicy: IfNotPresent
        name: {{pgwatch2.nom_container}}
        env:
        - name: GF_SERVER_DOMAIN
          value: {{host_dns}}
        - name: GF_SERVER_ROOT_URL
          value: http://{{host_dns}}/grafana
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: pgwatch2admin
        - name: GF_AUTH_LDAP_ENABLED
          value: "false"   
        ports:
        - containerPort: 3000
          name: grafana
          protocol: TCP
        - containerPort: 8080
          name: admin-ui

**Comment by kmoppel** [comment]
hugh, i'm afraid can't help too much with k8s ingress topics...@ermajn - can you maybe pick up some signals from the description?

**Comment by Martin-Hogge** [comment]
Hi ! Did you finally find a solution ?
Thank you.

**Comment by debellabre** [comment]
Je suis absent(e) du bureau jusqu'au 02/11/2020

Si urgent merci de contacter le support  technique Isocel

support-technique@isocel.info


Remarque : ceci est une réponse automatique à votre message  "Re:
[cybertec-postgresql/pgwatch2] k8s and deployment with ingress (#165)"
envoyé le 27/10/2020 11:23:41.

C'est la seule notification que vous recevrez pendant l'absence de cette
personne.

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.
