### ISSUE TITLE
Patroni continuous discovery config cannot be created

### ISSUE THREAD

**Issue by nvarscar** [cybertec-postgresql/pgwatch2#166]
Constraint `monitored_db_md_dbtype_check`
defined as `md_dbtype in ('postgres', 'pgbouncer', 'postgres-continuous-discovery', 'patroni'), which doesn't allow for `patroni-continuous-discovery` md_dbtype to be created.
The following SQL code modifies the constraint accordingly:
```
alter table pgwatch2.monitored_db
drop constraint monitored_db_md_dbtype_check,
add constraint monitored_db_md_dbtype_check
check (md_dbtype in ('postgres', 'pgbouncer', 'postgres-continuous-discovery', 'patroni', 'patroni-continuous-discovery'));
```

**Comment by kmoppel** [comment]
Thanks for letting know! An oversight ineed. Labeled SQL fix script as upcoming 1.6.1 already.
