### ISSUE TITLE
Question: can I store PostgreSQL metrics in Prometheus data model and use Grafana to display them?

### ISSUE THREAD

**Issue by sasadangelo** [cybertec-postgresql/pgwatch2#169]
Hi,

I need to monitor a Patroni cluster and I need to monitor PostgreSQL metrics and Linux node metrics (CPU, Memory, etc.). For several reasons I cannot use the python extension library in PostgreSQL so I need to use Prometheus agent on the node that exports the node metrics via HTTP.

Now in order to avoid to use InfluxDB for PostgreSQL metrics and Prometheus data model for node metrics, I was wondering if I could use just one of them.

Since the go controller allows to store data in the Prometheus data model I thought I could use just this one to store my data and then let Grafana display the data from here.

However, I noticed in the code there is only one dashboard for Prometheus (db-overview-dashboard for developers). 

Suppose I could change the pgwatch2 code, is there any technical reason why you didn't develop all the dashboard for Prometheus? Technically is it possible to store all data in Prometheus data model and show them via Grafana? If so, what part of code should I change to support this?
Thanks in advance for help.

**Comment by kmoppel** [comment]
Hi, basically yes I think 95% of dashboards could be created 1 to 1 also for Prometheus. The only limitation is that in Prometheus you can have only numeric measurements thus need to play more with "labels". But to save on the amount of work and as we as a company don't use Prom yet, made no sense to invest that time yet. Contributions there would be very welcome though!

**Comment by kmoppel** [comment]
Prometheus is now supported as of v1.6.

**Comment by surajthakur** [comment]
@kmoppel 
I was trying pgwatch2 using prometheus as a datastore. I thought metrics coming through, but there is only one dashboard available in git for prometheus as datasource. 
Will there be more dashboards available in future for prometheus ?

**Comment by kmoppel** [comment]
Hi @surajthakur , currently not on the TODO list...as we don't use too much Prometheus ourselves...but feel free to create an enhancement ticket on that. Or just browse what is out there for ideas - this old issue might be a starting point: https://github.com/wrouesnel/postgres_exporter/issues/218
