### ISSUE TITLE
A  little advice about pgwatch2

### ISSUE THREAD

**Issue by jwh5566** [cybertec-postgresql/pgwatch2#17]
hello @kmoppel 
about pgwath2, I have a little advice. pgwatch2 default provide some graph, could provide some default threshold value about the metric alert.
I not the pg dba, but as a sys admin, that will helps  a lot, just the advice. I hope the application become better and better.
thanks for the develop team.

**Comment by kmoppel** [comment]
Now I  tend to think that "global alert thesholds" are still not a good idea - people have very distinct ideas about "good performance", it depends on available hardware and test/production servers might have also very different criticality  classes. Thus closing
