### ISSUE TITLE
How do we install  PGWATCH2 docker container 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#173]
Hi ,
We need help on installing/downloading pgwatch2 docker image from the GitHub site - 
How to get the container and put on my centos Linux server , and then run it?
Would you please provide me the steps/documentation on it?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Hi, for Docker I think there should be no big problems once you follow the [README](https://github.com/cybertec-postgresql/pgwatch2#installing)

**Comment by bikramma** [comment]
Hi  Kaarel,
Thanks for your quick response.
HOWEVER we are not able to install – getting the following error.

[root@cemtore01 ~]# docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2
Unable to find image 'cybertec/pgwatch2:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.40.151:53: read udp 192.168.40.143:57156->192.168.40.151:53: i/o timeout.
See 'docker run --help'.

Bikram Majumdar
Sr Software Developer/DBA, Aqsacom Inc.
c. 1.972.365.3737

[cid:image002.png@01D55682.5F2846F0]<http://www.aqsacom.com/>

Disclaimer. This electronic mail message contains CONFIDENTIAL information which is (a) CUSTOMER / SUPPLIER / PARTNER PRIVILEGED COMMUNICATION, WORK PRODUCT, PROPRIETARY IN NATURE, OR OTHERWISE PROTECTED BY LAW FROM DISCLOSURE, and (b) intended only for the use of the Addressee(s) named herein. If you are not an Addressee, or the person responsible for delivering this to an Addressee, you are hereby notified that reading, copying, or distributing this message is prohibited. If you have received this electronic mail message in error, please reply to the sender and take the steps necessary to delete the message completely from your computer system. Statement and opinions expressed in this e-mail are those of the sender, and do not necessarily reflect those of AQSACOM. AQSACOM accepts no liability for any damage caused by any virus/worms transmitted by this email.

**Comment by bikramma** [comment]
Hi Kaarel
Any idea why we are receiving the following errors:

docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2
Unable to find image 'cybertec/pgwatch2:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.40.151:53: read udp 192.168.40.143:57156->192.168.40.151:53: i/o timeout.
See 'docker run --help'.
