### ISSUE TITLE
Can not install pgwatch2

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#174]
Hi  Kaarel,
Thanks for your quick response.
 we are not able to install following readme of install – getting the following error.

[root@cemtore01 ~]# docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2
Unable to find image 'cybertec/pgwatch2:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.40.151:53: read udp 192.168.40.143:57156->192.168.40.151:53: i/o timeout.
See 'docker run --help'.

**Comment by kmoppel** [comment]
Hi, sadly this has nothing to do witg pgwatch - it's probably some network restriction topic or something with Docker...
