### ISSUE TITLE
Can we download the pgwatch2 docker container 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#176]
[root@cemtore01 ~]# docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2
Unable to find image 'cybertec/pgwatch2:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.40.151:53: read udp 192.168.40.143:57156->192.168.40.151:53: i/o timeout.
See 'docker run --help'.

**Comment by bikramma** [comment]
Hi Karrel  - In response  to the above issue ( #174)  you indicated its a network restriction or docker issue.  Is there any way we can download the pgwatch2 docker container and put it into the docker repository?

**Comment by kmoppel** [comment]
@bikramma yes of course you could set up your own internal Docker registry (https://docs.docker.com/registry/deploying/) if needed and build also your own pgwatch2 Docker images from this project's Dockerfiles
