### ISSUE TITLE
Installation of pgwatch2 docker image

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#177]
Hi ,
 We have installed the pgwatch2 docker image  and running it from our database server with the following command: 
#docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2

Question 1. When we open db-overview   dashboard, we see a database test -  with a size of 7.2 MB.    
Who created it and when? Does it create any file (or any table) on the server that we can check?

Question 2. What is the use/meaning of -e PW2_TESTDB=true in the above  docker run command?

Question 3. What is the use/meaning of --name pw2 cybertec/pgwatch2
Question 4. Our postgres database is running on port 5433. How do we kill or rerun/restart the pgwatch2 docker container to expose port 5433 so that we can then add our database for monitoring?

**Comment by kmoppel** [comment]
Hi,
Q1/2: this "test" database you see is created by pgwatch indeed as result of this PW2_TESTDB env. variable. It's documented also in the README.
Q3: It's standard Docker usage - I'd recommend to do a plain install of separate components (https://github.com/cybertec-postgresql/pgwatch2#installing-without-docker) if Docker is new to you
Q4: You need to delete the old Docker container and launch a new one, I think it's not possible to change port mappings once container is created
