### ISSUE TITLE
We are not able to add database for monitoring

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#178]
2019/08/23 03:47:40 ERRO main: could not start metric gathering for DB "cemtore" due to connection problem: pq: no pg_hba.conf entry for host "172.17.0.2", user "cemtore", database "cemtore", SSL off

**Comment by bikramma** [comment]
Hi , we are not able to add our database for monitoring in the admin interface. We are getting the following error: 
2019/08/23 03:47:40 ERRO main: could not start metric gathering for DB "cemtore" due to connection problem: pq: no pg_hba.conf entry for host "172.17.0.2", user "cemtore", database "cemtore", SSL off.   
Just FYI - Our postgres database is running on port 5432.

**Comment by bikramma** [comment]
Our database is running on IP - 192.168.40.143 . How and why are we connecting to 172.17.0.2? And, which pg_hba.conf are we looking at?

**Comment by bikramma** [comment]
In the admin interface, we have entered the following values to add our database:
DB type - postgres
DB host - 192.168.40.143
DB port - 5432 
DB dbname - cemtore
DB user - cemtore

**Comment by bikramma** [comment]
I see the following pg_hba.conf files related to the installation: Why there are so many?. And which one is used? Can we modify the one we need to? 
/var/lib/docker/overlay2/1d2360cb31226b30db093cd0c9bd814dac27107da82aa4ceb1065c243b39f6d3/diff/etc/postgresql/9.5/main/pg_hba.conf
/var/lib/docker/overlay2/1d2360cb31226b30db093cd0c9bd814dac27107da82aa4ceb1065c243b39f6d3/diff/usr/share/postgresql/9.5/pg_hba.conf.sample
/var/lib/docker/overlay2/41f3994360a03aa76fef98cb2e1d93e4e29a5463c6b4120af29fd7ebdcdd502f/diff/etc/postgresql/9.5/main/pg_hba.conf
/var/lib/docker/overlay2/8d5075c5335aa21ae43cf16e8701bd90d2e52bacdeaed5a6e7da747336bcf03d/diff/pgwatch2/pg_hba.conf
/var/lib/docker/overlay2/d0d21c1d840d5adc514bc54a2e082765539678f866ed7b4eaa22addae86ff0e7/merged/etc/postgresql/9.5/main/pg_hba.conf
/var/lib/docker/overlay2/d0d21c1d840d5adc514bc54a2e082765539678f866ed7b4eaa22addae86ff0e7/merged/usr/share/postgresql/9.5/pg_hba.conf.sample
/var/lib/docker/overlay2/d0d21c1d840d5adc514bc54a2e082765539678f866ed7b4eaa22addae86ff0e7/merged/pgwatch2/pg_hba.conf

**Comment by kmoppel** [comment]
Sorry these are general PG access and Docker topics - please use Google
