### ISSUE TITLE
Errors in pgwatch2 log 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#179]
I have added my database in the admin interface. But, pgwatch log is showing the following errors:
Any idea what I have missed ?
019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:table_bloat_approx_summary]: pq: function get_table_bloat_approx() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 14:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 14:19:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 14:19:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 6
2019/08/23 14:20:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 14:20:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 12
2019/08/23 14:20:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 14:20:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 12
2019/08/23 14:20:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 14:20:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 12
2019/08/23 14:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 14:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 7
2019/08/23 14:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 14:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 7
2019/08/23 14:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 14:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 7
2019/08/23 14:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 14:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 7
2019/08/23 14:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 14:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 7
2019/08/23 14:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 14:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 5
2019/08/23 14:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 14:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 7
2019/08/23 14:29:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 14:29:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 11
2019/08/23 14:30:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 14:30:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 22
2019/08/23 14:30:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 14:30:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 22
2019/08/23 14:31:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 14:31:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 12
2019/08/23 14:31:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 14:31:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 12
2019/08/23 14:31:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 14:31:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 23
2019/08/23 14:31:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 14:31:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 12
2019/08/23 14:33:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 14:33:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 13
2019/08/23 14:33:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 14:33:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 13
2019/08/23 14:33:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 14:33:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 13
2019/08/23 14:33:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 14:33:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 9
2019/08/23 14:40:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 14:40:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 32
2019/08/23 14:41:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 14:41:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 17
2019/08/23 14:41:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 14:41:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 33
2019/08/23 14:42:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 14:42:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 34
2019/08/23 14:43:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 14:43:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 18
2019/08/23 14:43:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 14:43:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 18
2019/08/23 14:43:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 14:43:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 18
2019/08/23 14:43:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 14:43:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 18
2019/08/23 14:43:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 14:43:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 18
2019/08/23 14:45:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 14:45:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 19
2019/08/23 14:45:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 14:45:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 13
2019/08/23 14:51:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 14:51:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 43
2019/08/23 14:51:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 14:51:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 43
2019/08/23 14:53:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 14:53:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 23
2019/08/23 14:53:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 14:53:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 23
2019/08/23 14:53:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 14:53:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 45
2019/08/23 14:53:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 14:53:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 23
2019/08/23 14:55:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 14:55:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 24
2019/08/23 14:55:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 14:55:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 24
2019/08/23 14:55:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 14:55:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 24
2019/08/23 14:57:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 14:57:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 17
2019/08/23 14:57:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 14:57:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 25
2019/08/23 15:02:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 15:02:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 54
2019/08/23 15:02:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 15:02:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 54
2019/08/23 15:03:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 15:03:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 55
2019/08/23 15:03:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 15:03:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 28
2019/08/23 15:03:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 15:03:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 28
2019/08/23 15:05:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 15:05:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 29
2019/08/23 15:05:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 15:05:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 29
2019/08/23 15:05:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 15:05:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 29
2019/08/23 15:07:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 15:07:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 30
2019/08/23 15:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 15:09:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 21
2019/08/23 15:09:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 15:09:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 31
2019/08/23 15:12:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 15:12:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 64
2019/08/23 15:12:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 15:12:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 64
2019/08/23 15:14:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 15:14:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 66
2019/08/23 15:15:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 15:15:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 34
2019/08/23 15:15:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 15:15:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 34
2019/08/23 15:15:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 15:15:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 34
2019/08/23 15:17:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 15:17:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 35
2019/08/23 15:17:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 15:17:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 35
2019/08/23 15:17:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 15:17:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 35
2019/08/23 15:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 15:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 25
2019/08/23 15:21:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 15:21:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 37
2019/08/23 15:23:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 15:23:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 75
2019/08/23 15:23:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 15:23:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 75
2019/08/23 15:25:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 15:25:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 77
2019/08/23 15:25:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 15:25:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 39
2019/08/23 15:27:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 15:27:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 40
2019/08/23 15:27:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 15:27:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 40
2019/08/23 15:27:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 15:27:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 40
2019/08/23 15:27:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 15:27:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 40
2019/08/23 15:27:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 15:27:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 40
2019/08/23 15:33:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 15:33:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 85
2019/08/23 15:33:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 15:33:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 29
2019/08/23 15:33:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 15:33:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 43
2019/08/23 15:34:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 15:34:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 86
2019/08/23 15:35:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 15:35:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 87
2019/08/23 15:37:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 15:37:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 45
2019/08/23 15:37:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 15:37:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 45
2019/08/23 15:39:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:kpi]: pq: function get_stat_activity() does not exist
2019/08/23 15:39:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:kpi]: 46
2019/08/23 15:39:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 15:39:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 46
2019/08/23 15:39:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 15:39:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 46
2019/08/23 15:39:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/08/23 15:39:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:wal_size]: 46
2019/08/23 15:43:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:cpu_load]: pq: function get_load_average() does not exist
2019/08/23 15:43:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:cpu_load]: 95
2019/08/23 15:45:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk]: pq: function get_psutil_disk() does not exist
2019/08/23 15:45:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk]: 49
2019/08/23 15:45:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:backends]: pq: function get_stat_activity() does not exist
2019/08/23 15:45:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:backends]: 97
2019/08/23 15:45:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements]: pq: function get_stat_statements() does not exist
2019/08/23 15:45:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements]: 33
2019/08/23 15:45:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist
2019/08/23 15:45:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_statements_calls]: 97
2019/08/23 15:47:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2019/08/23 15:47:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_cpu]: 50
2019/08/23 15:47:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2019/08/23 15:47:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_disk_io_total]: 50
2019/08/23 15:49:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:psutil_mem]: pq: function get_psutil_mem() does not exist
2019/08/23 15:49:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:psutil_mem]: 51
2019/08/23 15:49:46 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:stat_ssl]: pq: function get_stat_activity() does not exist
2019/08/23 15:49:46 ERRO MetricGathererLoop: Total failed fetches for [cemtore:stat_ssl]: 51

**Comment by kmoppel** [comment]
Hi, these errors are considered normal if you haven't configured the "helper functions", that are used to escalate privileges for normal users to be able to read certain protected metrics. One could also just remove those metrics though...but default dashboards would look a bit empty then.
https://github.com/cybertec-postgresql/pgwatch2#steps-to-configure-your-database-for-monitoring
