### ISSUE TITLE
Integrating pgwatch2 with existing InfluxDB/Grafana

### ISSUE THREAD

**Issue by jdeveloperw** [cybertec-postgresql/pgwatch2#18]
Hi - pgwatch2 is exactly what we're looking for to monitor our AWS RDS postgres instance.  If we wanted to use the built-in pgwatch2, postgres config, and Web UI, but ship metrics to an existing InfluxDB/Grafana installation that we have, what would be the easiest way? Thanks!

**Comment by kmoppel** [comment]
Hi!
I see. Well currently I would still recommend to run the pgwatch daemon separately (it needs also a postgres db for storing the monitoring config) - then you don't need to mess with Docker. The other option would be to modify /etc/supervisor/conf.d/supervisord.conf inside the container and point the gatherer to your Influxdb using iurl/idbname/iuser/ipassword parameters (see below) and reload the service (supervisorctl restart pgwatch2).
You'd then also need to import the dashboards (for example https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/db-overview/dashboard.json) manually to your existing Grafana installation.

I'll leave the ticket open though for now, would be actually good to achieve what you're trying via environment variables when launching the container. All help would be appreciated here:)

---
[program:pgwatch2]
command=/pgwatch2/pgwatch2 --host=localhost --port=5432 --dbname=pgwatch2 --user=pgwatch2 --password=pgwatch2admin --iurl=http://myinflux ...

**Comment by kmoppel** [comment]
Now possible for all components in ver 1.2 ! Use according env variables like PW2_PGHOST, PW2_PGPORT, ... and PW2_GRAFANA_BASEURL. See README.md for more. Thanks for the input!
