### ISSUE TITLE
Added our database in the pgwatch2 admin interface -- are there other extra steps to run to configure our database for general level monitoring - monitoring the system/OS stats, database activities etc.? 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#180]
I have some questions if you can help me in my understanding how one should configure a database for monitoring. 

I was with the idea that, to configure our database for monitoring, we just need to add it in the admin interface.  And, the admin interface will run the required psql scripts in our database to create the required objects to collect the metrices.

I was able to add our database (database name - cemtore)  in the admin interface.
Our database name is cemtore and we selected  full monitoring for it in the admin interface (see under admin_interface  in attached screen shots' file  PGWATCH2_SCREENSHOTS.docx  )

I can see my database cemtore  both  in the pgwatch2 dashboard, and in the configuration database of the pgwatch2 container (see under query output in attached screen shots' file  PGWATCH2_SCREENSHOTS.docx  ) , but, I am getting some errors in the pgwatch2 log of the admin interface ( see under pgwatch2 log ).  And the dashboard also does not show system stats - system load,CPU utilization etc for the database cemtore (see under cemtore dashboard)

  What do we have to do  to monitor our database after adding it in the  pgwatch2 admin interface.
  Any help will be greatly appreciated.

[PGWATCH2_SCREENSHOTS.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3547765/PGWATCH2_SCREENSHOTS.docx)

**Comment by kmoppel** [comment]
admin interface will run the required psql scripts in our database to create the required objects to collect the metrices.

This is by default not like that - some steps are always needed from user. Only when using Superuser as monitoring role and ticking the "Auto-create helpers?" box in Web UI, pgwatch will create some helpers automatically...but it's of course not recommend to gather metrics as Superuser remotely (locally it should be OK). And you still need to enable "pg_stat_statements" extension previously and also install "plpython" package if wanting system level metrics (CPU, RAM etc).

All steps should be covered here: https://github.com/cybertec-postgresql/pgwatch2#steps-to-configure-your-database-for-monitoring
