### ISSUE TITLE
db_stats [ver: 9.0,9.3,12] backup_duration_s is missing

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#181]
Hello,
my monitored db is 
select version();
 
PostgreSQL 11.5 (Ubuntu 11.5-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
(1 row)

 "db_stats": 60 every 60s

metrics are stored in postgres db 

 select * from db_stats limit 1
=>  2019-08-21 07:25:53.563443+00 | europe_stock | {"blks_hit": 1758920362, "blks_read": 47285646, "conflicts": 0, "deadlocks": 0, "temp_bytes": 0, "temp_files": 0, "numbackends": 71, "tup_deleted": 678, "tup_fetched": 95541170, "tup_updated": 95337145, "xact_commit": 1122323, "tup_inserted": 52663997, "tup_returned": 305729276, "blk_read_time": 0, "xact_rollback": 15, "blk_write_time": 0, "postmaster_uptime_s": 80681}

there is no fields :"backup_duration_s", just as if it were executing db_stats version 9 instead of 9.3 (with backup_duration_s included)

fyi, i have added the column "  extract(epoch from (now() - pg_backup_start_time()))::int8 as backup_duration_s" in the 9 version, the result is the same  
Hope it helps...

**Comment by kmoppel** [comment]
Hi! Thanks for picking up a potential problem....this time it works as designed though :) NULL-s values are currently not stored as 1) they're difficult to work with 2) InfluxDB does not support them at all.

So basically you'd only see this column if there is an actual binary backup running.
