### ISSUE TITLE
Questions on the default test configuration db in pgwatch2 container

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#182]
Hi Team, 
 We want to monitor our database and trying to run steps to configure it for monitoring using the pgwatch2 docker container. 
As of now, after the running the following command :
docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2

We get the test database in the default dashboard. And, I believe as I understand from reading the pgwatch2 document, this test database is the configuration  database where we need to add our database(s) for monitoring.  
  I understand, ideally the configuration database and its instance should be separate than the databases that it will monitor.
But, my questions is:  Do we always need to have a separate configuration database and its instance ? Can we not create the configuration database within the database itself that we want to monitor?
Need more clarifications on the following section in the pgwatch2 install document:
"For defining your own dashboards you need to log in as admin (admin/pgwatch2admin). NB! If you don't want to add the "test" database (the pgwatch2 configuration db) for monitoring set the NOTESTDB=1 env parameter when launching the imagel "
 Can you please give me steps/examples of defining new dashboards other than the default 
 dashboard?
 How would we create the pgwatch2 configuration db if we do not want to add the test database? Can you please provide steps/examples?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Hi, no you don't need the "config DB" - one could also use YAML config files. See [here](https://github.com/cybertec-postgresql/pgwatch2#file-based-operation)

But if you want of course you can also create teh configuration database within the database itself that you want to monitor. Basically you don't even need a separate DB as "config DB" is using it's own schema named "pgwatch2".

For a quick start on creating dahsboards maybe start [here](https://grafana.com/docs/tutorials/screencasts/).

**Comment by bikramma** [comment]
Hi Kmoppel,
Thanks for help. But I need some more help  -- You commented in your response - quoting it here
"But if you want of course you can also create teh configuration database within the database itself that you want to monitor. Basically you don't even need a separate DB as "config DB" is using it's own schema named "pgwatch2"."

But, now that we already have the test configuration db within the pgwatch2 docker container, how do we drop it or revert it, and, then create the configuration db in the database itself?   Do we run a separate docker command to create the configuration db in our database? Or, do we create it by running scripts ? And, how do we locate these scripts? Do we have any zip/tar file that we need to download from GitHub or  these scripts are already available when we downloaded the pgwatch2 docker image? 

Thanks and regards
Bikram

**Comment by kmoppel** [comment]
@bikramma If you use Docker, configuration db is always created. If you want to use a custom install with / or without Docker then the "Config DB" schema can be found here: https://github.com/cybertec-postgresql/pgwatch2/tree/master/pgwatch2/sql/config_store
