### ISSUE TITLE
How to download the sql scripts needed in ruuning the  Steps to configure your database for monitoring

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#183]
Hi Team,

I am trying to add my database following the section - "Steps to configure your database for monitoring" following the pgwatch2 README.md.
How do we download the scripts (psql scripts or shell scripts) and  any other relevant files that are needed in this section? Which tar file in github we should down load?
For e.g, how would we get the pgwatch2/sql/metric_fetching_helpers/stat_statements_wrapper.sql?

We installed the pgwatch2 docker container and see the  stat_statements_wrapper.sql script in the following folder -- but I am not sure if these folders are sticky/permanent folders for these scripts, and rather should we need to download  any tar file and install them in separate  permanent folders?
[root@cemtore01 ~]# find / -name '*stat_statements_wrapper.sql*'
/var/lib/docker/overlay2/d9c8a24b29e7628f114ae144742cc4d4e019d4feb30ece6b8df8d6ce6ea18089/diff/pgwatch2/sql/metric_fetching_helpers/stat_statements_wrapper.sql
/var/lib/docker/overlay2/d0d21c1d840d5adc514bc54a2e082765539678f866ed7b4eaa22addae86ff0e7/merged/pgwatch2/sql/metric_fetching_helpers/stat_statements_wrapper.sql

**Comment by kmoppel** [comment]
Hi, no "sticky/permanent folders" are needed to run the pgwatch2 collector - it's one time rollout operation only on the config DB and on the monitored hosts so all file sources are good. Also when using superuser (not recommended) and setting the "autocreate helpers" only one time config DB rollout is needed and the monitoring daemon will create "helpers" automatically.
