### ISSUE TITLE
Questions on the  configuration db in pgwatch2 container

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#184]
Hi Kmoppel,
Thanks for your great help in responding to the issues . 
 I need some more help in response to the issue #`182 (Questions on the default test configuration db in pgwatch2 container) -- 
You commented in your response - quoting it here
"But if you want of course you can also create teh configuration database within the database itself that you want to monitor. Basically you don't even need a separate DB as "config DB" is using it's own schema named "pgwatch2"."

But, now that we already have the test configuration db within the pgwatch2 docker container, how do we drop it or revert it, and, then create the configuration db in the database itself?   Do we run a separate docker command to create the configuration db in our database? Or, do we create it by running scripts ? And, how do we locate these scripts? Do we have any zip/tar file that we need to download from GitHub or  these scripts are already available when we downloaded the pgwatch2 docker image? 

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
See https://github.com/cybertec-postgresql/pgwatch2/issues/182#issuecomment-529377728
