### ISSUE TITLE
DOWNLOAD PGWATCH2 SCRIPTS

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#185]
Hi Kmoppel,
Thanks for your great help always.
In response  "How to download the sql scripts needed in runing the Steps to configure your database for monitoring (issue #183)" you commented - quoted below
"Hi, no "sticky/permanent folders" are needed to run the pgwatch2 collector - it's one time rollout operation only on the config DB and on the monitored hosts so all file sources are good. Also when using superuser (not recommended) and setting the "autocreate helpers" only one time config DB rollout is needed and the monitoring daemon will create "helpers" automatically."
But, my question now is  - is there a single tar file or zip file that we can download somewhere that will contain the file sources?  
In the "Steps to configure your database for monitoring"  we need to run the 
pgwatch2/sql/metric_fetching_helpers/stat_activity_wrapper.sql

When I login to GitHub I can see the script 
But, how do we download it from GitHub pgwatch2/sql/metric_fetching_helpers/ folder?
Is there a tar/zip file that we can download ?

Also, in following the steps to configure your  database for monitoring, we have this instructions:
 If using a superuser login (not recommended) you can skip this step, just ensure that you check the Is superuser? checkbox (or "is_superuser: true" in YAML mode) when configuring databases.

In the admin interface we have specified a superuser to login for monitoring -    and we do not see any Is superuser? checkbox in the admin interface.  Where and how to check Is superuser? checkbox?

Also, we are getting the following error when we are trying to run: 
cemtore=# CREATE EXTENSION plpythonu;
ERROR:  could not open extension control file "/usr/share/pgsql/extension/plpythonu.control": No such file or directory.
How do we fix this error?  (we are on centos 7)

Thanks and regards
Bikram

**Comment by kmoppel** [comment]
Hi,
all Github project can be downloaded as Zip folder. And pgwatch project also has RPM / DEB / TAR packages available under the "Releases" tab.

About the "Is superuser?" checkbox - sorry, my mistake. The new name for this checkbox is "Auto-create helpers?".
