### ISSUE TITLE
How to show CPU utilization in the pgwatch2 dashboard 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#186]
Hi Team,
We should be able to show CPU utilization and other system stats.
Following the section "Steps to configure your database for monitoring"
we ran the following statements to monitor our database (cemtore) logging in using the superuser (cemtore) 
-bash-4.2$ psql -U cemtore -f stat_activity_wrapper.sql cemtore.
We then run cemtore=# CREATE EXTENSION pg_stat_statements;
CREATE EXTENSION

cemtore=# CREATE EXTENSION plpythonu;
ERROR:  could not open extension control file "/usr/share/pgsql/extension/plpythonu.control": No such file or directory

And, in the admin interface, we added our database with the following values:
DB db name - cemtore
DB db user   - cemtore
Auto-create helpers  button selected
Preset metrics config - full

But we are still not able to see the CPU utilization in DB overview screen , and we are not seeing anything in the system stats screen ( see attached screenshots in the CPU_UTILIZATION.docx).
The pgwatch2 log still shows errors (see attached PGWATCH2_LOG.docx)

Is it because of not being able to create the plpythonu extension?
We are using a superuser  called cemtore in the admin interface for monitoring ( DB username cemtore has the superuser role)

We also ran the following two statements --replacing superuser for cemtore and database mydb for cemtore  as instructed in the "Steps to configure your database for monitoring" 

psql -U cemtore -f pgwatch2/sql/metric_fetching_helpers/stat_statements_wrapper.sql cemtore
psql  -U cemtore -f pgwatch2/sql/metric_fetching_helpers/cpu_load_plpythonu.sql cemtore
 
 But we got these errors when we run them:
-bash-4.2$ psql -U cemtore -f  stat_statements_wrapper.sql cemtore
psql:stat_statements_wrapper.sql:54: NOTICE:  extension "pg_stat_statements" already exists, skipping
DO
-bash-4.2$ psql  -U cemtore -f cpu_load_plpythonu.sql cemtore
BEGIN
psql:cpu_load_plpythonu.sql:15: ERROR:  language "plpythonu" does not exist
HINT:  Use CREATE LANGUAGE to load the language into the database.
psql:cpu_load_plpythonu.sql:17: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:cpu_load_plpythonu.sql:19: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK

How do we fix these issues so that we can see the CPU utilizations and system stats?

Thanks and regards,
Bikram

**Comment by bikramma** [comment]
Forgot to add the attachments: Added them now.
[CPU_UTLIZATION.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3571725/CPU_UTLIZATION.docx)
[PGWATCH2_LOG.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3571728/PGWATCH2_LOG.docx)

**Comment by kmoppel** [comment]
For fetching CPU load via pgwatch2 you need to: 1) install plpython extension on monitored host 2) install the "psutil" Python package 3) create the "psutil_cpu" helper / wrapper function provided by the pgawtch project.

**Comment by bikramma** [comment]
Hi Kaarel,
Thanks for all your help.
 I have  completed the steps to add my database (cemtore)  following the section "Steps to configure your database for monitoring" - but I am still getting the following errors  in pgwatch2.log  in the admin interface ( uploaded PGWATCH2_LOG.docx) .  All the extensions and helper functions have been successfully  created in my database (see in the uploaded DATABASE_SCREENSHOT.docx). 
We have run the helper scripts connecting with the superuser cemtore -- which has a default search path of easyshare,public.  And, as you can see in the uploaded DATABASE_SCREENSHOT.docx, all the helper functions have been created in the easyshare schema.  The role pgwatch2 has a search path easyshare,public - but looks like pgwatch2 role is not able to see or access the  required database objects and functions  -- what did I do wrong?  

BTW - We have specified pgwatch2 as the database monitoring user in the admin interface ( see attached PGWATCH2_ADMIN.docx)

Thanks and regards,
Bikram
[PGWATCH2_LOG.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3597883/PGWATCH2_LOG.docx)
[PGWATCH2_ADMIN.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3597885/PGWATCH2_ADMIN.docx)

[DATABASE_SCREENSHOT.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3597886/DATABASE_SCREENSHOT.docx)
