### ISSUE TITLE
Failing to create the plpythonu extension;

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#187]
We are following  "Steps to configure your database for monitoring" section  to add our database for monitoring in pgwatch2 (docker container)
We are getting the following error when we run create extension plpythonu;
ERROR:  could not access file "$libdir/plpython2": No such file or directory.

What should we be doing now to create the plpythonu extension? Is there a rpm that we need to download and install for this extension?
Any help will be greatly appreciated.

**Comment by kmoppel** [comment]
https://lmgtfy.com/?q=how+to+install+plpythonu+extension

**Comment by kmoppel** [comment]
This is a generic Postgres issue and not part of pgwatch
