### ISSUE TITLE
Query un

### ISSUE THREAD

**Issue by demethan971** [cybertec-postgresql/pgwatch2#189]
When I use pgwatch2 on one of my big database (100 tables some of them have a size over than 50Go) i see than this query use ressource than application query.
I think this for have information about table bloat.
I use  Postgresql realease version 11.

```
select
  (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
  quote_ident(n.nspname)||'.'||quote_ident(c.relname) as tag_full_table_name,
  approx_free_percent,
  approx_free_space as approx_free_space_b,
  approx_tuple_count,
  dead_tuple_percent,
  dead_tuple_len as dead_tuple_len_b
from
  pg_class c
  join lateral pgstattuple_approx(c.oid) st on (c.oid not in (select relation from pg_locks where mode = 'AccessExclusiveLock'))  -- skip locked tables,
  join pg_namespace n on n.oid = c.relnamespace
where
  relkind in ('r', 'm')
  and c.relpages >= 128 -- tables > 1mb
  and not n.nspname like any (array[E'pg\\_%', 'information_schema']);
```

**Comment by kmoppel** [comment]
Hi! Yes, this is easy to happen if not so much going on on the target DB. The default settings would need changing in this case. For new setups this should  be already [fixed](https://github.com/cybertec-postgresql/pgwatch2/commit/2a1231f6976a1261366bc3df9aa4f904828b8f32) though - SQL based estimates are now used by default to avoid such problems.

**Comment by kmoppel** [comment]
@demethan971 for your old setup you should either increase timeouts or install the SQL based helper and then change the preset configs to use "table_bloat_approx_summary_sql" instead of "table_bloat_approx_summary".
