### ISSUE TITLE
Errors in pgwatch2.log PGWATCH2 monitoring 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#190]
Hi Team,
Looking for help with my issue. 

 I have  completed the steps to add my database (cemtore)  following the section "Steps to configure your database for monitoring" - 

Here are the psql commands I performed:

--Created the pgwatch2 role
CREATE ROLE pgwatch2 WITH LOGIN PASSWORD 'secret';
ALTER ROLE pgwatch2 CONNECTION LIMIT 3;

--Defined  the helper function using superuser cemtore for our database cemtore
psql -U cemtore -f pgwatch2/sql/metric_fetching_helpers/stat_activity_wrapper.sql cemtore

Added pg_stat_statements to our postgresql.conf and restarted the server
shared_preload_libraries = 'pg_stat_statements'
After restarting the server installed the extensions as the superuser cemtore
CREATE EXTENSION pg_stat_statements;
CREATE EXTENSION plpythonu;

--Installed the wrapper functions
psql -U cemtore -f pgwatch2/sql/metric_fetching_helpers/ stat_statements_wrapper.sql cemtore
psql  -U cemtore -f pgwatch2/sql/metric_fetching_helpers/cpu_load_plpythonu.sql cemtore

--Installed the other helper functions for detailed statistics
psql -U cemtore -f psutil_cpu.sql cemtore
psql -U cemtore -f psutil_disk_io_total cemtore
psql -U cemtore -f psutil_disk_io_total.sql cemtore
psql -U cemtore -f psutil_disk.sql cemtore
psql -U cemtore -f psutil_mem.sql cemtore
psql -U cemtore -f table_bloat_approx.sql cemtore
psql -U cemtore -f wal_size.sql cemtore

All the above psql commands completed successfully.
But we  are   getting the following errors  in pgwatch2.log  in the admin interface ( uploaded PGWATCH2_LOG.docx) .  All the extensions and helper functions have been successfully  created in my database (see in the uploaded DATABASE_SCREENSHOT.docx). 
We have run the helper scripts connecting with the superuser cemtore -- which has a default search path of easyshare,public.  And, as you can see in the uploaded DATABASE_SCREENSHOT.docx, all the helper functions have been created in the easyshare schema.  The role pgwatch2 has a search path easyshare,public - but looks like pgwatch2 role is not able to see or access the  required database objects and functions  -- what did I do wrong?  

BTW - We have specified pgwatch2 as the database monitoring user in the admin interface ( see attached PGWATCH2_ADMIN.docx)

Any help will be greatly appreciated.

Thanks and regards,
Bikram

[DATABASE_SCREENSHOT.docx](https://github.com/cybertec-
[PGWATCH2_ADMIN.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3597958/PGWATCH2_ADMIN.docx)
postgresql/pgwatch2/files/3597957/DATABASE_SCREENSHOT.docx)
[PGWATCH2_LOG.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3597964/PGWATCH2_LOG.docx)

**Comment by kmoppel** [comment]
Probably the "psutil" Python package was missing
