### ISSUE TITLE
Using existing Prometheus and Grafana dashboard for pgwatch2

### ISSUE THREAD

**Issue by richad1** [cybertec-postgresql/pgwatch2#191]
Hello,

I am trying to use existing Prometheus and grafana dashboard to run pgwatch2.
I already have a metric dashboard in grafana which is fetching the data from Prometheus.
Please help me with this.

**Comment by kmoppel** [comment]
Hi, you should really provide some more details...but currently there are no pgwatch2 preset dashboards for Prometheus you need to customize the old ones on your own I'm afraid...
