### ISSUE TITLE
Is there a way to query only modified data from source?

### ISSUE THREAD

**Issue by vahem2lu** [cybertec-postgresql/pgwatch2#192]
Hi

I wanted to ask if there's a possibility to ask only new data from metric's source database?
I have metric that fetches all necessary data from a log-like-database. Now I'd like to make Grafana graphs out from it. Seems like a plan, eh?

But when I run metric every 60 sec I will always ask for all rows and therefore always duplicate results. Although I make graphs out of the time used in result query (request_time) it's not a good setup.

I'm not sure if there is any nice way to filter (`WHERE` clause) results, because I cannot be sure when last query was ran. I could filter out all the `ID`s already fetched, but is there a way to do this?

Or is there any other way to solve this? Adding this log-db as a database in Grafana and then run query over it without pgwatch2 metric seems like an idea, but I'm not sure how good one? Also this would result only in one week result, because log database only keeps this long records. By using pgwatch2 metric database I could see graphs based on logs (queries, times and count of different sets of data) on a longer period of time.

**Comment by kmoppel** [comment]
Hi,
Currently what you're describing cannot be done with pgwatch...as it's some ETL process already basically requiring "state", this would make stuff too complex - before fetching we should always query the metric database for example. Currently it work in a "push only" way. So yes my advice would be to try directly with Grafana if one week is enough or build some simple Cron ETL pipeline.
