### ISSUE TITLE
database 'test' does not exists

### ISSUE THREAD

**Issue by Purik** [cybertec-postgresql/pgwatch2#193]
1. Run command for running docker Demo: 
docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2

2. List of databases (DB Overview dashboard) is empty

3. Error message popup Templating init failed
pq: syntax error at or near "VALUES"
![2019-09-18_01-53-49](https://user-images.githubusercontent.com/9501753/65085605-57fdbc80-d9b7-11e9-86f3-aedea609098d.png)

**Comment by kmoppel** [comment]
Hi, works for me™ :) Are you sure you're using the latest image or waited for a minute?

**Comment by Purik** [comment]
# docker images

REPOSITORY                   TAG                 IMAGE ID            CREATED                                                                              SIZE
cybertec/pgwatch2-postgres   latest              8fa247f3f45a        3 weeks ago                                                                          1.12GB
cybertec/pgwatch2            latest              0350667fe87c        3 weeks ago


# docker-compose.yml
version: '2.1'

services:

  grafana:
    image: cybertec/pgwatch2
    container_name: pgwatch2
    environment:
      - PW2_TESTDB=true
    volumes:
      - ./pg:/var/lib/postgresql
      - ./influx:/var/lib/influxdb
      - ./grafana:/var/lib/grafana
      - ./pw2:/pgwatch2/persistent-config
    ports:
      - "3000:3000"

**Comment by kmoppel** [comment]
@Purik what do the gatherer logs say?

**Comment by Purik** [comment]
Attaching to pgwatch2
pgwatch2   | 2019-09-18 13:39:30,575 INFO Set uid to user 0 succeeded
pgwatch2   | 2019-09-18 13:39:30,668 INFO RPC interface 'supervisor' initialized
pgwatch2   | 2019-09-18 13:39:30,668 CRIT Server 'unix_http_server' running without any HTTP authentication checking
pgwatch2   | 2019-09-18 13:39:30,668 INFO supervisord started with pid 1
pgwatch2   | 2019-09-18 13:39:31,695 INFO spawned: 'postgres' with pid 10
pgwatch2   | 2019-09-18 13:39:31,697 INFO spawned: 'influxdb' with pid 11
pgwatch2   | 2019-09-18 13:39:31,699 INFO spawned: 'pgwatch2' with pid 12
pgwatch2   | 2019-09-18 13:39:31,702 INFO spawned: 'webpy' with pid 13
pgwatch2   | 2019-09-18 13:39:31,706 INFO spawned: 'grafana' with pid 14
pgwatch2   | 2019-09-18 13:39:31,709 INFO spawned: 'grafana_dashboard_setup' with pid 15
pgwatch2   | 2019-09-18 13:39:32,528 INFO success: grafana_dashboard_setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
pgwatch2   | 2019-09-18 13:39:32,528 INFO exited: pgwatch2 (exit status 1; not expected)
pgwatch2   | 2019-09-18 13:39:33,497 INFO success: postgres entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pgwatch2   | 2019-09-18 13:39:33,497 INFO success: influxdb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pgwatch2   | 2019-09-18 13:39:33,497 INFO success: webpy entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pgwatch2   | 2019-09-18 13:39:33,497 INFO success: grafana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pgwatch2   | 2019-09-18 13:39:33,649 INFO spawned: 'pgwatch2' with pid 53
pgwatch2   | 2019-09-18 13:39:34,222 INFO exited: pgwatch2 (exit status 1; not expected)
pgwatch2   | 2019-09-18 13:39:34,222 INFO exited: grafana (exit status 1; not expected)
pgwatch2   | 2019-09-18 13:39:34,225 INFO spawned: 'grafana' with pid 64
pgwatch2   | 2019-09-18 13:39:34,448 INFO exited: grafana (exit status 1; not expected)
pgwatch2   | 2019-09-18 13:39:35,452 INFO spawned: 'grafana' with pid 90
pgwatch2   | 2019-09-18 13:39:36,348 INFO spawned: 'pgwatch2' with pid 109
pgwatch2   | 2019-09-18 13:39:36,349 INFO exited: grafana_dashboard_setup (exit status 0; expected)
pgwatch2   | 2019-09-18 13:39:36,604 INFO success: grafana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
pgwatch2   | 2019-09-18 13:39:37,512 INFO success: pgwatch2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by kmoppel** [comment]
This looks fine but it's very high level - better to go into Docker and look at "/var/log/supervisor/pgwatch2-stderr*"

**Comment by kmoppel** [comment]
or there's a button "Logs" in the Web UI

**Comment by Purik** [comment]
root@4701cd005fda:/# tail -f /var/log/supervisor/pgwatch2-stderr---supervisor-d339b6b9.log
2019/09/18 13:39:32 CRIT InitAndTestConfigStoreConnection: could not ping configDb! exit. dial tcp 127.0.0.1:5432: connect: connection refused
2019/09/18 13:39:34 CRIT InitAndTestConfigStoreConnection: could not ping configDb! exit. pq: the database system is starting up

**Comment by kmoppel** [comment]
Gatherer log seems good also (first errors are Ok as DB was not there yet)...
And the Web UI had no "monitored DBs" entries? Was there something on the "Metrics" tab?

I've also pushed a new image now...maybe just try that - `dockert stop pw2 && docker rmi cybertec/pgwatch2:latest && docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2`
