### ISSUE TITLE
Can not monitor statements or OS (CPU loads etc) using pgwatch2 login in the admin interface

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#194]
Hi

I have an issue which I am not able figure it out or resolve myself yet.
As you may know, we are trying to configure pgwatch2 to monitor our postgress database named cemtore ( version 10.3). 
We have installed the pgwatch2 docker container from GitHub and followed the steps under the section 'Steps to configure your database for monitoring'  for monitoring statements and CPU loads etc,  that are provided through the helper functions.
All the steps - 1.Creation of the pgwatch2 role 2. Creation of  all the helper functions as the superuser cemtore   were completed.
                          3. Added our database (cemtore) in the pgwatch2 admin interface for monitoring using the pgwatch2 role 
But, pgwatch2monitoring dashboards  do not show us the statement activities or CPU load etc  - and the pgwatch2 log shows errors that it can not access the helper functions - for e.g, [cemtore:stat_statements_calls]: pq: relation "pg_stat_statements" does not exist etc.
However, when we use the superuser cemtore for monitoring in the admin interface, instead of pgwatch2, everything shows up.
We are using postgress 10.3 – do we need to grant any extra access privileges ,for e.g granting pg_monitor role to pgwatch2  to monitor using pgwatch2 ?  
Any help will be greatly appreciated.

Thanks and regards,

Bikram Majumdar

**Comment by kmoppel** [comment]
Hi,
The "pq: relation "pg_stat_statements" does not exist" error might be also a search path issue if the extension is actually installed. As out of the box even regular users can look at this view, just without query / querid data.
But CPU load helper always needs the wrapper function as it's Python so make sure the functions is there and the monitoring role has execute privileges:
`psql -U pgwatch2 -d cemtore -c "select * from get_load_average()"`

**Comment by bikramma** [comment]
Thank you so much Kaarel for helping with your explanations.

Thanks and regards,
Bikram Majumdar
Sr Software Developer/DBA, Aqsacom Inc.
c. 1.972.365.3737

[cid:image002.png@01D57232.4BA28110]<http://www.aqsacom.com/>

Disclaimer. This electronic mail message contains CONFIDENTIAL information which is (a) CUSTOMER / SUPPLIER / PARTNER PRIVILEGED COMMUNICATION, WORK PRODUCT, PROPRIETARY IN NATURE, OR OTHERWISE PROTECTED BY LAW FROM DISCLOSURE, and (b) intended only for the use of the Addressee(s) named herein. If you are not an Addressee, or the person responsible for delivering this to an Addressee, you are hereby notified that reading, copying, or distributing this message is prohibited. If you have received this electronic mail message in error, please reply to the sender and take the steps necessary to delete the message completely from your computer system. Statement and opinions expressed in this e-mail are those of the sender, and do not necessarily reflect those of AQSACOM. AQSACOM accepts no liability for any damage caused by any virus/worms transmitted by this email.
