### ISSUE TITLE
Permission denied for function pg_ls_waldir

### ISSUE THREAD

**Issue by goodkiller** [cybertec-postgresql/pgwatch2#196]
Hello

I'm using PgWatch2 with default configuration in docker and I got following error:

Oct  9 15:04:54 xxxxxxxxx postgres[20499]: [8-1] 2019-10-09 15:04:54 EEST ERROR:  permission denied for function pg_ls_waldir
Oct  9 15:04:54 xxxxxxxxx  postgres[20499]: [8-2] 2019-10-09 15:04:54 EEST CONTEXT:  SQL function "get_wal_size" statement 1
Oct  9 15:04:54 xxxxxxxxx  postgres[20499]: [8-3] 2019-10-09 15:04:54 EEST STATEMENT:
Oct  9 15:04:54 xxxxxxxxx  postgres[20499]: [8-4] #011select
Oct  9 15:04:54 xxxxxxxxx  postgres[20499]: [8-5] #011  (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
Oct  9 15:04:54 xxxxxxxxx  postgres[20499]: [8-6] #011  get_wal_size() as wal_size_b;

PG versions are 10 and 11.

**Comment by kmoppel** [comment]
Hi, I think most probably the get_wal_size "helper" is missing. So you'd need to run the below SQL with superuser powers or actually the [documentation](https://www.postgresql.org/docs/11/functions-admin.html#FUNCTIONS-ADMIN-GENFILE-TABLE) even says that the built-in "pg_monitor" role and normal grants should work. But for non-superusers (the recommended way) you'd still need the helper.

https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/00_helpers/get_wal_size/10/metric.sql
