### ISSUE TITLE
Biggest relation treemap shows no data

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#197]
Hi Team,

We are having the following  issues with the following pgwatch2 dashboards:

1.Biggest relations treemap dashboard issue:
    No data is shown for indexes in the Biggest relations treemap dashboard --- any idea what we  
    are missing.  Even  for the test database that comes with the pgwatch2 docker, nothing is 
    shown.
  I have attached a word document showing the screenshots of the dashboards
  Biggest_relations_treemap_dashboard.docs  

2.Sprocs & Top Sprocs dashboard issues:
 Sprocs dashboard  only shows test in the dbname list.  It does not show our database cemtore
 Top Sprocs dashboard shows both test and cemtore in the dbname list.  But when we select our 
 database cemtore – it does no show any data.
 Attached Sprocs_dasboard.docs showing the screenshots of the dashboards.

3. DB Overview & Global DB Overview dash boards
   What is the difference between these two dashboards ?
   In the Global DB Overview - dashboard, the top panel shows query runtime of 28ms for our 
   database  cemtore, but under the Avg query runtime panel - the average is shown as 50 ms.  
   Why is this discrepancy?
   And, interestingly, in the DB Overview dashboard the query runtime for the same database is 
   much less -  only 8 ms .  Why is this difference in values for the same metric (Query runtime) in 
   the top panels between these two dashboards? 
  Attached a word document - DB_Overview_dashboards.docx showing the screenshots of these two dashboards.

    Any help/clarifications will be greatly appreciated.

Thanks and regards,
Bikram

**Comment by bikramma** [comment]
Forgot to attach the screenshots' documents corresponding to the above issues.
Attaching the screensots 
 for Issue 1 - Biggest_relations_treemap_dashboard.docs
 for issue 2 -  Sprocs_dasboard.docs
 for issue 3 -  DB_Overview_dashboards.docx
[Sprocs_dashboards.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3709484/Sprocs_dashboards.docx)
[DB_Overview_dashboards.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3709485/DB_Overview_dashboards.docx)
[Biggest_relations_treemap_dashboard.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3709486/Biggest_relations_treemap_dashboard.docx)

**Comment by kmoppel** [comment]
@bikramma  Could you please also post your metric config info also and which version are you using?

**Comment by bikramma** [comment]
Hi Kaarel,

Thanks for your quick help.
In response to your question:
<Could you please also post your metric config info also and which version are you using?>
Our pgwatch2 version is 9.5.17
Our PostgreSQL version is 10.3
I have attached a word document with the active metrics that are shown in pgwatch2 admin interface screen shot (Active_Metrics.docs). Is there any other way to get that information?
[Active_Mterics.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3713630/Active_Mterics.docx)

shown in the admin interface

**Comment by kmoppel** [comment]
Well active metrics listing just tells which one are defined...but in short it's important to see if "index_stats" metrics is enabled for your monitored DB - either directly or via a preset config. It should be active out of the box though...
