### ISSUE TITLE
New questions related to your response on issue 195 - Questions/clarifications on pgwatch2 dashboard (#195) 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#198]
In response to my following question:
<<Q 1. What is the use/meaning of the min. "pg_stat_statements.calls" ? Its list allows to select
1,10,100,1000,10000 -- Are we displaying statements that were called/executed a minimum
number of 1,10,100,1000,10000 times within the selected time period?>>

You responded:
>>Q 1. Almost correct. Not within the selected time period but global call count. This lets you to only look at regular i.e. application generated queries and leave out some ad-hoc queries.<<

Would you please explain global call count for me?

In another clarification related to discrepancy between values for same metric, you responded  
>>Q4. Some top panel stuff are based on last 6h data, the tooltip explains it also. If in doubt always click "edit" to see the metric query that should explain everything<<
I can see the tooltip (with the i - icon) and I can read the explanation as you pointed out -- but how do I get the SQL query that is exeuted?  In following your response above, I was looking for "edit" - but, when I clicked on the little down triangle icon,  I found the following items:
 View, Share,More
When I clicked on the little down triangle icon on the right -  I see the JSON query. But, where can we get the SQL query that is executed?

I have attached a word doc -Find_Edit.docs with the screenshots of the clicks I executed for finding "edit"   

Your help will be greatly appreciated.
[Find_Edit.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3709467/Find_Edit.docx)

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
1) Global call count - it's the actual cumulative "calls" value direct from the "pg_stat_statements" extension, i.e. not for a specific time period selected in Grafana but since last Postgres side stats reset or server crash.
2) To see "edit" you need to log into Grafana! The default Docker image uses admin/pgwatch2admin, this is documented also in README.
