### ISSUE TITLE
How to find the query that pgwatch2 runs - continuation of issue #198   

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#199]
Hi Kaarel,
Thanks for your quick response on the issue #198.
[Query.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3713566/Query.docx)

I was able to see the "Edit" after I sign in to Grafana.
When I click on Edit on the metric items, I can see the SQL query in the A - wnidow as well as in the Query Inspector-- (attached a screenshot doc -Query.docs). But, the queries shown do not appear to be direct psql queries - they are formatted with column aliases and escape characters, etc. I can not run them in psql even after chopping off the escape characters. Would you be able to tell me where can I see the related query that I can run in PostgreSQL?

**Comment by kmoppel** [comment]
Hi, the feature you want is under the button "Query inspector":
https://grafana.com/docs/guides/whats-new-in-v4-5/#query-inspector
