### ISSUE TITLE
Influx max key length exceeded

### ISSUE THREAD

**Issue by mastak** [cybertec-postgresql/pgwatch2#2]
After 30 minutes of work, all the statistics is no longer updated and the next message appears in the logs:
```
CRIT SendToInflux: NewPoint failed: max key length exceeded: 70284 > 65535
```
`pg_stat_statements_reset` - helped, but after 5 min stable work error appears again.

PS here some debug info:
```
DEBU SendToInflux: SendToInflux data[0] of  14 : 
map[shared_blks_written:0 epoch_ns:1485952965864720128 tag_queryid:1691203631 calls:7 total_time:7.696999999999999 shared_blks_hit:1862 blk_write_time:0 
tag_query:SELECT (extract(? from now()) * ?)::int8 as epoch_ns, schemaname::text as tag_schema, indexrelname::text as tag_index_name, relname::text as tag_table_name, coalesce(idx_scan, ?) as idx_scan, coalesce(idx_tup_read, ?) as idx_tup_read, coalesce(idx_tup_fetch, ?) as idx_tup_fetch, coalesce(pg_relation_size(indexrelid), ?) as index_size_b 
FROM pg_stat_user_indexes WHERE pg_relation_size(indexrelid) > ? -- >1MB AND NOT schemaname like ? 
ORDER BY schemaname, relname, indexrelname;  
shared_blks_read:0 temp_blks_read:0 temp_blks_written:0 blk_read_time:0]
```

**Comment by kmoppel** [comment]
Thanks for the bugreport! I think the issue is caused by the "stat_statements" metric, and probably you have some very long query texts being executed and that errors out on Influx. I've changed the metric definition now in master also but for a quick fix I hope this helps - https://gist.github.com/kmoppel/71a89b3b32cb32a4c38c7233551e4973

**Comment by kmoppel** [comment]
@mastak btw, i've now pushed new version of the Docker image also if you want to start from scratch
