### ISSUE TITLE
adding multiple databases at once?

### ISSUE THREAD

**Issue by neerajwadhwani** [cybertec-postgresql/pgwatch2#20]
Is there a way to add all the databases from an instance to the monitoring dashboard in one go? I tried leaving database as blank and * but didn't work.

**Comment by kmoppel** [comment]
yes, currently not possible. didn't implement it at first because DB names need to be unique..but two separate clusters both have a "postgres" DB.
but let's leave the issue open for now, i think some name auto-generation or prefixing with a cluster name might do the trick.

**Comment by kmoppel** [comment]
Now possible in ver 1.2 ! Leaving the "DB name" field empty on the /dbs page will get all non-template DBs and store them separately. Thanks a lot for the input @neerajwadhwani !
