### ISSUE TITLE
Clarifications on Query Panel in pgwatch2

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#200]
Hi Team,
We have installed the pgwatch2 docker container and added our postgres database for monitoring. 
Now we are trying to view the PostgreSQL SQL statements/queries  that are run , and, if we can edit them if needed.   When we login into Grafana and click on "Edit"  in these metrices, we can see the query in the query window panels (- A etc) , as well as more details in the Query Inspector.
As we have not changed/edited  anything yet, all of these metrices shows  "default" in the Query panel. But, I see other choices ( attached a screenshot doc - Query.docs) when I click on the little triangle at the right next to "default"
 What are the meaning of the various items that are shown?
 - default
 -Influx
-Grafana
-Mixed
-PostgreSQL

Any help will be greatly appreciated
Thanks and regards,
Bikram
[Query.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3713691/Query.docx)

**Comment by bikramma** [comment]
Also forgot to talk about 
 another issue:
We have installed the pgwatch2 docker container on another  separate remote server to be used only for monitoring our postgres databases.  We have not installed/running any postgres database on this server.  But, we do not see the -PostgreSQL choice   when I click on the little triangle at the right next to "default" in the Query panel,  I only see these choices:
default
-Influx
-Grafana
-Mixed
Attached the screenshot in the Query.docx.

Any help/clarifications will be greatly appreciated.
Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Hi, the question is actually about usage of Grafana...and it seems all OK with the list of data sources - pgwatch2 only configure the "default" data source indeed, depending whether it's a Influx or Postgres Docker image. But you can of course add any other datasources if you need...but for looking at metrics gathered with a standard setup you don't need others, all data should be stored in this default datastore.
