### ISSUE TITLE
Back up of metrics data in the config db within the  pgwatch docker

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#201]
Hi Team,

Question 1.
We are using the pgwatch2 docker container and using the config db (test) to store the metrices of our monitored databases. How do we backup this test database that is running within the docker.
Question 2.
How do we run/configure  the pgwatch2 docker so that it will automatically  start after any server reboot ?
Question 3.
Is their any inbuilt retention configurations of the various logs generated from pgwatch2 docker so that they do not grow indefinitely and  filling up storage?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
1) The easiest is to expose the Postgres port and use some pg_dump in Cron or similar
2) There's a sample also in README. Docker syntax for that is "--restart=unless-stopped"
3) Yes default are coming from Supervisord process manager - I think it's max  500MB per component and images has 4 components running so in worst case it's 2GB.
