### ISSUE TITLE
Archiving pg_dump backups of pgwatch2 docker container

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#202]
Hi Kaarel,

Thanks for your quick response on my questions/clarifications on #201
In response 1. 
<The easiest is to expose the Postgres port and use some pg_dump in Cron or similar>
 Would you illustrate more -- 
Question 1.
 what do you mean by expose the Postgres port?
 In the postgresql.conf of the pgwatch2 docker 
 (/etc/postgresql/9.5/main/postgresql.conf /tmp/postgresql.conf)  , the port is 5432. 
Q2. How do we move the dump that will be created within the docker container's filesystem to outside filesystem for archiving?

Thanks and regards,
Bikram 
                                            --

**Comment by kmoppel** [comment]
Hi Bikram, these questions are not really related to pgwatch2. First was though about specifying the PG port 5432 on "docker run", but for the 2nd there are many options - you could push it wherever from within the container basically but the common way is to "pull" the backups. So better expose the Postgres port and set up some Cronjob or similar from a backup host where file system is already backed up.
