### ISSUE TITLE
Admin Interface - choices for Preset metrics config

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#204]
Hi Team,

We have the following questions -- if you can clarify we will really appreciate.
Questions 1.
We are debating on which of the following choices under the preset metrics config will provide more metrices and will be more useful
basic
exhaustive
full .
Question2. 
Do we have to tweak/set any configuration item in the database' PostgreSQL.conf file to get more IO timings and statistics?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Q1: [Here](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/preset-configs.yaml) you can see the differences in actual metrics that are part of the listed presets. Generally "exhaustive" should be enough. "basic" is good basically for alerting, to notice if some DB is down.

Q2: Yes some tweaking is recommended to get more metrics, see here: https://github.com/cybertec-postgresql/pgwatch2#steps-to-configure-your-database-for-monitoring
