### ISSUE TITLE
Document on using the pgwatch2 admin interface

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#206]
Hi Team,

I can see the pop-up notes when I click on the configuration items on the interface. Most of the these items' names  are self explanatory and the associated notes are helpful. 
But, is there any document available that will help me using the pgwatch2 admin interface better?
How can we use the custom metric config? Do we just need to enter the metric and its interval period pairs within the {..}, separated by commas in the box?
What is the purpose of ticking/unticking the Enabled?  item?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
1) Yes, for custom metrics enter the metric and its interval period pairs within the {}, i.e: {"metric_x": 60}
2) No metrics will be gathered for hosts that are not "enabled"
