### ISSUE TITLE
Clarification on using the http://127.0.0.1:8080

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#207]
Hi Kaarel and Team,

To use/connect to the web GUI of the pgwatch2  admin interface, the document instructs the local host loopback IP address 127.0.0.1 of server  where pgwatch2 is running (see below section from the documentation). This local IP can not be accessed from our  browsers - we have to replace it with the physical IP address of the server instead.  I am wondering why have we instructed to use 127.0.0.1?  

**[section from pgwatch2 documentation]**

Usage (Docker based, for file or ad-hoc based see further below) 
by default the "pgwatch2" configuration database running inside Docker is being monitored so that you can immediately see some graphs, but you should add new databases by opening the "admin interface" at 127.0.0.1:8080/dbs or logging into the Postgres config DB and inserting into "pgwatch2.monitored_db" table (db - pgwatch2 , default user/pw - pgwatch2/pgwatch2admin). Note that it can take up to 2min before you see any metrics for newly inserted databases. 
one can create new Grafana dashboards (and change settings, create users, alerts, ...) after logging in as "admin" (admin/pgwatch2admin) 
metrics (and their intervals) that are to be gathered can be customized for every database by using a preset config like "minimal", "basic" or "exhaustive" (monitored_db.preset_config table) or a custom JSON config. 
to add a new metrics yourself (simple SQL queries returing point-in-time values) head to http://127.0.0.1:8080/metrics. The queries should always include a "epoch_ns" column and "tag_" prefix can be used for columns that should be tags (thus indexed) in InfluxDB. 
a list of available metrics together with some instructions is also visible from the "Documentation" dashboard

**Comment by kmoppel** [comment]
This is yes a bit OS specific if 127.0.0.1:8080/dbs works...but I think the intent should be clear.
