### ISSUE TITLE
pgwatch2 Config db archive parameters 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#208]
Hi Team,

I am finding in the pgwatch_postgresql.conf that the pgwatch2 config database is running in archive mode:
wal_level=archive
archive_mode=on
archive_command='/bin/true'

How are we cleaning up the archives ?  Is the pgwatch2 docker running pg_archivecleanup job or some other archive cleanup job? We find postgres filesystem within the docker is at 70%.

postgres@e141bfc1a426:~/9.5/main/pg_xlog$ df -k .
Filesystem                        1K-blocks     Used Available Use% Mounted on
/dev/mapper/centos_cemtore01-root  52403200 36426448  15976752  70% /var/lib/postgresql
postgres@e141bfc1a426:~/9.5/main/pg_xlog$
    
Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
With `archive_command='/bin/true'` there are no archives created in reality...so nothing to clean up. It's just a good practice to do like that as one can enable real archiving quickly without restart when the need comes by changing the archive_command to something more meaningful.
