### ISSUE TITLE
DB Overview Dashboard 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#209]
Hi Team,

I find DB size Y axis showing same value in the WAL rate + DB size panel:  I have attached the screenshot - DB SIZE Y AXIS.docx
Why DB size Y axis (Right side) always shows same value – highlighted in vertical red? 
Your help and clarification will be greatly appreciated.
Thanks and regards,
Bikram
[DB SIZE Y AXIS.docx](https://github.com/cybertec-postgresql/pgwatch2/files/3772552/DB.SIZE.Y.AXIS.docx)

**Comment by kmoppel** [comment]
The changes in DB size were too small and precision is limited to 1 decimal point, but can be changed on the "visualization" panel
