### ISSUE TITLE
take_backup.sh doesn't backup grafana db

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#21]
Hello @kmoppel , 
while deploying pgwatch2 for our PG databases I've noticed, that the backupscript isn't complete / current.

I tried to restore a backup taken with the provided script but my grafana config was gone including all dashboards a.s.o. 
So I poked around to find the reason and finally found that the script dumps twice the same database and both times schema pgwatch2

--=====

echo "backing up Postgres config store DB..."
pg_dump -p $PGPORT -U $PGUSER -n pgwatch2 $PGDATABASE > pgwatch2_config.sql

echo "backing up Grafana config DB..."
pg_dump -p $PGPORT -U $PGUSER -n pgwatch2 $PGDATABASE > grafana_config.sql

--=====

while the docker PG cluster contains 2 databases called pgwatch2 and pgwatch2_grafana and within pgwatch2_grafana schema public is used for the grafana config.
So I've added an additional variable for the second database and modified the pg_dump line for the grafana db.

--=====

PGHOST=127.0.0.1
PGPORT=5432
PGDATABASE=pgwatch2
GRAFANADATABASE=pgwatch2_grafana #this one is new
PGUSER=pgwatch2
PGPASSWORD=pgwatch2admin

echo "backing up Grafana config DB..."  #I've left  -n pgwatch2  for the case that later versions might switch back to use this schema instead of public
pg_dump -h $PGHOST -p $PGPORT -U $PGUSER -n public -n pgwatch2 $GRAFANADATABASE > grafana_config.sql  
--=====

Now the backup contains the data I missed before.

kind regards 
Georg

**Comment by kmoppel** [comment]
Indeed, pgwatch2 schema slipped in for Grafana also - fixed in master now. Thanks a lot for noticing!
