### ISSUE TITLE
Functions get_wal_size() and get_table_bloat_approx_sql()

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#212]
Hi Team,

We are using the pgwatch2 account in the admin interface for monitoring. 

We are finding these failures messages in the pgwatch2 log:
2019/10/24 17:20:35 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:wal_size]: pq: function get_wal_size() does not exist
2019/10/24 19:18:35 ERRO MetricGathererLoop: Failed to fetch metric data for [cemtore:table_bloat_approx_summary_sql]: pq: function get_table_bloat_approx_sql() does not exist 

Question 1:  Which dashboard/panel is/are affected  due to error  'pq: function get_wal_size() does not exist'

Question 2:  Which dashboard/panel is/are affected  due to error 'pq: function get_table_bloat_approx_sql() does not exist'

Question 3:  We see two scripts in relation to table bloat   1. get_table_bloat_approx.sql 2. get_table_bloat_approx_sql.sql .    What is the differences between them?  We have not run none of these scripts when we added our database for monitoring. But, we only see error message for get_table_bloat_approx_sql() and not for the  get_table_bloat_approx.sql().  Any reason?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
"get_table_bloat_approx" and "get_table_bloat_approx_sql" have the difference that first is more exact but also possibly much more slower and causes more disk IO. "get_table_bloat_approx_sql" is an inexpensive estimation.
