### ISSUE TITLE
Issue with monitoring using the pgwatch2 account 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#214]
Hi Team,

We have followed steps in the section "Steps to configure your database for monitoring" and run the following required wrapper function/ statement  as our superuser(cemtore) to monitor statements (stat statements overview and stat statements top dashboards)

psql  -U cemtore -f pgwatch2/sql/metric_fetching_helpers/ stat_statements_wrapper.sql mydb .

And  you said also to run the following:
<Additionally for extra insights ("Stat statements" dashboard and CPU load) it's also recommended to install the pg_stat_statement contrib extension (Postgres 9.2+ needed to be useful for pgwatch2)>
And we have created the pg_stat_statement extension.  

When we connect with the superuser(cemtore) the dashboards show all the queries' texts perfectly ,but, when we connect with the pgwatch2, we do not see all the queries'  texts.  Why? 
Our superuser's search_path is easyshare,public.  And we have granted usage on easyshare to pgwatch2,and granted all on easyshare.pg_stat_statements to pgwatch2.

How can we fix this issue?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Using the get_stat_statements() wrapper should give exactly the same info if using pg_stat_statements directly as superuser. If not so then I'd check the execute privileges and search_path configuration of the role used for monitoring.
