### ISSUE TITLE
Grafana does not start (in Kubernetes deployment)

### ISSUE THREAD

**Issue by arnostv** [cybertec-postgresql/pgwatch2#218]
There seems to be an issue with Grafana when starting pgwatch2:

I'm trying to run the pgwatch2 in Kubernetes, using openshift_k8s/k8s_deployment_simple.yaml file from this repository.

Deployment seems to be OK, but the _grafana_ process is not able to start.

When I check logs directly in Kubernetes pod, in file `/var/log/grafana/grafana.log` I see this:

```
t=2019-11-22T11:12:07+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: mkdir /var/lib/grafana/png: permission denied"
```

Owner of direcotory `/var/lib/grafana` is `root` but Grafana runs as `grafana` user.

I was able to resolve this by running `chown grafana /var/lib/grafana` - after that the Grafana process immediately started.

**Comment by kmoppel** [comment]
Just checked on Minikube (v1.15.1) and seems to work nicely. I think you might have deployed it onto OpenShift instead, then such error is thrown indeed. For OpenShift one must currently use the "pgwatch2-nonroot" image.

**Comment by arnostv** [comment]
Just FYI, I definitely did not deploy to OpenShift. It was Kubernetes -  Google Kubernetes Engine (in Google Cloud) to be more specific. 

But let's keep this closed, maybe it's not issue anymore if there is no more comments on this after year.
