### ISSUE TITLE
missing in documentation

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#22]
Hello @kmoppel ,
I'm missing some details within the documentation that took me some time to figure out and many dropped and recreated containers.
As I tried to restore the backup I wasn't able to access the mounted folder from inside docker because of "access denied" for root caused by SElinux(on the host, CentOS 7).
To solve this I had to mount the folder with :rw,z and the complete command looks now like this:

docker run -d --net=bridge -p 10.xxx.xxx.101:3000:3000 -p 10.xxx.xxx.101:8080:8080 -p 127.0.0.1:5432:5432 -p 127.0.0.1:8083:8083 -p 127.0.0.1:8086:8086 -p 127.0.0.1:8088:8088 --restart unless-stopped -v /home/pgwatch2/pgwbackup:/pgwbackup:rw,z --name pw2 -e PW2_WEBNOANONYMOUS=1 -e PW2_WEBUSER=OurWebADM -e PW2_WEBPASSWORD=OurWebPW -e PW2_WEBSSL=1 -e PW2_GRAFANASSL=1 cybertec/pgwatch2

I'm using a configured docker bridge to have a static Bridge IP and also DNS:

/etc/docker/daemon.json :

{
  "bip": "172.17.0.1/16",
  "mtu": 1392,
  "dns": ["172.17.0.1","10.xxx.xxx.101","8.8.8.8"]
}

source: https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/

Maybe you could add above information to your documentation to speed up others while getting familiar with pgwatch2 :)

**Comment by kmoppel** [comment]
Documentation updated on mounting with "rw,z". Thanks a lot!
