### ISSUE TITLE
[Clarify] Document build process/command

### ISSUE THREAD

**Issue by rockaut** [cybertec-postgresql/pgwatch2#221]
Can you document how the "official" image is build? I'm always getting startup errors if I build it manually myself.

I am using master branch and build-docker-nonroot.sh but this always gives me these errors on startup ( so not while build but on usage ):

```shell
/pgwatch2/docker-launcher-nonroot.sh: line 42: /etc/postgresql/9.5/main/pgwatch_postgresql.conf: Permission denied
/pgwatch2/docker-launcher-nonroot.sh: line 43: /etc/postgresql/9.5/main/pgwatch_postgresql.conf: Permission denied
```

**Comment by kmoppel** [comment]
Actually I use the same build scripts from repository root - build-docker*.sh so not too much to document. Launching the nonroot latest tag seemed to work fine for me with latest Minishift (details in #216)
