### ISSUE TITLE
Active Prometheus exporter in addition to other datastores

### ISSUE THREAD

**Issue by jinnerbichler** [cybertec-postgresql/pgwatch2#222]
I am wondering if it is possible to start the Prometheus exporter AND have a separate datastore (e.g. postgres).

In the end, the Prometheus exporter is just an API endpoint providing monitoring data (or am I wrong): https://github.com/cybertec-postgresql/pgwatch2/blob/238773adffb4d39b2e58fb211ab294a05b6086ae/pgwatch2/prom.go#L212

It would be great to have all the awesome pre-build dashboards in Grafana and the data in Prometheus (e.g. for alerting).

**Comment by kmoppel** [comment]
@jinnerbichler  Yes this should be doable of course. But as I didn't see a need for our purposes I just tried to keep it simple initially. Will investigate how much code needs to be shuffled around, and when not too much then will implement that.

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.
