### ISSUE TITLE
[Enhancement] Split up single Image

### ISSUE THREAD

**Issue by rockaut** [cybertec-postgresql/pgwatch2#223]
As much as I like the solution it's just not good practice to just use a single image for all. It would be way more "container native" to use more services in a single deployment config. Also this would somewhat solve some of the questions like #222

Also the update to newer versions of the underlying software would be way easier. The split would be somewhat drastic that's granted. Maybe you could start an branch where we can contribute an try to make it happen?

**Comment by kmoppel** [comment]
Hey, you mean each architecture component separately? So basically something to glue together  1) config DB 2) metrics DB 3) collector 4) optional web UI 5) grafana ? Something like that I had in mind also some years ago, and it worked even I think (see the [docker](https://github.com/cybertec-postgresql/pgwatch2/tree/master/docker) folder for example), but I had to customize also for example Grafana (can't remember the exact reason) so it was quite some work and these files haven't gotten recent updates as mostly we do custom setups without Docker or container management systems.

**Comment by rockaut** [comment]
Yes - every component it's own service. I'm speaking just for k8s here.
That way you may - if you want - combine services.

For example: you may have 5 teams with 5 servers each running 2 instances/dbs. Currently you may of course just deploy one pgwatch2 but that way you loose the separation. So you run 5 pgwatch2 - but then you will waste system resources.

Why not just run the collector and influx component one time and the grafana for each team separate.

**Comment by borland667** [comment]
I went through an install without docker to understand every component properly and I think it would be great to have a docker-compose file with all the environment variables accordingly set just to show how everything is tied together.
It took me some time to figure out some of the bootstrap scripts that you need to run. 
We also have k8s and we were thinking of having a pgwatch gatherer in each environment inside the k8s cluster using metrics and config from files embedded in the image for k8s, an influxdb host for storing the metrics, and reuse our existing grafana instance.
Any hints and or advice is more than welcome! I'll be trying to share our experience soon.

**Comment by kmoppel** [comment]
I've now added a sample docker-compose file that show how to set up pgwatch2 using loosely coupled images / services: https://github.com/cybertec-postgresql/pgwatch2/blob/master/docker-compose.yml

**Comment by pnunn** [comment]
I know this is closed, but I tried to run the docker-compose setup as explained here, but it doesn't seem to have graphana in it? Am I missing something or should this be expanded to work with garphana?

**Comment by pashagolub** [comment]
@pnunn yeap, that's true. That file assumes you have your ows Grafana running somewhere. 
One should add such a section (please, change param values accordingly):
```compose
grafana:
    image: grafana/grafana:latest
    user: "0:0"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: pgwatch3_grafana
      GF_DATABASE_USER: pgwatch3
      GF_DATABASE_PASSWORD: pgwatch3admin
      GF_DATABASE_SSL_MODE: disable
      GF_AUTH_ANONYMOUS_ENABLED: true
    ports:
      - "3000:3000"
    restart: unless-stopped
```


Or you can try the [latest dev version](https://github.com/cybertec-postgresql/pgwatch3/blob/master/docker-compose.yml)
