### ISSUE TITLE
pgbouncer_stats: data collection does not work with PgBouncer v1.12

### ISSUE THREAD

**Issue by vitabaks** [cybertec-postgresql/pgwatch2#224]
I upgraded PgBouncer 1.8.1 to version 1.12.0 and statistics (pgbouncer_stats) immediately stopped collecting.

There are no errors in the pgwatch2 log.

pgwatch2 v1.6.2
influxdb v1.7.7

**Comment by kmoppel** [comment]
@vitabaks Hmm, that's weird...just checked and it seemed to work fine. Was using the Docker image of pgbouncer, but that should matter. Did restart help? Still nothing in logs?
---
localhost:5439 krl@pgbouncer=# show version;
     version      
──────────────────
 PgBouncer 1.12.0
(1 row)

**Comment by vitabaks** [comment]
@kmoppel 
The first thing I tried was to restart the pgwatch2 gatherer service. But it did not help.

If I install PgBouncer version 1.11, then it works.
As soon as I upgrade to version 1.12, the PgBouncer stats dashboard is empty.
Even if you delete v1.12 and then install v1.11, it still remains empty.

https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_12_0 
> Send statistics columns as numeric instead of bigint. This avoids some client libraries failing on values that overflow the bigint range. (#360, #401)

Could this problem be related to these changes in version 1.12? 

Database: Influxdb v1.7.7

**Comment by vitabaks** [comment]
```
Dec 05 17:40:08 tz-pw2-83 systemd[1]: Started pgwatch2 gatherer service.
Dec 05 17:40:09 tz-pw2-83 pgwatch2[19607]: 2019/12/05 17:40:09 WARN main: host info refreshed, nr. of enabled hosts in configuration: 44
```

**Comment by vitabaks** [comment]
![изображение](https://user-images.githubusercontent.com/37010174/70248500-0da50400-178c-11ea-8203-fd15669f1bb0.png)

**Comment by kmoppel** [comment]
Ok I think what's going on is that InfluxDb cannot handle the column data type changes - as it works with a fresh setup. Theoretically it would be possible to do a type conversion on pgwatch2 collector side...but it's still quite a cornercase and think there is a workaround. 

Didn't have time to test it but this could work if you want to preserve old data: 1) create a new measurement based on old "pgbouncer_stats" data with SELECT * INTO temp FROM pgbouncer_stats 2) drop old bouncer data with DROP MEASUREMENT pgbouncer_stats 3) start pgwatch2 on new bouncer 4) insert old data from the temp table into fresh pgbouncer_stats

**Comment by vitabaks** [comment]
Yes, it seems the problem only affects InfluxDb.

After I updated pgbouncer (to v1.12) on all my servers, and then I recreated MEASUREMENT "pgbouncer_stats", this solved my problem.

Thank you @kmoppel !
