### ISSUE TITLE
ERRO MetricsFetcher: failed to fetch metrics for xxx ,metric 'wal': pq: recovery is in progress

### ISSUE THREAD

**Issue by liyingxiao94** [cybertec-postgresql/pgwatch2#225]
Hello, I encountered some errors when running pgwatch2, grafana can't display the data normally, the error is reported as the title

**Comment by liyingxiao94** [comment]
Thanks ,I had solved the problem

**Comment by kmoppel** [comment]
yes this I think happend with some older 'wal' metric versions, should go away after metrics refresh
