### ISSUE TITLE
LDAP support enabled

### ISSUE THREAD

**Issue by marmelin** [cybertec-postgresql/pgwatch2#227]
Hello , 

we need LDAP enabled in grafana, but I cannot see how to implement without rebuilding the image on my own.

**Comment by kmoppel** [comment]
Hi,
yes this could be an issue. But the thing is that Grafana has tons of features and we have no way of determining what is needed so the only option is indeed to do customization on your end - either Docker build or a custom Grafana install. Easier than rebuilding the image though would be to use Docker volumes (like described in README) and to do a one time config change manually and then restart the container. Hope it helps.
