### ISSUE TITLE
Backup and restore of the pgwatch2 docker container

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#229]
Hi Team,

We have taken a backup of the pgwatch2 docker container as shown below in the following steps:

1.  Invoked shell within the docker container (our pgwatch2 docker container - e141bfc1a426):
    [root@cemtore01 ~]##docker exec -it e141bfc1a426 /bin/bash
2. Take backup using the provided backup script ( passing date of the backup as the backup name):
   root@e141bfc1a426:~# pgwatch2_bkup.sh 20200106
3. Verified the  generated backups in the pgwatch2 backup folder:
    root@e141bfc1a426:~# cd /pgwatch2/backup_20200106
    root@e141bfc1a426:/pgwatch2/backup_20200106# ll
    total 956
    drwxr-xr-x. 3 root root     82 Jan  6 11:30 ./
    drwxr-xr-x. 1 root root    147 Jan  6 11:30 ../
   -rw-r--r--. 1 root root 853615 Jan  6 11:30 grafana_config.sql
   drwx------. 2 root root   4096 Jan  6 11:30 influxdb_backup/
  -rw-r--r--. 1 root root 118609 Jan  6 11:30 pgwatch2_config.sql.

Now we would like to verify this backup by restoring it:
Please note we are not upgrading the pgwatch2 docker container at this time, we just need to verify that we can restore from the backups. 
In the backup script - pgwatch2_bkup.sh, you have provided the section (shown below) which talks about restore.

############
# STEPS FOR RESTORING DATA FROM A OLDER DOCKER VERSION
#
# FYI - restoring cannot be currently fully automated so here just the steps
############

# 1. make sure you have successful backups from old Docker container for all components from above
# 2. stop the old container
# 3. launch the new docker container with specifying a shared volume to access the backup easily (you could also set up ssh etc)
#       docker run ... -v ~/pgwatch2_backups:/pgwatch2_backups:rw,z ...
#       nb! when having problems accessing the share with SELinux see Github issue #22 for potential relief.
# 4. connect to the Postgres DB and rename "pgwatch2" and "pgwatch2_grafana" databases to "*_original" for example and
# recreate them (could also just drop and recreate, but just in case...)
# 5. restore both Postgres DB dumps
#       psql -f ~/pgwatch2_backups/pgwatch2_backup_20170123/pgwatch2_config.sql pgwatch2
#       psql -f ~/pgwatch2_backups/pgwatch2_backup_20170123/grafana_config.sql pgwatch2_grafana
# 6. log into the running Docker image and kill the InfluxDB process (as restoring requires it)
#       pkill influxd
# 7. restore InfluxDB meta files
#       influxd restore -metadir /var/lib/influxdb/meta /pgwatch2_backups/influxdb_backup
# 8. restore InfluxDB data files (real metric infos)
#       influxd restore -database pgwatch2 -datadir /var/lib/influxdb/data /pgwatch2_backups/influxdb_backup
# 9. restart the Docker image
#        docker stop pw2 && docker start pw2
# 10. done!

We have a few questions/clarifications from this section before we can try a restore:

For our restore when we are not changing/upgrading the pgwatch2 container, I believe we can safely skip steps 1,2,and 3 and, run only all the remaining steps 4 to 10.  Please confirm.

And, if we have to upgrade a new version of pgwatch2 container, then as you noted in the restore sections, we will need to perform all the steps from 1-10.  But, we are not clear on step 3 (following)

# 3. launch the new docker container with specifying a shared volume to access the backup easily (you could also set up ssh etc)
#       docker run ... -v ~/pgwatch2_backups:/pgwatch2_backups:rw,z ...

**Comment by kmoppel** [comment]
Hi, yes you're correct. I also noticed that for latest Influx versions the restore process / syntax has changed a bit so I've updated the instructions also accordingly.

**Comment by bikramma** [comment]
Hi Kaarel -  Thanks for your quick response. In your response, you noted that you have updated your instructions for the restore process for the latest Influx versions. How do I get these latest instructions?
And, as I requested earlier, I wanted to understand step 3 that is needed for upgrading the container:
docker run ... -v ~/pgwatch2_backups:/pgwatch2_backups:rw,z …

Would you be able to clarify clearly the various arguments/parameters that are needed for the above command?

Also, can you please provide me any good links/examples on how to run a cron job to take the pgwatch backups from within the pgwatch container.
