### ISSUE TITLE
feature request: switch to prevent creation of "test"  data

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#23]
Hello @kmoppel ,
it would be nice to have a switch when pulling the docker image to prevent creation of the "test" data. 
Even if I delete the configuration for it (as renaming isn't possible) grafana shows this as default choice every time one accesses the dashboards. And it's really hard to delete these data out of the influx db...

kind regards
Georg

**Comment by kmoppel** [comment]
hi! yes, actually generating test-data could well be an "opt in" flag. and a button for deleting all data for a host would make sense also.

**Comment by kmoppel** [comment]
Now possible with "docker run ... -e NOTESTDB=1 ..."
Decided to still insert the test database to make it easier for beginners to get an overview of the project.
