### ISSUE TITLE
More questions/clarifications on pgwatch2 restores from backups - #230

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#232]
Hi Kaarel, 
Thx for your response about the "z" option - but I was looking also for understanding of the other arguments -- 
for e.g  
1. what are the use/meaning of the two file paths /pgwatch2_backups:/pgwatch2_backups
2. why is "rw" needed in the command?  
3. what are the meaning of the "..." s ?
Do you have some document/link where I can read more on this docker run command.

Also, would you please provide me some examples of restore of pgwatch2 -- 1. Restore of backups in an existing pw2 container 2. Restore of backups in a new upgraded container

Regards,
Bikram

**Comment by kmoppel** [comment]
@bikramma I would not want to go deep into the Docker run options, it has nothing to do with pgwatch2. Please read more from official [documentation](https://docs.docker.com/engine/reference/run/). The "..." part means though the usual Docker part of choosing the ports you want to expose and image versions etc.

And restoring into and existing container or to a new one is exactly the same and it should work as described at the end of [take_backup.sh](https://github.com/cybertec-postgresql/pgwatch2/blob/master/take_backup.sh) sample script.
