### ISSUE TITLE
patroni type, i didn't get any data from grafana

### ISSUE THREAD

**Issue by jianhaiqing** [cybertec-postgresql/pgwatch2#233]
- monitored database config, i didn't get any data from grafana.
![](https://tva1.sinaimg.cn/large/006tNbRwgy1gaqc7flk8qj313w0gh0yb.jpg)
- zookeeper for patroni
![](https://tva1.sinaimg.cn/large/006tNbRwgy1gaqbw9evd9j30vl0h6wgs.jpg)

- refer to other issue
https://github.com/cybertec-postgresql/pgwatch2/issues/71
https://github.com/cybertec-postgresql/pgwatch2/issues/231

- [Q]: how does the DB-type patroni work ?

**Comment by kmoppel** [comment]
@jianhaiqing but is there data in the pgwatch metrics DB? Is it a gathering or display problem? Are there any errors in the logs?

**Comment by kmoppel** [comment]
[Q]: how does the DB-type patroni work ?
[A]: The difference for "patroni" dbtype is that the list of actually monitored instances is dynamic: pgwatch2 connects to DCS (etcd, zk, consul) and fetches a list of members and then starts monitoring them as usual. If you don't want to monitor the replica nodes but only track the current master then you could also set the "only_if_master" flag additionally.
