### ISSUE TITLE
change_events scraping fails with "empty SQL"

### ISSUE THREAD

**Issue by bukem** [cybertec-postgresql/pgwatch2#234]
Hi,

I have the following message when using `exhaustive` config:
`ERRO Collect: failed to scrape [postgres_postgres:change_events]: empty SQL`

Since `change_events` is expected to be emply, I do not quite understand what should I do to make that metric work?

I use Config DB:
```
postgres=# select * from metric where m_name = 'change_events';
-[ RECORD 1 ]------+------------------------------
m_id               | 43
m_name             | change_events
m_pg_version_from  | 9.0
m_sql              |                              +
                   |
m_comment          |
m_is_active        | t
m_is_helper        | f
m_last_modified_on | 2020-01-08 09:58:23.124728+00
m_master_only      | f
m_standby_only     | f
m_column_attrs     |
m_sql_su           |

```

Thanks!

Mike

**Comment by kmoppel** [comment]
@bukem Hi, seems that you're running in Prometheus mode...and there indeed "state" based metrics are not available as technically Promehteus metrics should be stateless. So made the error just a bit nicer. The default Prometheus [config](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/preset-configs.yaml#L112) also does not include that metric.
