### ISSUE TITLE
Different ways of pgwatch2 installs using the pgwatch2 docker container 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#235]
Hi Team,

Following the install documentation - Pgwatch2 -- readme (Github  - https://github.com/cybertec-postgresql/pgwatch2#installing,  we fetched and installed the pgwatch2 docker image with the quick start option:
# fetch and run the latest Docker image, exposing Grafana on port 3000 and administrative web UI on 8080 
docker run -d -p 3000:3000 -p 8080:8080 -e PW2_TESTDB=true --name pw2 cybertec/pgwatch2 

And, added our database for monitoring in the admin interface, and followed other steps to add helper metrices etc.  We are OK so far in monitoring what we wanted.
 
But, going through your install document, we find the following steps that look interesting:

> for v in pg influx grafana pw2 ; do docker volume create $v ; done 
> # with InfluxDB for metrics storage 
> docker run -d --name pw2 -v pg:/var/lib/postgresql -v influx:/var/lib/influxdb -v grafana:/var/lib/grafana -v pw2:/pgwatch2/persistent-config -p 8080:8080 -p 3000:3000 -e PW2_TESTDB=true cybertec/pgwatch2 
> # with Postgres for metrics storage 
> docker run -d --name pw2 -v pg:/var/lib/postgresql -v grafana:/var/lib/grafana -v pw2:/pgwatch2/persistent-config -p 8080:8080 -p 3000:3000 -e PW2_TESTDB=true cybertec/pgwatch2-postgres 
> 
> 
   
We have not done none of these steps -  create the volumes (docker volume create) nor specify the metrics storage database.  What are the repercussions ?

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Well nothing critical, it's all optional. Using volumes just makes it easier to update the pgwatch2 containers to new versions and the image with Postgres as metrics storage DB is 95% the same as with Influx storage, but has the benefit that there are couple of extra dashboards based on queries that are not possible with Influx as the query language is very primitive and limited there.
