### ISSUE TITLE
Can you clarify little more on some of the pgwatch2 features

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#236]
Hi Team,

Your pgwatch2 install document is clear in most of the sections  and thank you all for your great works.
However, if you all have some time, it would really help me if you can provide me some clarifications with examples on the following of the pgwatch2 features:
Features 

>Easy extensibility by defining metrics in pure SQL (thus they could also be from business domain) 
  Where in the DB overview/Grafana dashboard I can create metrics in pure SQL? 

>Multiple configuration options (YAML, PostgreSQL, ENV) supporting both "push" and "pull" models 
  Can you please provide me examples of each of these options: YAML, PostgreSQL, ENV -- ?
  And, what do we mean by "push" and "pull" -- it would help me if you can give me some examples.

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
* Metrics can be defined via the UI (https://github.com/cybertec-postgresql/pgwatch2/blob/master/screenshots/web_ui_metrics_and_preset_configs.png) or just as new files in the ["metrics"](https://github.com/cybertec-postgresql/pgwatch2/tree/master/pgwatch2/metrics) folder when using YAML setup.

* Multiple configuration options
  - normal setup means monitoring config is kpet in a Postgres DB 
  - YAML setup is file based and no DB for config is needed (Ansible etc), description [here](https://github.com/cybertec-postgresql/pgwatch2#file-based-operation)
  - Env. mode means that a single DB can be monitored directly with ENV or command line params, like the sample [here](https://github.com/cybertec-postgresql/pgwatch2#ad-hoc-operation)

* Push / pull
  - "pull" is the typical operating model - 1 metrics collector can monitor X DBs
  - "push" means that you have a collector on each DB host and they all push metrics to a common metrics DB
