### ISSUE TITLE
Problems with the panel "Avg. time from last autovacuum (tbls > 100MB)"

### ISSUE THREAD

**Issue by 100317667** [cybertec-postgresql/pgwatch2#237]
Hi,

I think the dashboard query "Avg. time from last autovacuum (tbls > 100MB)" of version 1.5.1,  does not collect the expected data. In the way the dashboard is defined, I understand that it is the average time since the last vacuum / autovacuum in tables is greater than 100MB.

However the result I understand this query return, is the data collected by influxdb in the last half hour, to group them by hour (regardless of which table they are) and to throw the value with the most recent timestamp. As the timestamp of the information in all tables is usually the same, it returns the one with the oldest void, and this does not match the definition of the query.

In addition, if in the last half hour data have been collected from two different hours, for example, from 13:59 and 14: xx, the average of both is performed (therefore, this average is not all tables with a size larger than 100 MB, but instead of that, the tables that have a higher vacuum value).
I enclose an image, of a monitored database, which contains four tables, empty at different times, where you can see what I have explained above.

![image1](https://user-images.githubusercontent.com/49982095/72719954-3553fe00-3b79-11ea-9834-2ef61dd1e510.jpg)

I believe that the result of the query would be improved with the following:
Change the current "GROUP BY time (1h)" to "GROUP BY time (1h)," table_name "". In this way the GROUP BY will return a sample of each table and then the average would be made.

![image2](https://user-images.githubusercontent.com/49982095/72719978-456bdd80-3b79-11ea-83ba-cf66c2e96c1e.jpg)

I would like to know your opinion about it. Thanks. 

Regards,

**Comment by kmoppel** [comment]
Hi, you're absolutely correct - should be grouped by table_name / table_full_name. I've changed it...but for recent version (for Grafana v6) there's no such check anymore even as "averages" don't work so well for some data sets.
