### ISSUE TITLE
error m_sql_su

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#238]
Hello, i face this error while starting pgwatch2 . I did not modify anything, it was ok yesterday.....

2020/01/21 16:24:02 CRIT InitAndTestConfigStoreConnection: could not ping configDb! exit. pq: the database system is starting up
2020/01/21 16:24:04 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2020/01/21 16:24:09 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s 
(max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2020/01/21 16:24:14 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2020/01/21 16:24:19 CRIT main: Could not initialize InfluxDB Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2020/01/21 16:24:19 WARN InitAndTestInfluxConnection: Database 'pgwatch2' not found! Creating with 30 retention and retention policy name "pgwatch_def_ret"...
2020/01/21 16:24:19 CRIT ReadMetricDefinitionMapFromPostgres: pq: column "m_sql_su" does not exist
2020/01/21 16:24:20 CRIT ReadMetricDefinitionMapFromPostgres: pq: column "m_sql_su" does not exist
2020/01/21 16:24:22 CRIT ReadMetricDefinitionMapFromPostgres: pq: column "m_sql_su" does not exist
2020/01/21 16:24:24 CRIT ReadMetricDefinitionMapFromPostgres: pq: column "m_sql_su" does not exist
2020/01/21 16:24:26 CRIT ReadMetricDefinitionMapFromPostgres: pq: column "m_sql_su" does not exist
2020/01/21 16:24:27 CRIT ReadMetricDefinitionMapFromPostgres: pq: column "m_sql_su" does not exist

**Comment by pmpetit** [comment]
i have remove pvc and pv from k8s, it is ok now....

**Comment by kmoppel** [comment]
@pmpetit This type of stuff happens when a new container version is started without applying the SQL migration scripts. There's a hint on that in CHANGELOG. You're probably running the "latest" container? This is not a good idea usually, better specify always a tag version so that things don't automatically break.
