### ISSUE TITLE
logon on pgwatch2 config (:8080) opens a new tab

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#24]
Hello @kmoppel ,

When the config at :8080 is password protected the login page is kept open after login while a new page/ browser tab is opened with the configuration itself. This is a little bit confusing...

kind regards

Georg

**Comment by kmoppel** [comment]
This could be annoying indeed when using logins. Fixed now with https://github.com/cybertec-postgresql/pgwatch2/commit/df2d86987c84a8049d46623bd3da1280e129613e. Thanks for reporting!

**Comment by margaretmm** [comment]
I can not  visit the 8080 port, and my docker has exposed 8080
my docker image:　https://hub.docker.com/r/cybertec/pgwatch2/tags/　　　tag=latest

**Comment by kmoppel** [comment]
Hi @margaretmm, without logs hard to say anything...logs are available when logging into the docker container under /var/logs/supervisor/. does it happen consistently, even when starting a new container?
