### ISSUE TITLE
pgwatch2/bootstrap/grafana_datasource.sql don`t have in rpm

### ISSUE THREAD

**Issue by patsevanton** [cybertec-postgresql/pgwatch2#242]
Hello! I use pgwatch2 1.7.0-SNAPSHOT-91e1d21
[root@postgresql-apatsev ~]# rpm -ql  pgwatch2 | grep datasource
[root@postgresql-apatsev ~]# rpm -ql  pgwatch2 | grep bootstrap

```
2.2. Set up the Influx datasource as default

Use the Grafana UI (Admin -> Data sources) or adjust and execute the "pgwatch2/bootstrap/grafana_datasource.sql"
```

**Comment by kmoppel** [comment]
Yes was not there because not too useful, but I've added it now so the next version will have the samples also installed:)
