### ISSUE TITLE
Where execute  "pgwatch2/bootstrap/grafana_datasource.sql"

### ISSUE THREAD

**Issue by patsevanton** [cybertec-postgresql/pgwatch2#243]
Hello. I try run pgwatch2 without docker.

Use the Grafana UI (Admin -> Data sources) or adjust and execute the "pgwatch2/bootstrap/grafana_datasource.sql"

Where execute  "pgwatch2/bootstrap/grafana_datasource.sql"

Thanks!

**Comment by kmoppel** [comment]
Hi, allkinds of initialization / bootstrap scripts can be found here: https://github.com/cybertec-postgresql/pgwatch2/tree/master/pgwatch2/bootstrap
