### ISSUE TITLE
Installing pgwatch2 without docker

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#244]
Hi, 
We are getting the following errors in step 1.3 Roll out the pgwatch2 schema (will holds connection strings of DB-s to be monitored + metric definitions)
psql -f pgwatch2/sql/config_store/config_store.sql pgwatch2

Errors:
-bash-4.2$ psql -f /config_store.sql pgwatch2^C
-bash-4.2$ psql -f config_store.sql pgwatch2
psql:config_store.sql:1: ERROR:  syntax error at or near "not"
LINE 1: create schema if not exists pgwatch2 authorization pgwatch2;
                         ^
psql:config_store.sql:3: ERROR:  could not open extension control file "/usr/share/pgsql/extension/pg_stat_statements.control": No such file or directory
psql:config_store.sql:5: ERROR:  could not open extension control file "/usr/share/pgsql/extension/plpythonu.control": No such file or directory
SET
ALTER DATABASE
SET
psql:config_store.sql:13: NOTICE:  table "preset_config" does not exist, skipping
DROP TABLE
psql:config_store.sql:21: ERROR:  schema "pgwatch2" does not exist
psql:config_store.sql:23: ERROR:  schema "pgwatch2" does not exist
psql:config_store.sql:57: ERROR:  schema "pgwatch2" does not exist
psql:config_store.sql:59: ERROR:  relation "monitored_db" does not exist
psql:config_store.sql:64: ERROR:  schema "pgwatch2" does not exist
psql:config_store.sql:84: NOTICE:  CREATE TABLE will create implicit sequence "metric_m_id_seq" for serial column "metric.m_id"
psql:config_store.sql:84: ERROR:  type "jsonb" does not exist
LINE 12:     m_column_attrs      jsonb,
                                 ^
psql:config_store.sql:91: ERROR:  relation "schema_version" already exists
psql:config_store.sql:93: ERROR:  schema "pgwatch2" does not exist
LINE 1: insert into pgwatch2.schema_version (sv_tag) values ('1.6.2'...
                    ^
psql:config_store.sql:237: ERROR:  schema "pgwatch2" does not exist
LINE 1: insert into pgwatch2.preset_config (pc_name, pc_description,...

**Comment by bikramma** [comment]
Note: We have installed PostgreSQL 9.2.24-1.el7_5  for CentOS 7
[root@cemtor02 install]# yum list postgresql*
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos.dfw.quadranet.com
 * extras: repos.dfw.quadranet.com
 * updates: repos.dfw.quadranet.com
Installed Packages
postgresql.x86_64                 9.2.24-1.el7_5       @base
postgresql-libs.x86_64            9.2.24-1.el7_5       @base
postgresql-server.x86_64          9.2.24-1.el7_5       @base
Available Packages
postgresql.i686                   9.2.24-1.el7_5       base
postgresql-contrib.x86_64         9.2.24-1.el7_5       base
postgresql-devel.i686             9.2.24-1.el7_5       base
postgresql-devel.x86_64           9.2.24-1.el7_5       base
postgresql-docs.x86_64            9.2.24-1.el7_5       base
postgresql-jdbc.noarch            9.2.1002-6.el7_5     base
postgresql-jdbc-javadoc.noarch    9.2.1002-6.el7_5     base
postgresql-libs.i686              9.2.24-1.el7_5       base
postgresql-odbc.x86_64            09.03.0100-2.el7     base
postgresql-plperl.x86_64          9.2.24-1.el7_5       base
postgresql-plpython.x86_64        9.2.24-1.el7_5       base
postgresql-pltcl.x86_64           9.2.24-1.el7_5       base
postgresql-static.i686            9.2.24-1.el7_5       base
postgresql-static.x86_64          9.2.24-1.el7_5       base
postgresql-test.x86_64            9.2.24-1.el7_5       base
postgresql-upgrade.x86_64         9.2.24-1.el7_5       base
[root@cemtor02 install]#

**Comment by kmoppel** [comment]
Ok yes seems to be a DDL problem - "IF NOT EXISTS" is not supported on such an old version as 9.2. 
Why on earth are you starting with a version that's out of the Postgres support window for years?
But probably if you remove the "if not exists", "if exists" and replace "jsonb" with "json" it should work.
