### ISSUE TITLE
Looking for one more help/response  clarifications on issue #244 - Install pgwatch2 without docker  

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#245]
Hi Kaapel,
Thanks for your time and help with the clarification and response -- yes I also thought that the postgres version could be the problem -- I really do not know why yum install of PostgreSQL picked up this old verion (I have attached the screen snapshot -install-PostgreSQL-snapshot.doc).
If you would point me to the right url to download the right version I will appreciate.

But, if you check the errors again that I sent you in request #244, I also encountered the following errosr:
psql:config_store.sql:3: ERROR: could not open extension control file "/usr/share/pgsql/extension/pg_stat_statements.control": No such file or directory
psql:config_store.sql:5: ERROR: could not open extension control file "/usr/share/pgsql/extension/plpythonu.control": No such file or directory
 
I am wondering if that is also due to installing the old version:

**Comment by bikramma** [comment]
Forgot to attach the installation screenshot:
[install-postgresql-snapshot.docx](https://github.com/cybertec-postgresql/pgwatch2/files/4171772/install-postgresql-snapshot.docx)

**Comment by kmoppel** [comment]
Yes this is a known problem with Centos that it uses some very old PG versions, altough Centos 8 is a bit more better at PG v10. The best way is not to download the RPM-s directly but to configure your system to use the official Postgres repos - details for Centos / Redhat here: https://yum.postgresql.org/
