### ISSUE TITLE
Pgpool support

### ISSUE THREAD

**Issue by jolet** [cybertec-postgresql/pgwatch2#246]
Hi, any plans to include pgpool metrics?

**Comment by kmoppel** [comment]
@jolet Hi, what metrics do you have in mind more exactly? Last time I checked (maybe 1 year ago) there were not so many usable statistics with the "SHOW" commands, only amount of sessions which could be measured also on PG side. Let me know if there's something new

**Comment by jolet** [comment]
@kmoppel hm, correct observation, but let me explain my situation - we have 2 postgres instances in master/slave config, with pgpool in front of them load-balancing the traffic. 
Many times we are in situation where pgpool decides to go hairy, while postgres instances are working fine and I know pgwatch just reflects this but I cant rely on that, I still have to monitor pgpool separately. 
Useful data on the board would be 'show pool_nodes', aka what pgpool considers dead/alive, replication lag/delay, maybe some other metrics. I am dev by trade so don't know really. I learned alot from pgwatch and default metrics about postgres, would be interesting if pgpool allowed that insight into it's own working internals but I understand this might not be the case, so feel free to close this if pgpool team should deal with this first. Thanks anyway :)

**Comment by kmoppel** [comment]
Default dashboard looks like that: https://raw.githubusercontent.com/cybertec-postgresql/pgwatch2/master/screenshots/pgpool_status.png
