### ISSUE TITLE
Looking for one more help/response  clarifications on issue #245 - Install pgwatch2 without docker

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#247]
Hi Kaarel,

Thanks for all your timely help in quick response to our issues  and clarifying me.
Just to let you know, we now installed the latest PostgreSQL 10 (10.11) and it fixed most of the errors when we ran the config_store.sql, except one error in creating the plpython extension (shown below):
 ERROR:  could not open extension control file "/usr/pgsql-10/share/extension/plpythonu.control": No such file or directory
Why are we attempting to create the plpythonu extension here?   Are we not supposed to have the  plpython rpm installed before we try to create its extension?

I also have a few questions/clarifications needed if you can help me:
Question 1. In pgwatch2 docker install, we created the pg_stat_statements and plpythonu extensions in the database(s) that we wanted to monitor, but not in the pgwatch2 configuration database that comes in the docker container.  But, in this non-docker individual component installation, we are creating these extensions in the pgwatch2  configuration database and not in the monitored databases --- any obvious reason(s) for this?  
Question 2. In this non-docker individual component installations, do we have to always create the  pgwatch2  database separately  on a different server from the databases/servers that we want to monitor ?

**Comment by kmoppel** [comment]
@bikramma Hi, you're actually right - the extensions are not needed for common operation and the declarations could make setup harder, so I've removed them now.

Q1: No good reason, some historical leftover.
Q2: No, the pgwatch2 database doesn't necessarily have to be a separate server but it's a best practice. One could also leave out the config DB completely and use YAML by the way if number of monitored servers is small or everythings is well automated.

**Comment by bikramma** [comment]
Hi Kaarel,

Thanks a lot.

Regarding your following response on Q2, I have a few new clarifications/questions:

<< Q2: No, the pgwatch2 database doesn't necessarily have to be a separate server but it's a best practice. One could also leave out the config DB completely and use YAML by the way if number of monitored servers is small or everythings is well automated.>>

  Q 1 – If we want to run the pgwatch2 database on the same server as the database we want to monitor, I believe we have to run it as a separate postgresql system service on a different port (e.g 5433) than the monitored database port(e.g 5432).

  Q 2 – Can we create the pgwatch2 configuration db within the  monitored database itself?

Thanks and regards,

Bikram


Bikram Majumdar
Sr Software Developer/DBA, Aqsacom Inc.
c. 1.972.365.3737

[cid:image003.png@01D5E194.6C0209E0]<http://www.aqsacom.com/>

Disclaimer. This electronic mail message contains CONFIDENTIAL information which is (a) CUSTOMER / SUPPLIER / PARTNER PRIVILEGED COMMUNICATION, WORK PRODUCT, PROPRIETARY IN NATURE, OR OTHERWISE PROTECTED BY LAW FROM DISCLOSURE, and (b) intended only for the use of the Addressee(s) named herein. If you are not an Addressee, or the person responsible for delivering this to an Addressee, you are hereby notified that reading, copying, or distributing this message is prohibited. If you have received this electronic mail message in error, please reply to the sender and take the steps necessary to delete the message completely from your computer system. Statement and opinions expressed in this e-mail are those of the sender, and do not necessarily reflect those of AQSACOM. AQSACOM accepts no liability for any damage caused by any virus/worms transmitted by this email.

**Comment by kmoppel** [comment]
Q 1 – If we want to run the pgwatch2 database on the same server as the database we want to monitor, I believe we have to run it as a separate postgresql system service on a different port (e.g 5433) than the monitored database port(e.g 5432).
A: not really. just a plain separate database on the same instance would be enough also. i.e. "create database pgwatch2". But it's more of architectural decision you need to take on your own, pgwatch2 doesn't care too much where the config schema is created.

  Q 2 – Can we create the pgwatch2 configuration db within the  monitored database itself?
A: Yes you can
