### ISSUE TITLE
Installation of pgwatch2 - Non Docker 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#248]
Hi Team,

In the documentation of pgwatch2 installation of non-docker individual components, I see you have step2  to install influx db as shown below:
==============================
Install InfluxDB (for Postgres as metrics storage DB see instructions here)

INFLUX_LATEST=$(curl -so- https://api.github.com/repos/influxdata/influxdb/tags | grep -Eo '"v[0-9\.]+"' | grep -Eo '[0-9\.]+' | sort -nr | head -1)
wget https://dl.influxdata.com/influxdb/releases/influxdb_${INFLUX_LATEST}_amd64.deb
sudo dpkg -i influxdb_${INFLUX_LATEST}_amd64.deb 
==============================
Q 1. We are installing on CentOS 7 --- would you please provide the URL to download InfluxDB for CentOS 7.   And would you also modify the above instructions as applicable for CentOS 7.  
Q 2. Why do we need the InfluxDB installation -- is it mandatory for pgwatch2 non-docker individual installation?

Any help/clarifications will be greatly appreciated.

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Q1: Please look here for downloads, googling also helps: https://portal.influxdata.com/downloads/
Q2: No, it's not mandatory. Only when you want to store your metrics in InfluxDB
