### ISSUE TITLE
Grafana alerting with permanent "no data" state

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#25]
Hello @kmoppel ,
I'm having problems with Grafanas alerting function. I do have current data within the dashboards and I'm also able to download time series but the alerting tells me always and on any places I've tried that state is "no data" causing no alerts to be fired.
Checking the data source gives also a "valid" back. 
So it seems that just alerting doesn't get anything for some reason. If you don't have any hints for me I'll ask within the Grafana community.

kind regards
Georg

**Comment by kmoppel** [comment]
Hi! I looked into the problem but couldn't actually reproduce the problem. But I made some changes to the overview dashboard and there's a new Grafana version (4.5.1) so maybe just try again. Closing the issue for now as it looks more like a pure Grafana problem. Thanks for the feedback though!
