### ISSUE TITLE
Index Overview -> Duplicate Indices is empty

### ISSUE THREAD

**Issue by mhorbul** [cybertec-postgresql/pgwatch2#250]
I am using external InfluxDB (v1.4.3rc0) to store metrics. 

The following query from this [dashboard](https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/influxdb/v6/index-overview/dashboard.json#L148) causes the error and therefor nothing shows up in the "Duplicate Indices" panel.

**QUERY:**

```
select 
  "index_def", 
  "max_index_size", 
  "count" 
from (
  select 
     mode("index_def") as "index_def", 
     count(distinct("index_full_name_val")), 
     max("index_size_b") as "max_index_size"  
  from 
    index_stats 
  where "dbname" =~ /^$dbname$/  AND $timeFilter 
  group by "table_full_name", "index_def_hash", "dbname"
) 
where "count" > 1 
group by "table_full_name", "index_def_hash", "dbname"
```

**ERROR:**

```
aggregate function distinct() cannot be combined with other functions or fields
```

**Comment by kmoppel** [comment]
Hi @mhorbul , thanks for looking into it. The new query seems to work...but produces too many false positives :/ See the below screenshots. Also you're running quite an old Influx version...I'd recommend to update first.
![Screenshot from 2020-02-13 16-56-20](https://user-images.githubusercontent.com/346788/74447365-e94b5f00-4e81-11ea-9836-4f4ab96fda72.png)
![Screenshot from 2020-02-13 16-56-35](https://user-images.githubusercontent.com/346788/74447370-e9e3f580-4e81-11ea-9514-a1b6f275d5d1.png)
