### ISSUE TITLE
Installation of pgwatch2 non-docker -- Grafana installation 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#253]
Hi Team,

In the document we get this step to install grafana, but, we are encountering a 404 URL not found, or certificate errors:  Is there any other URL to download grafana?
[root@cemtor02 ~]# wget https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_${GRAFANA_LATEST}_x86_64.rpm
--2020-02-12 15:59:48--  https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_6.6.1_x86_64.rpm
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.244.48
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.244.48|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-12 15:59:48 ERROR 404: Not Found.

[root@cemtor02 ~]# wget https://52.218.244.48/grafana-releases/release/grafana_${GRAFANA_LATEST}_x86_64.rpm
--2020-02-12 16:00:49--  https://52.218.244.48/grafana-releases/release/grafana_6.6.1_x86_64.rpm
Connecting to 52.218.244.48:443... connected.
    ERROR: certificate common name â*.s3-us-west-2.amazonaws.comâ doesn't match requested host name â52.218.244.48â.
To connect to 52.218.244.48 insecurely, use `--no-check-certificate'.

**Comment by kmoppel** [comment]
Not a pgwatch2 topic, assuming some firewall on your side...
