### ISSUE TITLE
Incorrect data from pgbouncer.

### ISSUE THREAD

**Issue by dan-aksenov** [cybertec-postgresql/pgwatch2#256]
Hello. I'm unable to read data from pgbouncer in grafana. Im using docker build of pgwatch with postgres database as storage.
Having following error in grafana:
> pq: invalid input syntax for type double precision: "MTkwODA="

When I connect to database I see that pbbouncer data is really "corrupted"
```
SELECT data FROM pgbouncer_stats limit 1;
data     | {"avg_recv": "Mjg=", "avg_sent": "MzU=", "total_sent": "NDg3Mzg=", "avg_wait_time": "MA==", "avg_xact_time": "MjM0", "avg_query_time": "MjM0", "avg_xact_count": "MA==", "total_received": "NDU5NzA=", "avg_query_count": "MA==", "total_wait_time": "MTkwODA=", "total_xact_time": "MTMwNTIx", "total_query_time": "MTMzOTMx", "total_xact_count": "MTM2", "total_query_count": "MTM3"}
```
Any ideas on what am i doing wrong?

**Comment by kmoppel** [comment]
Indeed...seems v1.12.0 of PgBouncer changed counter data type. Will fix asap

**Comment by kmoppel** [comment]
Fixed. Will try to publish a new Docker image also in next days.
