### ISSUE TITLE
Install pgwatch2 non-docker - how do we monitor the pgwatch2 database as  test database as we are able to do in docker version? 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#257]
Hi Kaarel & Team,

We have followed and performed  the following steps 1,2,&3, and all the sub-steps within these steps.
1.Install Postgres and create DB-s/roles for pgwatch2/Grafana
2.Install InfluxDB
3.Install Grafana

And, then we ran the  /pgwatch2/insert_test_monitored_db_nonroot.sql (shown below) thinking it will show the test database dashboards, but, nothing is showing up on grafana dashboards: 
]# cat insert_test_monitored_db_nonroot.sql
insert into pgwatch2.monitored_db (md_unique_name, md_preset_config_name, md_config, md_hostname, md_port, md_dbname, md_user, md_password)
  select 'test', 'exhaustive', null, 'localhost', '5432', 'pgwatch2', 'pgwatch2', 'pgwatch2admin'
  where not exists (
      select * from pgwatch2.monitored_db where (md_unique_name, md_hostname, md_dbname) = ('test', 'localhost', 'pgwatch2')
  )
;

And we are yet to perform the following remaining steps:
4.Install Python 3 and start the Web UI
5.Install Go and compile the gatherer

Question 👍 Do we need to complete step 5 ( Install Go and compile the gatherer
) before we can see any monitored databases  even if we just want to monitor the pgwatch2 configuration database as the test database initially?

In the same folder, I also see another SQL script - insert_test_monitored_db.sql, and a shell script -insert_test_monitored_db.sh.  I am assuming these are used in the docker version. If you would please kindly confirm that.  

Question 👍:  Step 4 instructs to install python 3. 
We earlier had installed python 2 (OS) , and  plpython (rh-postgresql10-plpython-10.3)  to create the plpythonu extension.  Can we start Web UI using  python2 ?  Or do we still need to install python 3? 
And, if we can use python2 to start the Web UI , then  how do we do that -- meaning which pgwatch2 folder/script we can run to start the Web UI using python2

Please I will appreciate very much if you can help me and clarify and answer my questions.

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Q: Do we need to complete step 5 ( Install Go and compile the gatherer
) before we can see any monitored databases even if we just want to monitor the pgwatch2 configuration database as the test database initially?
A: Yes, if you really want to set up from zero, i.e. "git pull"

Q: In the same folder, I also see another SQL script - insert_test_monitored_db.sql, and a shell script -insert_test_monitored_db.sh. I am assuming these are used in the docker version. If you would please kindly confirm that.
A: Yes, all configuration files in the project are for Docker as we cannot know what users want for custom setups

Q: Step 4 instructs to install python 3....Can we start Web UI using python2 ?
A: No, the Web UI code does not work with Python 2. Python 2 is also already deprecated / EOL so not recommended. And to run web.py it should not really matter from which folder you call it.
