### ISSUE TITLE
Install/configure pgwatch2  data sources (non-docker) 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#258]
Hi Kaarel and Team,
Thank you so much always for your time and immediate responses. Really appreciated all your help and patience with me all along.

I need a bit more clarifications on how to configure data sources:
As per the documentation in step 2.2, we have two options to create our metrics data source:
We can add our data source(s) via the Grafana UI or,
We can adjust and execute the "pgwatch2/bootstrap/grafana_datasource.sql"

Q 1.
I see that we are using influxdb as the data source in the pgwatch2/bootstrap/grafana_datasource.sql.  It specifies 'root','root' for the password,"user" as shown below. I am assuming we need to adjust/specify the root(host root account) password here -- right?  
======================================
Script: pgwatch2/bootstrap/grafana_datasource.sql
======================================
insert into data_source (org_id, version, type, name, access, url,
password, "user", database, basic_auth, is_default, json_data, created, updated
) values (
1, 0, 'influxdb', 'Influx', 'proxy', 'http://localhost:8086',
'root', 'root', 'pgwatch2', 'f', 't', '{}', now(), now()
);
=======================================
Q 2.
I also see you have put a script to use PostgreSQL as the metric data store -
as shown below:
=======================================
Script:pgwatch2/bootstrap/grafana_datasource_pg.sql
=======================================
insert into data_source (org_id, version, type, name, access, url,
password, "user", database, basic_auth, is_default, json_data, created, updated
) values (
1, 0, 'postgres', 'pg-metrics', 'proxy', 'localhost:5432',
'pgwatch2admin', 'pgwatch2', 'pgwatch2_metrics', 'f', 't', '{"postgresVersion":1000,"sslmode":"disable","timescaledb":false}', now(), now()
);
=========================================
Q 2.1 I see we are not using the pgwatch2 configuration database to store metrics but using a separate database 'pgwatch2_metrics' --  is it for performance reasons? 
Q 2.2  And, if we use PostgreSQL/pgwatch2_metrics for our metric data store, do we still get the same monitoring functionalities/timeseries views as we can get using the influxdb?
Q 2.3 And, I am assuming we can run the "pgwatch2/bootstrap/set_up_grafana_dashboards_pg.sh" script to create the dashboards -- right?

I really appreciate your time and help in clearing out my doubts and clarifying me.

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Q1: yes, smaller customization needed in many places with custom setups
Q2.1 - not really for performance (still the same instance) but for logical separation / manageability
Q2.2 - yes, and even more as more complex dashboards as possible with Postgres metrcis storage
Q2.3 - yes this should work also if you're in correct path but also there's a 2nd dashboards rollout script [here](https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/import_all.sh)

**Comment by kmoppel** [comment]
Btw if you're only setting up one Grafana instance then the most convenient ways is add the data sources manually:
![Screenshot from 2020-03-04 10-47-16](https://user-images.githubusercontent.com/346788/75862076-0206bf00-5e07-11ea-98de-5913fa141310.png)
![Screenshot from 2020-03-04 10-47-43](https://user-images.githubusercontent.com/346788/75862116-134fcb80-5e07-11ea-9c3a-4a55f3eb2d86.png)
