### ISSUE TITLE
Installation of pgwatch2 non-docker Web UI - Step 4

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#259]
Hi,

Q 1. 
     Are we  supposed to run the command to start web UI  in background?  
     Do we run  #python3 web.py     or, do we run run it in background as shown below:
     # python3 web.py &
  The reason I am asking is, when I run # python3 web.py   it never returns to the shell giving me 
   back the command prompt .  So I wonder if we are supposed to run it in background?

 Q 2. 
    After completing step 4, we started the Web UI and wanted to see if we can access the URL 
    successfully and if we can access the logs and if there are any errors. 
    The result is:
    We are able to access the URL (attached screenshot - WEB_UI_Screenshot.doc).
    But, we are finding these messages (shown below)  in the grafana log:
    Why are we getting the eror msg="Failed to send usage stats"  ?
============================================
t=2020-02-24T10:28:19-0600 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/5/query status=400 remote_addr=192.168.40.110 time_ms=2 size=106 referer="http://192.168.40.144:3000/d/5fda0a377/postgres-version-overview?orgId=1"
t=2020-02-24T11:56:16-0600 lvl=eror msg="Failed to send usage stats" logger=metrics err="Post https://stats.grafana.org/grafana-usage-report: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
============================================

**Comment by bikramma** [comment]
Sorry, forgot to add the screenshot (WEB_UI_Screenshot.doc) earlier. Attaching it now.
[WEB_UI_Screenshot.docx](https://github.com/cybertec-postgresql/pgwatch2/files/4247093/WEB_UI_Screenshot.docx)

**Comment by kmoppel** [comment]
Q 1. Are we supposed to run the command to start web UI in background?
A: There is no best practice from my side, it should work either way but normally yes a background process is wanted.
Q2: Why are we getting the eror msg="Failed to send usage stats" ?
A: InfluxDB by default "phones home" for statistics gathering. You can disable it in the config file
