### ISSUE TITLE
Bad datatype in m_pg_version_from

### ISSUE THREAD

**Issue by slardiere** [cybertec-postgresql/pgwatch2#26]
In the table `metric`, the field `m_pg_version_from` use `float` datatype, which is wrong, because it could approximate 9.6 to 9.59999999
Please use `numeric` for this

**Comment by kmoppel** [comment]
Yes, you're right..technically this could happen. When first building pgwatch2 I though checked that it would be fine with all recent versions - the thing was that Go sadly doesn't support Numeric...so one needs a library for that. But to be safe for future I've implemented it now. No need to patch the working setups though. Thanks for the input @slardiere !
