### ISSUE TITLE
Installation of pgwatch2 - non-docker

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#260]
Hi Team,

We are trying to understand this following note in the installation of Go - step 5:
=========================================================
NB! There are pre-built binaries DEB / RPM / Tar packages also avaialble on the "releases" tab so this step is not really mandatory if maximum control or code changes are not required.
=========================================================

We are installing pgwatch2 non-docker on Linux/CentOS. 
In the "releases"  I find the following RPM/Tar for Linux/CentOS:
pgwatch2_v1.7.0-SNAPSHOT-91e1d21_linux_64-bit.rpm
pgwatch2_v1.7.0-SNAPSHOT-91e1d21_linux_64-bit.tar.gz

Q1. What files are required to be extracted from the above RPM/Tar to install Go and compile and run the pgwatch2 ?

In the "releases"  you have also provided the source codes zip/tar  (pgwatch2-1.7.0.zip &  pgwatch2-1.7.0.tar).  How can we use any of these to extract the required files to install Go and compile and run the pgwatch2 ?
 
I know these questions may appear very dumb to you -- but if you can please clarify I will appreciate very much.

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Hi Bikram,
when you install from a pre-built package then you don't really need to compile anything anymore unless you want to change some behaviour - all should be included.
```
rpm -qlp pgwatch2_v1.7.0-SNAPSHOT-91e1d21_linux_64-bit.rpm | grep bin
/usr/bin/pgwatch2-daemon
```

**Comment by bikramma** [comment]
Thanks a lot Kaarel.
