### ISSUE TITLE
Not getting the logs in pgwatch2 web  UI 

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#261]
Hi Team,

We have installed/configured pgwatch2 non-docker with the following component versions:
OS – CentOS 7 ; PostgreSQL-10.11; Influxdb – 1.7.10; Grafana – 6.6.1; python3;
But, we are encountering these two issues:
 1.	Logs are not showing for Web UI, postgres,  influxdb, pgwatch2  
        (screenshot doc attached - ISSUES_IN_UI_&_DASHBOARDS.docx)
  2.	The Biggest relations treemap shows no relations: 

 Screenshots showing these issues are enclosed in the attached -   
 ISSUES_IN_UI_&_DASHBOARDS.docx

[ISSUES_IN_UI_&_DASHBOARDS.docx](https://github.com/cybertec-postgresql/pgwatch2/files/4258098/ISSUES_IN_UI_._DASHBOARDS.docx)

Please help.

Thanks and regards,
Bikram

**Comment by kmoppel** [comment]
Hi,
Yes this is actually expected to happen but it was not mentioned in the Readme - I've added info on that now. In short:
1) Logs view is only configured to work with Docker and needs adjusting
2) One Grafana plugin is needed:  `grafana-cli plugins install savantly-heatmap-panel`
