### ISSUE TITLE
Clarifications on DB overview dashboard

### ISSUE THREAD

**Issue by bukem** [cybertec-postgresql/pgwatch2#262]
Dear pgwatch2 team,

I have a few questions on panels composition for DB overview dashboards and I would appreciate if you can give more details of the ideas that underpinned this:
1. why _shared buffers hit ratio and rollback ratio_ are on one panel? The relationship between these indicators does not seem obvious.
2. _Total sessions + Deadlocks + Temp bytes_ . I believe we can find correlation between the number of active sessions and deadlocks and between the number of active sessions and temp bytes, but the relation between them and total sessions number does not seem obvious.
3. _WAL rate + DB size_ . Here we can have any combination of small/big database, both with low or high WAL rate and it seems impracticable to make a meaningful conclusion from this. Well, expect that both refer to disk space :slightly_smiling_face:

I'm working on rewritting the dashboard to work on the Prometheus datasource and I think may be it make sense or rearrange to separate some of the panels.

Thank you!

Mike

**Comment by kmoppel** [comment]
Hi @bukem, yes you're right in that that the highlighted metrics are not really connected. The only reason why they're together is that we wanted for all most important information to fit even on a smaller screen like a laptop. But indeed some years have passed and screens have higher resolutions now so I think it would make sense to move some info to another row of panels. Thanks for the input!

**Comment by kmoppel** [comment]
I've now reorganized the Overview dash a bit by extending it with two new panels - temp_bytes now has it's own panel so it should be a bit more readable. (https://github.com/cybertec-postgresql/pgwatch2/commit/a134939c83fc6ce892cef92c85cfff81d6ee0f4a, https://github.com/cybertec-postgresql/pgwatch2/commit/5a99174fd569f861100dc464d4cf7690a253c9e4)
