### ISSUE TITLE
Upgrade pgwatch2 version from 1.5 to 1.7 on docker.

### ISSUE THREAD

**Issue by darshansh** [cybertec-postgresql/pgwatch2#263]
Hi Kaarel Moppel, 
I have installed pgwatch 1.5 version on docker. Which I used to monitor my postgresql production server. I have also prepared some custom metrics on pgwatch2. Now I want to upgrade pgwatch2 with latest version 1.7. How can I do it without loosing my data and custom metrics in pgwatch2 ? 
while installing pgwatch2 I used below command which install all together pgwatch2, influxdb,postgresqldb and grafana. 
 
docker run -d -p 3000:3000 -p 8080:8080 --name pw2 cybertec/pgwatch2:1.5.1

**Comment by kmoppel** [comment]
Hi,
Ok with this simple launch version it's a bit more work - the readme suggest usage of volumes for production usage actually.
But in short I'd recommend to start from [here](https://github.com/cybertec-postgresql/pgwatch2#updating-to-a-newer-docker-version). Basically you need to take backups of the 1) InfluxDB metric DB 2) Postgres pgwatch2 config DB 3) Postgres Grafana DB...and re-play them into a new image. It should be sufficiently documented but let me know if something is missing.
