### ISSUE TITLE
WebUI documentation incomplete (non docker installation)

### ISSUE THREAD

**Issue by Madd-Scientist** [cybertec-postgresql/pgwatch2#264]
A few parameters are left unexplained in the documentation. 
While using the Web UI, I encounter the following error (screenshot attached)

![Screenshot from 2020-03-12 16-09-07](https://user-images.githubusercontent.com/19285349/76513230-fc9b1b80-647b-11ea-905c-b05bfc162ad4.png)

Please provide instruction so as how to configure custom metrics. 

Also, does the database server which is being remotely monitored using pgwatch2 need to have a user named pgwatch2, or just creating a local user enough?

**Comment by kmoppel** [comment]
Ok, made the message a bit more descriptive now - "Preset OR custom config needs to be specified, i.e. only one of these fields must be filled!".
So you need to choose between a preset config from the dropdown or enter your own, but you need to clear the preset selection then.

**Comment by Madd-Scientist** [comment]
The drop down menu isn't showing any options.

**Comment by kmoppel** [comment]
@Madd-Scientist I think then you missed some setup steps - check if pgwatch2.preset_config table has the info.

**Comment by Madd-Scientist** [comment]
I rechecked each and every step of the installation, and followed each one of them as mentioned in the documentation. The preset-config table (in the metrics directory) has the info.

**Comment by kmoppel** [comment]
@Madd-Scientist maybe some GRANT issue? Does the Web UI log say anything?
As hard as I tried I cannot make it not work...should look like the image below and one can only fill the left or the right box, but not both.
![webui_preset](https://user-images.githubusercontent.com/346788/76944608-fd173480-6909-11ea-9861-3338a75e797f.png)

**Comment by kmoppel** [comment]
And about that question - well having the monitoring user called pgwatch2 makes it a lot easier...as the helper functions are granted to this user. But with some 'sed' magic on helper rollout there's no real difference.
> Also, does the database server which is being remotely monitored using pgwatch2 need to have a user named pgwatch2, or just creating a local user enough?

**Comment by Madd-Scientist** [comment]
I wiped my hard drive clean and installed Ubuntu again, and just followed the documentation for pgwatch2. I'm still facing the same problem. All the logs show a blank page. There is no issue with GRANT permissions, postgres is on the correct port. 
Also, on top of the page, these errors pop up: (screenshot attached)
All the postgres, influx, and grafana configurations have been edited as mentioned in the documentation.

![pgwatch2_screenshot2](https://user-images.githubusercontent.com/19285349/77165952-55506100-6ad9-11ea-88aa-4a976f660e59.png)

**Comment by kmoppel** [comment]
@Madd-Scientist ok, yes now I understand the problem - the UI can't connect to the DB at all, you probably have some pg_hba.conf restrictions or such...you need to maybe change the config / metric DB connect strings accordingly. Added a hint to the README also under chapter 4.1. Start the Web UI.
