### ISSUE TITLE
How to add Standby DB in pgwatch2

### ISSUE THREAD

**Issue by Delphsa** [cybertec-postgresql/pgwatch2#265]
Hello,
I'm trying to add the standby DB to pgwatch2 but can't because of the field "md_unique_name" is a primary key. 
Indeed, the standby DB has the same name as the primary DB. If it specifies another name for the "md_unique_name" field, I get errors in pgwatch for metrics collection. Exemple : 

ERRO MetricGathererLoop: Failed to fetch metric data for [***:wal_receiver]: pq: function pg_last_wal_receive_lsn() does not exist
ERRO MetricGathererLoop: Total failed fetches for [***:wal_receiver]: 2090
ERRO MetricGathererLoop: Failed to fetch metric data for [***:wal_receiver]: pq: function pg_last_wal_receive_lsn() does not exist

Could you help me with this problem ?

Many thanks.
Delphine.

**Comment by kmoppel** [comment]
Hi, yes you need to give a new name for each instance...but to distinguish "clusters" in queries / Grafana one can use custom tags or the wal.sys_id column.

But for me - I don't get errors on the standby...what version of pgwatch2 are you using? If some older version then I'd recommend to at least [refresh](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/sql/config_store/refresh_metrics_from_github.sh) the metric definitions, better also the binaries.

> 2020/03/20 12:18:49 INFO FetchMetrics: [replica:wal_receiver] fetched 1 rows in 0.8 ms

**Comment by Delphsa** [comment]
Hello,

Many thanks for your answer. 
I updated my version of pgwatch2 to the last version and now it's working. 

Thanks!
Delphine.
