### ISSUE TITLE
(non-docker) pgwatch2 forcing its own retention policy

### ISSUE THREAD

**Issue by thibmac** [cybertec-postgresql/pgwatch2#266]
Hello!

I am discussing this behavior committed [here](https://github.com/cybertec-postgresql/pgwatch2/commit/befb403e2da00ac72c214f9ca86028121fa817fc#diff-b527939e9061d8171dffe1544884555b), and released in 1.7.1.

If I understand correctly, when starting, the daemon checks wether the retention policy for the influx pgwatch2 database matches $PW2_IRETENTIONDAYS or not.
If it doesnt, it forces the modification of the retention policies in InfluxDB, which requires admin rights on the InfluxDB instance. Since i didn't grant admin rights to influx's pgwatch2 user, the query fails and the daemon doesn't start anymore.

Is there any option I am missing to avoid this? My pgwatch2 database is hosted of an Influxdb instance regrouping multiple databases, and I dont want the pgwatch2 daemon to have admin access to my Influx instance. I don't necessarily need to change the default retention policy of my database either.

Thanks ! 

Regards.

**Comment by kmoppel** [comment]
Hey, I think you're right - not everyone wants admin rights on Influx. So now it's just an error. And if you don't want that error or no adjustments from pgwatch2 side then this can be now signalled with setting --iretentiondays to 0.

**Comment by Skoffer** [comment]
What if I want to change the default $PW2_IRETENTIONDAYS on a running container? 

How can I do this? thanks

**Comment by kmoppel** [comment]
@Skoffer Yes sure you can rebuild the gatherer if you first install Go and then run the build_gatherer.sh script. But if you use volumes it's easier just to re-launch a new container with the newest version.
