### ISSUE TITLE
missing stat_activity_realtime and show_plans_realtime

### ISSUE THREAD

**Issue by aliciahogue** [cybertec-postgresql/pgwatch2#268]
Grafana says the relations do not exist.  I am running latest docker image on pg11.  Did I miss something?

**Comment by kmoppel** [comment]
Hi, yes it needs extra configuration - default presets (exhaustive, full, ...) don't include these metrics as they have some "cost" and for realtime plans also need the pg_show_plans extension to be present on the monitored server.
