### ISSUE TITLE
Support AWS RDS PostgreSQL database monitoring. provide alternative of 'cpu_load_plpythonu.sql'

### ISSUE THREAD

**Issue by rvsoni** [cybertec-postgresql/pgwatch2#27]
Support AWS RDS PostgreSQL database monitoring,

AWS RDS PostgreSQL database does not support plpython programming. 

Need alternative of 'cpu_load_plpythonu.sql' in RDS Postgresql supported language to deploy pgWatch2 to monitor RDS Postgresql databases. 

RDS PostgreSQL support following language extension: Perl, pgSQL, Tcl, and JavaScript (via the V8 JavaScript engine) Ref. https://aws.amazon.com/rds/postgresql/

pgWatch2 is amazing tool and looking forward to deploy it on AWS RDS postgresql database monitring. 

Thanks,
Ravi

**Comment by kmoppel** [comment]
Hi @rvsoni!
Yes, sadly no support for that on AWS...but one can actually access same metrics from CloudWatch - it's already supported in Grafana (see http://docs.grafana.org/features/datasources/cloudwatch/) and one can mix different datasources on one panel.
But yes no pre-defined AWS-ready dashboard so will keep the ticket opened and I'll see when I get to it. A pull request would be very welcome also :) Cheers

**Comment by kmoppel** [comment]
@rvsoni Hi, now there's a sample dashboard for the RDS CloudWatch API. See release notes here - https://github.com/cybertec-postgresql/pgwatch2/blob/master/CHANGELOG.md#v130-2018-01-26
