### ISSUE TITLE
seems like RetentionPeriod not set, only to default

### ISSUE THREAD

**Issue by TiJof** [cybertec-postgresql/pgwatch2#270]
Hi,
Here is my context : external InfluxDB, docker (and external grafana, not relevent here)
I have a write-only user for my InfluxDB, so it can't run any SHOW command, so pgwatch2 crash saying : 

> 2020/04/22 15:30:48 ERRO InitAndTestInfluxConnection: Could not check Influx retention policies: error authorizing query: telegraf not authorized to execute statement 'SHOW RETENTION POLICIES ON telegraf', requires READ on telegraf
> 2020/04/22 15:30:48 CRIT main: Could not initialize InfluxDB error authorizing query: telegraf not authorized to execute statement 'SHOW RETENTION POLICIES ON telegraf', requires READ on telegraf

In pgwatch2.go - line 2883, there is a test `RetentionPeriod > 0`
I think PW2_IRETENTIONDAYS=0 (docker env variable) should work for my case, but RetentionPeriod seem to be set to default in line 3796 : `retentionPeriod := InfluxDefaultRetentionPolicyDuration`. No way to find where opts.RetentionPeriod is set ...

So, is PW2_IRETENTIONDAYS=0 the right thing to do in order to have pgwatch2 working with a write-only user in InfluxDB ? And if this is the way, is RetentionPeriod worrectly set ?

Thank you !

**Comment by kmoppel** [comment]
Hi, you're sadly correct. RETENTIONDAYS=0 was in the end not respected due to the oversight on line 2883. Thanks a lot for the investigation! Will try to release a new minor version also on the next days.

**Comment by kmoppel** [comment]
@TiJof FYI - now there are also new Docker images including this fix - tag 1.7.2.

**Comment by TiJof** [comment]
It's working nicely now !
Thank you
