### ISSUE TITLE
pg_qualstats 1.0.9 vs 2.0.2

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#276]
Hi,
just to tell you that in pg_qualstats 2.0.2 , views
 public | pg_qualstats_indexes     | view | postgres
 public | pg_qualstats_indexes_ddl | view | postgres

does not exist any more.

**Comment by kmoppel** [comment]
Thanks for the heads up! A quite bad API change....
But anyways, I've now added support for such class of cases. Currently though pgwatch2 doesn't know anything about extension versions, only PG versions, so one needs to replace the query text in a bit hacky way and define some new "private" metrics. But there should not be many and currently the one called "reco_add_index_ext_qualstats_2.0" is the only one.
