### ISSUE TITLE
AES GCM keyphrase question

### ISSUE THREAD

**Issue by dvanhollen** [cybertec-postgresql/pgwatch2#278]
The docs and pgwatch2 --help explains that if I want to encrypt connection passwords, I need to pass in a value to "aes-gcm-keyphrase" or "ae-gcm-keyphrase-file". But I'm not totally sure what that is. Is that like a self-signed cert file? Do you have an example of how to generate what pgwatch2 needs for this functionality?

**Comment by kmoppel** [comment]
Actually the "keyphrase", fed directly or via a file (theoretically safer if file deleted later), can be any random string so no special magic there. The important part - if you also use the Web UI it needs to match with the gatherer. And if using the YAML mode and wanting to use some configuration management system then one can generate such encrypted passwords with the help of the "--aes-gcm-password-to-encrypt" flag of the gatherer.
