### ISSUE TITLE
psutil_cpu function

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#284]
Hello, 
i do not understand why i have to create function psutil_cpu, it is not created when auto-create helpers is enable ?
thx

**Comment by kmoppel** [comment]
Hi,
seems to work for me :) Are there some errors? Maybe an issue of Python 2 vs Python 3 with latter assumed default now as v2 is deprecated.
--
2020/08/03 16:28:16 INFO main: Connect OK. [test] is on version 12.3 (in recovery: false)
2020/08/03 16:28:16 INFO main: Trying to create helper functions if missing for "test"...
2020/08/03 16:28:16 INFO ReadMetricsFromFolder: Searching for metrics from path metrics/00_helpers ...
2020/08/03 16:28:16 INFO TryCreateMetricsFetchingHelpers: Successfully created metric fetching helper for test get_psutil_cpu
2020/08/03 16:28:16 INFO TryCreateMetricsFetchingHelpers: Successfully created metric fetching helper for test get_stat_statements
2020/08/03 16:28:16 INFO TryCreateMetricsFetchingHelpers: Skipping get_load_average_windows rollout. Windows helpers need to be rolled out manually
2020/08/03 16:28:16 INFO TryCreateMetricsFetchingHelpers: Successfully created metric fetching helper for test get_psutil_disk

**Comment by pmpetit** [comment]
Hello,
i created nothing manually, i just set pgwatch2 as superuser
here are the errors :
2020/08/14 08:40:10 ERRO MetricGathererLoop: Failed to fetch metric data for [pgwatch-db_metricsdb:cpu_load]: pq: function get_load_average() does not exist
2020/08/14 08:40:10 ERRO MetricGathererLoop: Total failed fetches for [pgwatch-db_metricsdb:cpu_load]: 12
2020/08/14 08:41:10 ERRO MetricGathererLoop: Failed to fetch metric data for [pgwatch-db_metricsdb:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2020/08/14 08:41:10 ERRO MetricGathererLoop: Total failed fetches for [pgwatch-db_metricsdb:psutil_cpu]: 7
2020/08/14 08:41:10 ERRO MetricGathererLoop: Failed to fetch metric data for [pgwatch-db_metricsdb:psutil_disk]: pq: function get_psutil_disk() does not exist
2020/08/14 08:41:10 ERRO MetricGathererLoop: Total failed fetches for [pgwatch-db_metricsdb:psutil_disk]: 7

**Comment by kmoppel** [comment]
@pmpetit Hmm. Then I'd try installing some helper manually and see what is the error. For example get_load_average - https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/00_helpers/get_load_average/9.1/metric.sql

**Comment by pmpetit** [comment]
for your information, i only use .yaml files to configure monitored targets : 
so in pgsql db logs i can see that when pgwatch2 starts, it try to connect to db pgwatch2 that did not exists.

So i create the db pgwatch2.

i restart the pod pgwatch2 and then i can see that the 3 missing fn are created in the schema pgwatch2, db metrics-db

**Comment by pmpetit** [comment]
so now it is ok, i did have to create them manually

**Comment by kmoppel** [comment]
Might be some configuration issue then also somewhere. Helpers normally should not be created in the metrics-db...unless you of course specifically want to monitor it and have added a YAML entry for that. But closing for now.
