### ISSUE TITLE
Want to add one metric to collect locking/blocking  details. 

### ISSUE THREAD

**Issue by darshansh** [cybertec-postgresql/pgwatch2#285]
Hello, 
I have installed phwatch2  on docker to monitor postgresql database. I would like to captures blocked and blocking statements and other details. I have added new metric with below query but can not get data on dashboard in Table formate same as Statement top. I prepared this query based on stat_statements metric. Can any one please help me in this ? 
SELECT  (extract(epoch from now()) * 1e9)::int8 as epoch_ns,blocked_locks.pid ::int8     AS blocked_pid,
         blocked_activity.usename::text  AS blocked_user,
         blocking_locks.pid::int8     AS blocking_pid,
         blocking_activity.usename::text AS blocking_user,
         blocked_activity.query::varchar(16000)  AS blocked_statement,
		 blocking_activity.query::varchar(16000)  AS current_statement_in_blocking_process,
         blocked_activity.application_name::text AS blocked_application,
         blocking_activity.application_name::text AS blocking_application,
		 blocked_locks.mode::text as blocked_lockmode,
		 blocking_locks.mode::text as blocking_lockmode
   FROM  pg_catalog.pg_locks         blocked_locks
    JOIN pg_catalog.pg_stat_activity blocked_activity  ON blocked_activity.pid = blocked_locks.pid
    JOIN pg_catalog.pg_locks         blocking_locks 
        ON blocking_locks.locktype = blocked_locks.locktype
        AND blocking_locks.DATABASE IS NOT DISTINCT FROM blocked_locks.DATABASE
        AND blocking_locks.relation IS NOT DISTINCT FROM blocked_locks.relation
        AND blocking_locks.page IS NOT DISTINCT FROM blocked_locks.page
        AND blocking_locks.tuple IS NOT DISTINCT FROM blocked_locks.tuple
        AND blocking_locks.virtualxid IS NOT DISTINCT FROM blocked_locks.virtualxid
        AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid
        AND blocking_locks.classid IS NOT DISTINCT FROM blocked_locks.classid
        AND blocking_locks.objid IS NOT DISTINCT FROM blocked_locks.objid
        AND blocking_locks.objsubid IS NOT DISTINCT FROM blocked_locks.objsubid
        AND blocking_locks.pid != blocked_locks.pid
 
    JOIN pg_catalog.pg_stat_activity blocking_activity ON blocking_activity.pid = blocking_locks.pid
   WHERE NOT blocked_locks.GRANTED;

**Comment by kmoppel** [comment]
Hi, the query seems to run through...so I assume if there's some locking going on you'd get the data. Or is nothing reaching the metric store if to leave aside Grafana?

**Comment by darshansh** [comment]
Thanks Kmoppel, 
I got the output now.  In Visualization tab as shown in image, I selected Time series to column and  now I can see the output. 

![image](https://user-images.githubusercontent.com/14271741/89255552-a3f13880-d63f-11ea-94d3-3ba3a8d90243.png)
![image](https://user-images.githubusercontent.com/14271741/89255644-dd29a880-d63f-11ea-8bee-e66ef48dd02e.png)
