### ISSUE TITLE
Add more data to queries for debugging

### ISSUE THREAD

**Issue by Sascha8a** [cybertec-postgresql/pgwatch2#286]
Greetings,

I had an incident recently and needed to look at pg_stat_bgwriter column checkpoint_write_time & checkpoint_sync_time. I wished I had the statistics for those of the last few days, however, these columns where no saved in the database.

Instead of 

```sql
select
   (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
   checkpoints_timed,
   checkpoints_req,
   buffers_checkpoint,
   buffers_clean,
   maxwritten_clean,
   buffers_backend,
   buffers_alloc
 from
   pg_stat_bgwriter;
```
change most of the queries to 

```sql
select
   (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
   *
 from
   pg_stat_bgwriter;
``

**Comment by kmoppel** [comment]
Yes, these two fields actually would be useful I think, no idea why they were initially left out...but in general I'm not fond of the wildcard idea, some fields are not so useful generally also I think explicit is better than implicit. Also one can immediately see the the differences between metrics different Postgres versions are exposing.

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.
