### ISSUE TITLE
template1 can't be set as default db in some cases

### ISSUE THREAD

**Issue by RachadAbiChahine** [cybertec-postgresql/pgwatch2#289]
some cloud providers like Aiven (https://aiven.io/) don't give us the rights to connect to template1

`        if params['md_dbtype'] == 'postgres':
            # get all active non-template DBs from the entered host

            active_dbs_on_host, err = datadb.executeOnRemoteHost(sql_active_dbs, host=params['md_hostname'], port=params['md_port'],

                                                                 dbname='template1', user=params['md_user'], password=password_plain,
                                                                 sslmode=params['md_sslmode'])`
in the code template1 is used as defaultdb when we want to insert a new cluster,

so  I'am getting an error 
`ERROR: FATAL: pg_hba.conf rejects connection for host "XX.XX.XX.XX", user "UUUUUUUUU", database "template1", SSL on`

**Comment by kmoppel** [comment]
Oh, I see. Wasn't aware of that. In some cases also the default "postgres" DB is dropped / revoked...so I guess we need to check both of them.

**Comment by kmoppel** [comment]
@RachadAbiChahine Oh that's interesting on Aiven's part...but anyways, I've now just added this "defaultdb" next to "postgres" and "template1" in the code. There are already too many parameters and would like to avoid adding some more, especially as this is the first such report.
