### ISSUE TITLE
Auto-create helpers

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#290]
Hello
how do you set "Auto-create helpers" to true when using an instance.yaml file 
thank

**Comment by kmoppel** [comment]
Yes a very good question indeed - that attribute was originally a bit badly named so it's called "is_superuser" actually:
https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/config/instances.yaml#L11
