### ISSUE TITLE
cleanup job

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#291]
Hello, 
could you please tell me when is executed the "delete or drop partitions" of data older than PW2_PG_RETENTION_DAYS ?
Thanks

**Comment by kmoppel** [comment]
Hi,
Seems it's running currently just 2x per day, relative to at what time the collector was started:
https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/pgwatch2.go#L1072

**Comment by kmoppel** [comment]
But note that data is only dropped when the whole old partition is out of retention bounds...so usually it's more like 3 weeks of data instead of 2 weeks.
