### ISSUE TITLE
for info: "delete all metrics"

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#292]
Hello,
here is my conf:
i do not use the db monitored_db, to store dbs. i use yaml files instead, located in pgwatch2 folder.

i remove 1 .yaml file, because it is not more needed, then i go to the pgwatch2 app to delete data from this db. I thought i could use "delete all metrics for all non-active dbs" button, thinking that db with .yaml file are considered as active.

You should not !

it deletes all metrics from all dbs.

(i think it only use db's from monitored dbs, it does not take care of yaml description files)

**Comment by kmoppel** [comment]
Hi, yes indeed YAML has no knowledge of Config DB based setups and vice versa...thus it's dangerous to mix these setups. Will add a note to the documentation about that
