### ISSUE TITLE
Wrong unit of measurement on the Biggest relations treemap

### ISSUE THREAD

**Issue by afroede** [cybertec-postgresql/pgwatch2#293]
Hi,
For a table with a size of several gigabytes, B is displayed in the mouseover instead of GB. Everything is okay for  MB sizes.

![pgwatch2](https://user-images.githubusercontent.com/69967616/90763534-2851e580-e2e7-11ea-9f93-0cf0aec2884f.png)

**Comment by kmoppel** [comment]
Hi, thank for letting know. Yes, it's a known issue - the plugin actually only shows size in bytes. So in your case its 222 Billion bytes equals around 200GB.
Leaving the ticket open though to see if maybe there's some better plugin around...

**Comment by kmoppel** [comment]
This looks promising - https://grafana.com/grafana/plugins/marcusolsson-treemap-panel
Will try to test...

**Comment by pashagolub** [comment]
📅  I'm closing this outdated issue. 

♻️  If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.
