### ISSUE TITLE
pq: relation "psutil_disk" does not exist

### ISSUE THREAD

**Issue by denis-argentin** [cybertec-postgresql/pgwatch2#296]
Please help!

Installations without docker.

Previous deploy on a test environment i've had no problem with that.
So i put on production and these tables were not created.

**Comment by kmoppel** [comment]
Very little information here to work with...are the any errors? Are you using the same configs? Is PL/Python installed and you have rolled out the helpers manually to production or set the "auto rollout" flag?

**Comment by kmoppel** [comment]
This might help: https://pgwatch2.readthedocs.io/en/latest/preparing_databases.html#rolling-out-helper-functions

**Comment by denis-argentin** [comment]
So sorry I thought was good enough information,
This error "_pq: relation "psutil_disk" does not exist_" show up on grafana dashboard.
![image](https://user-images.githubusercontent.com/68968323/91846878-adff5a80-ec30-11ea-9724-7ccbc020db76.png)

Looking for this table on pgwatch2_metrics db (production server), it does not exist. 
in some point it was not created. See image below
![image](https://user-images.githubusercontent.com/68968323/91848824-6fb66b00-ec31-11ea-8433-23662c59cd65.png)


The below image is from the test server. You can see the table is there
![image](https://user-images.githubusercontent.com/68968323/91848485-19492c80-ec31-11ea-9d4a-932b0f3b0cb7.png)

**Comment by denis-argentin** [comment]
I believe that the ultimate question is: Who creates the "psutil_* " tables on the db store metrics, the pgwatch2_metrics DB?

**Comment by kmoppel** [comment]
Yes, the pictures confirm that there are no metrics for "psutil_disk" (and other psutil based metrics). Common reasons why they're not there:

  1. Not enabled in monitoring config - the "full" preset includes them for example
  1. Helpers are not rolled out on the monitored DB. This can be also done automatically when using a superuser monitoring user and ticking the "auto create" checkbox in the Web UI or setting the "is_superuser" attribute in YAML config. The manual way is to roll out wanted functions from /etc/pgwatch2/metrics/00_helper folder.
  1. PL/Python not installed

**Comment by denis-argentin** [comment]
oh my gosh, I've spent so many days on it, but I've never tried the full preset, because I intent not to use in the production. thats why.
it worked
thanks very mutch for your help
