### ISSUE TITLE
Possible bug in InfluxDB Test connection

### ISSUE THREAD

**Issue by sasadangelo** [cybertec-postgresql/pgwatch2#297]
Hi,

I am working on a solution based on pgwatch2 and I found a strange behavior. Looking at the code I noticed that there is a function InitAndTestInfluxConnection when we try 3 times to connect to the InfluxDB.
Here the piece of code:
https://github.com/cybertec-postgresql/pgwatch2/blob/9f03caa81835c6d550d968719f63fa3e7ffeb199/pgwatch2/pgwatch2.go#L3480-L3492

I am not a Go expert but something is not clear to me. This line of code that effectively runs SHOW DATABASES to test the connection:
res, err := queryDB(c, "SHOW DATABASES")

is outside of the loop. If my consideration is correct the code does the test once and if it fails the test is considered failed.
Am I correct? If no, please explain.

**Comment by kmoppel** [comment]
Well spotted! Re-try never worked seems...thanks a lot @sasadangelo!

**Comment by sasadangelo** [comment]
yw
