### ISSUE TITLE
Dashboard based on Graphite metrics

### ISSUE THREAD

**Issue by helenazarr** [cybertec-postgresql/pgwatch2#301]
Hi!
Is it possible to use text values from metric SQL as part of metric name in Graphite? For example, there is pre-defined metric called "table_stats" which returns 

table_name, total_relation_size_b
table1, 100
table2, 200

I need to create "The biggest tables" dashboard in Grafana using Graphite as a source. To do this I need to query metrics like following:
pgwatch2.table_stats.db_name.table_name.total_relation_size_b
pgwatch2.table_stats.db1.table1.total_relation_size_b
pgwatch2.table_stats.db1.table2.total_relation_size_b.

Now I have:
pgwatch2.table_stats.db_name.total_relation_size_b.

How I should do this? Are there any other ways to build TopN tables dashboard based on Graphite?

**Comment by kmoppel** [comment]
Hi @helenazarr - a good question...I've only implemented the most basic things for Graphite...but seems it could be possible via the "maxSeries" function: https://stackoverflow.com/questions/44653687/graphite-max-of-a-series-with-wildcards
Feel free to create a PR if you manage to set up some nice Graphite dashboards that you'd be willing to share.
