### ISSUE TITLE
Duplicate variable value in the warning output

### ISSUE THREAD

**Issue by eshkinkot** [cybertec-postgresql/pgwatch2#305]
https://github.com/cybertec-postgresql/pgwatch2/blob/1c2cd21a868a99eaa98782dc05499b61ec4be15b/pgwatch2/pgwatch2.go#L1582

Perhaps this `t` here meant the name of the type, and not the value of the variable?
Because now this output looks like this:
```
 WARN SendToGraphite: Invalid type for column: tag_lockmode value: AccessShareLock type: AccessShareLock
 WARN SendToGraphite: Invalid type for column: tag_lockmode value: ExclusiveLock type: ExclusiveLock
 WARN SendToGraphite: Invalid type for column: tag_lockmode value: RowShareLock type: RowShareLock
```
that is, it just repeats the value of the variable twice

**Comment by kmoppel** [comment]
Thanks, merged the PR. Will also add make it INFO level instead of WARN  as with default metrics which are not optimized for Graphite (Graphite can't store text) you get a lot of these
