### ISSUE TITLE
pgwatch2 - canceling statement due to statement timeout

### ISSUE THREAD

**Issue by darshansh** [cybertec-postgresql/pgwatch2#307]
Hello Kmoppel,
I have pgwatch2 version 1.5.1 and currently I'm getting error in one metric like below. I see that this query takes 5 sec. to execute using pgadmin.
Failed to fetch metric data for [dbname_metricname]: pq: canceling statement due to statement timeout
On Postgresql server statement_timeout =0.

**Comment by kmoppel** [comment]
Hi, yes seems indeed that the pgwatch2 default query timeout of 5s kicks in...assuming you're using the Docker image it can be changed on the Web UI "dbs" page:
![Screenshot from 2020-09-30 16-57-32](https://user-images.githubusercontent.com/346788/94695236-5bec4a80-033e-11eb-915b-af550a24bf30.png)

**Comment by darshansh** [comment]
Aha thanks Kmoppel.  I tried to search this option in custom metrics. Didn't look at database level.
