### ISSUE TITLE
Kubernetes install - Could not connect to InfluxDB

### ISSUE THREAD

**Issue by Martin-Hogge** [cybertec-postgresql/pgwatch2#308]
Hello,

I have followed the instruction at https://pgwatch2.readthedocs.io/en/latest/kubernetes.html to install pgwatch2 on a kubernetes cluster. I created my first database definition with "Auto-create helpers" enabled but when I try to get metrics I always got the error message:

> ERROR - Could not connect to InfluxDB

![image](https://user-images.githubusercontent.com/9304680/94913234-30d23a00-04a9-11eb-9f6c-f07be7c024b2.png)

The last logs in pgwatch2 logs:

```
2020/10/02 10:12:21 ERRO MetricGathererLoop: Failed to fetch metric data for [adisoft_dev:cpu_load]: pq: function get_load_average() does not exist
2020/10/02 10:12:21 ERRO MetricGathererLoop: Total failed fetches for [adisoft_dev:cpu_load]: 64
2020/10/02 10:13:20 ERRO MetricGathererLoop: Failed to fetch metric data for [adisoft_dev:psutil_cpu]: pq: function get_psutil_cpu() does not exist
2020/10/02 10:13:20 ERRO MetricGathererLoop: Total failed fetches for [adisoft_dev:psutil_cpu]: 33
2020/10/02 10:13:20 ERRO MetricGathererLoop: Failed to fetch metric data for [adisoft_dev:psutil_disk]: pq: function get_psutil_disk() does not exist
2020/10/02 10:13:20 ERRO MetricGathererLoop: Total failed fetches for [adisoft_dev:psutil_disk]: 33
2020/10/02 10:15:20 ERRO MetricGathererLoop: Failed to fetch metric data for [adisoft_dev:psutil_mem]: pq: function get_psutil_mem() does not exist
2020/10/02 10:15:20 ERRO MetricGathererLoop: Total failed fetches for [adisoft_dev:psutil_mem]: 34
2020/10/02 10:17:20 ERRO MetricGathererLoop: Failed to fetch metric data for [adisoft_dev:psutil_disk_io_total]: pq: function get_psutil_disk_io_total() does not exist
2020/10/02 10:17:20 ERRO MetricGathererLoop: Total failed fetches for [adisoft_dev:psutil_disk_io_total]: 35
```

My postgresql database version is 9.6.18.

Any idea what's wrong in my config ?

Thank you.

**Comment by kmoppel** [comment]
Did you try with the latest image or everything at defaults? For me seems to work out of the box with the latest version...

**Comment by Martin-Hogge** [comment]
I tried with everything at default. I updated the deployment to use :latest image instead of 1.8.0 and I'm now having this error: 
![image](https://user-images.githubusercontent.com/9304680/95717981-11d46480-0c6e-11eb-970e-dfc100caabee.png)

Aslo the kubernetes cluster is running on GKE.

**Comment by kmoppel** [comment]
Hmm pretty weird...seems Postgres failed to start for some reason. Some more logs would do good here but I've seen such things happen on weak hardware where some [services](https://github.com/cybertec-postgresql/pgwatch2/blob/master/supervisord-postgres.conf) fail to start in time. Btw, using the "latest" tag is also not recommended for long term setups, it could contain anything basically.

**Comment by Martin-Hogge** [comment]
I fixed my issue by totally reinstalling pgwatch. The only thing that has changed is the latest commit I used to get chart values.
The first time I was on commit 796f73dd9bad9a98f9245c4bbd29a7c7553d69a9 and I'm now on latest commit (babb9eca3bd952a8aaeac803d46c5d04e670d815). Not sure if this was the reason why it first failed or if something went wrong inside the container but at least this is now working.

This is not related to this issue but now that I have the admin dashboard, do you know how I can get the beautiful grafana dashboards ?

Thank you for your help.
