### ISSUE TITLE
rename dasboard folder

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#310]
Hello
i tried to push, but i'm not granted..
is it possible to rename 
pgwatch2/grafana_dashboards/postgres/v6/stat_activity_realtime
to 
pgwatch2/grafana_dashboards/postgres/v6/stat-activity-realtime

in order to folder name to match the dashboard name, because i have some python process to update dashboards, and this one must be managed manually (due to its name folder<>dash name)
thanks

**Comment by kmoppel** [comment]
Sure, was just some oversight, looks nicer now.
