### ISSUE TITLE
Column "spill_bytes" does not exist

### ISSUE THREAD

**Issue by lbogdan** [cybertec-postgresql/pgwatch2#313]
First of all, I want to thank all maintainers and contributors for such an amazing tool!

On to my issue: I'm using `pgwatch2` with a 13.0 PostgreSQL server, and I see the following error in the `pgwatch2` log:

```
2020/10/29 14:57:10 ERRO MetricGathererLoop: Failed to fetch metric data for [db:replication]: pq: column "spill_bytes" does not exist
```

This most probably comes from https://github.com/cybertec-postgresql/pgwatch2/blob/d0ef8111a7d90a1d3ce4b26c75bda962a46fee12/pgwatch2/metrics/replication/13/metric_master.sql#L10-L16

which was introduced in [Metrics: support for upcoming PostgreSQL v13](https://github.com/cybertec-postgresql/pgwatch2/commit/dfac085630452eadd33676c36f6f9023396ab1ab).

Still, from what I can see in the PostgreSQL 13 [pg_stat_replication documentation](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-REPLICATION-VIEW), the view doesn't seem to have a `spill_bytes` column.

**Comment by kmoppel** [comment]
Indeed, seems that column did not make it into the final release after all :/ I added support based on the beta version. Is fixed in code now, but for your running setup you just need to delete the "13" version of that "replication" metric.
Thanks for the report and glad that you enjoy the tool otherwise! If you see anything else suspicious please open an issue again:)

**Comment by FireEmerald** [comment]
@kmoppel I don't really know how to `delete the "13" version of that "replication" metric` in a docker setup - but for now i disabled the `replication` from the preset config. I was looking for documentation of the **Config JSON** parameters and it's values but didn't find something. I mean what does for example this setting enable in detail: `"replication": 120`

``` json
{"wal": 60, "locks": 60, "db_size": 300, "archiver": 60, "backends": 60, "bgwriter": 60, "cpu_load": 60, "db_stats": 60, "settings": 7200, "wal_size": 300, "locks_mode": 60, "index_stats": 900, "sproc_stats": 180, "table_stats": 300, "wal_receiver": 120, "change_events": 300, "table_io_stats": 600, "stat_statements": 180, "replication_slots": 120, "stat_statements_calls": 60, "table_bloat_approx_summary_sql": 7200}
```

**Comment by kmoppel** [comment]
@FireEmerald The simplest way to delete is via the [Web UI](https://github.com/cybertec-postgresql/pgwatch2/blob/master/screenshots/web_ui_metrics_and_preset_configs.png), given you've exposed that port on the Docker container.
The other option would be via SQL: `DELETE FROM pgwatch2.metric WHERE m_name = 'replication' AND m_pg_version_from = 13;`

And `"replication": 120` enables execute / store of the SQL behind this name every 120 seconds.
