### ISSUE TITLE
Wrong jQuery version on /stats-summary page

### ISSUE THREAD

**Issue by lbogdan** [cybertec-postgresql/pgwatch2#314]
While fiddling with pgwatch2's web interface, I've noticed that on the `/stats-summary` page it's trying to load `/static/jquery-3.4.1.min.js`, which returns a 404:

![image](https://user-images.githubusercontent.com/2083930/97709070-6f680e00-1ac2-11eb-9d27-7f3e712e3472.png)

Looking at other pages, I see they're using `jquery-3.5.1.min.js`, so I'm guessing this is the issue.

**Comment by kmoppel** [comment]
Well spotted, thanks! This page is not really critical luckily - yet another way how to quickly verify that statistics are trickling in.
