### ISSUE TITLE
pgwatch2 is writing in Influx only two series. Custom installation.

### ISSUE THREAD

**Issue by kearalex** [cybertec-postgresql/pgwatch2#315]
I'm fairly new with pgwatch2 so I would like to ask for some help.
Currently I'm trying to get pgwatch2 to work with custom installation via YAML files.
I've been install pgwatch2 on the one of the nodes HA PostgreSQL cluster. 
My test environements: SLES15 SP2, Python 3.6.10, PostgreSQL 10.14, patroni 2.0.1, etcd 3.4.13.  And I have other server with Influx 1.8.2 and Grafana 7.1.5.
I've been running pgwatch2 but I've seen in Influx only 2 series:

`configured_dbs`
`kpi`

In the pgwatch2-daemon log I see next: [pgwatch2-daemon. log.txt](https://github.com/cybertec-postgresql/pgwatch2/files/5465300/pgwatch2-daemon.log.txt). Daemon read 60 metric definitions, but can't gather it from DB except for two.
My configuration file: [instances.yaml.txt](https://github.com/cybertec-postgresql/pgwatch2/files/5465313/instances.yaml.txt)

What I did wrong when installing the program. I can't see my mistake. Tell me, please.

**Comment by kmoppel** [comment]
Hi, seems all OK from the system and logs side - you're using the "minimal" preset config (`preset_metrics: minimal` in the YAML config) which only has 1 metric called "kpi". Most popular presets (I assume) are "exhaustive" and "standard", but advanced users or when monitoring zounds of DB-s, would want to use a custom selection of metrics  / intervals.

**Comment by kearalex** [comment]
Kaarel, thank you so much for the tip!
The documentation is not very detailed for the newbie. So I did not pay attention to this parameter in the configuration file.
Should you create an additional section in the documentation that at least briefly enumerates what the values of each of the configuration file parameters might be?
Or add comments to each parameter directly in the configuration file?

**Comment by kearalex** [comment]
Kaarel, sorry!
I found where wrote about metrics. This is ["Metric definitions"](https://pgwatch2.readthedocs.io/en/latest/metric_definitions.html)

**Comment by kmoppel** [comment]
Added some more comments to the sample YAML file also, so hopefully things are a bit better now..
