### ISSUE TITLE
ERRO main: could not start metric gathering for DB "x_pgbouncer" due to connection problem: pq: not allowed

### ISSUE THREAD

**Issue by Imoustak** [cybertec-postgresql/pgwatch2#317]
Hello, I am trying to monitor a `pgbouncer` instance and I get this error on pgwatch2 logs,
`ERRO main: could not start metric gathering for DB "X_pgbouncer" due to connection problem: pq: not allowed` 

I couldnt find anything related to this, could you kindly point me on how to solve this?

**Comment by Imoustak** [comment]
Solved the issue was that the user wasnt able to login to the pgbouncer console, need to specifically allow this in pgbouncer config

**Comment by kmoppel** [comment]
Yes the "admin_users" config parameter...
