### ISSUE TITLE
Pgbouncer add pools information

### ISSUE THREAD

**Issue by Imoustak** [cybertec-postgresql/pgwatch2#318]
Hello, I ve been using pgwatch2 for couple of days and it's really a handy tool! 

I have a postgres and and a pgbouncer in front that I have configured and currently monitoring. For `pgbouncer` I can see the metrics that I can typically get with the `show stats` command. I am interested also in the metrics that are shown with the `show pools` command where you can see info per db user and the pool_mode used. Would this be easy to achieve? Could you maybe add this metric or point me a bit on how to do this and maybe I can open a PR to add these extra metrics? 

Thanks for your time and the great tool!

**Comment by kmoppel** [comment]
Hi, good to hear!
And about the "show pools" command - sure, it would be doable. Just in general we try to gather summary data when possible to keep data amounts under control. But as an extra option, that is not activated by default, why not.
But if you want to give this PR a try I'd recommend to check the implementation of similar stuff for pgpool2 support. Those commits were done on Jul 7, 2020.

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.

**Comment by vitabaks** [comment]
`show pools` metrics are very lacking ...

**Comment by AndrewJackson2020** [comment]
> `show pools` metrics are very lacking ...

Agree would very much like this ability out of pgwatch.

**Comment by pashagolub** [comment]
PRs are more than welcome!
