### ISSUE TITLE
Some links are not working with Health-Check dashboard

### ISSUE THREAD

**Issue by rostamiani** [cybertec-postgresql/pgwatch2#319]
Hi

I installed PGWatch2 with config DB. On HealthCheck dashboard most of metriks are linked to other dashboards but a lot of them are not working. 
For example QPS opens Grafana using IP like this: `122.121.121.121:3000/...`
But Max connections opens this link: `localhost:3000/...`

All links with `localhost` address are not working. I tried to edit the panel but both are similar:

```text
/dashboard/db/db-overview?$__all_variables&panelId=11&fullscreen
/dashboard/db/db-overview-developer?$__all_variables&panelId=15&fullscreen
```

**Comment by kmoppel** [comment]
Hi, which version of dashboards and for which storage DB - Postgres or Influx?
With the latest version the links seems to work for me...

**Comment by rostamiani** [comment]
for Postgres, but I don't know how to find the dashboard version. I just install PGWatch2 using this package:

pgwatch2_v1.8.1-SNAPSHOT-8410812_linux_64-bit.deb

**Comment by FzzyBnny** [comment]
I think I am experiencing a similar issue at least with the "Stat Activity Realtime" dashboard and the test database. I installed via the Docker route in the documentation (version info below), but when I try to use "Stat Activity Realtime" there is an error message in the top left, "pq: relation "stat_activity_realtime" does not exist". Any ideas?

`REPOSITORY                   TAG       IMAGE ID       CREATED       SIZE
cybertec/pgwatch2-postgres   latest    50e7099a9307   6 weeks ago   1.15GB`

**Comment by kmoppel** [comment]
@FzzyBnny Hi, please note that about half of the preset dashboards need some extra configuration steps! We don't want to collect a lot of "nische" information out of the box, that most users don't need. So in your case you need to explicitly add the "stat_activity_realtime" metric to the preset config (or custom config) you specified for your DB.

**Comment by FzzyBnny** [comment]
@kmoppel Thank you for the information. I updated the FULL preset config definition to include the stat_activity_realtime metric. Looks like it is working now.

Not sure if it will be helpful or is needed, just wanted to see what it does. Thanks again!

**Comment by kmoppel** [comment]
All links should be ok now after https://github.com/cybertec-postgresql/pgwatch2/commit/974a7cc478053e2e0adc2dedd8051ef61ba979af
