### ISSUE TITLE
function get_stat_statements() does not exist at character 910

### ISSUE THREAD

**Issue by rostamiani** [cybertec-postgresql/pgwatch2#321]
I saw this error in postgres log:

```log
ERROR:  function get_stat_statements() does not exist at character 910
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  
        with q_data as (
          select
            (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
            queryid::text as tag_queryid,
            max(ltrim(regexp_replace(query, E'[ \\t\\n\\r]+' , ' ', 'g')))::varchar(16000) as tag_query,
            array_to_string(array_agg(distinct quote_ident(pg_get_userbyid(userid))), ',') as users,
            sum(s.calls)::int8 as calls,
            round(sum(s.total_time)::numeric, 3)::double precision as total_time,
            sum(shared_blks_hit)::int8 as shared_blks_hit,
            sum(shared_blks_read)::int8 as shared_blks_read,
            sum(shared_blks_written)::int8 as shared_blks_written,
            sum(shared_blks_dirtied)::int8 as shared_blks_dirtied,
            sum(temp_blks_read)::int8 as temp_blks_read,
            sum(temp_blks_written)::int8 as temp_blks_written,
            round(sum(blk_read_time)::numeric, 3)::double precision as blk_read_time,
            round(sum(blk_write_time)::numeric, 3)::double precision as blk_write_time
          from
            get_stat_statements() s
          where
...

```

Should be there a get_stat_statements function or this is a miss typing?

**Comment by kmoppel** [comment]
Hi, I assume a) the helper was not rolled out or there is some `search_path` issue - the latest CREATE FUNCTION code also checks security of the schemas on `search_path` and doesn't use those with public CREATE privileges.

**Comment by kmoppel** [comment]
I've now just in case updated the documentation also on that `search_path` checking detail - https://github.com/cybertec-postgresql/pgwatch2/commit/26eb7877286a469b6cadb3b847d91c5ffc1fe480.

More information on helper rollouts: https://pgwatch2.readthedocs.io/en/latest/preparing_databases.html#rolling-out-helper-functions

**Comment by rostamiani** [comment]
I don't get it.
Then I cannot add this helper to the `public` schema? Do I really need it?
I tried to auto create helpers. Should I do this manually?

**Comment by kmoppel** [comment]
@rostamiani Yes "by default" `public` will not be used. Options: a) revoke public create grants from `public` schema b) create some other schema and make sure the DB user pgwatch2 is using to collect metrics has it on the path c) change the helper code to throw out that extra security check...
