### ISSUE TITLE
`pq: relation "pgbouncer_stats" does not exists` error. What's wrong?

### ISSUE THREAD

**Issue by rostamiani** [cybertec-postgresql/pgwatch2#323]
Hi
I tried to config pgbouncer but there is no data!
This is my configurations:
```config
DB type: pgbouncer
DB host: [the ip of my pgbouncer]
DB port: 64322
DB dbname: pgbouncer
DB user: admin
DB password: [admin password]
Preset metrics config: pgbouncer
```
I can connect to the pgbouncer cli using this user and get `show stats;` command. but there is a `pq: relation "pgbouncer_stats" does not exists` error in grafana.

This works:
```
psql -h [pooling IP] -U admin -d pgbouncer -p 64322
pgbouncer=# show stats;

```

This is the error I see in the configuration we b interface:
> Could not connect to specified host (ignore if gatherer daemon runs on another host): invalid command 'select 1', use SHOW HELP; 

And this error on  `pgwatch2.service` logs:
> ERRO main: could not start metric gathering for DB "PGBouncer" due to connection problem: pq: unsupported startup parameter: extra_float_digits

**Comment by kmoppel** [comment]
Ahha, the error seems familiar. It's about some default Postgres driver behaviour for some languages like Go and Java. I've changed PgBouncer config to get around it so far - just search for "extra_float_digits" in the `pgbouncer.ini`. Some more info here: https://github.com/lib/pq/issues/475

I'll also see if I can disable it on the driver level automatically...as we're not gathering any floating point statistics anyways.

**Comment by kmoppel** [comment]
Sadly seems this "extra_float_digits" still cannot be "blended out" on the Go driver level so closing the issue...

**Comment by rostamiani** [comment]
> Sadly seems this "extra_float_digits" still cannot be "blended out" on the Go driver level so closing the issue...
I just added `ignore_startup_parameters = extra_float_digits` to the pgbouncer configuration. The error disapeared but there is no logs yet.
_I didn't understand the "blended out" thing._

**Comment by kmoppel** [comment]
@rostamiani  This "blended out" was in the context of working around extra_float_digits on the driver level automatically in the daemon code...but this was not possible.

**Comment by rostamiani** [comment]
There is no log
And still no monitoring

How can I find the problem?

**Comment by kmoppel** [comment]
Hmm...is the pool actively in use also? So that if you execute `SHOW stats` manually you get some non-zero metrics? All errors should be logged still so I assume it's some sort of misconfiguration...
