### ISSUE TITLE
Installing Helm in Openshift, produces permission denied error

### ISSUE THREAD

**Issue by gil0109** [cybertec-postgresql/pgwatch2#324]
When using the following command, helm install ./helm-chart --name-template pgwatch2 -f chart-values.yml

The pgwatch pod gives the following error:

mkdir: cannot create directory '/var/run/grafana': Permission denied
Error: Can't drop privilege as nonroot user
For help, use /usr/local/bin/supervisord -h

Any suggestions?

**Comment by kmoppel** [comment]
Aha yes can well be as the defaults are for K8s not OpenShift - so you'd need to switch to the "cybertec/pgwatch2-nonroot" image instead. Let me know if it still doesn't work. Cheers
