### ISSUE TITLE
Problem with 'Unique Name' containing special characters

### ISSUE THREAD

**Issue by UltramanJack** [cybertec-postgresql/pgwatch2#325]
Hello,

One of my databases is named with a special character, "@".

And the auto-generated unique name (I left 'dbname' empty) for that database on administrative web UI also containts character "@".

![unique_name_with_special_char](https://user-images.githubusercontent.com/31789530/100750962-b62e8800-3421-11eb-878d-c7144b101287.png)

But if I try to update this entry, it will raise an error:

'Unique name' can only contain letters, digits and underscores.

![update_error](https://user-images.githubusercontent.com/31789530/100751393-38b74780-3422-11eb-9726-c314ca434fd6.png)

Is it a bug? Thanks for your help.

**Comment by kmoppel** [comment]
Hi, hmm yes, could be called a bug I guess - will take a look.
I'm surprised though that other parts like metrics collection and storage even work as using "@" is definitely not recommend I would say...first time I see that btw, and I've seen hundreds and hundreds of setups :)
Until a fix you need to use the config DB directly to make any changes...

**Comment by kmoppel** [comment]
Fixed in master, will be part of next v1.8.2. release (hopefully today).
