### ISSUE TITLE
PW2_RETENTION_DAYS or PW2_PG_RETENTION_DAYS ?

### ISSUE THREAD

**Issue by FireEmerald** [cybertec-postgresql/pgwatch2#326]
[Here ](https://pgwatch2.readthedocs.io/en/latest/custom_installation.html) is written:
```
NB! Default retention for Postgres storage is 2 weeks! To change, use the --pg-retention-days / PW2_RETENTION_DAYS gatherer parameter.
```

And [here ](https://github.com/cybertec-postgresql/pgwatch2/blob/master/ENV_VARIABLES.md)is written:
```
PW2_PG_RETENTION_DAYS Effective when PW2_DATASTORE=postgres. Default: 14
```

Which one is correct?

**Comment by kmoppel** [comment]
Good catch! It's PW2_PG_RETENTION_DAYS indeed for Postgres storage. Corrected.
