### ISSUE TITLE
Security issue [https]

### ISSUE THREAD

**Issue by mastak** [cybertec-postgresql/pgwatch2#33]
Hello Kaarel,
Thanks for that great tool!

I placed pgwatch2 behind https proxy, but browser shows that connection unsafe, the reason: logo of Cybertec use http connection (DB overview dashboard), can you change it to https.

thanks!

**Comment by mastak** [comment]
as I see www.cybertec.at does not provide https connection =(

**Comment by kmoppel** [comment]
Hi! You mean the Grafana logo? I'll see if there's a workaround...

**Comment by mastak** [comment]
I mean this:
https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/db-overview/dashboard.json#L1982

Here image src use http.

**Comment by kmoppel** [comment]
Corrected now in https://github.com/cybertec-postgresql/pgwatch2/commit/46cad861b6de6d1b7fd06d4580c36ec25084cf92. Thanks for reporting!

**Comment by kmoppel** [comment]
@mastak NB! There's also some built in SSL support (self-signed certs) so a proxy is not needed for not so critical stuff. See https://github.com/cybertec-postgresql/pgwatch2#technical-details
