### ISSUE TITLE
Missed ORDER BY in alert-template dashboard in 'Waiting sessions' panel

### ISSUE THREAD

**Issue by eshkinkot** [cybertec-postgresql/pgwatch2#336]
Without ORDER BY:
![изображение](https://user-images.githubusercontent.com/69589/105774800-ce7cd800-5f76-11eb-8921-0218a1c11d4d.png)

With ORDER BY:
![изображение](https://user-images.githubusercontent.com/69589/105774901-f3714b00-5f76-11eb-9467-25fa788ca270.png)

**Comment by kmoppel** [comment]
Merged
