### ISSUE TITLE
cpu是怎么计算得来的

### ISSUE THREAD

**Issue by guanhua-dba** [cybertec-postgresql/pgwatch2#338]
您好，请问图中这个cpu load 是怎么计算得到的呢？
![image](https://user-images.githubusercontent.com/59173239/105955473-4d762b80-60b1-11eb-9cf3-d633df0c574b.png)

**Comment by kmoppel** [comment]
Hi, if it's a screenshot of the "Health-check" dash then it's the direct value from /proc/loadavg which is fetched by default over the PL/Python wrapper called get_load_average().
--
Hello, how is the cpu load calculated in the figure?
