### ISSUE TITLE
runtime error:index out of range stops pgwatch2 from gathering metrics anymore

### ISSUE THREAD

**Issue by MahatmaFatalError** [cybertec-postgresql/pgwatch2#34]
While it was monitoring a running postgres instance the following runtime error occurred without a obvious reason. From this point in time, no more new metrics are shown in Grafana, while old metrics still persist.

public.pgstattuple , oid: 12535437
panic: runtime error: index out of range

```
goroutine 219 [running]:
main.DetectSprocChanges(0xc4201329e0, 0x12, 0xc42032ba60, 0xc4ffffffff, 0xc420010840, 0xc420327e48, 0x0, 0x3, 0xc42001a050)
	/pgwatch2/pgwatch2.go:578 +0x1bab
main.CheckForPGObjectChangesAndStore(0xc4201329e0, 0x12, 0xc42032ba60, 0xffffffff, 0xc420010840, 0xc420327e48)
	/pgwatch2/pgwatch2.go:779 +0x82
main.MetricsFetcher(0xc420356720, 0xc420010840)
	/pgwatch2/pgwatch2.go:827 +0xa70
created by main.main
	/pgwatch2/pgwatch2.go:1177 +0x1d27
```

During my tests today this error appeared several times.

**Comment by kmoppel** [comment]
Thanks for the report @MahatmaFatalError ! Hmm...haven't seen something like that myself...and don't have any ideas currrently. Would it be possible to see if there was also something done on the database? So that we could have a repeatable error. And what version Docker image are you using?

**Comment by MahatmaFatalError** [comment]
Thanks for replying @kmoppel. Which DB do you mean with `done on the database`? There a lot different databases in this setup ;)

Docker image version is the latest
`{"grafana": "Version 4.5.2 (commit: ec2b0fe)", "pgwatch2_git_version": "35cc5aede6da0ca2a715126cfde1fd8e821556eb", "influxdb": "InfluxDB v1.3.6 (git: 1.3 a7c3d3c0f7b74f71919047adbc4933460967a576)", "postgres": "PostgreSQL 9.5.9 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit"}
`

**Comment by kmoppel** [comment]
Problem fixed with https://github.com/cybertec-postgresql/pgwatch2/commit/a3873f9977dca15d7e6394703cf1259c2f75df23 - new image available. Thanks for the error report!
