### ISSUE TITLE
pg_show_plans extension.

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#340]
Hi, 
did you see that using pg_show_plan extension, 
you can not create a logical replication slot ?

i describe this issue here, but i never received any answer...
https://github.com/cybertec-postgresql/pg_show_plans/issues/14

**Comment by kmoppel** [comment]
@pmpetit Ouch...this is definitely a bug of pg_show_plans then so pgwatch2 can't do too much here...will notify the developer though.
