### ISSUE TITLE
Missing pgwatch2 objects in monitored postgres database

### ISSUE THREAD

**Issue by taf1-cornell-edu** [cybertec-postgresql/pgwatch2#341]
We are trying to get pgwatch2 running for the first time.  Our pgwatch2 collection daemon can connect successfully to the monitored postgres dbm but isn't able to gather stats because of missing postgres tables/views.  Many/most of the queries running on the monitored db by the daemon sessions are failing due to missing tables/views with these error messages:   

relation "admin.all_distinct_dbname_metrics" does not exist
relation "archiver" does not exist                         
relation "backends" does not exist                         
relation "bgwriter" does not exist                         
relation "configuration_changes" does not exist            
relation "db_size" does not exist                          
relation "db_stats" does not exist                         
relation "index_stats" does not exist                      
relation "pg_qualstats_indexes_ddl" does not exist         
relation "pg_stat_statements" does not exist               
relation "psutil_disk" does not exist                      
relation "replication" does not exist                      
relation "replication_slots" does not exist                
relation "settings" does not exist                         
relation "stat_statements" does not exist                  
relation "stat_statements_calls" does not exist            
relation "table_bloat_approx_summary_sql" does not exist   
relation "table_changes" does not exist                    
relation "table_stats" does not exist                      
relation "wal" does not exist                              
relation "wal_size" does not exist                         

We see similar errors on the Health Check dashboard when hovering the mouse over the red "!" in the upper left corner of each cell on that page. 

What did we miss?   Thanks very much.

**Comment by kmoppel** [comment]
Hmm...looks like somekind of `search_path` issue. And you also might be mixing up the monitored DB and the metrics DB - there shouldn't be any tables like "archiver" etc on the monitored DB...so some more information / facts would be required here to pinpoint the problem.

**Comment by taf1-cornell-edu** [comment]
I did indeed have the Grafana datasource pointed to a monitored database.  Thanks.

**Comment by franxav06** [comment]
Good morning
I have exactly the same problem, and I have a question, most of the objects in schema pgwatch2_admin are into the pubic schema. Is this normal ? 
Thanks in advance
Francesco

**Comment by pashagolub** [comment]
@franxav06 would you please rephrase? What does "schema in schema" mean anyway?

**Comment by franxav06** [comment]
Sorry, I wanted to say into database pgwatch2_admin.
I come from Oracle Work, so sometimes I confuse Cluster with database and databases with schemas..... ;o)
Thanks in advance
Francesco
