### ISSUE TITLE
Missing relations on custom installation

### ISSUE THREAD

**Issue by JeffRossMT** [cybertec-postgresql/pgwatch2#342]
Hello!

I know this is going to be something I missed.

I followed the guide to doing a custom installation of pgwatch2 with timetable extensions but I'm getting errors in the postgres logs about missing the following relations:

db_stats
db_size
add_compress_chunks_policy(text, interval)

So, nothing shows up in the dashboards at all.

Clue-by-four, please!

**Comment by JeffRossMT** [comment]
Update...I've grepped through the pgwatch2 code and although I see lots of places where db_stats is queried I see no place where the table/view is created.  Same with db_size.

The missing function add_compress_chunks_policy(text, interval) looks like it should be a part of timescaledb, but a new installation of timescaledb enterprise on a separate computer does not have this function.

Also missing is table_bloat_approx_summary_sql as found in this query in the Approx Table Bloat dashboard:
```
SELECT
  time,
  avg((data->'approx_table_bloat_b')::int8)
FROM
 table_bloat_approx_summary_sql 
WHERE
  $__timeFilter(time)
  AND dbname = '$dbname'
GROUP BY
  1
ORDER BY
  1
```

And, finally so far, this query in the CPU load + avg. query runtime dashboard is failing missing stat_statements:

```
select
  time,
  avg(avg) as "avg_query_runtime"
from (

select
time_bucket('300s',time) AS "time",
queryid,
avg((tt-tt_lag)::numeric / (c-c_lag))

from (

        select 
          (data->>'total_time')::float8 as tt, lag((data->>'total_time')::float8) over w as tt_lag,
          (data->>'calls')::int8 as c, lag((data->>'calls')::int8) over w as c_lag,
          tag_data->>'queryid' as queryid,
          time
        from stat_statements
        where dbname = 'pg1' and time BETWEEN '2021-02-11T19:16:30.036Z' AND '2021-02-11T22:16:30.036Z'
        and not tag_data->>'query' like '%$2)::int8 as epoch_ns,%' /*trying to not include queries by pgwatch itself*/
        window w as (partition by tag_data->>'queryid' order by time)
) x
where c > c_lag and tt >= tt_lag
group by 1, 2
order by 1, 2
) y
group by 1
order by 1
```

**Comment by kmoppel** [comment]
Hi,

About the add_compress_chunks_policy - this was indeed recently introduced by some API change on Timescale side, so I've pushed a new release to work around that: https://github.com/cybertec-postgresql/pgwatch2/blob/master/CHANGELOG.md#v184-2021-02-12

But I can't quite grasp the problem with missing metrics still...I'm guessing it's some configuration problem still. What "preset config" are you using? And how does the deployment model look like?

**Comment by JeffRossMT** [comment]
Thanks for the followup.  I'm using the Exhaustive set for 6 postgres servers, the pgbouncer set for several pgbouncer servers and the pgpool set for 2 pgpool servers.  

I'm not sure what you mean by the deployment model.  I walked through the Custom Install docs and did the steps in order.  I had to re-install timescaledb (2.0.1) a few times to get the version with the timescale license but I don't think that's related.

Where file are those tables (or views) created in?  I don't see a table/view creation for db_stats anywhere.  Additionally missing are backends and stat_statement_calls so clearly I missed some schema creation script.

**Comment by JeffRossMT** [comment]
Ah, I'm using the "pull" deployment.

**Comment by JeffRossMT** [comment]
I started over and think it's working now.  Most of the helper functions did not install because of 

failed to roll out get_stat_statements: get_stat_statements() SECURITY DEFINER helper will not be created as all schemas on search_path are unsecured where all users can create objects -

That's an error message I missed the first time.

Once that is fixed if all is well, I'll close this ticket.

**Comment by JeffRossMT** [comment]
I'm pretty sure that any remaining errors showing up in the logs are fixable by me now.

Thanks for pgwatch2--I think it's going to be a great step up from Nagios.
