### ISSUE TITLE
lockmodes array doesn't contain mode SHARE UPDATE EXCLUSIVE

### ISSUE THREAD

**Issue by kostiantyn-nemchenko** [cybertec-postgresql/pgwatch2#35]
Hi, @kmoppel 
Table-level lock array `lockmodes` has missing mode ShareUpdateExclusiveLock.

https://github.com/cybertec-postgresql/pgwatch2/blob/a356f3dad6fa8bf47102fc36ba4fd201209ac6a6/pgwatch2/sql/datastore_setup/metric_definitions.sql#L687

**Comment by kmoppel** [comment]
Fixed. Thanks a lot!
