### ISSUE TITLE
Configuration persistence in docker-compose deployment

### ISSUE THREAD

**Issue by joshuaganger** [cybertec-postgresql/pgwatch2#351]
We are building out a more complete docker-compose based implementation of pgwatch2 for deployment on a docker swarm cluster.  I have most aspects working, however when testing configuration persistence, I found that the config_store.sql used by the config database bootstrap container drops the pgwatch2.monitored_db table on line 19:

`drop table if exists pgwatch2.monitored_db;`

This means that even though we have successfully persisted the database to a docker volume, if the stack is ever redeployed, the configured databases are lost.  It's not totally clear to me if this behavior is also present for the metrics database, but I don't believe so.

Why is this necessary?  I could remove line 19 in a local copy of the file and copy it into my local database boostrap image but I'm hoping to understand the rationale behind this.  Thanks!

**Comment by kmoppel** [comment]
Hi! You're right, this line of code (and another DROP TABLE) are basically not needed - I think it's just a leftover from early days, to make testing / re-rollout easier.

**Comment by kmoppel** [comment]
Fixed on master
