### ISSUE TITLE
pg_stat_statement error

### ISSUE THREAD

**Issue by pcouas** [cybertec-postgresql/pgwatch2#357]
Hi

I use an pgwatch2 docker installation with an postgres12 installed on windows10 server
So i install proc like this "psql -U postgres -f D:\pgwatch2\get_pg_statements\metric.sql mybase"
But i have following error message
psql:D:/pgwatch2/get_pg_statements/metric.sql:52: ERROR:  get_stat_statements() SECURITY DEFINER helper will not be created as all schemas on search_path are unsecured where all users can create objects -
              execute 'REVOKE CREATE ON SCHEMA $my_schema FROM public' to tighten security or comment out the DO block to disable the check
CONTEXTE : fonction PL/pgSQL inline_code_block, ligne 15 à RAISE
ROLLBACK

Why ?
Regards

**Comment by kmoppel** [comment]
Hi, I know, security is annoying :) Here's the backstory: https://github.com/cybertec-postgresql/pgwatch2/pull/226
Feel free to change the helper definition though to roll out anyways if you don't want to restrict the schema create privs.
