### ISSUE TITLE
Stat Statements SQL Search grafana view empty

### ISSUE THREAD

**Issue by pcouas** [cybertec-postgresql/pgwatch2#360]
Hi

My "Stat Statements SQL Search grafana" view is empty ? 
But DbOverview contains datas on my Postgres12
Which pgsql need to be installed ?

Regards

**Comment by kmoppel** [comment]
Hi, details are scarse, but basically you need: 1) the pg_stat_statements installed and activated 2) a superuser as monitoring user 
 OR the pg_monitor role OR the [helper functions](https://pgwatch2.readthedocs.io/en/latest/preparing_databases.html#rolling-out-helper-functions) to access the pg_stat_statements data 3) the "stat_statements" metrics activated in your monitoring configuration
