### ISSUE TITLE
function remove_single_dbname_data fails with TimeScale extension

### ISSUE THREAD

**Issue by Lobo75** [cybertec-postgresql/pgwatch2#363]
I am using postgres 12.2 with TimeScale 2.1.0

When using the webpy admin tool if you try to delete a single DB's data you get the following error:

ERROR: cannot update/delete rows from chunk "_hyper_11_5_chunk as it is compressed CONTEXT.

From looking at the Timescale API it appears once the chunk is compressed it's immutable.  So two questions,  I'm wondering if the gatherer is still able to clear out old data when using Timescale?

Second should compression be disabled?  If so which tables and what does that do to pgwatch2?

Thanks.

**Comment by kmoppel** [comment]
Yes, the gatherer will work basically as retention is implemented over "DROP TABLE". Probably should just show a nicer error here that "per DB" deletion is not possible. But if you really want to delete that data make sure you have enough disk space before and disable the compression policy first as mentioned in the [docs](https://docs.timescale.com/latest/api#decompress_chunk).

**Comment by Lobo75** [comment]
It does not appear the metrics are actually getting cleaned up.  I removed a database from monitoring via webpy.  It's been 22 days and I can still see the metrics for example in psutil_disk table going back to 03/23/2021.

I have also tried changing the retention to 10 days to see what would happen.  

From looking at pgwatch2.go I would have expected to see the message "starting old Postgres metrics cleanup job"  right after "starting UniqueDbnamesListingMaintainer" but that is not occurring.

Thanks.

**Comment by kmoppel** [comment]
@Lobo75 Yes, you're right - there was indeed quite a bug with Timescale not being cleaned up. Is fixed now in master (https://github.com/cybertec-postgresql/pgwatch2/commit/e423c5457634ddc8597c07430346b346f4441f10) and will also push a new release in a day or two.

**Comment by kmoppel** [comment]
And currently the workaround is to execute "drop_chunk" SQL per hand or set up some TimescaleDB retention policies on all top level metrics tables.

**Comment by kmoppel** [comment]
v1.8.5 released now
