### ISSUE TITLE
docker image using timescaleDB

### ISSUE THREAD

**Issue by mszpulak** [cybertec-postgresql/pgwatch2#364]
Do you provide docker image for using postgres + timescaleDB extension out of the box ?
As I understand, postgres image uses classical postgres. 

My problem with influxDB is that when loading certain metrics, Influx can eat up to 60GB RAM.

**Comment by kmoppel** [comment]
Not yet, but it's on the TODO list. And we'll probably drop further support for InfluxDB anyways, as TimescaleDB has comparable compression + full power of SQL.
