### ISSUE TITLE
docker-daemon ssl skip verify logs

### ISSUE THREAD

**Issue by aromanvw** [cybertec-postgresql/pgwatch2#365]
Hi guys, Im using docker-daemon image1.8.0 to push metrics to influxdb. The influxdb certificate is self signed so I set the value of PW2_ISSL_SKIP_VERIFY to true.
When pgwatch2 obtains the database list from influxdb its working fine but when try to write metrics its failing and I dont get any error messages with kubectl logs ..... . Searching in documentation I found this folder /var/logs/supervisor/ for logs but it doesn´t exist in my container.

So could you add a log in func SendToInflux when c.Write(bp) get an error?

The problem may be in this function where the client is being created again but it is not receiving the InsecureSkipVerify argument

**Comment by kmoppel** [comment]
@aromanvw Thanks a lot for the input! You're right, these were both an oversight I believe. Btw, another way to fix Influx selfsigned cert errors is to install the cert: https://github.com/cybertec-postgresql/pgwatch2/issues/162
