### ISSUE TITLE
pgbouncer doesn't work with docker distribution

### ISSUE THREAD

**Issue by StdCarrot** [cybertec-postgresql/pgwatch2#366]
I use "cybertec/pgwatch2:1.8.4" image on docker.

And pgbouncer DB connection is working, no errors shows on pgwatch2 logs.

But, all values are 0 like this.

![image](https://user-images.githubusercontent.com/1968929/115827654-8d964180-a447-11eb-9dda-5fcae627c161.png)

**Comment by kmoppel** [comment]
Does the data exists on pgbouncer if you go in directly and execute "SHOW STATS"? And what version of Bouncer are you using?

**Comment by StdCarrot** [comment]
`SHOW STATS` on PGBouncer is working well like this:
![image](https://user-images.githubusercontent.com/1968929/116056504-d6086600-a6b8-11eb-9976-f222f2f81850.png)

And I use pgbouncer at 1.15.0.


Additionally I saw something wired:

PgWatch2 call `SELECT 1` when trying to connect PGBouncer even DB type is `pgbouncer` like this:

![image](https://user-images.githubusercontent.com/1968929/116057004-562ecb80-a6b9-11eb-8e42-ffad54a4d26d.png)

**Comment by kmoppel** [comment]
Thanks for the info! I'm getting this weird "0 value" behaviour also...so something must have changed somewhere :/ Will dig deeper...

**Comment by kmoppel** [comment]
@StdCarrot  Actually I think everything still worked as designed. Which might not mean "as expected" :D The thing is that so far only monitoring of one pool was assumed, which name was specified as the "DB name" in config. So I assume that you left the DbName field empty - then I got the same result. But yes now I think that it also makes sense to monitor all pools if the user wants that - I've added that in master now.

**Comment by ismailazerty** [comment]
Hello, same error for me with same versions (pgwatch,pgpool) .
 and I have specified dbname to "pgbouncer". 
In pgwatch logs I have also : ERRO MetricGathererLoop: Failed to fetch metric data for [pgbouncer:pgbouncer_stats]: pq: unrecognized configuration parameter "stats"

**Comment by kmoppel** [comment]
@ismailazerty Setting dbname as "pgbouncer" is not correct - you should set it to the pool name you actually want to track.

**Comment by ismailazerty** [comment]
@kmoppel  where can i find the pool name in the config file ?
