### ISSUE TITLE
[Enhancement] Dashboard for transactions

### ISSUE THREAD

**Issue by ismailazerty** [cybertec-postgresql/pgwatch2#367]
Hello,

   Is there any dashboard for viewing transactions state, average time for a transactions ...

Thank you

**Comment by kmoppel** [comment]
Hi, I can suggest looking at the `backend` metric data with columns like longest_session_seconds, longest_tx_seconds, active, idleintransaction, waiting. But for it to be really representative you might have to decrease the interval considerably. And for near realtime needs there's the `stat_activity_realtime`.

**Comment by kmoppel** [comment]
Ah ok the question was more about dashboards - in short there is only a high level overview panel on the "overview" dashboard and a couple of counters on the "health check" dash also...so yes, basically there's room for a completely new dashboard - so will leave the issue open currently.

**Comment by kmoppel** [comment]
Now there's a new "Sessions Overview" dashboard showing max / avg TX, query, session and autovacuum durations.

**Comment by ismailazerty** [comment]
great news,  thank you.
any idea for next release date ?

**Comment by kmoppel** [comment]
@ismailazerty  today or tomorrow :)

**Comment by ismailazerty** [comment]
great thx a lot

**Comment by ismailazerty** [comment]
Hello I have upgraded my docker config to cybertec/pgwatch2-postgres:1.8.5  but still no new "sessions Overview dashboard".
Should I execute some scripts ?

**Comment by kmoppel** [comment]
Yes, dashboards are not updated automatically on updates. Please look into [documentation](https://pgwatch2.readthedocs.io/en/latest/upgrading.html#updating-grafana-dashboards) for more info.

**Comment by kmoppel** [comment]
@ismailazerty
