### ISSUE TITLE
Can I use the same timescaledb for metric and config db?

### ISSUE THREAD

**Issue by shab2** [cybertec-postgresql/pgwatch2#368]
Hello!

I try to use configuration with one host where docker with (timescaledb(metric db) and grafana)
and some hosts with monitoring Postges db and locally installed metric collectors.

Where should I place ConfigDB? And can I use timescale (metric db) for ConfigDB goal?
Is it efficience for collector to read metric templates on remote ConfigDB?

Thanks

**Comment by kmoppel** [comment]
Hi, yes it's possible to place the ConfigDB on any Postgres DB basically. And there is no need to worry about performance - the config is cached for 2 minutes by default, so a couple of small queries only every 2 minutes.
