### ISSUE TITLE
Incorrect instruction on https://pgwatch2.readthedocs.io/en/latest/custom_installation.html#config-db-based-setup 

### ISSUE THREAD

**Issue by shab2** [cybertec-postgresql/pgwatch2#371]
Original:

```
Get the pgwatch2 project’s code and compile the gatherer daemon

git clone https://github.com/cybertec-postgresql/pgwatch2.git
cd pgwatch2
./build_gatherer.sh
# after fetching all the Go library dependencies (can take minutes)
# an executable named "pgwatch2" should be generated ...

```
1. After cd pgwatch2 I didnt found ./build_gatherer.sh, so I found it after next cd to pgwatch2
2. After ./build_gatherer.sh I didnt found file /etc/pgwatch2/startup-scripts/pgwatch2.service, but found ./pgwatch2/pgwatch2/startup-scripts/pgwatch2.service
3. I this file sting
[Service]
User=pgwatch2
   But I dont see create OS user pgwatch2 anywhere.
4. I this file sting ExecStart=/usr/bin/pgwatch2-daemon, but I didnt found file pgwatch2-daemon anywhere on server
  May be it is ./pgwatch2/pgwatch2/pgwatch2?
  May be need some make install routines?
Thank you

**Comment by kmoppel** [comment]
Right, there was small oversight - should have been: `cd pgwatch2/pgwatch2`. Also added a comment about `pgwatch2-daemon`.
