### ISSUE TITLE
relation stat_activity_realtime does not exist

### ISSUE THREAD

**Issue by q16marvin** [cybertec-postgresql/pgwatch2#375]
Hey,

i got this errors:

> 
",39,,""
2021-05-11 07:52:27.413 UTC,"pgwatch2","pgwatch2_metrics",15850,"127.0.0.1:52924",609a3411.3dea,3,"SELECT",2021-05-11 07:36:49 UTC,6/50129,0,ERROR,42P01,"relation ""stat_activity_realtime"" does not exist",,,,,,"SELECT
  tag_data->>'pid' AS pid,
  data->>'user' AS user,
  data->>'appname' AS appname,
  data->>'ip' AS ip,
  (data->'duration_s')::int AS duration,
  data->>'waiting' AS waiting,
  coalesce(data->>'blocking_pids', '') AS blocking_pids,
  data->>'query' AS query
FROM
  stat_activity_realtime
WHERE
  dbname = ''
  AND time = (SELECT max(time) FROM stat_activity_realtime WHERE dbname = '' AND time BETWEEN '2021-05-11T07:47:27.458Z' AND '2021-05-11T07:52:27.458Z')
  AND (data->'duration_s')::int > 1
ORDER BY
  duration DESC
LIMIT 25

but the query is working without any probs, can someone help?

**Comment by kmoppel** [comment]
Hey,
It's left a bit unclear what part is actually working - but are you sure the "stat_activity_realtime" metric is enabled in the monitoring config?

**Comment by q16marvin** [comment]
Hi,

yes of course:

![grafik](https://user-images.githubusercontent.com/19844709/117800102-189e7680-b253-11eb-925a-1f79cc2c0232.png)

**Comment by kmoppel** [comment]
@q16marvin This actually doesn't mean that the metrics are activated. The upper section could answer the activation better or the "DBs" page.

**Comment by q16marvin** [comment]
@kmoppel you mean this?

![grafik](https://user-images.githubusercontent.com/19844709/118262142-bf358200-b4b4-11eb-9648-f14246492e25.png)

**Comment by kmoppel** [comment]
@q16marvin  Rather this ![Screenshot from 2021-05-14 13-56-01](https://user-images.githubusercontent.com/346788/118282059-8c9c8100-b4d6-11eb-85c6-ef3d8784e729.png)

**Comment by q16marvin** [comment]
this?

![grafik](https://user-images.githubusercontent.com/19844709/118294264-d38c7580-b4da-11eb-99a0-4ae23c9c2aa8.png)

**Comment by kmoppel** [comment]
Ok yes, this show that stat_activity_realtime is not activated. You could add it to the "full" preset with some interval you consider useful. Usually 5-10 seconds is enough.
