### ISSUE TITLE
pg_stat_file() returns "must be superuser to get file information"

### ISSUE THREAD

**Issue by DeepBlueMussel** [cybertec-postgresql/pgwatch2#380]
Hello,

I'm not sure if this is misconfiguration from me or something else:
Whenever pg_stat_file() function is used, I'm getting the following permission error. Even after granting pgwatch2 user execute the function, I still get the same error.

Postgres version: 10.17-1

```bash
2021-05-20 17:36:13.526 CEST [11167] pgwatch2@dbname ERROR:  must be superuser to get file information
2021-05-20 17:36:13.526 CEST [11167] pgwatch2@dbname STATEMENT:
        /* NB! If using not a real superuser but a role with "pg_monitor" grant then below execute grant is needed:
          GRANT EXECUTE ON FUNCTION pg_stat_file(text) to pgwatch2;
        */
        select
          (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
           (sum((pg_stat_file('pg_wal/' || name)).size))::int8 as wal_size_b
        from pg_ls_waldir();
```

**Comment by kmoppel** [comment]
Indeed, seems to work only with Postgres v12+. So that leaves 2 options only: 1) disable the metric (used in "wal" and "wal_size" I think) 2) use indeed a superuser...which should be of course then done in a secure manner

**Comment by kmoppel** [comment]
@DeepBlueMussel for the "wal_size" there's also a wrapper function, to still enable it in a safe way: https://github.com/cybertec-postgresql/pgwatch2/tree/master/pgwatch2/metrics/00_helpers/get_wal_size

**Comment by DeepBlueMussel** [comment]
Thanks @kmoppel, I'll look into it.
