### ISSUE TITLE
tables top seems to fail after update to 1.8.5

### ISSUE THREAD

**Issue by Lobo75** [cybertec-postgresql/pgwatch2#384]
I completed the update to 1.8.5 and it appears that the grafana dashboard "Tables Top" fails with:

Templating[dbname]
Error updating options: Cannot read property 'text' of null.

Even in debug mode there is no further information on what the error is.

I'm running on Grafana 7.4.3.

Please note that due to the time 1.8.5 was applied and finding this issue was more than a week so I cannot be absolutely sure the update cause the error.

Can you provide any assistance in further trouble shooting the dashboard error?

Thanks.

**Comment by markwort** [comment]
Hey @Lobo75 , 
can you take a look at the dashboard definition (by clicking "edit" on the context menur for the dashboard in question)? That should show which table is the source for whatever is displayed in the dashboard.
You can then connect to your metrics database and check the table there.
The main question: is there nothing (recent) in that table, or does it look like the format for the data has changed?

Best regards
Julian

**Comment by Lobo75** [comment]
I was not able to edit the dashboard at all, grafana was throwing and error as it tried to do the initial load of the dashboard.  I discovered that re-importing the json for that dashboard into another folder worked.  So it was not a data driven issue but some how the dashboard got corrupted.

Thanks for the suggestion on the edit.
