### ISSUE TITLE
"pq: relation "stat_statements" does not exist"

### ISSUE THREAD

**Issue by rinshadka** [cybertec-postgresql/pgwatch2#393]
Hi, I am getting this error from grafana dashboard, while checking the pgwatch2_metrics database I am not able to see this table .

I have enabled the pg_stat_statements extension in pgwatch2_metrics and also monitored db. But couldnt find the **stat_statements** table

Thanks.

**Comment by kmoppel-cognite** [comment]
Sounds like a metrics configuration problem. When pg_stat_statements extension is enabled / created on the target DB and "stat_statements" metrics also configured in pgwatch2 monitoring config for that DB then it must work..or there must be some error logs either on pgwatch2 side or target DB side.
