### ISSUE TITLE
Don't know what error means

### ISSUE THREAD

**Issue by pgvirtuoso** [cybertec-postgresql/pgwatch2#394]
I am running pgwatch2 on kubernetes. I am seeing this error in the pod logs:

2021/08/09 17:20:32 WARN tryDetermineLogMessagesLanguage: [timescale_ro] Server log language 'C.' is not yet mapped, assuming severities in english: [DEBUG INFO NOTICE WARNING ERROR LOG FATAL PANIC]

What does it mean?

**Comment by kmoppel-cognite** [comment]
What version of pgwatch2 was used? "C." Seems to be added already - https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/logparse.go#L16
