### ISSUE TITLE
Don't know what this warning means

### ISSUE THREAD

**Issue by pgvirtuoso** [cybertec-postgresql/pgwatch2#395]
Deployed pgwatch2 in kubernetes. I am seeing this warning in pods logs:

Total fetching time of 669.7s bigger than 180s interval for [timescale_wr:stat_statements]

What does it mean?

**Comment by kmoppel-cognite** [comment]
This just means that there's a huge lag somewhere (the monitoring host, network, target DB) and you're real collecting interval is not the specified 3min anymore
