### ISSUE TITLE
Missing documentation for requirements on monitored database

### ISSUE THREAD

**Issue by kagkarlsson** [cybertec-postgresql/pgwatch2#4]
It would be neat of the README.md here had a guide for what is required in the monitored database for pgwatch2 to work. 

* Users/schemas
* Functions
* pg_hba.conf entry

**Comment by gcaraciolo** [comment]
### pg_stat_statement
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.max = 10000
pg_stat_statements.track = all

* restart postgres server

### users
```
$ psql
$ create role pgwatch2;
```

### extensions
- CREATE EXTENSION pg_stat_statements;
- CREATE EXTENSION plpythonu;

### metrics fetching helpers
exec queries in the pgwatche/sql/metrics_fetching_helpers files as pgwatch2 users in postgresql target database.

**Comment by kmoppel** [comment]
Thanks for writing it out! Hope I'll find some time next week to improve the documentation. PRs also welcome:)

**Comment by kmoppel** [comment]
I've updated the README now in commit https://github.com/cybertec-postgresql/pgwatch2/commit/3183a6f7effcb418064f78db9fc3204ca5a56806, so closing the issue:) Thanks a lot for the input!
