### ISSUE TITLE
pgwatch2 stopped working with "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#40]
Hello Kaarel,
I noticed today morning that pgwatch2 died yesterday with:

2017/11/02 13:28:49 13:28:49.879 WARN DetectSprocChanges: detected delete of sproc: public.soundex , oid: 16425
2017/11/02 13:28:49 13:28:49.950 WARN DetectIndexChanges: detected drop of index: public.ffh1e_menu_types_pkey
panic: runtime error: index out of range

goroutine 288 [running]:
main.DetectIndexChanges(0xc4201195a0, 0xf, 0x4023333333333333, 0xc420010840, 0xc420539e48, 0x0, 0x0, 0x0)
	/pgwatch2/pgwatch2.go:707 +0x19d2
main.CheckForPGObjectChangesAndStore(0xc4201195a0, 0xf, 0x4023333333333333, 0xc420010840, 0xc420539e48)
	/pgwatch2/pgwatch2.go:774 +0x152
main.MetricsFetcher(0xc420319c80, 0xc420010840)
	/pgwatch2/pgwatch2.go:820 +0xa58
created by main.main
	/pgwatch2/pgwatch2.go:1169 +0x1d27

used versions:
{"influxdb": "InfluxDB v1.3.5 (git: HEAD 9d9001036d3585cf21925c13a57881bc6c8dcc7e)", "postgres": "PostgreSQL 9.5.8 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit", "grafana": "Version 4.5.1 (commit: c114c46)", "pgwatch2_git_version": "b4ad2fd324b1ff8aef315c0998c427240898dcc3"}

I've restarted the docker container and now it's working again but misses all the data in between.

**Comment by georg-h** [comment]
it died today again

2017/11/03 11:28:15 11:28:15.304 ERRO SendToInflux: NewPoint failed: max key length exceeded: 73759 > 65535
2017/11/03 11:28:15 11:28:15.306 ERRO SendToInflux: NewPoint failed: max key length exceeded: 73759 > 65535
2017/11/03 11:28:15 11:28:15.390 WARN DetectIndexChanges: detected drop of index: public.ffh1e_fields_groups_idx_checked_out
panic: runtime error: index out of range

goroutine 418 [running]:
main.DetectIndexChanges(0xc420141fc0, 0xf, 0x4023333333333333, 0xc420010840, 0xc420561e48, 0x0, 0x0, 0x0)
	/pgwatch2/pgwatch2.go:707 +0x19d2
main.CheckForPGObjectChangesAndStore(0xc420141fc0, 0xf, 0x4023333333333333, 0xc420010840, 0xc420561e48)
	/pgwatch2/pgwatch2.go:774 +0x152
main.MetricsFetcher(0xc4204827e0, 0xc420010840)
	/pgwatch2/pgwatch2.go:820 +0xa58
created by main.main
	/pgwatch2/pgwatch2.go:1169 +0x1d27

**Comment by georg-h** [comment]
I've no idea if the "max key length exceeded: 73759 > 65535" and the panic error belong together as there is no hint for the affedcted database in the log.

**Comment by kmoppel** [comment]
Both issues should be now fixed in latest version 1.2.2. Thanks for the report!
