### ISSUE TITLE
Fix skip locked tables

### ISSUE THREAD

**Issue by eshkinkot** [cybertec-postgresql/pgwatch2#403]
An AccessExclusiveLock that has not yet been granted already blocks SELECT, because postgres has a queue/priority of locks to forcibly push AccessExclusiveLock before other.

So, check for "granted" in lock check is not needed, it just totally break lock check.

**Comment by kmoppel-cognite** [comment]
Yes seems it worked only without other queue members besides the monitoring agent, thanks @eshkinkot !
