### ISSUE TITLE
"port" parameter passed to function not used

### ISSUE THREAD

**Issue by krisavi** [cybertec-postgresql/pgwatch2#407]
Hi,

It seems the port that is passed to the function is not used, since it is using opts.PrometheusPort

https://github.com/cybertec-postgresql/pgwatch2/blob/7ac2eac48fced3bb1f0c37c9cdd60986c1106e06/pgwatch2/prom.go#L292

I am not sure why the port is int64, when it could be uint16 or int32, since the port is in range of 0-65535 (range of unsigned 16-bit integer)

**Comment by kmoppel-cognite** [comment]
Yes, seems like an oversight indeed :) The int 16 / 32 is just a matter of unification / taste and not a problem I would say - everything is pretty much 64. PR-s are always welcome :)
