### ISSUE TITLE
add db to monitor

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#41]
Hello,
While adding a new db to monitor, if you leave "db name" empty, for it to add all the db, then it will use the connection parameters from the line 1

![capture du 2017-11-06 14-23-22](https://user-images.githubusercontent.com/4059185/32443098-13aa7702-c2fe-11e7-8df2-6df2b76f9b14.png)

for example, adding a new db in this context without setting db_name : all newly added database will come from the line 1 instead of bditz1pgs03

**Comment by kmoppel** [comment]
Hi! Could not repeat the situation with the latest Docker image...are you sure you did everything correctly on your side? Please re-check and re-open the issue if needed.
