### ISSUE TITLE
Rewrite database pool handling

### ISSUE THREAD

**Issue by eshkinkot** [cybertec-postgresql/pgwatch2#413]
IMHO database pool is used very strangely. `conn *sqlx.DB` is not really a single connection, but a pool of connections and it already have limits and other pool's features. As stated in the documentation https://pkg.go.dev/database/sql#Open:
> The returned DB is _safe for concurrent use_ by multiple goroutines and maintains its own pool of idle connections. Thus, the Open function should be called just once. It is _rarely necessary to close a DB_.

So realy there is no needed for cache or locking, you can use pool directly. Also there is no needed to close it, if I not mistaken — it have reconnect logic in it.  I think all that is needed here is to use carefully context.Context and timeouts.

Closing the entire pool breaks metrics fetch running simultaneously with the erroneous one. For example:
```
2021/09/30 20:57:57 INFO DBExecRead: 0xc000458c30 conn close test {2 1 1 0 0 0s 0 0 0}
2021/09/30 20:57:57 INFO DBExecRead: 0xc000458c30 cache assign nil test
2021/09/30 20:57:57 INFO FetchMetrics: [test:err_metric] failed to fetch metrics: pq: column "error" does not exist
...
2021/09/30 20:57:57 INFO FetchMetrics: [test:backends] failed to fetch metrics: sql: database is closed
```

The "err_metric" metric have error and fetching it closes the pool, but this pool has a connection for "backends" metric, which could have been executed without errors, but was closed.

**Comment by kmoppel** [comment]
#418 merged now
