### ISSUE TITLE
Collector hangs at startup when a configured db is not responsive

### ISSUE THREAD

**Issue by Lobo75** [cybertec-postgresql/pgwatch2#416]
I had a case where the collector was started but one of the configured monitored instances was hung up.  A TCP connection would hang.

It looks like there is not a connection_timeout on the sqlx connection to each DB true?

From looking at an strace of the collector I see where it's in UpdateMetricDefinitionMap function:

 write(2, "2021/10/22 18:24:31 DEBU UpdateMetricDefinitionMap: metrics definitions refreshed - nr. found: 81\n", 98 <unfinished ...>

Then the collector seems to get a list of the configured DB's:

2715  write(7, "Q\0\0\3\343\n\t\tselect /* pgwatch2_generated */\n\t\t  md_unique_name, md_group, md_dbtype, md_hostname, md_port, md_dbname, md_user, coalesce(md_password, '') as md_password,\n\t\t  coalesce(p.pc_config, md_config)::text as md_config, coalesce(s.pc_config, md_config_standby, '{}'::jsonb)::text as md_config_standby,\n\t\t  md_statement_timeout_seconds, md_sslmode, md_is_superuser,\n\t\t  coalesce(md_include_pattern, '') as md_include_pattern, coalesce(md_exclude_pattern, '') as md_exclude_pattern,\n\t\t  coalesce(md_custom_tags::text, '{}') as md_custom_tags, md_root_ca_path, md_client_cert_path, md_client_key_path,\n\t\t  md_password_type, coalesce(md_host_config, '{}')::text as md_host_config, md_only_if_master\n\t\tfrom\n\t\t  pgwatch2.monitored_db\n\t          left join\n\t\t  pgwatch2.preset_config p on p.pc_name = md_preset_config_name /* primary preset if any */\n\t          left join\n\t\t  pgwatch2.preset_config s on s.pc_name = md_preset_config_name_standby /* standby preset if any */\n\t\twhere\n\t\t  md_is_enabled\n\t\0", 996 <unfinished ...>

I'm not sure exactly where the connection attempt is made but the trace shows one of the entries:

2720  connect(10, {sa_family=AF_INET, sin_port=htons(5432), sin_addr=inet_addr("10.xx.xx.xx")}, 16 <unfinished ...>

The collector just hangs or the sqlx connection is in a loop trying to make that connection that will never complete.

2720  <... connect resumed>)            = -1 EINPROGRESS (Operation now in progress)
2720  epoll_ctl(4, EPOLL_CTL_ADD, 10, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3203429136, u64=128615999107856}}) = 0
2720  futex(0xc000052d48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
2716  <... nanosleep resumed>NULL)      = 0
2716  futex(0x1090ef8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=16086694} <unfinished ...>
2717  <... epoll_pwait resumed>[], 128, 16, NULL, 0) = 0
2717  epoll_pwait(4, [], 128, 0, NULL, 548) = 0
2717  epoll_pwait(4,  <unfinished ...>
2716  <... futex resumed>)              = -1 ETIMEDOUT (Connection timed out)

Can someone look into adding a connection timeout?

Thanks.

**Comment by kmoppel-cognite** [comment]
Merged now
