### ISSUE TITLE
Question about hundreds databases on same postgresql instance monitored

### ISSUE THREAD

**Issue by lenhardtx** [cybertec-postgresql/pgwatch2#417]
Good morning everyone, congratulations on the project.

I have a question regarding the configuration of pgwatch2 when we have an PostgreSQL Server instance with hundreds of databases, is there any recommendation on how to configure it so that it is not invasive?

What seems to happen is a frantic firing of connections, logically because the tool issues queries by database, here a suggestion would be a global way to collect, and in practically all cases we could with a single query search for the information grouped by database . (Perhaps the problem here will be how to control the list of databases to be monitored).

Here where I work we use microservices in golang too, and I witnessed exactly this same phenomenon when the parameter "SetMaxIdleConns" is smaller than "SetMaxOpenConns", it happens that in this situation the golang is frantically trying to close the connections and with that happens the connection overhead.

Is it possible to parameterize the "SetMaxIdleConns" so that we can customize its value and thus try to keep more connections open in order to reduce the connect/disconnect overhead?

Only today, for 46 monitored databases:

[root@XXXX log]# grep "disconnection: session time" postgresql-2021-10-29.log | grep pgwatch2 | wc -l
165890
[root@XXX log]# date
Fri Oct 29 13:01:42 UTC 2021

I have servers with more than 300 databases, if there is no connection pool always available it is impossible to monitor opening and closing connections all the time for each database.

Another question, is there someone working on something for "repmgr"?

Thanks a lot!

**Comment by bukem** [comment]
Hi @lenhardtx ,
we had the same issue and solved it by establishing pgwatch2 connections through pgbouncer. Some statistics:
- before we had more than 1.5M connections per day
- now we have about 500 connections/day

We could not switch the main connection (https://github.com/cybertec-postgresql/pgwatch2/issues/359 and https://github.com/cybertec-postgresql/pgwatch2/issues/348) , but we successfully switched the connections to collect the metrics themselves.

Best of luck!

**Comment by kmoppel-cognite** [comment]
Yes, I think for 300 DBs there's no way around PgBouncer...but, I've now also merged the re-worked connection pooling...so that theoretically it could work also if a high `max_connections` is not a problem . Use the following params to play around: `--conn-pooling` and `--max-parallel-connections-per-db`
