### ISSUE TITLE
[Enhancement/aiven/metrics os]: using avn cli

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#425]
Hi, 
it wouldd be great, if we could retreive aiven pg metrics using https://developer.aiven.io/docs/tools/cli/service.html (avn service metrics).
and insert result into public.psutil_cpu table for example. (using extension plpython3u is not possible on managed dbs)

I'm currently working on it.

keep you informed.

**Comment by pmpetit** [comment]
Hello,
fyi we have write a python script that collect system metrics from an aiven pg service.
Those values are inserted into psutil_cpu and cpu_load tables. We also did the same for rds dbs.
Using kustomize, it is run in a sidecar every hours, near pw2 image.
Connection informations are retreive from table "configured_dbs". With a custom-tag we add the aiven "project name" and "service name" to the monitored db, then we can call avn api.
[main.py.zip](https://github.com/cybertec-postgresql/pgwatch2/files/7959578/main.py.zip)

**Comment by pmpetit** [comment]
Dockerfile and cronta
[Archive.zip](https://github.com/cybertec-postgresql/pgwatch2/files/7959691/Archive.zip)
b

**Comment by pashagolub** [comment]
Hello,

pull requests are welcome. We cannot proceed with the zip archives attached.

Thanks for understanding. 🙏
