### ISSUE TITLE
Supervisord.conf overrides environment variables for pgwatch2 program

### ISSUE THREAD

**Issue by alexyuscott** [cybertec-postgresql/pgwatch2#43]
Hi,

Current value

```
[program:pgwatch2]
command=/pgwatch2/pgwatch2 --host=localhost --port=5432 --dbname=pgwatch2 --user=pgwatch2 --password=<password obscured>

```
This appears to mean that the environment variables for Postgresql connection are ignored

Alex

**Comment by thearthur** [comment]
I confirmed that this breaks using an external config DB, and that fixing it makes it work

**Comment by kmoppel** [comment]
Fixed now in https://github.com/cybertec-postgresql/pgwatch2/commit/93956abcbc092eef9685d8f4f7a450c700e4b93a - thanks a lot for reporting!
