### ISSUE TITLE
pgwatch2 build error

### ISSUE THREAD

**Issue by YoonSungHyun-inzent** [cybertec-postgresql/pgwatch2#432]
Hi,
I want to build. An error occurred along the way. The errors are as follows: I need help.

PS C:\workspace\pgwatch2\pgwatch2> go build  .\pgwatch2.go .\prom.go .\patroni.go .\logparse.go
.\pgwatch2.go:4641:21: undefined: syscall.Stat_t

**Comment by pashagolub** [comment]
Good day,

`pgwatch2` doesn't support Windows yet. Would you please describe your environment? Why do you need Windows binaries?

Thanks in advance!

**Comment by YoonSungHyun-inzent** [comment]
Hi,
I want to fix pgwatch2.go and build it
I used window 10, visual studio code, 
go : version go1.17.6 windows/amd64
build command : go build .\pgwatch2.go .\prom.go .\patroni.go .\logparse.go
If you need more ways to build or something, let me know
Thank you
