### ISSUE TITLE
Performance issues with pg_database_size

### ISSUE THREAD

**Issue by ants** [cybertec-postgresql/pgwatch2#433]
There are some cases of pg_database_size where it is called once per database object. (example: https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/reco_drop_index/9.4/metric_master.sql ) pg_database_size() is volatile and calls stat() on every file in the database which leads to O(n²) performance issues in databases with lots of tables/indexes.

Caching the result once using a CTE would be enough to mitigate the issue.

**Comment by kmoppel-cognite** [comment]
Indeed not too nice :) Add the CTE
