### ISSUE TITLE
Vacuum progress metrics

### ISSUE THREAD

**Issue by bukem** [cybertec-postgresql/pgwatch2#434]
Hi @kmoppel 

I just have found a great article by David Pacheco where he dives deep into the vacuum process and it's stages, where he shows how it can be visualized https://www.davepacheco.net/blog/2019/visualizing-postgresql-vacuum-progress/ .
Inspired by the article I want to ask - are there plans to add metrics based on `pg_stat_progress_vacuum` view?

Regards, Mikhail

**Comment by pashagolub** [comment]
Hello Mikhail,

we are always open to new pull requests! Do not hesitate to improve our metrics by adding another one!

Best regards!
