### ISSUE TITLE
docker install fails

### ISSUE THREAD

**Issue by fahadshery** [cybertec-postgresql/pgwatch2#435]
Hi,

I am trying to install this. I already have working `Grafana` and `prometheus` instances. 

When I try to install `cybertec/pgwatch2-postgres` it fails at creating `/etc/run/grafana` due to permission issues.

The question is: I don't need to install Grafana and Prometheus. All I want is the data scrapper and the dashboards. How do I achieve this?

Many thanks

**Comment by pashagolub** [comment]
Hello,

Did you try the [cybertec/pgwatch2-daemon image](https://pgwatch2.readthedocs.io/en/latest/docker_installation.html)?

**Comment by fahadshery** [comment]
> Hello,
> 
> Did you try the [cybertec/pgwatch2-daemon image](https://pgwatch2.readthedocs.io/en/latest/docker_installation.html)?

thank you for your prompt response. 
Sorry but there are no clear instructions on how to just setup the daemon? All I want is the Grafana dashboards of your awesome tool.
I already have a separate docker instances of Prometheus and Grafana running. 
Would you be able to provide a docker run for me to try?

Tom

**Comment by pashagolub** [comment]
We cannot provide you with the command line, because we have no idea about your environment. You may want to read [this chapter](https://pgwatch2.readthedocs.io/en/latest/components.html#component-reuse) about using external Grafana, Prometheus, and other components.
