### ISSUE TITLE
Create dashboards in different organization

### ISSUE THREAD

**Issue by blogh** [cybertec-postgresql/pgwatch2#44]
Hi, 

Thanks for sharing this tool.

We would like to centralize the metrics of several databases on the same server.
We have to create different organizations to limit what users can see.

Is there an easy wait to create the dashboard in a different organisation from the pgwatch2 interface ? 

Benoit.

PS: I noticed a small typo in README.md  
"(e.g. docker exec -it ps2 /bin/bash)" => should be pw2 instead of ps2.
I can create a PR if you want.

**Comment by kmoppel** [comment]
Hi! Thanks for noticing the typo, no worries, will adjust it myself with some other next correction :)
But with dashboards - sadly no good way...dashboards are tied to organizations, so one needs to do the "copy the JSON (the settings cog)" and "Import  dashboard" process :(
