### ISSUE TITLE
pgbouncer with empty dbname fails with "Failed to resolve DBs"

### ISSUE THREAD

**Issue by z26egors** [cybertec-postgresql/pgwatch2#451]
Hello,

In pgwatch2 documentation it says that we can put an empty dbname if we want to track all pools in pgbouncer: 

> "Note that for the “DB Name” field you should insert not “pgbouncer” (although this special DB provides all the statistics) but the real name of the pool you wish to monitor or leave it empty to track all pools"

In `FilterPgbouncerData` function we can see that it's the case as it doesn't filter if `databaseToKeep` parameter is empty.

But unfortunately when dbtype is pgbouncer it still tries to list databases to monitor, and there's no such thing in pgbouncer:
```
ERRO GetMonitoredDatabasesFromMonitoringConfig: Failed to resolve DBs for "myserver-pgbouncer": Failed to connect to any of the template DBs: [template1 postgres defaultdb]
```

In the `GetMonitoredDatabasesFromMonitoringConfig` function it misses an if with `e.DBType == DBTYPE_BOUNCER` to not try to list databases.

Regards,

**Comment by markwort** [comment]
> In the GetMonitoredDatabasesFromMonitoringConfig function it misses an if with 'e.DBType == DBTYPE_BOUNCER' to not try to list databases.

I agree with your assessment.
Should not be too difficult to fix but of course requires at least a small test case to make sure that the rest of the pipeline also works...

**Comment by AndrewJackson2020** [comment]
I believe that I'm seeing this issue. Was a fix for this ever implemented?

**Comment by pashagolub** [comment]
Not that I'm aware of. PRs are more than welcome!

**Comment by AndrewJackson2020** [comment]
> Not that I'm aware of. PRs are more than welcome!

I'm down to give it a shot. Above another contributor mentions writing a test case but I couldn't find any unit tests for the golang code. Are there automated tests for the go code anywhere that I would need to update?

**Comment by pashagolub** [comment]
> Are there automated tests for the go code anywhere that I would need to update?

Unfortunately pgwatch2 doesn't have any tests :(
