### ISSUE TITLE
Replica stopped getting stat_statements but master still works

### ISSUE THREAD

**Issue by rostamiani** [cybertec-postgresql/pgwatch2#461]
I'm using pgwatch2 for about a year for a master and two replications. Recently I found out that none of replicas have top statements log for about two month and this error happens on pgwatch server:
```10:03:13 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica1:cpu_load]: pq: could not access file "$libdir/plpython3": No such file or directory
10:03:13 WARN main: sent STOP message to 10 gatherers (it might take some minutes for them to stop though)
10:03:13 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica2:cpu_load]: pq: could not access file "$libdir/plpython3": No such file or directory
10:03:44 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica2:stat_statements]: pq: function get_stat_statements() does not exist
10:03:44 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica1:stat_statements]: pq: function get_stat_statements() does not exist
10:05:13 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica1:cpu_load]: pq: could not access file "$libdir/plpython3": No such file or directory
10:05:13 WARN main: sent STOP message to 10 gatherers (it might take some minutes for them to stop though)
10:05:14 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica2:cpu_load]: pq: could not access file "$libdir/plpython3": No such file or directory
10:05:44 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica1:stat_statements]: pq: function get_stat_statements() does not exist
10:05:44 ERRO MetricGathererLoop: Failed to fetch metric data for [Replica2:stat_statements]: pq: function get_stat_statements() does not exist

```

Is `get_stat_statements` a helper function? Is it possible to exist on master but not replications?

**Comment by pashagolub** [comment]
Thanks for your request. Yes, this is an absent [helper function](https://github.com/cybertec-postgresql/pgwatch2/blob/b27310ca3cb41828a2fca776d0485ad594cb4633/pgwatch2/metrics/00_helpers/get_stat_statements/9.4/metric.sql)

**Comment by rostamiani** [comment]
How can I check existence of this function?
Replications are read-only and the same as master but master generates top-query report!

**Comment by rostamiani** [comment]
Thanks
Enabling "Auto Create Helpers?" didn't create this function on master So I tried to create it manually. But this exception apeared:

> get_stat_statements() SECURITY DEFINER helper will not be created as all schemas on search_path are unsecured where all users can create objects
> execute 'REVOKE CREATE ON SCHEMA $my_schema FROM public' to tighten security or comment out the DO block to disable the check

I revoked create privilege and executed the script

```
postgres@db-master:/home/rostamiani$ psql -f get-stat-statements.sql -d skyroom
BEGIN
psql:get-stat-statements.sql:17: NOTICE:  extension "pg_stat_statements" already exists, skipping
CREATE EXTENSION
CREATE FUNCTION
GRANT
COMMENT
psql:get-stat-statements.sql:55: NOTICE:  ALTER FUNCTION get_stat_statements() SET search_path TO public
DO
COMMIT
```
Now both master and replica have `get_stat_statements` function but now none has logs on Garfana
### Master lost logs too :cry:

**Comment by markwort** [comment]
Can you please apply some basic troubleshooting?
- What are the schemas were the get_stat_statements() function is defined?
- Where is pgwatch2 looking?
- Are the pgwatch2 configurations identical?
- is pg_stat_statements even installed and in shared_preload_libraries? If it isn't then there is no way to get anything even if the functions are there and functional.

Best regards
Julian

**Comment by rostamiani** [comment]
Finally I found the solution
After adding get-stat-statements both master and replica are correct but replica server had a timeout because it has a lot more queries. Increased time limit from 30 to 60 fixed the problem (Oh, the query is soooo slow!)

**Comment by pashagolub** [comment]
Would you please provide us with the slowest queries EXPLAIN plans? Just curious how can we improve that

**Comment by rostamiani** [comment]
> Would you please provide us with the slowest queries EXPLAIN plans? Just curious how can we improve that

Thanks
This is the EXPLAIN of this slow query:
https://github.com/cybertec-postgresql/pgwatch2/issues/462#issuecomment-1059645121
