### ISSUE TITLE
grafana shows dbname None

### ISSUE THREAD

**Issue by tengilim** [cybertec-postgresql/pgwatch2#463]
Hi;

   I have just installed pgwatch2  as manuel installation.   After complete the all configuration , I  dont see the my monitored db on grafana. Grafana shows  dbname none all dashboards.  what should  I do?

**Comment by markwort** [comment]
hey, can you check that pgwatch2 is actually retrieving metrics from your database and sending them to the "metrics storage" ?

Can you provide more details on your setup, which parts have you used to run pgwatch2, where is grafana running, where is pgwatch2 storing the metrics and where is grafana accessing them?

**Comment by tengilim** [comment]
Hi;

 Sure. I have installed grafana and pgwatch and webUI on the same server.  When I run   select * from monitored_db; I am getting my monitored db info also my pgwatch2 deamon logs looks like the below:

_

> 2022/03/09 16:52:41 INFO logparseLoop: [postgres62] No logfiles found to parse from glob '/data/pg11/log/*.csv'. Sleeping 60s...
> 2022/03/09 16:52:41 INFO FetchMetrics: [postgres62:psutil_cpu] fetched 1 rows in 551.1 ms
> 2022/03/09 16:52:41 INFO ReadMetricDefinitionMapFromPostgres: updating metrics definitons from ConfigDB...
> 2022/03/09 16:52:41 INFO main: host info refreshed, nr. of enabled entries in configuration: 1, nr. of distinct metrics: 81
> 2022/03/09 16:52:41 INFO SendToPostgres: wrote 1/1 rows to Postgres for [postgres62:psutil_cpu] in 0.8 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:locks] fetched 9 rows in 3.6 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:stat_statements_calls] fetched 1 rows in 1.8 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:sproc_stats] fetched 0 rows in 12.9 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:backends] fetched 1 rows in 3.9 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:instance_up] fetched 1 rows in 0.7 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:locks_mode] fetched 8 rows in 2.9 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:archiver] fetched 1 rows in 1.2 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:db_stats] fetched 1 rows in 1.7 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:stat_statements] fetched 35 rows in 7.3 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:bgwriter] fetched 1 rows in 0.9 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:wal] fetched 1 rows in 1.2 ms
> 2022/03/09 16:53:40 INFO FetchMetrics: [postgres62:cpu_load] fetched 1 rows in 17.0 ms
> 2022/03/09 16:53:41 INFO SendToPostgres: wrote 60/60 rows from 11 metric sets to Postgres in 6.1 ms
> 2022/03/09 16:53:41 INFO logparseLoop: [postgres62] No logfiles found to parse from glob '/data/pg11/log/*.csv'. Sleeping 60s...

_


pgwatch2_grafana=#  select * from data_source;
 id | org_id | version |   type   |    name    | access |          url          | password | user | database | basic_auth | basic_auth_user | basic_auth_password | is_default | json_data
 |          created           |          updated           | with_credentials | secure_json_data | read_only |    uid
----+--------+---------+----------+------------+--------+-----------------------+----------+------+----------+------------+-----------------+---------------------+------------+----------
-+----------------------------+----------------------------+------------------+------------------+-----------+-----------
  1 |      1 |       1 | postgres | PostgreSQL | proxy  |                       |          |      |          | f          |                 |                     | t          | {}
 | 2022-03-09 15:24:02        | 2022-03-09 15:24:02        | f                | {}               | f         | uxzhm_Y7k
  2 |      1 |       0 | influxdb | Influx     | proxy  | http://localhost:8086 | root     | root | pgwatch2 | f          |                 |                     | t          | {}
 | 2022-03-09 15:32:31.026755 | 2022-03-09 15:32:31.026755 | f                |                  |           | 0
(2 rows)


My grafana.ini postgres block:

type = postgres
host = 127.0.0.1:5432
name = pgwatch2_grafana
user = pgwatch2_grafana
password = mypassword


  If  you want more info I can replay you.

**Comment by markwort** [comment]
There are usually two databases: one contains the databases that pgwatch2 should monitor, and one contains the metrics themselves.

I believe your pgwatch2 may be writing into a dbname (perhaps `pgwatch2_metrics`) that is different to the dbname that you query in grafana (`pgwatch2_grafana`).

You can add another data source in grafana for the `pgwatch2_metrics` database (if it is called that way).
Perhaps you'll need to rerun the `grafana-dashboards/import_all.sh` script to recreate the dashboards, pointing them to the new data source (the metrics).

**Comment by tengilim** [comment]
Let me show my db name on monitoring server:

postgres=# \l
                                         List of databases
       Name       |      Owner       | Encoding |   Collate   |    Ctype    |   Access privileges
------------------+------------------+----------+-------------+-------------+-----------------------
 pgwatch2         | pgwatch2         | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 pgwatch2_grafana | pgwatch2_grafana | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 pgwatch2_metrics | pgwatch2         | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
   
database tables are:


> 
> ```
> pgwatch2=# \d
>                     List of relations
>   Schema  |          Name          |   Type   |  Owner
> ----------+------------------------+----------+----------
>  pgwatch2 | metric                 | table    | pgwatch2
>  pgwatch2 | metric_attribute       | table    | pgwatch2
>  pgwatch2 | metric_m_id_seq        | sequence | pgwatch2
>  pgwatch2 | monitored_db           | table    | pgwatch2
>  pgwatch2 | monitored_db_md_id_seq | sequence | pgwatch2
>  pgwatch2 | preset_config          | table    | pgwatch2
>  pgwatch2 | schema_version         | table    | pgwatch2
> (7 rows)
> 
> pgwatch2=# \c pgwatch2_metrics
> psql (14.2, server 13.6)
> You are now connected to database "pgwatch2_metrics" as user "postgres".
> pgwatch2_metrics=# \d
>                            List of relations
>  Schema |              Name              |       Type        |  Owner
> --------+--------------------------------+-------------------+----------
>  public | archiver                       | partitioned table | pgwatch2
>  public | backends                       | partitioned table | pgwatch2
>  public | bgwriter                       | partitioned table | pgwatch2
>  public | change_events                  | partitioned table | pgwatch2
>  public | configuration_changes          | partitioned table | pgwatch2
>  public | configured_dbs                 | partitioned table | pgwatch2
>  public | cpu_load                       | partitioned table | pgwatch2
>  public | db_size                        | partitioned table | pgwatch2
>  public | db_stats                       | partitioned table | pgwatch2
>  public | index_changes                  | partitioned table | pgwatch2
>  public | index_stats                    | partitioned table | pgwatch2
>  public | instance_up                    | partitioned table | pgwatch2
>  public | kpi                            | partitioned table | pgwatch2
>  public | locks                          | partitioned table | pgwatch2
>  public | locks_mode                     | partitioned table | pgwatch2
>  public | logical_subscriptions          | partitioned table | pgwatch2
>  public | object_changes                 | partitioned table | pgwatch2
>  public | privilege_changes              | partitioned table | pgwatch2
>  public | psutil_cpu                     | partitioned table | pgwatch2
>  public | psutil_disk                    | partitioned table | pgwatch2
>  public | psutil_disk_io_total           | partitioned table | pgwatch2
>  public | psutil_mem                     | partitioned table | pgwatch2
>  public | recommendations                | partitioned table | pgwatch2
>  public | replication                    | partitioned table | pgwatch2
>  public | replication_slots              | partitioned table | pgwatch2
>  public | sequence_health                | partitioned table | pgwatch2
>  public | server_log_event_counts        | partitioned table | pgwatch2
>  public | settings                       | partitioned table | pgwatch2
>  public | sproc_changes                  | partitioned table | pgwatch2
>  public | sproc_stats                    | partitioned table | pgwatch2
>  public | stat_ssl                       | partitioned table | pgwatch2
>  public | stat_statements                | partitioned table | pgwatch2
>  public | stat_statements_calls          | partitioned table | pgwatch2
>  public | table_bloat_approx_summary_sql | partitioned table | pgwatch2
>  public | table_changes                  | partitioned table | pgwatch2
>  public | table_io_stats                 | partitioned table | pgwatch2
>  public | table_stats                    | partitioned table | pgwatch2
>  public | wal                            | partitioned table | pgwatch2
>  public | wal_receiver                   | partitioned table | pgwatch2
>  public | wal_size                       | partitioned table | pgwatch2
> (40 rows)
> 
> pgwatch2_metrics=# \c pgwatch2_grafana
> psql (14.2, server 13.6)
> You are now connected to database "pgwatch2_grafana" as user "postgres".
> pgwatch2_grafana=# \d
>                             List of relations
>  Schema |               Name                |   Type   |      Owner
> --------+-----------------------------------+----------+------------------
>  public | alert                             | table    | pgwatch2_grafana
>  public | alert_configuration               | table    | pgwatch2_grafana
>  public | alert_configuration_id_seq        | sequence | pgwatch2_grafana
>  public | alert_id_seq                      | sequence | pgwatch2_grafana
>  public | alert_instance                    | table    | pgwatch2_grafana
>  public | alert_notification                | table    | pgwatch2_grafana
>  public | alert_notification_id_seq         | sequence | pgwatch2_grafana
>  public | alert_notification_state          | table    | pgwatch2_grafana
>  public | alert_notification_state_id_seq   | sequence | pgwatch2_grafana
>  public | alert_rule                        | table    | pgwatch2_grafana
>  public | alert_rule_id_seq                 | sequence | pgwatch2_grafana
>  public | alert_rule_tag                    | table    | pgwatch2_grafana
>  public | alert_rule_tag_id_seq             | sequence | pgwatch2_grafana
>  public | alert_rule_version                | table    | pgwatch2_grafana
>  public | alert_rule_version_id_seq         | sequence | pgwatch2_grafana
>  public | annotation                        | table    | pgwatch2_grafana
>  public | annotation_id_seq                 | sequence | pgwatch2_grafana
>  public | annotation_tag                    | table    | pgwatch2_grafana
>  public | annotation_tag_id_seq             | sequence | pgwatch2_grafana
>  public | api_key                           | table    | pgwatch2_grafana
>  public | api_key_id_seq1                   | sequence | pgwatch2_grafana
>  public | builtin_role                      | table    | pgwatch2_grafana
>  public | builtin_role_id_seq               | sequence | pgwatch2_grafana
>  public | cache_data                        | table    | pgwatch2_grafana
>  public | dashboard                         | table    | pgwatch2_grafana
>  public | dashboard_acl                     | table    | pgwatch2_grafana
>  public | dashboard_acl_id_seq              | sequence | pgwatch2_grafana
>  public | dashboard_id_seq1                 | sequence | pgwatch2_grafana
>  public | dashboard_provisioning            | table    | pgwatch2_grafana
>  public | dashboard_provisioning_id_seq1    | sequence | pgwatch2_grafana
>  public | dashboard_snapshot                | table    | pgwatch2_grafana
>  public | dashboard_snapshot_id_seq         | sequence | pgwatch2_grafana
>  public | dashboard_tag                     | table    | pgwatch2_grafana
>  public | dashboard_tag_id_seq              | sequence | pgwatch2_grafana
>  public | dashboard_version                 | table    | pgwatch2_grafana
>  public | dashboard_version_id_seq          | sequence | pgwatch2_grafana
>  public | data_keys                         | table    | pgwatch2_grafana
>  public | data_source                       | table    | pgwatch2_grafana
>  public | data_source_id_seq1               | sequence | pgwatch2_grafana
>  public | kv_store                          | table    | pgwatch2_grafana
>  public | kv_store_id_seq                   | sequence | pgwatch2_grafana
>  public | library_element                   | table    | pgwatch2_grafana
>  public | library_element_connection        | table    | pgwatch2_grafana
>  public | library_element_connection_id_seq | sequence | pgwatch2_grafana
>  public | library_element_id_seq            | sequence | pgwatch2_grafana
>  public | login_attempt                     | table    | pgwatch2_grafana
>  public | login_attempt_id_seq1             | sequence | pgwatch2_grafana
>  public | migration_log                     | table    | pgwatch2_grafana
>  public | migration_log_id_seq              | sequence | pgwatch2_grafana
>  public | ngalert_configuration             | table    | pgwatch2_grafana
>  public | ngalert_configuration_id_seq      | sequence | pgwatch2_grafana
>  public | org                               | table    | pgwatch2_grafana
>  public | org_id_seq                        | sequence | pgwatch2_grafana
>  public | org_user                          | table    | pgwatch2_grafana
>  public | org_user_id_seq                   | sequence | pgwatch2_grafana
>  public | permission                        | table    | pgwatch2_grafana
>  public | permission_id_seq                 | sequence | pgwatch2_grafana
>  public | playlist                          | table    | pgwatch2_grafana
>  public | playlist_id_seq                   | sequence | pgwatch2_grafana
>  public | playlist_item                     | table    | pgwatch2_grafana
>  public | playlist_item_id_seq              | sequence | pgwatch2_grafana
>  public | plugin_setting                    | table    | pgwatch2_grafana
>  public | plugin_setting_id_seq             | sequence | pgwatch2_grafana
>  public | preferences                       | table    | pgwatch2_grafana
>  public | preferences_id_seq                | sequence | pgwatch2_grafana
>  public | query_history                     | table    | pgwatch2_grafana
>  public | query_history_id_seq              | sequence | pgwatch2_grafana
>  public | quota                             | table    | pgwatch2_grafana
>  public | quota_id_seq                      | sequence | pgwatch2_grafana
>  public | role                              | table    | pgwatch2_grafana
>  public | role_id_seq                       | sequence | pgwatch2_grafana
>  public | seed_assignment                   | table    | pgwatch2_grafana
>  public | server_lock                       | table    | pgwatch2_grafana
>  public | server_lock_id_seq                | sequence | pgwatch2_grafana
>  public | session                           | table    | pgwatch2_grafana
>  public | short_url                         | table    | pgwatch2_grafana
>  public | short_url_id_seq                  | sequence | pgwatch2_grafana
>  public | star                              | table    | pgwatch2_grafana
>  public | star_id_seq                       | sequence | pgwatch2_grafana
>  public | tag                               | table    | pgwatch2_grafana
>  public | tag_id_seq                        | sequence | pgwatch2_grafana
>  public | team                              | table    | pgwatch2_grafana
>  public | team_id_seq                       | sequence | pgwatch2_grafana
>  public | team_member                       | table    | pgwatch2_grafana
>  public | team_member_id_seq                | sequence | pgwatch2_grafana
>  public | team_role                         | table    | pgwatch2_grafana
>  public | team_role_id_seq                  | sequence | pgwatch2_grafana
>  public | temp_user                         | table    | pgwatch2_grafana
>  public | temp_user_id_seq1                 | sequence | pgwatch2_grafana
>  public | test_data                         | table    | pgwatch2_grafana
>  public | test_data_id_seq                  | sequence | pgwatch2_grafana
>  public | user                              | table    | pgwatch2_grafana
>  public | user_auth                         | table    | pgwatch2_grafana
>  public | user_auth_id_seq                  | sequence | pgwatch2_grafana
>  public | user_auth_token                   | table    | pgwatch2_grafana
>  public | user_auth_token_id_seq            | sequence | pgwatch2_grafana
>  public | user_id_seq1                      | sequence | pgwatch2_grafana
>  public | user_role                         | table    | pgwatch2_grafana
>  public | user_role_id_seq                  | sequence | pgwatch2_grafana
> 
> 
> ```

which one should i delete?

I run deamon like below:

pgwatch2-daemon   --host=localhost --user=pgwatch2 --dbname=pgwatch2   --datastore=postgres --pg-metric-store-conn-str=postgresql://pgwatch2@localhost:5432/pgwatch2_metrics   --verbose=info

**Comment by markwort** [comment]
Can you please confirm that metrics end up in `pgwatch2_metrics` ? 
If so, you just need to add a new datasource in grafana for this database.

**Comment by tengilim** [comment]
I resolved this problem thank you, I changed datasource ip from localhost to real ip. It was related wrong datasource configs.
