### ISSUE TITLE
Function get_table_bloat_approx_sql fails with division by zero

### ISSUE THREAD

**Issue by FireEmerald** [cybertec-postgresql/pgwatch2#464]
- Function: get_table_bloat_approx_sql
- Code: [pgwatch2/pgwatch2/metrics/00_helpers/get_table_bloat_approx_sql/12/metric.sql](https://github.com/cybertec-postgresql/pgwatch2/blob/0b3c7e63e7e00161b5de72295e59e01c0825437f/pgwatch2/metrics/00_helpers/get_table_bloat_approx_sql/12/metric.sql)
- Error: `ERROR:  division by zero`

**Problem:**

The divisions in these case statements fail when the `tblpages` from the subquery is 0 for some rows of a section of a partitioned table.
https://github.com/cybertec-postgresql/pgwatch2/blob/0b3c7e63e7e00161b5de72295e59e01c0825437f/pgwatch2/metrics/00_helpers/get_table_bloat_approx_sql/12/metric.sql#L30-L45

Sample row of subquery:
```
est_tblpages | est_tblpages_ff | tblpages | fillfactor | bs   | tblid    | schemaname | tblname               | heappages | toastpages | is_na
-3             -3                0          100          8192   17624404   public       partitioned_table_001   0           0            t
```
Table `partitioned_table_001` is a partition of `partitioned_table`.

**Possible fix?**
``` sql
--   v-----new------v
WHEN tblpages > 0 AND tblpages - est_tblpages > 0
    THEN 100 * (tblpages - est_tblpages) / tblpages::float
ELSE 0
END                        AS extra_ratio,
```
Should be added to all three CASES.

**Comment by pashagolub** [comment]
Thanks for your support. We will fix this ASAP.
