### ISSUE TITLE
Limitations, alerts and connections

### ISSUE THREAD

**Issue by mridude23** [cybertec-postgresql/pgwatch2#48]
Hi,

First of all thanks for pgwatch2. We've started working with it 2 months ago and after testing period we decided it's good to go on production servers as well.
We have some questions/issues which I'm not sure if it has to do with pgwatch2 or with Influx/Grafana, but here it goes:
1. Is there some sort of limitation for how many DB's to monitor? 
- we will have something like 14 servers, each with 5-7 databases. For now we set 4 servers with a total of 12 databases. This means for us 38 entries in DB's to monitor for now with multiple Metrics configs (each database type has a different metric config).  LE. Between 1 and 15 metrics for each db.
2. Alerts
- for now we have 73 alerts that are on but unfortunately a lot of the following error pops-up randomly: `Error: Could not find datasource Data source not found ` and of course alerts start to make noise (for me it seems it's losing connections to the InlfuxDB inside the docker).
- working now with 55 alerts on and 18 paused seem to be ok (we also paused DB's to watch); don't know why, maybe you have an idea?
3. Postgres
- on the postgres log inside the docker we can see a lot of the following:
`pgwatch2@pgwatch2_grafana FATAL:  remaining connection slots are reserved for non-replication superuser connections`
- unfortunately did not find anything useful while googling it
- while having all the DB's to watch on (38 entries) the log is quite full of these errors; making 7 of them inactive, thus eliminating a server completely from monitor seems to almost clear the error, at least it shows very rare.
- we increased the `max_connections = 200` and decreased `superuser_reserved_connections = 2` (this was the only thing i could find online) but it's not helping apparently; increasing superuser to 10 for example just floods the log with the same message every second.
Any ideas?
4. Retention policy
- can we change the retention policy to 30 days for example? As far as i can tell it's 90 now right?

Hardware:
Pgwatch2 runs on a dedicated VM with 4 gigs of RAM and 2 cores.

To me it seems that these are some minor changes we might need to do but can't seem to figure it out. Otherwise it runs great, metrics, alerts and so on. 

If there are any details we need to provide, please, let us know.
Thanks again.

**Comment by mridude23** [comment]
Update: 
Even with 29 databases to monitor and 55 alerts the errors are still appearing, both on the alerts and postgres side.

**Comment by kmoppel** [comment]
Hi! Thanks a lot for the feedback and glad that you find it useful! Some comments to your questions:

1. Is there some sort of limitation for how many DB's to monitor?

From the metrics gathering/storing side not really - my laptop (4 core, 16GB RAM) can easily (<10% load) handle 100 Postgres DB-s with "exhaustive" settings (~15 metrics, 60s interval)...so I think it comes down to Grafana...

2. Alerts and "Error: Could not find datasource Data source not found"

Sadly haven't tried to set up more than a couple of alerts for testing...so no real clue what does it really means. Would suggest to surf the Grafana github page...

3. Postgres connections

Indeed...no good reason why max_connection was so low as 15...originally the tool was meant more for ad hoc stuff so I assumed people would use some existing and tuned Postgres setups. Have removed the limitation though now. FYI - changing the config also requires a DB restart to be effective, maybe that was the issue.

4. Retention policy

I've added a new flag "--iretentiondays" to start with a different retention policy. Code is in master only but hoping to release the new Docker version also in 1-2days, currently you need to build the image yourself...

**Comment by mridude23** [comment]
Hi! And thanks for responding.

3. Postgres
- I was changing the wrong `postgresql.conf` unfortunately. I forgot about the `pgwatch_postgresql.conf`  :)
- Removing the limitation seems to have fixed all my issues. Activated all my 38 dbs with 73 alerts and everything seems fine now. I will however increase the number of db's and we'll see how it behaves.

One more question regarding data collection:
I know that we set the metrics to run 60s apart, but what is the reference time from which it calculates those 60s? I mean if you have 100 dbs, some concurrent connections are bound to happen right? The connection is opened and closed after each metric gathering right? I think this was my issue after all.

[Thought] It would be interesting to "schedule" the collector somehow, for example, no more that 10 metrics to be run at the same time, thus making them sequential. Seeing this useful if maybe you have limited resources.

**Comment by kmoppel** [comment]
Good news! Ah yes, currently the postgresql.conf is copied to pgwatch_postgresql.conf, maybe should change that :)

About the "scheduling" - currently yes, connections are closed after gathering the metrics. But from concurrency side it should already be safe - for one monitored DB only one metric query is guaranteed to executed at a time (see MetricsFetcher func in pgwatch2.go for details). If you've managed to observer parallel behaviour this would be a bug :) But then please open a new issue.

And about "reference time" - it would be the first run for a metric for a specific DB. There's no synchronization currently - goroutines are just created for all metrics and then they "fight" for resources.

I think we can close the isse?

**Comment by mridude23** [comment]
Yeah. Issue can be closed as it is was more of question :) 

Thanks for all the input. Good job making pgwatch2. Will be using it extensively for monitoring our servers.
