### ISSUE TITLE
documentation doesn't note stat_activity_wrapper.sql

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#49]
Hello Karel,

as I was wondering why the "sessions" chart (DB overview dashboard) doesn't show any values for my  configured DBs while both pgwatch2 DBs show graphs.
While sneaking through the /pgwatch2/sql/metric_fetching_helpers folder I noticed that there is a new script   stat_activity_wrapper.sql which solves this problem but isn't mentioned in the documentation on the <>Code page.

kind regards 
Georg

**Comment by kmoppel** [comment]
Hmm, I think actually I there's a reference in the [Steps to configure your database for monitoring](  https://github.com/cybertec-postgresql/pgwatch2#steps-to-configure-your-database-for-monitoring) section...but if it could be somehow improved then additional input would be very welcome!

**Comment by georg-h** [comment]
Hello Karel,
You're right. It's there and I've overlooked it because it's above the other both (not all together on one place)
just your 4. script (table_bloat_approx.sql) isn't mentioned explicitly 
I'll close this issue, thx :)
