### ISSUE TITLE
Metric table_bloat_approx_summary_sql fails with Divide by Zero

### ISSUE THREAD

**Issue by dtmdl** [cybertec-postgresql/pgwatch2#491]
Similar to #464 (get_table_bloat_approx_sql), the table_bloat_approx_summary_sql fails with a divide by zero error in some circumstances. I applied the same fix to the postgres 12 metric_su.sql, and it appears to work correctly.

**Comment by dtmdl** [comment]
Still applicable.

**Comment by pashagolub** [comment]
What version is affected? 

Thanks in advance

**Comment by dtmdl** [comment]
I encountered the problem using:

pgwatch2 1.9.0
postgresql 14.4

Not sure if it's limited to those versions, or just a problem with newly-created (empty) databases.

**Comment by dtmdl** [comment]
Still applicable.

**Comment by pashagolub** [comment]
Sorry for delay with answer. Would you please open the pull request with a fix?

Thanks in advance!
