### ISSUE TITLE
Biggest relations treemap no longer working

### ISSUE THREAD

**Issue by dtmdl** [cybertec-postgresql/pgwatch2#496]
I am getting javascript errors (and no data) when trying to view the Biggest relations treemap dashboard.

I assume something has changed in grafana that has broken the svantly-heatmap-panel plugin.

The demo site gives the same problem: https://demo.pgwatch.com/d/c25d66d2f/biggest-relations?orgId=1

<img width="843" alt="image" src="https://user-images.githubusercontent.com/78089781/174839804-728d6931-b4f3-4e9e-a24a-df6eee4d6d95.png">

**Comment by pashagolub** [comment]
Thanks for pointing this out! Seems like the `svantly-heatmap-panel` plugin is deprecated since 2017 and supports only Grafana v3.x

Is it better to replace this dashboard with the built-in [heatmap visualization](https://grafana.com/docs/grafana/latest/visualizations/heatmap/)?

**Comment by dtmdl** [comment]
I tried to re-implement it using the built-in visualization, but my lack of Grafana skills just left me rather confused!

**Comment by dtmdl** [comment]
Still applicable.
