### ISSUE TITLE
Do not prune Postgres error messages

### ISSUE THREAD

**Issue by NikolayS** [cybertec-postgresql/pgwatch2#497]
Had this:

```
2022/06/22 20:54:09 WARN main: Could not find PG version info for DB XXX, skipping shutdown check of metric worker process for wal_count
2022/06/22 20:54:09 WARN main: Could not find PG version info for DB XXX, skipping shutdown check of metric worker process for locks
2022/06/22 20:54:09 WARN main: Could not find PG version info for DB XXX, skipping shutdown check of metric worker process for table_io_stats
```

The problem is that original Postgres error message is not seen here (although it can be found in Postgres logs but it adds troubleshooting complexity; In this particular case, the problem was the lack of SSL=reqire in libpq connection, which is easily fixable).

It looks like the code here (and perhaps in other places) should be adjusted to keep the original PG error message: https://github.com/cybertec-postgresql/pgwatch2/blob/afa52e42a6663b5169483f4bc7f4d615ac86ed2e/pgwatch2/pgwatch2.go#L2152

Similar case: https://github.com/cybertec-postgresql/pgwatch2/issues/465

cc @vitabaks

**Comment by pashagolub** [comment]
Hey, thanks for pointing this out! 

Are there any preceding lines? This one is generated in the main loop already. I'm wondering is there any chance to see "connection refused" or something?

Thanks
