### ISSUE TITLE
Provide ARM docker image

### ISSUE THREAD

**Issue by stheine** [cybertec-postgresql/pgwatch2#502]
Hi,

on docker https://hub.docker.com/r/cybertec/pgwatch2-postgres/tags you're only providing linux/amd64 images.
do you have plans also providing linux/arm64 for running on AWS Graviton ARM?

Regards
  stheine

**Comment by pashagolub** [comment]
I've created a test image for `linux/arm64`. Would you please confirm it works for you?
```
docker pull cybertec/pgwatch2-postgres:arm64
```
Thanks in advance!

**Comment by stheine** [comment]
Hi @pashagolub ,

it works! :)

```
root@pgwatch2:/pgwatch2# ./pgwatch2 --version
3930f01a0e284e56aba6432e2949427e951fb3d9 (2022-07-01T10:26:54+02:00)
```

Regards
  sthein
