### ISSUE TITLE
pgwatch2 using pgbouncer problem

### ISSUE THREAD

**Issue by yinan8128** [cybertec-postgresql/pgwatch2#503]
Hi pgwatch2 team,

As described in [#348](https://github.com/cybertec-postgresql/pgwatch2/issues/348), once we switch pgwatch2 to pgbouncer transaction mode, as pgbouncer transaction mode doesn't support "prepared statement" then caused "pq: unnamed prepared statement" error.

So we switched pgwatch2 to pgbouncer session mode but faced pgbouncer_pools_client_maxwait_seconds too high problem(please check attached image file), this happened in postgresql replication node and there was very low load in the period, so mostly like caused by pgwatch2 using pgbouncer session mode.

![image](https://user-images.githubusercontent.com/71433811/182996363-d4ad8ca1-629c-4ede-ac81-643028ccefe4.png)

Go uses prepared statements by default, how to configure pgx driver not to use prepared statements maybe can check [here](https://medium.com/avitotech/how-to-work-with-postgres-in-go-bad2dabd13e4), could you please help fix it and then can support pgbouncer transaction mode, thanks

**Comment by pashagolub** [comment]
Hello,

Thanks for your request.

pgwatch2 doesn't use `pgx but thanks anyway. Would you add some logs for clarifications? I'm afraid I don't understand the screenshot completely.

Thanks in advance!

**Comment by yinan8128** [comment]
Hello,

Thank you for your reply

pgbouncer_pools_client_maxwait_seconds is a metric of prometheus-pgbouncer-exporter which means "How long the first (oldest) client in queue has waited, in seconds (labels: database, user)", now the metric showed that 120 seconds sometimes

This problem's root caused is using pgbouncer session mode, as pgbouncer transaction mode is much more efficient than pgbouncer session mode, could you please update the driver to support pgbouncer transaction mode please?

**Comment by pashagolub** [comment]
Hey,

We plan to switch to the `pgx` library in the new major version. However, I cannot provide you with any timeline, unfortunately.

Seems like there is no solution I'm aware of for the current `lib/pq` library used.

**Comment by yinan8128** [comment]
@pashagolub 

Thank you for the information, any news for pgwatch2 use `pgx` library please? Thank you

**Comment by pashagolub** [comment]
Yes, we switched to pgx in the dev branch. However it's not public at the moment
