### ISSUE TITLE
PGWatch2 not returning version

### ISSUE THREAD

**Issue by davidnateberg** [cybertec-postgresql/pgwatch2#508]
Hello, I am deploying pgwatch with helm, trying to use two databases, im not sure if thats related to the problem or not. One database is the one that I want metrics from, the other is the one with the `pgwatch2` db and the `pgwatch2_metrics` db. Everything seemed to be going fine with the deployment, except I have no data in the metrics db. The databases initialize successfully, and theres no connection issues with them. The error I'm seeing now is 

```
2022/09/08 12:36:07 WARN main: Could not find PG version info for DB , skipping shutdown check of metric worker process for backends
```
this is happening for all dbs. I tracked down the query its running in the daemon code, and I see its this query 

```
select (regexp_matches(
                        regexp_replace(current_setting('server_version'), '(beta|devel).*', '', 'g'),
                        E'\\\\d+\\\\.?\\\\d+?')
                        )[1]::text as ver, not pg_is_in_recovery() as is_primary
```
https://github.com/cybertec-postgresql/pgwatch2/blob/b27310ca3cb41828a2fca776d0485ad594cb4633/pgwatch2/metrics/test_all_metrics.py

when I run that, it returns nothing. Were running postgres version 12 in RDS. Not sure how to resolve this one. Thanks!

**Comment by archongum** [comment]
Same here, PG 14.4 docker run this project and add PG via localhost:8080

**Comment by pashagolub** [comment]
Would you please show what the result of

```sql
SELECT current_setting('server_version')
```

**Comment by archongum** [comment]
> Would you please show what the result of
> 
> ```sql
> SELECT current_setting('server_version')
> ```

Hold on... Let me deploy over again

**Comment by archongum** [comment]
> Would you please show what is the result of
> 
> ```sql
> SELECT current_setting('server_version')
> ```
14.4 (Debian 14.4-1.pgdg110+1)

Still not working
![image](https://user-images.githubusercontent.com/20929338/190969656-817d7903-3d5e-4baf-b52b-636a38dc43b0.png)

**Comment by pashagolub** [comment]
So just to be sure. Are you saying the metric is not working in the deployment or exactly [test_all_metrics.py](https://github.com/cybertec-postgresql/pgwatch2/blob/b27310ca3cb41828a2fca776d0485ad594cb4633/pgwatch2/metrics/test_all_metrics.py) test script?

**Comment by archongum** [comment]
> > Would you please show what is the result of
> > ```sql
> > SELECT current_setting('server_version')
> > ```
> 
> 14.4 (Debian 14.4-1.pgdg110+1)
> 
> Still not working ![image](https://user-images.githubusercontent.com/20929338/190969656-817d7903-3d5e-4baf-b52b-636a38dc43b0.png)

It works after docker restart container
![image](https://user-images.githubusercontent.com/20929338/190975755-2cf41983-edda-4da5-8eae-34d0c539fe59.png)

**Comment by pashagolub** [comment]
oh gosh. That's weird!

**Comment by davidnateberg** [comment]
So, for me, the metrics not being written to the metrics DB was not related to this warning. Instead I realized that with the helm deployment, if you remove the `databases` key from the `values.yaml` file, in this section

```
databases:
- host: pgwatch2-postgresql
  grafana_preset_metrics: remotedba
  port: 5432
  user: pgwatch2
  password: 'pgwatch2'
  dbs:
    - postgres
    - foo
    - bar
```

because the config map that is responsible for creating the rows in the `monitored_db`'s table with the connection information uses that value. So without it connections dont work. But it's hard to figure out why because, the connection will still pass the connection tests if you have the password set elsewhere.
