### ISSUE TITLE
how to get updates of pgwatch2 when restoring data from backup

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#51]
Hello Karel,

your guide for restoring data from take_backup.sh says that one should rename the databases created by pulling the docker image and to restore the data from pg_dump.
But on this way I would never get changes that you've puplished (saw some scripts changing tables / functions  but I have still the content from my first pull --e.g. pgwatch2/sql/datastore_setup/migrations/ * ) Maybe you've updated some of the dashboards too? 
Is there a way to apply these updates to the existing DBs without loosing my data?

kind regards
Georg

**Comment by kmoppel** [comment]
Yes you're right, the currently described "dump/restore" backup process will update the external components' and pgwatch code but dashboard improvements are not carried over. So basically only option would be the same as mentioned in https://github.com/cybertec-postgresql/pgwatch2/issues/52#issuecomment-359514434 - i.e. creating a new dasboard by loading the contents of the JSON files...don't see a good solution here with dasboards as we also don't want to overwrite any user modified dashboards blindly...

**Comment by kmoppel** [comment]
And yes, also with schema migrations (SQL changes) there's no automatic solution currently...users are expected to roll out the migrations scripts themselves on the old DB when they get errors from the new gatherer daemon version. A solution here could be some special smartness in the daemon that tracks all the changes and rolls them out automatically. All suggestions how to implement it are very welcome. Thanks for the report, will leave the issue open currently as enchancement.

**Comment by dankasak** [comment]
In other projects, I've done this by having a directory for SQL changes ( DDL and DML ), and I name them <sequence>_<descriptive_name>.ddl. Then whenever a new process is launched, it scans this directory, parses out the sequences, sorts them, and compares them against a 'last_executed_sql' value stored in the database. Any items beyond this sequence are executed, and each time one executes successfully, the 'last_executed_sql' value is bumped.

I'm *really* snowed under in other commitments at the moment, but if you like this idea, I can try to implement it for you.

**Comment by kmoppel** [comment]
Idea looks good to me! Would be great to have something like that:) Bear in mind though that now it's possible to run the gatherer also without the central "config DB" i.e. in file based mode, using the --config and --metrics input parameters - see https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/config/instances.yaml for a config sample. Then metrics are just gathered and sent to Influx.

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.
