### ISSUE TITLE
deprecated in cryptography and will be removed in a future release

### ISSUE THREAD

**Issue by shab2** [cybertec-postgresql/pgwatch2#514]
/etc/pgwatch2/webpy/crypto.py:4: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release

**Comment by pashagolub** [comment]
Hello.

We are working on implementing new webui without deprecated dependencies. It supposed to be implemented in the next major version. We have no any timeline yet since there are a lot of changes planned.

Kind regards
