### ISSUE TITLE
update document for the new Helm charts

### ISSUE THREAD

**Issue by finkr** [cybertec-postgresql/pgwatch2#516]
There are two efforts to create a Helm Charts for Kubernetes:

* https://github.com/cybertec-postgresql/pgwatch2/tree/master/helm-chart
and
* https://github.com/cybertec-postgresql/pgwatch2/tree/master/openshift_k8s

Only one of those is documented on https://pgwatch2.readthedocs.io/en/latest/kubernetes.html

**Comment by finkr** [comment]
It would be nice to document the status of each charts somehere (either here or in the readme file  or in the documentation)

**Comment by pashagolub** [comment]
Thanks for your request. We are looking into it! 

Any pull requests are more than welcome!

Kind regards
