### ISSUE TITLE
Metric reco_add_index

### ISSUE THREAD

**Issue by shab2** [cybertec-postgresql/pgwatch2#517]
Hi!
I use 'full' preset_config record for monitoring.
pc_config field dasnt contain metric reco_add_index but when I start pgwatch2-daemon, then I see in log:

```
#022/10/12 16:47:06 INFO GetRecommendations: [DBA13:reco_add_index_ext_qualstats_2.0] Could not execute recommendations SQL: pq: function pg_qualstats_index_advisor() does not exist
#022/10/12 16:47:06 INFO GetRecommendations: [DBA13:reco_add_index] Could not execute recommendations SQL: pq: relation "pg_qualstats_indexes_ddl" does not exist 
```
So, I want undestand where is relation between "full" preset_config record and reco_add_index metric?
Thanks

**Comment by pashagolub** [comment]
Hello.

This metric assumes the `pg_qualstats` extension and superuser or select grants on `pg_qualstats_indexes_ddl` view.
Did you [prepare your database for monitoring](https://pgwatch2.readthedocs.io/en/latest/preparing_databases.html)?

Best regards
