### ISSUE TITLE
What about patroni and etcdv3?

### ISSUE THREAD

**Issue by prorvazz** [cybertec-postgresql/pgwatch2#523]
Now pgwatch2 is support for etcd version 2, can we expect to add support for  etcd version 3?

**Comment by tamil-balasubramani** [comment]
Feature needed for us too,  OKD/Openshift now uses etcd-v3 which makes pqwatch2 unsuable on that environment

**Comment by adiosamig** [comment]
Hi,

Can we also support consul as dcs in patroni monitoring part ?

**Comment by pashagolub** [comment]
Hello, 

thank you for feature requests. This functionality is planned for the next major release for which we still have no deadline yet.

I will let you know when the public beta release with new functionality will be available in this thread.

Of course, you can always propose patch with pull request.

Thanks in advance!
