### ISSUE TITLE
Patroni and etcd v3

### ISSUE THREAD

**Issue by balait4** [cybertec-postgresql/pgwatch2#524]
Hello,

We tried to configure pgwatch2 with the option "dbtype: patroni-continuous-discovery" and getting the below issue. We have postgres cluster is `okd` environment and trying to use the native ETCD which is of vesion etcd v3. Currently version 3 is not support.

Is there any plan to support etcd v3? If so how long it will take for production-ready? Thanks.

```quote
 ERRO EtcdGetClusterMembers: Could not read Patroni scopes from ETCD: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint
```

**Comment by pashagolub** [comment]
Hello. 

We are working on implementing etcd v3 API support. It supposed to be implemented in the next major version. We have no any timeline yet since there are a lot of changes planned. 

Kind regards
