### ISSUE TITLE
Pgwatch2 stops collecting data

### ISSUE THREAD

**Issue by mridude23** [cybertec-postgresql/pgwatch2#53]
Hi again,

Weird things happening on my side. From time to time pgwatch2 just stops collecting data on 1-2 random databases. Checking the logs I could not find anything to help me determine the issue, or maybe I'm not looking at the problem right. The only suspicious thing is this error from pgwatch2 logs: `ERRO DBExecRead: read tcp 172.17.0.2:36978->xx.xx.xx.xx:5432: read: connection reset by peer` , xx.xx.xx.xx being one of my monitored machines. Keep in mind that pgwatch2 is in a different datacenter than some of the servers, but I'm not sure this is actually an issue because I get `No data` on alerts quite often for servers in the same datacenter.
Do you have any idea? I'm not sure what to debug anymore or what to look at.
The collecting only resumes after I restart the docker image, but is not consistent, its possible that on the same server data would not be collected shortly.

Regards.

**Comment by mridude23** [comment]
I restarted the docker image and I'm seeing the following message in the pgwatch2 log:
`CRIT InitAndTestConfigStoreConnection: could not ping configDb! exit. dial tcp 127.0.0.1:5432: getsockopt: connection refused`
`ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: getsockopt: connection refused` 3 times
`CRIT main: Could not initialize InfluxDB Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: getsockopt: connection refused`

Ideas?

**Comment by georg-h** [comment]
@mridude23 the first messages are normal as the databases (internal PG and influx) are down due docker restart and need some time to start. 
Following this thread also your last message should be harmless
http://www.postgresql-archive.org/Incomplete-startup-packet-help-needed-td5199030.html

regarding your initial problem: how is your docker configured? custom bridge0 or default settings?
Especially MTU size could be a show stopper when some of your packages are to big to go through your connections. This could lead to timeouts and maybe also connection closed by peer.
(see https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/ )

regards

**Comment by mridude23** [comment]
@georg-h 
Followed the thread you pointed and in my case is probably referring to pgwatch2 pinging postgres db. 

The docker is configured as default, no changes done by myself. Checking MTU, the default can be found: `mtu 1500 qdisc noqueue state UP group default`. I'll check some more on this MTU size to see if I can improve it somehow.
Thanks for the pointers. We'll update when I find something.

Regards

**Comment by mridude23** [comment]
Update.

So I've come at the conclusion that pgwatch2 just stops collecting data for random databases. If I go into the docker and restart only pgwatch2, it comes online collecting data for all dbs. After some time it just fails on some of them.
@kmoppel  Any ideas what could be the possible root cause? I'm a bit blocked right now.

**Comment by kmoppel** [comment]
@mridude23 ..hmm haven't seen such selective behaviour myself...I've only monitored DB-s in one datacentre also though. 
Could it be possible to compile and run the latest gatherer separately from Docker for some test period with verbose logging (-v flag) turned on? For running the latest daemon also a schema change is needed, see this sql diff file here:
https://github.com/cybertec-postgresql/pgwatch2/commit/257932fa12a9b862ee7d5a034227e351ff570584
I myself suspect Influx...some earlier versions needed restarting time to time, but again haven't seen any problems recently (last 6 months) myself.

**Comment by kmoppel** [comment]
The posted error messages as Georg said correctly are harmless and appear during image startup as there is some randomness involved in startup order - supervisord provides no ordering guarantees there sadly.

**Comment by mridude23** [comment]
@kmoppel Can I change the existing postgres with that schema change or will it have conflicts? I'm thinking of running pgwatch2 outside the docker on the same machine but use the db's in the docker.

**Comment by kmoppel** [comment]
@mridude23 no conflicts, the SQL diffs are meant to be executed on existings setups. very simple schema changes actually. Btw, yesterday one more metric fix was added for "Change detection" so you should also run the other v1.3.0 script if using this functionality.

**Comment by mridude23** [comment]
@kmoppel I managed to start outside of docker in my test env to see if anything is not ok here because I encounter some wierd (grafana I think) stuff. Unfortunately I can't test it on production machines until next week. Until then I can only check in test env and if something is out of ordinary will report back. 
Thanks.

**Comment by mridude23** [comment]
Update:
@kmoppel Pgwatch2 running great outside of docker container. It's been almost one day since it's running like this and every metric runs as expected, data is collected for each and one of them. So it seems everything is ok now. I have no idea why it's having this behaviour. I', gonna leave it until Monday at least to run on verbose mode.

**Comment by kmoppel** [comment]
@mridude23 About "Where do I set so that the webUI shows my new pgwatch2 log? The one from outside the docker."...currently sadly it is not possible to cofigure the logs location outside of Docker...hope to get to it soonish though

**Comment by mridude23** [comment]
Update: 4 days later
@kmoppel Pgwatch2 is still running without a glitch outside the docker. Metrics are collected as  expected, now I have 100 dbs. I'm not sure why it did not work ok in the container, thinking it has something to do with the VM maybe or with the fact that containers are not quite designed to run multiple processes in the same one, although in this case it's much more comfortable. From my point of view the issue can be closed, but maybe an observation in the readme would be ok. I will be running like this for a while but the final endgame is to pull everything out of the docker.

**Comment by kmoppel** [comment]
Thanks for the info @mridude23 ! For long-term setups I would also run it outside of Docker :) There's also a hint on that in the README - "For maximum flexibility, security and update simplicity though, best would to do a custom setup". Cheers

**Comment by pmpetit** [comment]
For your information, i am actually facing this problem (for about 30 instances)

**Comment by kmoppel** [comment]
@pmpetit ok, if this continues my recommendation would be the same - make sure you run the latest gatherer with no connection pooling (--conn-pooling=off) and also log to a file in verbose mode, to be able to track the problem later.

**Comment by pmpetit** [comment]
Hi, thx for feed back
--conn-pooling=off is it an Env variable ? to set in the docker start cmd ?

Thx
