### ISSUE TITLE
xx.xx.xx.xx:8080/dbs  seems invisiable...

### ISSUE THREAD

**Issue by margaretmm** [cybertec-postgresql/pgwatch2#54]
but http://xx.xx.xx.xx:3000/  is visiable,  I am confused...

I run docker this way: docker run -d -p 3000:3000 -p 8080:8080 --name pw2 cybertec/pgwatch2
and my tag is : latest

kind regards @kmoppel

**Comment by margaretmm** [comment]
I checked the docker port, and the 8080 port has been exposed...

            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3000"
                    }
                ],
                "5432/tcp": null,
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ],
                "8086/tcp": null,
                "8088/tcp": null
            },

**Comment by margaretmm** [comment]
my log:

root@51bfa90a23e6:/# tail -n 30  /var/log/supervisor/webpy-stderr---supervisor-uMs2v8.log    
Fatal Python error: getrandom() failed
Fatal Python error: getrandom() failed
Fatal Python error: getrandom() failed
Fatal Python error: getrandom() failed

**Comment by kmoppel** [comment]
@margaretmm wow, some wierd stuff...what platform are you on? I think it has something to do with the Docker host machine...google gave me that for example - https://bugzilla.redhat.com/show_bug.cgi?id=1410175...not much I can do here

**Comment by margaretmm** [comment]
I am in centos VM
