### ISSUE TITLE
ERROR:  could not access file "$libdir/plpython2": No such file or directory

### ISSUE THREAD

**Issue by margaretmm** [cybertec-postgresql/pgwatch2#55]
"CREATE EXTENSION plpythonu;"

I am on windows system , does anyone has plpython2 available??

**Comment by georg-h** [comment]
how have ýou installed PG on windwos? I assume using the graphical installer provided by bigsql?
If I recall correctly a collegue who used this on a test server had to install something like an "extensions" pack after the main installation finished. It's part of the installer but has to be triggered at the end of the first installation round. So maybe you should re-run the installer and check for this

regards
Georg

**Comment by kmoppel** [comment]
Yes, python+windows should be also possible. From googling I understand that one needs to really have some exact Python versions, like 2.7 - https://www.openscg.com/bigsql/docs/proclang/proclang/
Not really a pgwatch2 issue though, thus closing :)
