### ISSUE TITLE
Can't connect to remote Pg instance, and error handling seems wrong

### ISSUE THREAD

**Issue by dankasak** [cybertec-postgresql/pgwatch2#56]
I've tried running the docker image and pointing it to a dev database, and the pgwatch component can't connect. In the logs, I see:

`ERRO main: could not start metric gathering for DB "INT" due to connection problem: failed to set statement_timeout on INT, query not tried`

I see *no* attempt to connect in our postgres logs. I've tried setting the password to an incorrect one ( incorrect passwords are **definitely** logged at our end ), and I don't even see that. So maybe the docker image is set with a weird firewall setup that prevents connecting to external hosts or something? I'm not a docker person.

An additional problem seems to be with error handling. When I look at the source that's throwing the error: [https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/pgwatch2.go#L170](url) ... it seems like something quite bad has happened. The preceding call to GetPostgresDBConnection() is what's failing here - as noted above, I see no attempts to connect. But your error handling is not catching this. I don't know why - I'm also not a Go person.

I've also tried logging into our configured Pg instance with the pgwatch2 user I created, and manually ran the 'SET statement_timeout' command ... there's no problem with I run it from psql ( on the same host as the one running the docker image ).

**Comment by kmoppel** [comment]
Hi! Sad to hear that you're having problems...but hmm...somehow I think something might be still off with the connect string. Can't repeat the problem myself. I can only recommend to try to run the gatherer daemon outside of Docker and see if the connection problems persist...

With the error handling - also...I think it makes some sense already - when already setting the timeout fails, most probably running the query itself would fail so we don't continue (only with the next interval).

**Comment by dankasak** [comment]
Hi. I've done some more sniffing around inside the container, and found that it didn't inherit sane DNS settings, and so couldn't resolve the address I entered for my remote Postgres instance. I made changes to /etc/resolv.conf inside the container, and now it can connect.

What I said about error handling remains - functionally, there is none. You need to catch the connection error ( it would have been something like 'unable to resolve host xxxx' ) and return it. You can test this particular error condition by providing an invalid hostname for a Postgres instance to monitor, and see what it does. Again, I'm not a Go developer ... I can see that there is an attempt at error handling ... but this is clearly not working in this case.

**Comment by kmoppel** [comment]
Ah now I got it. Yes you're right, the original error got masked somehow. Fixed now. In other places it should already be so. Thank for the input!
