### ISSUE TITLE
postgres fails when started with volume

### ISSUE THREAD

**Issue by glookie1** [cybertec-postgresql/pgwatch2#57]
Hello,

If you start the container and use a volume for the postgres data (/var/lib/postgresql) postgres fails to start as it expects some data in that directory.

The pg_createcluster in the Dockerfile will populate the /var/lib/postgresql directory with data. If you want to persist said data with a data mount persistet on disk instead of using a docker volume (eg -v /data/pg:/var/lib/postgresql) postgres will fail to start.

The problem is that in the Dockerfile the `pg_createcluster --locale en_US.UTF-8 9.5 main` is already executed.

To fix this I would suggest adding a check to docker-launcher.sh to check if the directory /var/lib/postgresql/9.5 exists and if it does not trigger the postgresql setup.

```
if [ ! -d /var/lib/postgresql/9.5 ]; then
  pg_createcluster --locale en_US.UTF-8 9.5 main
  cp /pgwatch2/postgresql.conf /etc/postgresql/9.5/main/pgwatch_postgresql.conf
  cp /pgwatch2/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
fi
```

This would also require an edit to the Dockerfile in line 49++ to copy the postgresql.conf & pg_hba to /pgwatch2/ instead of the config directory directly.

https://github.com/cybertec-postgresql/pgwatch2/blob/master/Dockerfile#L6
https://github.com/cybertec-postgresql/pgwatch2/blob/master/Dockerfile#L49

**Comment by kmoppel** [comment]
Hi! Hmm...indeed, when used like that there is a problem. Will include the fix soon. Didn't see it because I created the volumes explicitly. One could use it as workaround here also:
```
for x in pg influx grafana pw2 ; do  docker volume create $x ; done
docker run .... -v pw2:/pgwatch2/persistent-config -v influx:/var/lib/influxdb -v pg:/var/lib/postgresql -v grafana:/var/lib/grafana ...
```

**Comment by kmoppel** [comment]
Fixed in master
