### ISSUE TITLE
[Dashboards] Replace plugin for the Biggest relations treemap dashboard

### ISSUE THREAD

**Issue by kmoppel-cognite** [cybertec-postgresql/pgwatch2#579]
The old [Savantly heatmap](https://grafana.com/grafana/plugins/savantly-heatmap-panel/) doesn't support Grafana 8+. [This](https://grafana.com/grafana/plugins/marcusolsson-treemap-panel/) seems to be a replacement alternative

**Comment by pashagolub** [comment]
Nice! Would you please provide a quick fix?

Kind regards
