### ISSUE TITLE
pgwatch falls behind writing to influx

### ISSUE THREAD

**Issue by dankasak** [cybertec-postgresql/pgwatch2#58]
I've been debugging an issue over the past couple of days, with pgwatch writing to an existing influx instance. The problem simply appears to be that pgwatch can't write to influx fast enough - the queue just keeps getting bigger, until it's full and starts dropping data points. This may be due to many things - eg remote influx instance, busy influx instance, etc.

Ideally, the TODO:
 // TODO batching of mutiple datasets
  ... would be implemented, which should fix things.

Otherwise, it would be good to be able to configure pgwatch to wait N seconds at the end of each polling loop.

_If_ I get time, I'll submit patches ...

**Comment by kmoppel** [comment]
Hi! Yes this TODO would be nice to implement it. Currently I think one needs to re-shuffle quite some code, so have been avoiding it so far as had no performance problems myself.
In your case though - if it's a Influx performance problem (any errors in the logs?) in the end one could adjust the configs to increase the metrics polling intervals...or of course beefing up the hardware.

**Comment by kmoppel** [comment]
I see. Yes with high latency the batching would do good. But to reduce polling intervals (traffic) one can adjust the default 60s intervals to 120 for example on the "/metrics" page in the admin UI. When monitoring many servers I'd though suggest to create a new "preset config" with something like that (based on existing "exhaustive" preset config):

{"wal": 120, "locks": 120, "backends": 120, "bgwriter": 120, "cpu_load": 120, "db_stats": 120, "locks_mode": 120, "index_stats": 120, "replication": 120, "sproc_stats": 120, "table_stats": 120, "change_events": 300, "table_io_stats": 120, "stat_statements": 120, "stat_statements_calls": 120, "table_bloat_approx_summary": 300}

**Comment by dankasak** [comment]
We've already blown these out to anywhere from 300 to 600 seconds, and pgwatch still falls behind by about 1 hour every 3 days. This is only a 'modest' collection of databases - 13.

**Comment by kmoppel** [comment]
Hi @dankasak! Batching is implemented in master now - by default with 250ms delay (use --batching-delay-ms to change or 0 value to disable). Would be great if you find time to try it out:)

**Comment by dankasak** [comment]
Hi @kmoppel ... I've had the current ( ie git ) collector running all day, with a --batching-delay-ms of 5000. It's working great :) Thanks a lot for implementing this.

**Comment by kmoppel** [comment]
Nice @dankasak ! And thanks for the feedback! Btw, I would suggest to update the gatherer code also...just fixed a problem today also with connection pooling...
