### ISSUE TITLE
PgWatch tries to start READ WRITE tx on Standby db

### ISSUE THREAD

**Issue by AnDBAIdewe** [cybertec-postgresql/pgwatch2#583]
PGWatch was recently upgraded to v1.9. Since then, I have problems monitoring stand-by db's, it worked fine before.
In PgWatch log, I get : 
2023/01/10 11:18:56 WARN main: Could not find PG version info for DB misi_prd_FO_misi_prd, skipping shutdown check of metric worker process for psutil_mem
2023/01/10 11:18:56 WARN main: Could not find PG version info for DB misi_prd_FO_misi_prd, skipping shutdown check of metric worker process for index_stats
2023/01/10 11:18:56 WARN main: Could not find PG version info for DB misi_prd_FO_misi_prd, skipping shutdown check of metric worker process for settings
:

In the stand-by db log, I see:
2023-01-10 13:53:35 CET[***.***.be][pgwatch2][misi_prd][pgwatch2]LOG:  statement: BEGIN READ WRITE
2023-01-10 13:53:35 CET[***.***.be][pgwatch2][misi_prd][pgwatch2]ERROR:  cannot set transaction read-write mode during recovery
It looks like PgWatch tries to start a READ WRITE transaction in the stand-by db, which is of course not possible.
Even the BASIC or MINIMAL metrics give the same error.
What did I do wrong?
An

**Comment by AnDBAIdewe** [comment]
I've found the workaround as described in https://github.com/cybertec-postgresql/pgwatch2/issues/520.
Will a fix be provided?

**Comment by pashagolub** [comment]
Hello. 

Would you please provide a pull request with workaround that works for you?

Thanks in advance!

**Comment by AnDBAIdewe** [comment]
We used the workaround as described in https://github.com/cybertec-postgresql/pgwatch2/issues/520. 
roles/pgwatch/templates/docker_compose_pw2.j2 MODIFIED
      - {{ pw2_data_folder }}/postgresql:/var/lib/postgresql
     environment:
       PW2_DATASTORE: "influx"
-      PW2_CONN_POOLING: "on"
+      PW2_CONN_POOLING: "off"
       PW2_VERBOSE: "warn"

 We noticed now it should be fixed in 1.10.0 , so we'll test that version soon.
