### ISSUE TITLE
where is the sybertec sub-directory

### ISSUE THREAD

**Issue by corama** [cybertec-postgresql/pgwatch2#6]
Cannot find the directory of sybertec after downing the zip package and unzip it. Would you please give more details? Thank you.

**Comment by kmoppel** [comment]
Hi! There is no "cybertec" folder, maybe you're confusing it with the Docker image name cybertec/pgwatch2 ? You would first have to install Docker:)

**Comment by kmoppel** [comment]
Closing as no feedback..
