### ISSUE TITLE
what is the usage of the pg  in pgwatch2 ?  thx  :) 

### ISSUE THREAD

**Issue by margaretmm** [cybertec-postgresql/pgwatch2#60]

**Comment by kmoppel** [comment]
@margaretmm Hi! You mean the Postgres DB running in Docker by default? It holds the config on which databases and metrics to monitor :)

**Comment by margaretmm** [comment]
thanks so much

**Comment by margaretmm** [comment]
thank you!

**Comment by kmoppel** [comment]
you're welcome. and to be more accurate - it also holds actually the grafana config also:)
