### ISSUE TITLE
ERRO MetricGathererLoop: Failed to fetch metric data for : pq: invalid input syntax for type integer: "C"

### ISSUE THREAD

**Issue by muhabbad** [cybertec-postgresql/pgwatch2#610]
I have an issue in my pgwatch2 daemon. I configured my instances, configs and metric store db. There was no any issue during the process untill when i saw error log in journalctl output of my pgwatch2 deamon. The output was like below:

> ERRO MetricGathererLoop: Failed to fetch metric data for [host_1:wal]: pq: invalid input syntax for type integer: "C"

Then i went into my metric folder and opened my metric.sql file which located in pgwatch2/metrics/wal/10 folder. And i saw the metric query. It was like below: 

```

1. select /* pgwatch2_generated */
2.   (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
3.   case
4.     when pg_is_in_recovery() = false then
5.       pg_wal_lsn_diff(pg_current_wal_lsn(), '0/0')::int8
6.     else
7.       pg_wal_lsn_diff(pg_last_wal_replay_lsn(), '0/0')::int8
8.     end as xlog_location_b,
9.   case when pg_is_in_recovery() then 1 else 0 end as in_recovery_int,
10.   extract(epoch from (now() - pg_postmaster_start_time()))::int8 as postmaster_uptime_s,
11.   system_identifier::text as tag_sys_id,
12.   case
13.     when pg_is_in_recovery() = false then
14.       ltrim(pg_walfile_name(pg_current_wal_lsn())::char(8), '0')::int
15.     else
16.       (select min_recovery_end_timeline::int from pg_control_recovery())
17.     end as timeline
18. from pg_control_system();

```

Then i executed the query and i get the same error message from my postgresql instance. I realized that the error occurs when the query comes in the 14. line.  

This line  `ltrim(pg_walfile_name(pg_current_wal_lsn())::char(8), '0')::int` gives me the error message. 

I queried my wal file name with this query : `select pg_walfile_name(pg_current_wal_lsn());` and got the result like `0000000C000000000000004E`. The LTRIM function tries to convert the C letter into int type. So, it causes the error message. Could there be a bug in the metric.sql query?

**Comment by pashagolub** [comment]
Hello. Thanks for your request. This bug is fixed by #604
