### ISSUE TITLE
Changing the password to AES-GCM-256 

### ISSUE THREAD

**Issue by ccavallie** [cybertec-postgresql/pgwatch2#623]
Hello,
In the Webui, I have multiple login users and I cannot use the current bulk password storage type change functionality (plain text or aes-gcm-256) which assumes that there is only one user.
Would it be possible to add a selection criterion to this functionality by adding the user as an additional criterion?

**Comment by pashagolub** [comment]
Hello,

this webUI is outdated and won't be updated/fixed/developed. 

We are currently working on a completely new webUI but, unfortunately, cannot provide you with any time frames.
