### ISSUE TITLE
Please do not enable metallb by default

### ISSUE THREAD

**Issue by andyndang** [cybertec-postgresql/pgwatch2#641]
https://github.com/cybertec-postgresql/pgwatch2/blob/26cb0be73c0e7256c31bb1dc2c05bc68858a8636/helm-chart/values.yaml#L206

This broke ALL of our load balancers (thankfully on a dev cluster). But it would be nice if such dangerous options are off by default

**Comment by andyndang** [comment]
re-open

**Comment by pashagolub** [comment]
Would you please provide a pull request addressing this issue?
