### ISSUE TITLE
Password change and AES-GCM-256

### ISSUE THREAD

**Issue by seanzechman** [cybertec-postgresql/pgwatch2#642]
All of our monitored clusters use a separate password and we are automating password changes.  Is there a way to programmatically get the proper encrypted password if we know the PW2_AES_GCM_KEYPHRASE being used so we can update the pgwatch2.monitored_db table directly during a password change of user pgwatch2

**Comment by seanzechman** [comment]
Bump

**Comment by seanzechman** [comment]
> Hello,
> 
> yes, it's possible. You can check how pgwatch2 is doing it [here](https://github.com/cybertec-postgresql/pgwatch2/blob/50a217c09d0a1af213c8d1b4760e78ad579b0b47/pgwatch2/pgwatch2.go#L896-L898)

We saw this but were reluctant to implement something ourselves because if the underlying code changed we would be unaware.  I was wondering if there was some kind of pgwatch2 procedure or function call that could be implemented to generate the encrypted password programmatically?

**Comment by pashagolub** [comment]
This code won't be changed. Pgwatch2 is in maintenance mode and we won't introduce breaking changes anymore. We're working on the next major release
