### ISSUE TITLE
DBs config issue due to proxy settings in docker?

### ISSUE THREAD

**Issue by ced75** [cybertec-postgresql/pgwatch2#65]
Hi,

I have installed the last version of pgwatch2 under a Debian-stretch server.
To achieve installations and compilations, I had to configure docker to pass through my enterprise proxy. This point is OK, since I could install pgwatch2 image correctly.

When I go to the DBs page (http://pgwatch_server:8080/dbs), I get the following error on top of the page:

> ERROR
> The requested URL could not be retrieved
> L'erreur suivante s'est produite en essayant d'accéder à l'URL : http://localhost:8086/query?
> La connexion 127.0.0.1 a échoué.
> Le système a retourné : (111) Connection refused
> L'hôte distant ou le réseau sont peut-être défaillants. Veuillez renouveler votre requête.
> Votre administrateur proxy est postmaster@ign.fr.
> Généré le Wed, 18 Apr 2018 13:12:30 GMT par proxy.ign.fr (squid/2.7.STABLE9)

This means that my pgwatch2 container is passing through the proxy for local http requests.
Here are the pgwatch2 log:

> 2018/04/18 13:08:11 CRIT main: Could not initialize InfluxDB Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused

However, I configured docker to avoid the proxy with local addresses by adding this line in /etc/systemd/system/docker.service.d/http-proxy.conf:
```
[Service]
Environment="HTTP_PROXY=http://proxy.ign.fr:3128/" "NO_PROXY=localhost,127.0.0.1,localhost:8086,127.0.0.1:8086"
```

What did I miss in my configuration?

Thanks in advance for your help.

Regards,
Cedric

**Comment by ced75** [comment]
Problem solved.
I added the following entry in the Dockerfile:
`ENV no_proxy=localhost,127.0.0.1,localaddress,.ign.fr`
I have rebuilt the image, created a new container and there is no more error message.

Sorry for the disturbance.

**Comment by kmoppel** [comment]
@ced75 thanks for the update! good that that it works:)
