### ISSUE TITLE
etcd3 support

### ISSUE THREAD

**Issue by krisavi** [cybertec-postgresql/pgwatch2#665]
Whenever I try to add patroni cluster that is using etcd3, then getting errors like:
```
ERRO extractEtcdScopeMembers: Could not read Patroni members from ETCD for pg-etcd3 scope pg-etcd3: 100: Key not found (/pg/pg-etcd3)
WARN ResolveDatabasesFromPatroni: Failed to get info from DCS for pg-etcd3, using previous member info if any
WARN ResolveDatabasesFromPatroni: No Patroni cluster members found for cluster [pg-etcd3:pg-etcd3]
```

While it works fine for patroni cluster that is using etcd v2.

From the code it seemed that there is only etcd and it is using "go.etcd.io/etcd/client/v2". 
Tried also to set dcs to etcd3, but it seems not to be implemented:
```
ERRO ResolveDatabasesFromPatroni: unknown DCS etcd3
ERRO GetMonitoredDatabasesFromMonitoringConfig: Failed to resolve DBs for "pg-etcd3": unknown DCS
```

**Comment by pashagolub** [comment]
Hello Kris,

etcd3 support is planned to the next major release. We're working hard on it and hope to release a public beta this summer, followed by the official release this fall
