### ISSUE TITLE
Allow statement timeout per metrics

### ISSUE THREAD

**Issue by pashagolub** [cybertec-postgresql/pgwatch2#68]
Right now statement timeout is set per DB. Some of the queries are time consuming, e.g. table bloat, thus having statement timeout per metrics will be great improvement

**Comment by vitabaks** [comment]
> thus having statement timeout per metrics will be great improvement

I completely agree.

```
Jan 24 11:27:41 pw2-28 pgwatch2[13808]: 2019/01/24 11:27:41 ERRO MetricsFetcher: failed to fetch metrics for 'CASSI130_crs', metric 'table_stats': pq: canceling statement due to statement timeout
Jan 24 11:27:46 pw2-28 pgwatch2[13808]: 2019/01/24 11:27:46 ERRO MetricsFetcher: failed to fetch metrics for 'CASSI130_crs', metric 'table_io_stats': pq: canceling statement due to statement timeout
Jan 24 11:27:52 pw2-28 pgwatch2[13808]: 2019/01/24 11:27:52 ERRO MetricsFetcher: failed to fetch metrics for 'CASSI130_crs', metric 'table_rows': pq: canceling statement due to statement timeout
```

**Comment by ZBernard** [comment]
alter user pgwatch2 set statement_timeout = '60 s';

**Comment by kmoppel** [comment]
@ZBernard not exactly the same sadly :) but now this feature can be implemented more easily, there's some infrastructure already in place with v1.6...so in v1.7 hopefully

**Comment by darshansh** [comment]
Hello Kmoppel, 
I have pgwatch2 version 1.5.1 and currently I'm getting error in one metric like below. I see that this query takes 5 sec. to execute using pgadmin. 
Failed to fetch metric data for [dbname_metricname]: pq: canceling statement due to statement timeout
On Postgresql server statement_timeout =0.

**Comment by kmoppel** [comment]
Implemented in master
