### ISSUE TITLE
pgwatch2 doesn't see few database in instance.

### ISSUE THREAD

**Issue by artemsafiyulin** [cybertec-postgresql/pgwatch2#687]
Hello! I installed pgwatch2, using docker. My config file with instances looking like this:
```
- unique_name: "my_hostname"
  dbtype: postgres-continuous-discovery
  host: "my_ip"
  port: 5432
  user: pgwatch2
  password: "my_password"
  sslmode: require
  stmt_timeout: 10
  preset_metrics: exhaustive
  dbname_exclude_pattern: postgres
  is_enabled: true

- unique_name: "my_hostname_dbname"
  dbtype: postgres
  host: "my_ip"
  port: 5432
  dbname: "my_dbname"
  user: pgwatch2
  password: "my_password"
  sslmode: require
  stmt_timeout: 60
  preset_metrics: exhaustive
  is_enabled: true
```

First block must detect all databases, but them don't detect few databases and i can't find any errors in pgwatch2 logs or in postgresql database (other databases detected correctly and metrics collect correctly too).

Second block give me next error in pgwatch log:
```
2023/09/19 09:45:55 WARN main: Could not find PG version info for DB "my_hostname_dbname", skipping shutdown check of metric worker process for vacuum_workers
2023/09/19 10:02:41 WARN MetricGathererLoop: Total fetching time of 28.6s bigger than 10s interval for [my_hostname_dbname:backends]
```

I trying find which code generate this error in repo and i finded this block:
[https://github.com/cybertec-postgresql/pgwatch2/blob/bb34a33b2bf097bab418f8783ed46bdc2b8411f4/pgwatch2/metrics/00_helpers/rollout_helper.py#L55](https://github.com/cybertec-postgresql/pgwatch2/blob/bb34a33b2bf097bab418f8783ed46bdc2b8411f4/pgwatch2/metrics/00_helpers/rollout_helper.py#L55)

when i trying run sql from previous code manually in database, i get empty string, what as i can see in the code generate my error:
```
postgres=# select (regexp_matches(
postgres(#                         regexp_replace(current_setting('server_version'), '(beta|devel).*', '', 'g'),
postgres(#                         E'\\\\d+\\\\.?\\\\d+?')
postgres(#                         )[1]::text as ver, not pg_is_in_recovery() as is_primary
postgres-# ;
 ver | is_primary 
-----+------------
(0 rows)
```

Maybe you will can said me what i doing not correctly?

**Comment by pashagolub** [comment]
Hello.

What is the PostgreSQL version involved?

**Comment by artemsafiyulin** [comment]
Hello! @pashagolub 
```
postgres=# select version();
                                                 version                                                  
----------------------------------------------------------------------------------------------------------
 PostgreSQL 11.21 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
(1 row)

postgres=#
```

**Comment by pashagolub** [comment]
Weird. Can you, please, show the result of `SELECT current_setting('server_version')`

**Comment by artemsafiyulin** [comment]
@pashagolub hello!
```
postgres=# SELECT current_setting('server_version');
 current_setting 
-----------------
 11.21
(1 row)

postgres=#
```

**Comment by pashagolub** [comment]
I've rechecked. Everything should work as expected. Let's return to the first question. Why do you think it's an error if we clearly see it says `WARN`?

**Comment by artemsafiyulin** [comment]
I was found my error. We can close this issue. Thank you!

**Comment by pashagolub** [comment]
What was it? Just to know possible workarounds
