### ISSUE TITLE
same error as #10 - 

### ISSUE THREAD

**Issue by seadba** [cybertec-postgresql/pgwatch2#69]
sorry to re-open ithis isssue - connecing latest pgwatch version to edb results in

edb 9.5.7.12
ERRO DBGetPGVersion: DBGetPGVersion failed pq: invalid input syntax for type double precision: "9.5.7"

edb  9.6.3.8

85ERROR:  invalid input syntax for type double precision: "9.6.3"

**Comment by pashagolub** [comment]
Hello @seadba.

Can you please provide us with 
`SELECT current_setting('server_version')`
output?

Thanks

**Comment by seadba** [comment]
thanks for fast response

edb=# select current_setting('server_version');
 current_setting
-----------------
 9.6.3.8
(1 row)


edb=#  select current_setting('server_version');
 current_setting
-----------------
 9.5.7.12

**Comment by pashagolub** [comment]
Great! Thanks. Can you please provide us with output for this?
```		
select (regexp_matches(
			regexp_replace(current_setting('server_version'), '(beta|devel).*', '', 'g'),
			E'\\d+\\.?\\d+?')
			)[1]::text as ver;
```

**Comment by seadba** [comment]
ver
-----
 9.6
(1 row)


 ver
-----
 9.5

**Comment by seadba** [comment]
is it possible i have the wrong version?

{"grafana": "Version 4.1.2 (commit: v4.1.2)", 
"pgwatch2_git_version": "873cf3a76dd34ace21c560e38955255312b4f19d",
 "influxdb": "InfluxDB v1.2.0 (git: master b7bb7e8359642b6e071735b50ae41f5eb343fd42)",
 "postgres": "PostgreSQL 9.5.6 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit"}

**Comment by seadba** [comment]
sorry, how do you confirm if that is set - i define the var restart the image - the log does not look different

2018/04/24 11:45:48 11:45:48.127 ERRO DBExecRead: pq: invalid input syntax for type double precision: "9.5.7"
2018/04/24 11:45:48 11:45:48.127 ERRO DBGetPGVersion: DBGetPGVersion failed pq: invalid input syntax for type double precision: "9.5.7"
2018/04/24 11:45:48 11:45:48.127 ERRO MetricsFetcher: failed to fetch pg version for  sws96 db_stats pq: invalid input syntax for type double precision: "9.5.7"
2018/04/24 11:45:48 11:45:48.147 ERRO DBExecRead: pq: invalid input syntax for type double precision: "9.5.7"
2018/04/24 11:45:48 11:45:48.148 ERRO DBGetPGVersion: DBGetPGVersion failed pq: invalid input syntax for type double precision: "9.5.7"
2018/04/24 11:45:48 11:45:48.148 ERRO MetricsFetcher: failed to fetch pg version for  sws96 replication pq: invalid input syntax for type double precision: "9.5.7"

**Comment by seadba** [comment]
im very sorry to have wasted your time with this - weve used this for some time and its excllent - i thought i pulled a new image - sorry again - fantastic product

everything looks good now
