### ISSUE TITLE
Instance level metric queried for the each database on multi-DB instance

### ISSUE THREAD

**Issue by markosutic** [cybertec-postgresql/pgwatch2#690]
Hello,

Is it expected that instance-level metric is queried for each database in multi-DB instance configuration?
For example metric `wal_size`:
[https://github.com/cybertec-postgresql/pgwatch2/blob/v1.10.0/pgwatch2/sql/config_store/metric_definitions.sql#L8060](https://github.com/cybertec-postgresql/pgwatch2/blob/v1.10.0/pgwatch2/sql/config_store/metric_definitions.sql#L8060)

```
curl -sSL localhost:9199/metrics | grep 'pgwatch2_wal_size'

pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db1",real_dbname="db1"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db2",real_dbname="db2"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db3",real_dbname="db3"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db4",real_dbname="db4"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db5",real_dbname="db5"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db6",real_dbname="db6"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db7",real_dbname="db7"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db8",real_dbname="db8"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_db9",real_dbname="db9"} 1.682767965e+10 1695640397757
pgwatch2_wal_size_wal_size_b{dbname="pgcluster11_postgres",real_dbname="postgres"} 1.682767965e+10 1695640397757
```

This seems like a bug or unnecessary overhead.

Can you please check.

Thank you

**Comment by pashagolub** [comment]
Hello. 

I suppose you have a per-database configuration with this metrics enabled. How did you create your config?

**Comment by markosutic** [comment]
We are using `postgres-continuous-discovery` as a part of config for monitoring databases. Or you needed different info?

**Comment by pashagolub** [comment]
No, thanks. That's enough. I'll check the configuration thoroughly.

**Comment by pashagolub** [comment]
Would you please provide the part of config used with `postgres-continuous-discovery`? I'm interested in `preset_metrics` and/or `presets`. Thanks in advance!

**Comment by markosutic** [comment]
Sharing required information.
```
md_id                         | 5
md_unique_name                | pgcluster11
md_hostname                   | 127.0.0.1
md_port                       | 6432
md_dbname                     |
md_user                       | pgwatch2
md_is_superuser               | f
md_sslmode                    | disable
md_preset_config_name         | corp_default
md_config                     |
md_is_enabled                 | t
md_last_modified_on           | 2023-08-30 19:16:28.216605+00
md_statement_timeout_seconds  | 5
md_dbtype                     | postgres-continuous-discovery
md_include_pattern            | .*
md_exclude_pattern            | (template0|template1)
md_custom_tags                |
md_group                      | default
md_root_ca_path               |
md_client_cert_path           |
md_client_key_path            |
md_password_type              | plain-text
md_host_config                | {"scope": "pgcluster11", "dcs_type": "consul", "namespace": "/service/", "dcs_endpoints": ["http://localhost:8500"]}
md_only_if_master             | f
md_preset_config_name_standby |
md_config_standby             |
```

```
pc_name             | corp_default
pc_description      | Preset based on exhaustive, just without cpu_load and change_events
pc_config           | {"wal": 55, "locks": 55, "db_size": 300, "archiver": 55, "backends": 55, "bgwriter": 55, "db_stats": 55, "settings": 7200, "stat_ssl": 60, "wal_size": 300, "locks_mode": 55, "index_stats": 900, "replication": 120, "sproc_stats": 180, "table_stats": 300, "wal_receiver": 120, "table_io_stats": 600, "sequence_health": 3600, "stat_statements": 180, "replication_slots": 120, "stat_statements_calls": 55, "table_bloat_approx_sql": 3600, "table_bloat_approx_summary_sql": 3600}
```

**Comment by pashagolub** [comment]
Hello. 

The `pc_config` value is to blame.

`postgres-continuous-discovery` means pgwatch2 will try to find new databases in the cluster and automatically add them with the configuration you specify. You configuration is based on the `exhaustive` template which is quite heavy.

I'd suggest you to reconsider the config. I'd first add the database for a exhaustive monitoring, e.g. `postgres`. And the next step I'd specify the `postgres-continuous-discovery` part with `md_exclude_pattern            | (template0|template1|postgres)`.

This way you'll have a cluster wide metrics from `postgres` and all database specific from other databases. 

Does it make sense?

**Comment by markosutic** [comment]
Hi,

It makes sense - I think mentioned approach would improve our monitoring to become more lightweight.

btw
Can you please explain what is the purpose of the flag `"is_instance_level": true`?
What should happen if you label metric as `is_instance_level`?

I thought, if you specify such flag, metric will be collected only on a single database (`postgres` for example) but maybe I am wrong.

Thank you for the suggestion and info

**Comment by pashagolub** [comment]
According to the manual:

>*is_instance_level*
--
Enables caching, i.e. sharing of metric data between various databases of a single instance to
  reduce load on the monitored server.

This is the property of a metric and should be applied automatically by the gatherer

**Comment by markosutic** [comment]
In other words, it does not restrict the collection of the metric to a single database but rather optimizes the data collection and storage process for metrics that are relevant at the instance level, not just for one specific database.

Thank you for clarification and suggestion how to make monitoring more lightweight in out case.

Best regards,
Marko
