### ISSUE TITLE
can't select DB's in http://localhost:3000

### ISSUE THREAD

**Issue by oberdeha** [cybertec-postgresql/pgwatch2#7]
First of all Thank you for this monitoring system. I've already tested it on "docker run -d -p 3000:3000 -p 8080:8080 --name pw2 cybertec/pgwatch2"

But I try to do it localy from Dockerfile. (by the way there is an error "Step 43 : COPY build_git_version.txt /pgwatch2/build_git_version.txt
lstat build_git_version.txt: no such file or directory
"  I've skipped it)
I have done everything and now can connect to the server, can add DBs but in Grafana http://localhost:3000 I can't select even test DB it's empty

When I select db in http://localhost:8080 and then press show I have this maybe errors
`500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/pgwatch2/webpy/web.py", line 173, in index
    data = pgwatch2_influx.get_db_overview(dbname)
  File "/pgwatch2/webpy/pgwatch2_influx.py", line 86, in get_db_overview
    data['TPS'] = exec_for_time_pairs(tps, dbname, time_pairs)
  File "/pgwatch2/webpy/pgwatch2_influx.py", line 65, in exec_for_time_pairs
    res = influx_query(isql.format(dbname, where_time, group_by_time))
  File "/pgwatch2/webpy/pgwatch2_influx.py", line 33, in influx_query
    return client.query(influxql, params=params)
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 347, in query
    in data.get('results', [])
  File "/usr/local/lib/python3.5/dist-packages/influxdb/client.py", line 346, in <listcomp>
    for result
  File "/usr/local/lib/python3.5/dist-packages/influxdb/resultset.py", line 23, in __init__
    raise InfluxDBClientError(self.error)
influxdb.exceptions.InfluxDBClientError: database not found: pgwatch2`

Could you please help me in my problem.

Thank you for your reply

**Comment by kmoppel** [comment]
Hi, thanks for the report!
The first problem - the file is generated in build.sh script, that's meant to be used for building the image.
The 2nd - I think (not sure) something must have gone wrong with building the image still. The "pgwatch2" database should be created by the data gathering daemon so I suggest taking a look at the error logs at http://0.0.0.0:8080/logs/pgwatch2/200 . For me it currently worked still after a fresh rebuild.
But in that sense yes some better error handling would be nice there, I'll fix it soonish.

**Comment by oberdeha** [comment]
Yes you a right Influx didn't create DB pgwatch2, but postgresql created 
pgwatch2         | pgwatch2 | SQL_ASCII | C       | C     |
 pgwatch2_grafana | pgwatch2 | SQL_ASCII | C       | C     |
Can I manualy create it inside the container? or maybe I need to restart the hole procedure?

skype: doduk333 if you will be able - contakt me. Thanks for your reply

**Comment by oberdeha** [comment]
Please check new version of docker which is launching with the help of this command 

# fetch and run the latest Docker image, exposing Grafana on port 3000 and administrative web UI on 8080
docker run -d -p 3000:3000 -p 8080:8080 --name pw2 cybertec/pgwatch2
In this new version Table details, if set filter for one table it didn't change any views. They are still the same for all filters for this database

In previous version was everything ok. This is new ver because  Replication Tag appeared.

Thanks for your reply

**Comment by kmoppel** [comment]
Thanks for letting now. Could well, be that the custom filter was accidentally removed, re-shuffled the sources a bit there. Will take a look soon.

**Comment by kmoppel** [comment]
Is fixed now with https://github.com/cybertec-postgresql/pgwatch2/commit/b0215cc9ab2fa77844647a2af15a7497b8cf45e8 :) "latest" Docker image also pushed, thanks again @oberdeha !
