### ISSUE TITLE
Problem Installing without Docker

### ISSUE THREAD

**Issue by Elmo8** [cybertec-postgresql/pgwatch2#70]
Hello,

i m fairly new with postgres and pgwatch2 so i would like to ask for some help.
Currently trying to get pgwatch2 to work outside of docker. 
i m stuck though at the last step of your guide where i issue this command: **./pgwatch2 --host=my-postgres-db --user=pgwatch2 --password=xyz  \
    --ihost=my-influx-db --iuser=pgwatch2 --ipassword=xyz**
but nothing happens...
Grafana is up and running, i havent isntalled web.py as i entered my desired monitored DBs in the pgwatch2 database on the monitored_db table and everything else seems to be ok..

**Comment by Elmo8** [comment]
![image](https://user-images.githubusercontent.com/14131080/39356390-9354a472-4a18-11e8-883c-603ab981995a.png)
![image](https://user-images.githubusercontent.com/14131080/39356496-cf740a92-4a18-11e8-9e55-45434466e7c6.png)

As you can see grafana is up and running, but when i try to start the gatherer it does not give a success or error message and i cannot find something wrong in the logs.. please can you give me some hints on this?

**Comment by Elmo8** [comment]
Postgres db is configured to accept connections from this ip and all the needed extensions are loaded also
InfluxDb is also up and running and accepting queries.. i really cannot think of anything else..

**Comment by kmoppel** [comment]
@Elmo8 Hi! I think your issue might be that there is no InfluxDB datasource configured in Grafana...the screen you posted is a dummy one just to show off Grafana features :)
Documentation on adding the datasource - http://docs.grafana.org/features/datasources/influxdb/
Was it the issue?

**Comment by Elmo8** [comment]
Hello @kmoppel.
I know it is a dummy that's why i asked for help since as you can see grafana says the datasource is working
![image](https://user-images.githubusercontent.com/14131080/39390277-d81c2918-4a9a-11e8-8e62-618ac8604efe.png)
and i can see there is data going in the influx db if i query the db on the terminal
![image](https://user-images.githubusercontent.com/14131080/39390290-0ab5be3e-4a9b-11e8-9ff5-d373a29b20ed.png)
The issue is i cannot select any database on the grafana web gui :/

**Comment by Elmo8** [comment]
Finally came to a solution.. in grafana gui where you select the datapoints you have to check the 'default option' so you can see the data visualised.. @kmoppel thanks for the response anyway much appreciated
