### ISSUE TITLE
Seeing lots of errors from missing helper functions in my logs

### ISSUE THREAD

**Issue by tomskopek** [cybertec-postgresql/pgwatch2#701]
I'm seeing loads of pgwatch2 errors in my postgres logs.

Most of these seem to be coming from helper functions which I have not added.

These errors are very long, and occur very frequently, making it difficult to parse my logs.

1. Is there any way to disable these logs?

2. From my understanding, these helper functions are optional. Is that correct? For example, [get_stat_statements()](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/00_helpers/get_stat_statements/9.4/metric.sql) says that beyond version 10, system GRANT can be used instead. Some helpers require plpython3u extension, which I'd rather not add if I can avoid it.

Here is an example of two:

eg:
```console
2023-10-20 18:47:49.539 EDT [140374] pgwatch2@mydb ERROR:  function get_load_average() does not exist at character 286
2023-10-20 18:47:49.539 EDT [140374] pgwatch2@mydb HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2023-10-20 18:47:49.539 EDT [140374] pgwatch2@mydb STATEMENT:  SET lock_timeout TO '100ms';SET statement_timeout TO '5s';
	select
	  (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
	  round(load_1min::numeric, 2)::float as load_1min,
	  round(load_5min::numeric, 2)::float as load_5min,
	  round(load_15min::numeric, 2)::float as load_15min
	from
	  get_load_average();   -- needs the plpythonu proc from "metric_fetching_helpers" folder

2023-10-20 18:47:49.554 EDT [140374] pgwatch2@mydb ERROR:  function get_stat_statements() does not exist at character 1195
2023-10-20 18:47:49.554 EDT [140374] pgwatch2@mydb HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2023-10-20 18:47:49.554 EDT [140374] pgwatch2@mydb STATEMENT:  SET lock_timeout TO '100ms';SET statement_timeout TO '5s';
	WITH q_data AS (
	    SELECT
	        coalesce(queryid::text, 'insufficient-privileges-total') as tag_queryid,
	        /*
	         NB! if security conscious about exposing query texts replace the below expression with a dash ('-') OR
	         use the stat_statements_no_query_text metric instead, created specifically for this use case.
	         */
	        array_to_string(array_agg(DISTINCT quote_ident(pg_get_userbyid(userid))), ',') AS users,
	        sum(s.calls)::int8 AS calls,
	        round(sum(s.total_time)::numeric, 3)::double precision AS total_time,
	        sum(shared_blks_hit)::int8 AS shared_blks_hit,
	        sum(shared_blks_read)::int8 AS shared_blks_read,
	        sum(shared_blks_written)::int8 AS shared_blks_written,
	        sum(shared_blks_dirtied)::int8 AS shared_blks_dirtied,
	        sum(temp_blks_read)::int8 AS temp_blks_read,
	        sum(temp_blks_written)::int8 AS temp_blks_written,
	        round(sum(blk_read_time)::numeric, 3)::double precision AS blk_read_time,
	        round(sum(blk_write_time)::numeric, 3)::double precision AS blk_write_time,
	        max(query::varchar(8000)) AS query
	    FROM
	        get_stat_statements() s
	    ...
            ...
            ...
```

Here are my logging settings (/etc/postgresql/12/main/postgresql.conf):

```
log_destination = 'stderr'
logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%a.log'
log_truncate_on_rotation = on
log_rotation_size = 100MB
log_min_duration_statement = 500
log_duration = off
log_line_prefix = '%m [%p] %q%u@%d '
log_lock_waits = on
log_timezone = 'America/Toronto'
```

Thanks!

**Comment by krisavi** [comment]
One way to lower it would be to disable get_load_average() and get_stat_statements() queries from PgWatch side. Now it depends on the profile you are using. 
https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/preset-configs.yaml
In that one you would need to use preset that does not include cpu_load and stat_statements.

If you are using web-ui to configure presets and databases, then you could either modify existing preset or make a copy and modify new one that will be used in servers you do not wish to make those requests that give errors. In presets config you would have to remove `"stat_statements": 180, ` and `"cpu_load": 60, ` if you happened to make copy of exhaustive preset. 

For stat statements you could also replace `stat_statements` with `stat_statements_no_query_text` to get query timings but no query text, just like the comment in error points towards.

**Comment by tomskopek** [comment]
Thanks for quick reply.

> 1. Add helper functions

 Sorry for stupid question, but what is the recommended approach to installing these functions? It's not clear to me...

I have a database `mydb` running on one droplet A, and a separate droplet B running pgwatch2 via docker which monitors `mydb`.

These commands `psql -f /etc/pgwatch2/metrics/00_helpers/get_stat_activity/$pgver/metric.sql mydb` obviously require the pgwatch2 files. Are they meant to be run where prod db resides (droplet A), or where pgwatch2 resides (droplet B)?

Is it recommended to clone the pgwatch2 repo onto droplet A and run them?

Or should I just manually copy/paste the sql from each function ([eg](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/metrics/00_helpers/get_sequences/10/metric.sql)) into mydb psql session once?

> 2. Disable checks that cause errors due to missing functions

Understood. Thanks!

> 3. Privileged user to make queries as it uses less helper functions

Does it need to be superuser or just given pg_monitor role? My pgwatch2 user has pg_monitor role. But this is not preventing errors. See exerpt from [documentation](https://pgwatch2.readthedocs.io/en/latest/preparing_databases.html#rolling-out-helper-functions:~:text=As%20of%20v1.6.0,the%20file%20name.):

`As of v1.6.0 though helpers are not needed for Postgres-native metrics (e.g. WAL size) if a privileged user (superuser or pg_monitor GRANT) is used ...`

**Comment by pashagolub** [comment]
CPU load is not a Postgres-native metric but system metric

**Comment by pashagolub** [comment]
Execute this to create a CPU helper in droplet A:


```sql
/*  Pre-requisites: PL/Pythonu and "psutil" Python package (e.g. pip install psutil)
    NB! "psutil" is known to behave differently depending on the used version and operating system, so if getting
    errors please adjust to your needs. "psutil" documentation here: https://psutil.readthedocs.io/en/latest/
*/
CREATE EXTENSION IF NOT EXISTS plpython3u; /* NB! "plpython3u" might need changing to "plpythonu" (Python 2) everywhere for older OS-es */

CREATE OR REPLACE FUNCTION get_psutil_cpu(
	OUT cpu_utilization float8, OUT load_1m_norm float8, OUT load_1m float8, OUT load_5m_norm float8, OUT load_5m float8,
    OUT "user" float8, OUT system float8, OUT idle float8, OUT iowait float8, OUT irqs float8, OUT other float8
)
 LANGUAGE plpython3u
AS $FUNCTION$

from os import getloadavg
from psutil import cpu_times_percent, cpu_percent, cpu_count
from threading import Thread

class GetCpuPercentThread(Thread):
    def __init__(self, interval_seconds):
        self.interval_seconds = interval_seconds
        self.cpu_utilization_info = None
        super(GetCpuPercentThread, self).__init__()

    def run(self):
        self.cpu_utilization_info = cpu_percent(self.interval_seconds)

t = GetCpuPercentThread(0.5)
t.start()

ct = cpu_times_percent(0.5)
la = getloadavg()

t.join()

return t.cpu_utilization_info, la[0] / cpu_count(), la[0], la[1] / cpu_count(), la[1], ct.user, ct.system, ct.idle, ct.iowait, ct.irq + ct.softirq, ct.steal + ct.guest + ct.guest_nice

$FUNCTION$;

GRANT EXECUTE ON FUNCTION get_psutil_cpu() TO pgwatch2;
COMMENT ON FUNCTION get_psutil_cpu() IS 'created for pgwatch2';
```

But I assume pgwatch2 already tried and failed. Because you're not allowed to use untrusted language extension on hosting
