### ISSUE TITLE
pgwatch2_.1.11.0_Linux_x86_64.tar.gz has space in extracted directory

### ISSUE THREAD

**Issue by parkerg21** [cybertec-postgresql/pgwatch2#709]
When extracting tar file for the 1.11.0 linux tar, there is a space in the directory that is causing the directory name to be extracted as 'pgwatch2_ 1.11.0_Linux_x86_64'
There are ways to fix this by using --transform flag from tar, but just pointing this out.  Here is subset of listing out contents:

$ tar -tvf pgwatch2_.1.11.0_Linux_x86_64.tar.gz
-rw-r--r-- runner/docker 12944 2023-08-21 05:41 pgwatch2_ 1.11.0_Linux_x86_64/README.md
-rw-r--r-- runner/docker 46593 2023-08-21 05:41 pgwatch2_ 1.11.0_Linux_x86_64/grafana_dashboards/influxdb/v4/aws-cloudwatch/dashboard.json
-rw-r--r-- runner/docker    23 2023-08-21 05:41 pgwatch2_ 1.11.0_Linux_x86_64/grafana_dashboards/influxdb/v4/aws-cloudwatch/title.txt
-rw-r--r-- runner/docker 11826 2023-08-21 05:41 pgwatch2_ 1.11.0_Linux_x86_64/grafana_dashboards/influxdb/v4/biggest-relations/dashboard.json
-rw-r--r-- runner/docker    25 2023-08-21 05:41 pgwatch2_ 1.11.0_Linux_x86_64/grafana_dashboards/influxdb/v4/biggest-relations/title.txt
-rw-r--r-- runner/docker 15757 2023-08-21 05:41 pgwatch2_ 1.11.0_Linux_x86_64/grafana_dashboards/influxdb/v4/change-events/dashboard.json

**Comment by pashagolub** [comment]
Renamed. Thanks for pointing this out. No idea how that dot got there.
