### ISSUE TITLE
Patroni dashboard

### ISSUE THREAD

**Issue by vitabaks** [cybertec-postgresql/pgwatch2#71]
Hi,
Do you have a dashboard to monitoring the Patroni cluster?

Thanks!

**Comment by kmoppel** [comment]
Hi! Currently no out of the box stuff:)...have managed to get by with _patronictl_ and there's a separate pgwatch2 dash for replication lag... but hmm interesting, is there something to display visually? @ants do you maybe have an idea?

**Comment by vitabaks** [comment]
@kmoppel  @ants 

Maybe this example?

```
-- An example of monitoring pgBackRest from within PostgresSQL
--
-- Use copy to export data from the pgBackRest info command into the jsonb
-- type so it can be queried directly by PostgresSQL.

-- Create monitor schema
create schema monitor;

-- Get pgBackRest info in JSON format
create function monitor.pgbackrest_info()
    returns jsonb AS $$
declare
    data jsonb;
begin
    -- Create a temp table to hold the JSON data
    create temp table temp_pgbackrest_data (data jsonb);

    -- Copy data into the table directory from the pgBackRest into command
    copy temp_pgbackrest_data (data)
        from program
            'pgbackrest --output=json info | tr ''\n'' '' ''' (format text);

    select temp_pgbackrest_data.data
      into data
      from temp_pgbackrest_data;

    drop table temp_pgbackrest_data;

    return data;
end $$ language plpgsql;
```

```
-- Get last successful backup for each stanza
--
-- Requires the monitor.pgbackrest_info function.
with stanza as
(
    select data->'name' as name,
           data->'backup'->(
               jsonb_array_length(data->'backup') - 1) as last_backup,
           data->'archive'->(
               jsonb_array_length(data->'archive') - 1) as current_archive
      from jsonb_array_elements(monitor.pgbackrest_info()) as data
)
select name,
       to_timestamp(
           (last_backup->'timestamp'->>'stop')::numeric) as last_successful_backup,
       current_archive->>'max' as last_archived_wal
  from stanza;
```
https://pgbackrest.org/user-guide.html#monitor

**Comment by kmoppel** [comment]
Ah now I get what you mean @vitabaks :) Basically yes we could have a PL/Pythonu procedure that queries the Patroni API for health and member info (similar to patronictl) and we could display it as a table for example. The downside though would be the architectural waek spot of getting cluster info from one of the members of the cluster.

Better approach would be even maybe to add some code to the gatherer daemon so that it communicates directly with Patroni API and then additionally maybe with master DB also and stores the info into Influx for flexible display. What do you think?

**Comment by vitabaks** [comment]
@kmoppel 
> "...add some code to the gatherer daemon" "...and stores the info into Influx".

I think this is a good option.

**Comment by vitabaks** [comment]
https://github.com/cybertec-postgresql/pgwatch2#patroni-usage

> v1.6.0

Thanks!
