### ISSUE TITLE
pgwatch2 retention does not purge old data based on setting of PW2_PG_RETENTION_DAYS

### ISSUE THREAD

**Issue by jiangjcsnapon** [cybertec-postgresql/pgwatch2#714]
We monitored the space usage of pgwatch2. We were close to running out of space in postgres cluster where pgwatch2 metrics is located. We changed the retention parameter PW2_PG_RETENTION_DAYS=7 and restart the service. We still see old data in metrics tables and no space was relieved.

How do we know when the purge is executed? 

can pgwatch2.service be started in debug mode to give us more information on wat is going on?

Is there a programmatic way to manually purge the old data?

**Comment by pashagolub** [comment]
One more notice. To reduce distracting log messages at startup pgwatch2 will actually start old data purging [1h after the start](https://github.com/cybertec-postgresql/pgwatch2/blob/9db408989ebd7e6bce9dc3464756e187cad386a5/pgwatch2/pgwatch2.go#L1309C31-L1309C76) and then [every 12h](https://github.com/cybertec-postgresql/pgwatch2/blob/9db408989ebd7e6bce9dc3464756e187cad386a5/pgwatch2/pgwatch2.go#L1354).

**Comment by jiangjcsnapon** [comment]
Thank you so much for your quick response! The cluster went down running out of space less an hour after I started the cluster and changed the retention. We just had more space added. I've started the cluster again. I will check space tomorrow since the purge starts 1 hour after the restart.

**Comment by pashagolub** [comment]
Please, feel free to close the issue if everything is working as expected on your side.

**Comment by jiangjcsnapon** [comment]
I searched "starting old Postgres metrics cleanup job" in log file and found nothing. Old data is not purged either.

**Comment by jiangjcsnapon** [comment]
I restarted pgwatch2.service again and we have these errors in the log. Not how to troubleshoot the errors.

Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]: 2023/11/28 13:01:44 ERRO ParseMetricAttrsFromString: Unmarshaling error: yaml: unmarshal errors:
Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]:  line 1: cannot unmarshal !!str `false` into bool
Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]: 2023/11/28 13:01:44 ERRO ParseMetricAttrsFromString: Unmarshaling error: yaml: unmarshal errors:
Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]:  line 1: cannot unmarshal !!str `false` into bool
Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]: 2023/11/28 13:01:44 ERRO ParseMetricAttrsFromString: Unmarshaling error: yaml: unmarshal errors:
Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]:  line 1: cannot unmarshal !!str `false` into bool
Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]: 2023/11/28 13:01:44 ERRO ParseMetricAttrsFromString: Unmarshaling error: yaml: unmarshal errors:
Nov 28 13:01:44 aws-adm-400-pv pgwatch2-daemon[2349897]:  line 1: cannot unmarshal !!str `false` into bool

**Comment by jiangjcsnapon** [comment]
Manual purge failed as well.

pgwatch2_metrics=# SELECT admin.drop_old_time_partitions(older_than_days => 7);
ERROR:  column "l_schema_type" does not exist
LINE 1: l_schema_type
        ^
QUERY:  l_schema_type
CONTEXT:  PL/pgSQL function admin.drop_old_time_partitions(integer,boolean,text) line 100 at RAISE

**Comment by jiangjcsnapon** [comment]
This is what's in our configuration.

pgwatch2_metrics=# select  schema_type FROM admin.storage_schema_type;
 schema_type
-------------
 metric
(1 row)

The schema_type is metric.  But function admin.drop_old_time_partitions only handles 

IF schema_type IN ('metric-time', 'metric-dbname-time') THEN  
...
ELSEIF schema_type = 'timescale' THEN 
...
ELSE                                                                                                                                                                    +|
       raise warning 'unsupported schema type: %', l_schema_type;
ENDIF

**Comment by pashagolub** [comment]
> Should we see more rows/old_time_partitions if I want to purge data manually?
> 
> ```
> postgres=# \c pgwatch2_metrics
> You are now connected to database "pgwatch2_metrics" as user "postgres".
> pgwatch2_metrics=# SELECT count(*) FROM information_schema.routines WHERE routine_schema = 'admin' AND routine_name = 'get_old_time_partitions';
>  count
> -------
>      1
> (1 row)
> ```

This doesn't make any sense to me. You're asking about **partitions** and then selecting the **number of stored routines**?

**Comment by pashagolub** [comment]
> This is what's in our configuration.
> 
> ```
> pgwatch2_metrics=# select  schema_type FROM admin.storage_schema_type;
>  schema_type
> -------------
>  metric
> (1 row)
> ```

For the `metric` schema type daemon will call [DeleteOldPostgresMetrics()](https://github.com/cybertec-postgresql/pgwatch2/blob/9db408989ebd7e6bce9dc3464756e187cad386a5/pgwatch2/pgwatch2.go#L1358) function. There is no possibility to purge data calling any SQL function.

Why did you choose `metric` schema type instead default `metric-time`?

**Comment by jiangjcsnapon** [comment]
I was not sure why metric schema type was chosen in our environment. After reading pgwatch2 documents, I am thinking the best option for us is to change the schema type to metric-time.

I will probably blow out the cluster and start from scratch with metric-time schema type.

**Comment by pashagolub** [comment]
> I will probably blow out the cluster and start from scratch with metric-time schema type.

Yes, the would be the best solution right now. Seems like there are some issues we cannot discover at the moment

**Comment by jiangjcsnapon** [comment]
We reconfigured pgwatch2 and changed the schema type to metric-time.  pgwatch2 started to collect data on 11/28/2023. We have the retention set to 7 days. 

[Service]
Environment="PW2_PGHOST=xxxxxx"
Environment="PW2_PGUSER=pgwatch2"
Environment="PW2_PGPASSWORD=*******"
Environment="PW2_PGDATABASE=pgwatch2"
Environment="PW2_DATASTORE=postgres"
Environment="PW2_PG_METRIC_STORE_CONN_STR=postgresql://pgwatch2:*****@<server_name>:5432/pgwatch2_metrics"
Environment="PW2_AES_GCM_KEYPHRASE=DBATEAMENCRYPT"
Environment="PW2_PG_RETENTION_DAYS=7"

It has been almost 2 weeks. I do see new partitioned table created but I do not see any sign of data purging. 

If data purge works the old partition of week48 should be deleted by now. Isnlt that right?
postgres=# \c pgwatch2_metrics
You are now connected to database "pgwatch2_metrics" as user "postgres".
pgwatch2_metrics=# select min(time) from subpartitions.table_io_stats_y2023w49;
              min
-------------------------------
 2023-12-04 00:44:25.972988+00
(1 row)

pgwatch2_metrics=# select min(time) from subpartitions.table_io_stats_y2023w48;
              min
-------------------------------
 2023-11-28 17:01:05.740771+00
(1 row)

**Comment by pashagolub** [comment]
Hello. Are still facing the issue?
