### ISSUE TITLE
How to wipe inactive or old DB entries in dbName dropdown list

### ISSUE THREAD

**Issue by Elmo8** [cybertec-postgresql/pgwatch2#72]
Helloo,
 
i m trying to figure out how to make the old entries in the dnName dropdown list in grafana, go away.

I've reset  the sequence in the monitored_dbs table and i have only 2 entries there, i dropped the measurements from pgwatch influx db restarted the services but i cannot get rid of the old deleted entries of monitored dbs..
![image](https://user-images.githubusercontent.com/14131080/40417059-8b60d7f8-5e87-11e8-9818-c68146501dcd.png)
As you can see there are 5 entries there but in my monitored_db table there are only 2 entries.

Thanks in advance

**Comment by kmoppel** [comment]
Hi!
The data for previously monitored DBs can be wiped from the Web UI - see here: https://raw.githubusercontent.com/cybertec-postgresql/pgwatch2/master/screenshots/web_ui_dbs.png
Or also just manually from InfluxDB for all (which is more work though): https://docs.influxdata.com/influxdb/v1.5/query_language/database_management/#drop-series-from-the-index-with-drop-series
