### ISSUE TITLE
Problem with PGWATCH2-WEBUI service

### ISSUE THREAD

**Issue by franxav06** [cybertec-postgresql/pgwatch2#720]
Good morning
I have a last problem to solve in order to have everything working perfectly :
When I start manually the  pgwatch2-webui service from /etc/pgwatch2/webpy I have no problems, but If I try to start it as a service with the command line systemctl start pgwatch2-webui I have the following error     :

`Nov 16 13:10:32 lpdbmgr01.cloud.ccc-ggc.brussels python3.10[3926243]: Traceback (most recent call last):
Nov 16 13:10:32 lpdbmgr01.cloud.ccc-ggc.brussels python3.10[3926243]:   File "/etc/pgwatch2/webpy/web.py", line 9, in <module>
Nov 16 13:10:32 lpdbmgr01.cloud.ccc-ggc.brussels python3.10[3926243]:     import cherrypy
Nov 16 13:10:32 lpdbmgr01.cloud.ccc-ggc.brussels python3.10[3926243]: ModuleNotFoundError: No module named 'cherrypy'` 

Thanks in advance for your help

**Comment by pashagolub** [comment]
Is that possible you have several versions of Python installed in the system?

Does this help?
```sh
/etc/pgwatch2/webpy> python3.10 -m pip install -r requirements.txt
```
