### ISSUE TITLE
Grafana panels doesnt see  pq: relations

### ISSUE THREAD

**Issue by gsl23** [cybertec-postgresql/pgwatch2#733]
Hello !  Pls help 

I've installed pgwatch2 
 /usr/bin/pgwatch2-daemon --version
5f7377084446c7f08b860cbb7f93acc31ef4966f (2023-12-28T10:28:20Z)
with postgres 15 and timescaledb plugin for pgwatch2_metrics storage schema.
Then i've added pgwatch2_metrics  datasource to Grafana and imported dashbords with jsons from /etc/pgwatch2/grafana-dashboards/postgres/
Most of it isn't working with errors like  :  db query error: pq: relation "wal" does not exist  ( from Db Overview - Instance stats, for example ). 
I've checked pg tables and haven't  found required relations. What i did wrong ? 

![pg_VKC2B6rWU1](https://github.com/cybertec-postgresql/pgwatch2/assets/47783145/e8ffffc3-0887-4db4-8843-c0dbf35ae07a)

**Comment by pashagolub** [comment]
Did you actually started pgwatch gatherer? The gatherer will create all those tables automatically

**Comment by gsl23** [comment]
Yes , and without any errors in journal 
( To good to be true , I thought :)

# systemctl status pgwatch2
● pgwatch2.service - Pgwatch2 Gathering Daemon
   Loaded: loaded (/etc/systemd/system/pgwatch2.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2024-01-15 18:00:51 +05; 3 days ago
 Main PID: 23896 (pgwatch2-daemon)
    Tasks: 7 (limit: 22974)
   Memory: 26.4M
   CGroup: /system.slice/pgwatch2.service
           └─23896 /usr/bin/pgwatch2-daemon -c /etc/pgwatch2/config/instances.yaml -m /etc/pgwatch2/metrics --datastore=postgres --pg-metric-store-conn-str=postgresql://pgwatch2@localhost:5432/pgwatch2_me>

Jan 15 18:00:51 pgwatch-app-p01 systemd[1]: Starting Pgwatch2 Gathering Daemon...
Jan 15 18:00:51 pgwatch-app-p01 systemd[1]: Started Pgwatch2 Gathering Daemon.
# ps -ef | grep pgwatch2
root       23896       1  0 Jan15 ?        00:09:38 /usr/bin/pgwatch2-daemon -c /etc/pgwatch2/config/instances.yaml -m /etc/pgwatch2/metrics --datastore=postgres --pg-metric-store-conn-str=postgresql://pgwatch2@localhost:5432/pgwatch2_metrics --pg-retention-days=31
postgres   54189   20591  0 Jan17 ?        00:00:01 postgres: pgwatch2 pgwatch2_metrics ::1(59610) idle
postgres   67148   20591  0 14:46 ?        00:00:00 postgres: postgres pgwatch2_metrics 192.168.201.6(55878) idle
postgres   67954   20591  0 15:43 ?        00:00:00 postgres: pgwatch2 pgwatch2_metrics 172.16.0.223(51236) idle
postgres   68630   20591  0 16:47 ?        00:00:00 postgres: pgwatch2 pgwatch2_metrics 172.16.0.223(43722) idle
postgres   68631   20591  0 16:47 ?        00:00:00 postgres: pgwatch2 pgwatch2_metrics 172.16.0.223(43724) idle
postgres   68635   20591  0 16:47 ?        00:00:00 postgres: pgwatch2 pgwatch2_metrics 172.16.0.223(43726) idle
postgres   68665   20591  0 16:50 ?        00:00:00 postgres: postgres pgwatch2_metrics 192.168.201.6(60187) idle
root       69887   68751  0 18:33 pts/3    00:00:00 grep --color=auto pgwatch2

**Comment by pashagolub** [comment]
ok, I see `kpi` and `configured_dbs` are created. These are certainly metric storage tables.

Maybe your `instances.yaml` has only these 2 metrics enabled? 

Storage tables are created only for active metrics. Meaning if you don't monitor `wal`, gatherer won't create a table for it

**Comment by gsl23** [comment]
Hmm, i've added db (localhost db pgwatch2) via direct inserts into the Config DB pgwatch2.monitored_db table, with md_preset_config_name = full. Now I've checked instances.yaml and saw than same local DB added with preset_metrics: minimal. 
Is it mean that instances.yaml has more priority than pgwatch2.monitored_db table and solution is just to remove DB from instances.yaml ?

**Comment by gsl23** [comment]
I've tried to remove DB from instances.yaml  and restarted daemon. It looks like daemon doest use pgwatch2.monitored_db table
```
$ systemctl restart pgwatch2
$ systemctl status pgwatch2
● pgwatch2.service - Pgwatch2 Gathering Daemon
   Loaded: loaded (/etc/systemd/system/pgwatch2.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2024-01-19 11:24:22 +05; 7s ago
 Main PID: 80667 (pgwatch2-daemon)
    Tasks: 6 (limit: 22974)
   Memory: 7.5M
   CGroup: /system.slice/pgwatch2.service
           └─80667 /usr/bin/pgwatch2-daemon -c /etc/pgwatch2/config/instances.yaml -m /etc/pgwatch2/metrics --datastore=postgres --pg-metric-store-conn-str=postgresql://pgwatch2@localhost:5432/pgwatch2_me>

Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 INFO InitAndTestMetricStoreConnection: connect to metricDb OK!
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 INFO main: starting PostgresPersister...
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 INFO main: starting UniqueDbnamesListingMaintainer...
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 INFO main: starting old Postgres metrics cleanup job...
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 INFO ReadMetricsFromFolder: Searching for metrics from path /etc/pgwatch2/metrics ...
Jan 19 11:24:22 pgwatch-app-p01 systemd[1]: Started Pgwatch2 Gathering Daemon.
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 INFO ReadPresetMetricsConfigFromFolder: Reading preset metric config from path /etc/pgwatch2/metrics/preset-configs.yaml ...
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 INFO ReadPresetMetricsConfigFromFolder: 17 preset metric definitions found
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 WARN ConfigFileToMonitoredDatabases: Could not find any valid monitoring configs from file: /etc/pgwatch2/config/instances.yaml
Jan 19 11:24:22 pgwatch-app-p01 pgwatch2-daemon[80667]: 2024/01/19 11:24:22 WARN main: host info refreshed, nr. of enabled entries in configuration: 0, nr. of distinct metrics: 73
```

**Comment by pashagolub** [comment]
You can use either config file, or config database afair

**Comment by gsl23** [comment]
Thanks Pavel
