### ISSUE TITLE
rollout_helper.py usage of yaml.load deprecated 

### ISSUE THREAD

**Issue by AndrewJackson2020** [cybertec-postgresql/pgwatch2#738]
As in the title the usage of yaml.load is deprecated in the rollout_helper.py file. Currently raises a warning but should be an easy one line fix although there are a number of ways to fix it. See link below for more information on the deprecation. Happy to submit a PR later.

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

```
./pgwatch2/metrics/00_helpers/rollout_helper.py --config-path ./pgwatch2/config/ --mode yaml-all
>> starting in DRY-RUN mode, add --confirm to execute
>> /root/repos/public/pgwatch2/./pgwatch2/metrics/00_helpers/rollout_helper.py:203: YAMLLoadWarning: calling yaml.load() without >>Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>>  monitored_dbs = yaml.load(config)
>> *** ROLLOUT TO TARGET DB-s ***
>> DB #0: [test1] failed to determine pg version for localhost@5432, skipping rollout
```

**Comment by pashagolub** [comment]
Thanks. Please feel free to contribute a fix.

Thanks in advance!
