### ISSUE TITLE
could not start metric gathering for DB "gp12" due to connection problem: pq: database "gp12" does not exist

### ISSUE THREAD

**Issue by diaowenyang** [cybertec-postgresql/pgwatch2#74]
HI:
   my steps:
   1.docker pull cybertec/pgwatch2
   2.docker run -d -p 3000:3000 -p 28080:8080 --name pw2 cybertec/pgwatch2 
   3.add dbs in  http://10.129.84.13:28080/dbs
 
   I am sure to add correct dbs,and it can be conneted by Navicat.
   But pgwatch2 conneted error:"Could not connect to specified host: FATAL: database "testgp08" does not exist".
   
![_20180603093418](https://user-images.githubusercontent.com/18416111/40882343-a738eb2c-6711-11e8-9bb0-507afe18bb67.png)
![10 129 84 13_28080_logs_pgwatch2_200 ipad pro](https://user-images.githubusercontent.com/18416111/40882348-b97d3f54-6711-11e8-8b5c-323326bc3e98.png)

**Comment by kmoppel** [comment]
Hi, thanks for reporting! Though I looked in the code and am 99% sure that it's a configuration (no privileges or monitored database was not really there at that time) issue - the error "could not connect to database X" comes directly from the driver. If you still get that issue please try to run again by building the latest docker image or running directly the Go gatherer in verbose mode (-v). Closing for now.
