### ISSUE TITLE
stat activity (not realtime) :  ID still present in json file (not importable)

### ISSUE THREAD

**Issue by jcarnu** [cybertec-postgresql/pgwatch2#741]
Hello,

In pgwatch2_1.11.0 debian package, the [stat activity dashboad file](https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/postgres/v8/stat-activity/dashboard.json#L27)  still contains `  "id": 1697`   which leads to error when loading with curl.

I had to ` sed`   it to get rid of the error:

~~~bash
curl --user admin:<redacted> -X POST -H "Content-Type: application/json;charset=UTF-8"   \
       --data-binary "{\"dashboard\": $(cat /etc/pgwatch2/grafana-dashboards/postgres/v8/stat-activity/dashboard.json|\
                                       sed -e 's/1697/null/g')}"   \
http://localhost:3000/api/dashboards/import
~~~

There may be other way to do, but I do think this id should be removed from the json file.

**Comment by pashagolub** [comment]
Thanks for pointing this out! PRs are welcome!
