### ISSUE TITLE
when adding pgwatch2 to monitor db xact_rollback start to increase

### ISSUE THREAD

**Issue by lukyanovbox** [cybertec-postgresql/pgwatch2#752]
After start  pw2 i noticed almost immediate xact_rollback increase. When i stop pw2 xact_rollback staying the same. 

I tried to set log_statement = 'all' but didnt find exact ROLLBACK entries so far.

Can i fix it with some setting?

**Comment by pashagolub** [comment]
We never heard of such behavior. Any pgwatch log showing errors/warnings?
