### ISSUE TITLE
Web UI - access under password future broken

### ISSUE THREAD

**Issue by xgoos** [cybertec-postgresql/pgwatch2#76]
Hallo.
   If I read all well, there is missing directive in file pgwatch2/webpy/web.py. I think that there has to be

"@logged_in"

on line 209

**Comment by kmoppel** [comment]
Hi @xgoos, thanks for thinking along! Currently though actually it is so "per design" - the idea is that some general performance information would be still visible and only changing montitoring config would require login. Not sure if it's worth another runtime parameter? Mostly pgwatch2 is deployed in safe environments or for ad-hoc troubleshooting where 100% tight security is not required. But if you provide a PR for example, would be happy to include it:)

```parser.add_argument('--no-anonymous-access', help='If set, login is required to configure monitoring/metrics',```

https://github.com/cybertec-postgresql/pgwatch2/blob/master/webpy/web.py#L267

**Comment by vitabaks** [comment]
@kmoppel 
Hi!
My pgwatch2 web ui is available to everyone!
How to enable authorization for /dbs and /metrics

**Comment by kmoppel** [comment]
Hi @vitabaks ! Yes by default there's no security - a safe / internal network assumed:) So if that's not the case there are some options:
1) use "docker run"-s  --network flag to expose ports on a safe network 
2) Don't expose the Web UI port in docker and add the monitored DBs directly from container via Postgres directly  
3) Use the PW2_WEBNOANONYMOUS / PW2_WEBUSER / PW2_WEBPASSWORD / PW2_WEBSSL flags to use SSL and a custom login

**Comment by vitabaks** [comment]
@kmoppel 
It is working for me:

/usr/bin/python3 /var/lib/pgwatch2/webpy/web.py --no-anonymous-access --admin-user admin --admin-password AdminPass --no-component-logs

I should have read the help (web.py --help) ...

Thank you for pgwatch2!
