### ISSUE TITLE
pgwatch2 1.12.0: periodically msg "WARN: main: Could not find PG version info for DB XXX, skipping ..." when monitoring aurora databases

### ISSUE THREAD

**Issue by jjamor** [cybertec-postgresql/pgwatch2#764]
Hello,

We have pgwatch2 1.12..0 monitoring several AWS (aurora), Azure and on-prem postgres databases.

Periodically, some aurora DBs stop being monitored with the given log in pgwatch2:

"WARN: main: Could not find PG version info for DB XXX, skipping ..."

This is recovered when restarting pgwatch2.

We are upgrading from pgwatch2 1.8.5, and this issue occurs only with the latest 1.12.0, with the same configuration.

Is this a known error in 1.12.0?

Many thanks in advance.

**Comment by jjamor** [comment]
It happens randomly with AWS aurora databases.

When the error occurs,, if I try to manually open a connection from the same machine (using psql client, for example), the connection can be establihshed without problems. Also, the error is fixed after restarting pgwatch2.

Is there a way to force a reconnection when the current connection is lost, without restarting pgwatch2?

Thanks!

**Comment by pashagolub** [comment]
What are the database name(s) of affected sources?
There is no connection loss. There is an absence of version (meta) information about the monitored databases.

**Comment by pashagolub** [comment]
And what are `select version()` results?

**Comment by jjamor** [comment]
Hello, sorry for the delay,

The problem happens randomly with AWS Aurora databases, it is fixed only by restarting pgwatch2 daemon. When a monitored database does not respond to pgwatch2, I can however connect to it with psql and show version:

`select version();
                                                   version
-------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.6 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 7.4.0, 64-bit`
