### ISSUE TITLE
cybertech logo broken link on Grafana dashboards

### ISSUE THREAD

**Issue by abernicchia-heroku** [cybertec-postgresql/pgwatch2#770]
it happened recently, before this link worked, now it appears to be missing https://www.cybertec-postgresql.com/wp-content/uploads/2020/11/CYBERTEC_RGB_300x80px.png, probably it worth adding the image to the pgwatch2 repo instead of using an external link

**Comment by pashagolub** [comment]
Thanks for pointing this out! Will fix it!
