### ISSUE TITLE
Adding new db to monitor with database name empty

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#79]
Hello,
When i add a new database to monitor, without filling the database name (for it to add all the db prefixed with the dbname) then, only 2 database are added : 
postgres and pgwatch2 (this db does not exists)

but the existing dbs are not added...

Thanks

**Comment by kmoppel** [comment]
Hi! I could not replicate the issue :/...are you sure the connect string was the correct one? Could anyone else try it out also?

**Comment by vitabaks** [comment]
Hi! @kmoppel 

I have the same problem...

This db does not exists:
![default](https://user-images.githubusercontent.com/37010174/41594192-3b47e604-73cb-11e8-9000-ee7c576c0c9f.png)

> ERRO main: could not start metric gathering for DB "deb136_pgwatch2" due to connection problem: pq: database "pgwatch2" does not exist
> ERRO main: could not start metric gathering for DB "deb136_pgwatch2_grafana" due to connection problem: pq: database "pgwatch2_grafana" does not exist


And my databases were not added.
(I'm interested in auto-adding new databases)
__
pgwatch2 latest version

**Comment by pmpetit** [comment]
the connection string is the good one, because with the same connection string, if i set the good dbname, then it is added without problem.

**Comment by kmoppel** [comment]
Thanks for the extra info - now I got it! Indeed a bug that my old test setup didn't allow to discover :( Fixed now in master only with 3e7638074e64bf379a858e7650a20e0aea1e47f0 so please re-build/deploy to use.

**Comment by pmpetit** [comment]
Thanks.
Is the image docker already updated ?

**Comment by vitabaks** [comment]
@kmoppel 
I manually update the web py, and it's working for me!

But...
if create a new database, and i need to add my new database of manually?

**Comment by kmoppel** [comment]
@pmpetit I've now updated the cybertec/pgwatch2:latest image, non-root version will follow soon...

**Comment by kmoppel** [comment]
@vitabaks hmm, I think I see what you mean....you mean if once enabled pgwatch2 would automatically monitor for new DBs and start monitoring them automatically?

**Comment by vitabaks** [comment]
@kmoppel 
Yes.
I would like to have an auto-discovery function for new databases.

__
Sorry for my english.
I use a translator...

**Comment by kmoppel** [comment]
No worries:) Created a new "enhancement"  ticket for that feature  - https://github.com/cybertec-postgresql/pgwatch2/issues/82
