### ISSUE TITLE
graphite for storing metrics

### ISSUE THREAD

**Issue by bchazalet** [cybertec-postgresql/pgwatch2#8]
pgwatch2 looks really useful, and I am keen on using it. We're already gathering metrics into Graphite within my company and I'd like to ask if you think one can easily swap influxDB by Graphite in your setup.

I am not asking you to implement it :), I'm just asking if you think that would be an easy thing to do (and I might even have a go at it myself, even though I have never written anything in go).

Thanks!

**Comment by internetuser2008** [comment]
Any idea how to resolve UDP error?
Running pgw2 from laptop virtualbox with docker-toolbox.
I can see its reading table information and etc, but its not plotting the graph on main view.

ERRO MetricsFetcher: failed to fetch metrics for  VM locks dial tcp: lookup mysqlsand02.dev 10.0.#.#:53: read udp 172.17.0.2:58351->10.0.#.#:53: i/o timeout
2017/03/10 17:42:56 17:42:56.954 ERRO DBExecRead: dial tcp: lookup mysqlsand02.dev.on 10.0.#.3:53: read udp 172.17.0.2:48288->10.0.#.#:53: i/o timeout

**Comment by HuanRuan** [comment]
Very good tool - easy and useful, thank you. I'm trying to make a small change and build it myself, but got the following errors about $GOPATH. Is this something that needs to be set in the Dockerfile?

```
package github.com/lib/pq: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/op/go-logging: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/jmoiron/sqlx: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/influxdata/influxdb/client/v2: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/jessevdk/go-flags: cannot download, $GOPATH not set. For more details see: go help gopath
pgwatch2.go:7:2: cannot find package "github.com/influxdata/influxdb/client/v2" in any of:
        /usr/lib/golang/src/github.com/influxdata/influxdb/client/v2 (from $GOROOT)
        ($GOPATH not set)
pgwatch2.go:8:2: cannot find package "github.com/jessevdk/go-flags" in any of:
        /usr/lib/golang/src/github.com/jessevdk/go-flags (from $GOROOT)
        ($GOPATH not set)
pgwatch2.go:9:2: cannot find package "github.com/jmoiron/sqlx" in any of:
        /usr/lib/golang/src/github.com/jmoiron/sqlx (from $GOROOT)
        ($GOPATH not set)
pgwatch2.go:10:2: cannot find package "github.com/lib/pq" in any of:
        /usr/lib/golang/src/github.com/lib/pq (from $GOROOT)
        ($GOPATH not set)
pgwatch2.go:11:2: cannot find package "github.com/op/go-logging" in any of:
        /usr/lib/golang/src/github.com/op/go-logging (from $GOROOT)
        ($GOPATH not set)
```

**Comment by kmoppel** [comment]
@bchazalet Hi! An interesting idea actually! And after looking quickly into Graphite documentation I think it's doable but needs quite some coding indeed as the data modeling there is not really row based as in InfluxDB. So let's keep the issue open and maybe someone can contribute. I'm a bit busy myself currently:)

**Comment by kmoppel** [comment]
@internetuser2008 Hi! Seems the issue is really at network/docker level there, pgwatch can't even connect - can't help there. Cheers

**Comment by leonartambunan** [comment]
@internetuser2008, port 53 is usually used for DNS resolution.
Suggest u to map your "mysqlsand02.dev" to its IP address in /etc/hosts (*nix) or C:\windows\system32\drivers\etc\hosts (win)

**Comment by kmoppel** [comment]
New image supporting Graphite pushed. Needs manual setup though, default Docker image uses still Influx...
