### ISSUE TITLE
failed to determine PG version on scalefield image & psutil related metrics missing 

### ISSUE THREAD

**Issue by SanjeevChoubey** [cybertec-postgresql/pgwatch2#801]
When running pgwathc2 with scalefield, we are getting failed to determine PG version and then few metrics are not available like get_psutil_cpu()

![image](https://github.com/cybertec-postgresql/pgwatch2/assets/31409038/17d8e1e6-e2f5-4140-9b7f-355210374546)

**Comment by pashagolub** [comment]
This issue should be open in @cybertec-postgresql/scalefield
