### ISSUE TITLE
pgbouncer stats : failed to fetch pg version for  test_pgbouncer pgbouncer_stats

### ISSUE THREAD

**Issue by Ashishveer0710** [cybertec-postgresql/pgwatch2#814]
I am getting failed to fetch pg version for  test_pgbouncer pgbouncer_stats pq: invalid command 'SET lock_timeout TO '100ms';show version', use SHOW HELP;

After doing some research , I found that this issue is being fixed in pgwatch2.go file but I am unable to locate this file .

Please guide how to proceed ahead.

**Comment by pashagolub** [comment]
Hello

What version you're using?

**Comment by pashagolub** [comment]
And please describe how you define monitored database and what version of pg_bouncer is

**Comment by Ashishveer0710** [comment]
[weblogic@heeng-hgarg ~]$ pgbouncer --version
PgBouncer 1.23.1


Postgres version : 16 

Unique name : test_pgbouncer 
DB type: pgbouncer
port: 6432 
dbname : test 
user: pgwatch2
preset-configs : pgbouncer 

I am making the conenction directly on the pgwatch2 webui . All other dashboards are working as per expectation but pgbouncer_stats table in not getting populated.

**Comment by pashagolub** [comment]
Thanks. And what is the version of pgwatch2 binary?

**Comment by Ashishveer0710** [comment]
[weblogic@heeng-mpal pgwatch2]$ rpm -qi pgwatch2
Name        : pgwatch2
Epoch       : 0
**Version     : 1.9.0**

**Comment by Ashishveer0710** [comment]
There are few grafana dashboards which are not loading and giving " this panel is angular deprecated and needs migration"
. Will using the latest release will fix this issue on grafana version 11.2?

**Comment by pashagolub** [comment]
The latest Grafana version supported is 10.4

**Comment by Ashishveer0710** [comment]
ok thanks .. I got the query answered. thanks for your support .Closing this now.
