### ISSUE TITLE
Could not determine instance version, reporting as 'down': pq: unrecognized configuration parameter "lock_timeout" - Postgres 9.2.24

### ISSUE THREAD

**Issue by markosutic** [cybertec-postgresql/pgwatch2#819]
Hello,

We have very PostgreSQL 9.2.24 cluster and would like to use pgwatch2 for monitoring. 
Github page mentions "Supports monitoring PG versions 9.0 to 16 out of the box.".

Monitoring is not working and I see errors in the log:
`pgwatch2[18775]: 2024/09/11 15:27:09 ERRO setInstanceUpDownState: [postgres_corp_dml_objects:instance_up] could not determine instance version, reporting as 'down': pq: unrecognized configuration parameter "lock_timeout"`

Probably this part specifies how lock_timeout will be used:
https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/pgwatch2.go#L734-L740

Connection pooling feature is used for pgwatch2:
```
# systemctl status pgwatch2
● pgwatch2.service - PGWatch2
   Loaded: loaded (/etc/systemd/system/pgwatch2.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/pgwatch2.service.d
           └─override.conf, required.conf
   Active: active (running) since Wed 2024-09-25 07:16:38 UTC; 1h 33min ago
 Main PID: 733 (pgwatch2-daemon)
    Tasks: 8
   Memory: 13.8M
   CGroup: /system.slice/pgwatch2.service
           └─733 /usr/bin/pgwatch2-daemon --datastore=prometheus --prometheus-port=9199 --add-real-dbname=true --host=127.0.0.1 --port=5432 --dbname=postgres --conn-pooling=true
```

Please check and share info if we can do something to workaround issue.

Thanks

**Comment by pashagolub** [comment]
Thanks for pointing this out. We are currently not planning to spend time to re-add compatibility for EOL PostgreSQL versions where feature development has broken this support. You are welcome [to contact Cybertec](https://www.cybertec-postgresql.com/en/contact/) for a paid support though.
