### ISSUE TITLE
Why aren't tables with '_realtime' suffix created as hypertables when using TimescaleDB?

### ISSUE THREAD

**Issue by kayform** [cybertec-postgresql/pgwatch2#826]
Hi there,

I hope you're doing well!

I have a question regarding the use of TimescaleDB. I noticed that tables with the suffix '_realtime' are not being created as hypertables. Could you please explain the reason behind this or if there's a specific design choice for this behavior?

Thank you

**Comment by pashagolub** [comment]
Hello.

pgwatch2 is in maintenance mode. We are not work on it anymore. Please, switch to [pgwatch v3](https://github.com/cybertec-postgresql/pgwatch/) as soon as possible.

Realtime tables suppose to hold very short amount of data for a short period of time. There is no any need in hypertables for those tables.
