### ISSUE TITLE
The checksums file published has errors

### ISSUE THREAD

**Issue by rbauduin** [cybertec-postgresql/pgwatch2#827]
It is not possible to use the checksums file as is because an additional space is present in the filenames in the checksums file.
It also prevents automatic validation with https://github.com/asfaload/asfald, a tool I'm working on (I discovered the problem that way ;-) )

**Comment by pashagolub** [comment]
Hello. Thanks for noticing. This is probably the bug of [goreleaser](https://github.com/goreleaser/goreleaser).
