### ISSUE TITLE
pgwatch2 and pg_stat_kcache

### ISSUE THREAD

**Issue by vitabaks** [cybertec-postgresql/pgwatch2#89]
Hi!

Did you plan to use pgwatch2 with pg_stat_kcache for gather statistics about physical disk access and CPU consumption done by backends?

Thanks!

**Comment by kmoppel** [comment]
Hi! Currently no plans...would ideally only want to support contrib extensions. But it's not hard to add it of course - main trouble would be installing the extension on the "to be monitrered" server side...so let's keep it open as a feature request. All PRs welcome :)

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.
