### ISSUE TITLE
WEBUI doesnt add database to monitored_db table

### ISSUE THREAD

**Issue by marielcherkassky** [cybertec-postgresql/pgwatch2#90]
Hi,
I'm trying to install pgwatch2 without using docker and I'm facing a few difficulties that I would like to get help with.
So I installed grafana and influxdb and I did all the steps until step 4.2 -  Configure DB-s to monitor from "/dbs" page. When I run the ui and I try to add new databases to be monitored nothing happens. In the log of the webui I see the next record is added : 
`172.16.207.129 - - [15/Jul/2018:10:10:58] "POST /dbs HTTP/1.1" 200 17331 "http://172.24.180.17:8080/dbs" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
2018-07-15 10:10:58,247 INFO 9615 172.16.207.129 - - [15/Jul/2018:10:10:58] "POST /dbs HTTP/1.1" 200 17331 "http://172.24.180.17:8080/dbs" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Sa`

And I dont see anything inside the postgresql table : 

> pgwatch2=# select count(*) from monitored_db;
 count 
     0
(1 row)

Inside the log of the postgres database I dont see any insert statement(I'm logging all statements). Moreover, in the web.py file I configured only the next settings : 
`# Postgres
    parser.add_argument('-H', '--host', help='Pgwatch2 Config DB host',
                        default=(os.getenv('PW2_PGHOST') or 'localhost'))
    parser.add_argument('-p', '--port', help='Pgwatch2 Config DB port',
                        default=(os.getenv('PW2_PGPORT') or 5432), type=int)
    parser.add_argument('-d', '--database', help='Pgwatch2 Config DB name',
                        default=(os.getenv('PW2_PGDATABASE') or 'pgwatch2'))
    parser.add_argument('-U', '--user', help='Pgwatch2 Config DB username',
                        default=(os.getenv('PW2_PGUSER') or 'pgwatch2'))
    parser.add_argument('--password', help='Pgwatch2 Config DB password',
                        default=(os.getenv('PW2_PGPASSWORD') or 'xyz'))
    parser.add_argument('--pg-require-ssl', help='Pgwatch2 Config DB SSL connection only', action='store_true',
                        default=(os.getenv('PW2_PGSSL') or False))
    # Influx
    parser.add_argument('--influx-host', help='InfluxDB host',
                        default=(os.getenv('PW2_IHOST') or 'localhost'))
    parser.add_argument('--influx-port', help='InfluxDB port',
                        default=(os.getenv('PW2_IPORT') or '8086'))
    parser.add_argument('--influx-user', help='InfluxDB username',
                        default=(os.getenv('PW2_IUSER') or 'pgwatch2'))
    parser.add_argument('--influx-password', help='InfluxDB password',
                        default=(os.getenv('PW2_IPASSWORD') or 'pgwatch2'))
    parser.add_argument('--influx-database', help='InfluxDB database',
                        default=(os.getenv('PW2_IDATABASE') or 'pgwatch2'))
    parser.add_argument('--influx-require-ssl', action='store_true',
                        help='Use SSL for InfluxDB', default=(os.getenv('PW2_ISSL') or False))`

I used the password in the instructions...
Any idea why I cant add any database to be monitored via the ui ? Just to make sure, I'm stuck on step 4.2 and didnt continue forward.

Help,Mariel.

**Comment by kmoppel** [comment]
Closed as stale

**Comment by marielcherkassky** [comment]
Sorry for the delay, it didn't work in the end..

**Comment by kmoppel** [comment]
@marielcherkassky Ok I see - feel free to re-open if you have some details that I could use for debugging.
