### ISSUE TITLE
*** glibc detected *** postgres: pgwatch2

### ISSUE THREAD

**Issue by mridude23** [cybertec-postgresql/pgwatch2#93]
Hi,

We had a recent crash of one Postgres system and the crash appears to be related to something that pgwatch2 was running at that time. Do you have any ideas what could have gone wrong? Seems to be related to pgwatch2 but I'm open to any ideas.

Version: CentOS release 6.8
Pgwatch is running on a different server and is only querying this one, which is one of many servers with tens of databases. The queries have a 20s timeout setup.

After the messages below, the server entered in recovery mode.

I'm pasting the full log error below (quite long unfotunately):
*** glibc detected *** postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT: double free or corruption (!prev): 0x0000000001db4470 ***
======= Backtrace: =========
/lib64/libc.so.6[0x38f2075f3e]
/lib64/libc.so.6[0x38f2078dd0]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecStoreMinimalTuple+0x89)[0x5c5229]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(tuplestore_gettupleslot+0x3a)[0x7d686a]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x5d71d4]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecScan+0x2a2)[0x5c4732]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x1e8)[0x5bd408]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecHashJoin+0x2a5)[0x5cef25]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x168)[0x5bd388]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(standard_ExecutorRun+0xd2)[0x5bbc52]
/usr/pgsql-9.5/lib/pg_stat_statements.so(+0x448b)[0x7f445903e48b]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(fmgr_sql+0x8cf)[0x5c7b4f]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x7b1a99]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecMakeTableFunctionResult+0x167)[0x5c3aa7]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x5d7432]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecScan+0x187)[0x5c4617]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x1e8)[0x5bd408]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x5ca0fd]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecAgg+0x578)[0x5cb418]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x128)[0x5bd348]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x5d99ac]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecScan+0x187)[0x5c4617]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x1c8)[0x5bd3e8]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecSort+0xf9)[0x5d9059]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x148)[0x5bd368]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecLimit+0xa8)[0x5d1d38]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x90)[0x5bd2b0]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecAppend+0x19)[0x5c8699]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x288)[0x5bd4a8]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x5ca0fd]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecAgg+0x578)[0x5cb418]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(ExecProcNode+0x128)[0x5bd348]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(standard_ExecutorRun+0xd2)[0x5bbc52]
/usr/pgsql-9.5/lib/pg_stat_statements.so(+0x448b)[0x7f445903e48b]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x6be447]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(PortalRun+0x188)[0x6bf608]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x6bc3ee]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(PostgresMain+0xd35)[0x6bda55]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(PostmasterMain+0x1885)[0x663df5]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT(main+0x7a8)[0x5f5618]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x38f201ed1d]
postgres: pgwatch2 database 10.10.XXX.XXX(49132) SELECT[0x4676a9]
======= Memory map: ========
00400000-009d1000 r-xp 00000000 08:03 32905469                           /usr/pgsql-9.5/bin/postgres
00bd1000-00bde000 rw-p 005d1000 08:03 32905469                           /usr/pgsql-9.5/bin/postgres
00bde000-00c2d000 rw-p 00000000 00:00 0
01c27000-01c6e000 rw-p 00000000 00:00 0
01c6e000-09a5b000 rw-p 00000000 00:00 0
38f1800000-38f1820000 r-xp 00000000 08:03 19399065                       /lib64/ld-2.12.so
38f1a1f000-38f1a20000 r--p 0001f000 08:03 19399065                       /lib64/ld-2.12.so
38f1a20000-38f1a21000 rw-p 00020000 08:03 19399065                       /lib64/ld-2.12.so
38f1a21000-38f1a22000 rw-p 00000000 00:00 0
38f1c00000-38f1c02000 r-xp 00000000 08:03 19399068                       /lib64/libdl-2.12.so
38f1c02000-38f1e02000 ---p 00002000 08:03 19399068                       /lib64/libdl-2.12.so
38f1e02000-38f1e03000 r--p 00002000 08:03 19399068                       /lib64/libdl-2.12.so
38f1e03000-38f1e04000 rw-p 00003000 08:03 19399068                       /lib64/libdl-2.12.so
38f2000000-38f218a000 r-xp 00000000 08:03 19399066                       /lib64/libc-2.12.so
38f218a000-38f238a000 ---p 0018a000 08:03 19399066                       /lib64/libc-2.12.so
38f238a000-38f238e000 r--p 0018a000 08:03 19399066                       /lib64/libc-2.12.so
38f238e000-38f2390000 rw-p 0018e000 08:03 19399066                       /lib64/libc-2.12.so
38f2390000-38f2394000 rw-p 00000000 00:00 0
38f2400000-38f2417000 r-xp 00000000 08:03 19399075                       /lib64/libpthread-2.12.so
38f2417000-38f2617000 ---p 00017000 08:03 19399075                       /lib64/libpthread-2.12.so
38f2617000-38f2618000 r--p 00017000 08:03 19399075                       /lib64/libpthread-2.12.so
38f2618000-38f2619000 rw-p 00018000 08:03 19399075                       /lib64/libpthread-2.12.so
38f2619000-38f261d000 rw-p 00000000 00:00 0
38f2800000-38f2807000 r-xp 00000000 08:03 19399076                       /lib64/librt-2.12.so
38f2807000-38f2a06000 ---p 00007000 08:03 19399076                       /lib64/librt-2.12.so
38f2a06000-38f2a07000 r--p 00006000 08:03 19399076                       /lib64/librt-2.12.so
38f2a07000-38f2a08000 rw-p 00007000 08:03 19399076                       /lib64/librt-2.12.so
38f2c00000-38f2c15000 r-xp 00000000 08:03 19399073                       /lib64/libz.so.1.2.3
38f2c15000-38f2e14000 ---p 00015000 08:03 19399073                       /lib64/libz.so.1.2.3
38f2e14000-38f2e15000 r--p 00014000 08:03 19399073                       /lib64/libz.so.1.2.3
38f2e15000-38f2e16000 rw-p 00015000 08:03 19399073                       /lib64/libz.so.1.2.3
38f3000000-38f3083000 r-xp 00000000 08:03 19399074                       /lib64/libm-2.12.so
38f3083000-38f3282000 ---p 00083000 08:03 19399074                       /lib64/libm-2.12.so
38f3282000-38f3283000 r--p 00082000 08:03 19399074                       /lib64/libm-2.12.so
38f3283000-38f3284000 rw-p 00083000 08:03 19399074                       /lib64/libm-2.12.so
38f3400000-38f341d000 r-xp 00000000 08:03 19399084                       /lib64/libselinux.so.1
38f341d000-38f361c000 ---p 0001d000 08:03 19399084                       /lib64/libselinux.so.1
38f361c000-38f361d000 r--p 0001c000 08:03 19399084                       /lib64/libselinux.so.1
38f361d000-38f361e000 rw-p 0001d000 08:03 19399084                       /lib64/libselinux.so.1
38f361e000-38f361f000 rw-p 00000000 00:00 0
38f3c00000-38f3c0c000 r-xp 00000000 08:03 19399071                       /lib64/libpam.so.0.82.2
38f3c0c000-38f3e0c000 ---p 0000c000 08:03 19399071                       /lib64/libpam.so.0.82.2
38f3e0c000-38f3e0d000 r--p 0000c000 08:03 19399071                       /lib64/libpam.so.0.82.2
38f3e0d000-38f3e0e000 rw-p 0000d000 08:03 19399071                       /lib64/libpam.so.0.82.2
38f4400000-38f4416000 r-xp 00000000 08:03 19399083                       /lib64/libresolv-2.12.so
38f4416000-38f4616000 ---p 00016000 08:03 19399083                       /lib64/libresolv-2.12.so
38f4616000-38f4617000 r--p 00016000 08:03 19399083                       /lib64/libresolv-2.12.so
38f4617000-38f4618000 rw-p 00017000 08:03 19399083                       /lib64/libresolv-2.12.so
38f4618000-38f461a000 rw-p 00000000 00:00 0
38f4800000-38f4803000 r-xp 00000000 08:03 19399095                       /lib64/libplds4.so
38f4803000-38f4a02000 ---p 00003000 08:03 19399095                       /lib64/libplds4.so
38f4a02000-38f4a03000 r--p 00002000 08:03 19399095                       /lib64/libplds4.so
38f4a03000-38f4a04000 rw-p 00003000 08:03 19399095                       /lib64/libplds4.so
38f5000000-38f5026000 r-xp 00000000 08:03 31985794                       /usr/lib64/libnssutil3.so
38f5026000-38f5225000 ---p 00026000 08:03 31985794                       /usr/lib64/libnssutil3.so
38f5225000-38f522b000 r--p 00025000 08:03 31985794                       /usr/lib64/libnssutil3.so
38f522b000-38f522c000 rw-p 0002b000 08:03 31985794                       /usr/lib64/libnssutil3.so
38f5400000-38f5439000 r-xp 00000000 08:03 19398766                       /lib64/libnspr4.so
38f5439000-38f5639000 ---p 00039000 08:03 19398766                       /lib64/libnspr4.so
38f5639000-38f563a000 r--p 00039000 08:03 19398766                       /lib64/libnspr4.so
38f563a000-38f563c000 rw-p 0003a000 08:03 19398766                       /lib64/libnspr4.so
38f563c000-38f563e000 rw-p 00000000 00:00 0
38f5800000-38f5937000 r-xp 00000000 08:03 31985795                       /usr/lib64/libnss3.so
38f5937000-38f5b37000 ---p 00137000 08:03 31985795                       /usr/lib64/libnss3.so
38f5b37000-38f5b3c000 r--p 00137000 08:03 31985795                       /usr/lib64/libnss3.so
38f5b3c000-38f5b3e000 rw-p 0013c000 08:03 31985795                       /usr/lib64/libnss3.so
38f5b3e000-38f5b40000 rw-p 00000000 00:00 0
38f5c00000-38f5c04000 r-xp 00000000 08:03 19399094                       /lib64/libplc4.so
38f5c04000-38f5e03000 ---p 00004000 08:03 19399094                       /lib64/libplc4.so
38f5e03000-38f5e04000 r--p 00003000 08:03 19399094                       /lib64/libplc4.so
38f5e04000-38f5e05000 rw-p 00004000 08:03 19399094                       /lib64/libplc4.so
38f6800000-38f6802000 r-xp 00000000 08:03 19399069                       /lib64/libfreebl3.so
38f6802000-38f6a01000 ---p 00002000 08:03 19399069                       /lib64/libfreebl3.so
38f6a01000-38f6a02000 r--p 00001000 08:03 19399069                       /lib64/libfreebl3.so
38f6a02000-38f6a03000 rw-p 00002000 08:03 19399069                       /lib64/libfreebl3.so
38f6c00000-38f6dba000 r-xp 00000000 08:03 31984768                       /usr/lib64/libcrypto.so.1.0.1e
38f6dba000-38f6fb9000 ---p 001ba000 08:03 31984768                       /usr/lib64/libcrypto.so.1.0.1e
38f6fb9000-38f6fd4000 r--p 001b9000 08:03 31984768                       /usr/lib64/libcrypto.so.1.0.1e
38f6fd4000-38f6fe0000 rw-p 001d4000 08:03 31984768                       /usr/lib64/libcrypto.so.1.0.1e
38f6fe0000-38f6fe4000 rw-p 00000000 00:00 0
38f7000000-38f7149000 r-xp 00000000 08:03 31985792                       /usr/lib64/libxml2.so.2.7.6
38f7149000-38f7348000 ---p 00149000 08:03 31985792                       /usr/lib64/libxml2.so.2.7.6
38f7348000-38f7352000 rw-p 00148000 08:03 31985792                       /usr/lib64/libxml2.so.2.7.6
38f7352000-38f7353000 rw-p 00000000 00:00 0
38f7800000-38f7807000 r-xp 00000000 08:03 19399070                       /lib64/libcrypt-2.12.so
38f7807000-38f7a07000 ---p 00007000 08:03 19399070                       /lib64/libcrypt-2.12.so
38f7a07000-38f7a08000 r--p 00007000 08:03 19399070                       /lib64/libcrypt-2.12.so
38f7a08000-38f7a09000 rw-p 00008000 08:03 19399070                       /lib64/libcrypt-2.12.so
38f7a09000-38f7a37000 rw-p 00000000 00:00 0
38f8800000-38f8803000 r-xp 00000000 08:03 19399087                       /lib64/libcom_err.so.2.1
38f8803000-38f8a02000 ---p 00003000 08:03 19399087                       /lib64/libcom_err.so.2.1
38f8a02000-38f8a03000 r--p 00002000 08:03 19399087                       /lib64/libcom_err.so.2.1
38f8a03000-38f8a04000 rw-p 00003000 08:03 19399087                       /lib64/libcom_err.so.2.1
38f9000000-38f9028000 r-xp 00000000 08:03 31985806                       /usr/lib64/libsmime3.so
38f9028000-38f9227000 ---p 00028000 08:03 31985806                       /usr/lib64/libsmime3.so
38f9227000-38f922c000 r--p 00027000 08:03 31985806                       /usr/lib64/libsmime3.so
38f922c000-38f922d000 rw-p 0002c000 08:03 31985806                       /usr/lib64/libsmime3.so
38f9800000-38f983e000 r-xp 00000000 08:03 31983620                       /usr/lib64/libssl3.so
38f983e000-38f9a3e000 ---p 0003e000 08:03 31983620                       /usr/lib64/libssl3.so
38f9a3e000-38f9a41000 r--p 0003e000 08:03 31983620                       /usr/lib64/libssl3.so
38f9a41000-38f9a42000 rw-p 00041000 08:03 31983620                       /usr/lib64/libssl3.so
38f9a42000-38f9a43000 rw-p 00000000 00:00 0
38f9c00000-38f9c02000 r-xp 00000000 08:03 19399082                       /lib64/libkeyutils.so.1.3
38f9c02000-38f9e01000 ---p 00002000 08:03 19399082                       /lib64/libkeyutils.so.1.3
38f9e01000-38f9e02000 r--p 00001000 08:03 19399082                       /lib64/libkeyutils.so.1.3
38f9e02000-38f9e03000 rw-p 00002000 08:03 19399082                       /lib64/libkeyutils.so.1.3
38fa000000-38fa041000 r-xp 00000000 08:03 19398744                       /lib64/libgssapi_krb5.so.2.2
38fa041000-38fa241000 ---p 00041000 08:03 19398744                       /lib64/libgssapi_krb5.so.2.2
38fa241000-38fa242000 r--p 00041000 08:03 19398744                       /lib64/libgssapi_krb5.so.2.2
38fa242000-38fa244000 rw-p 00042000 08:03 19398744                       /lib64/libgssapi_krb5.so.2.2
38fa800000-38fa829000 r-xp 00000000 08:03 19399086                       /lib64/libk5crypto.so.3.1
38fa829000-38faa29000 ---p 00029000 08:03 19399086                       /lib64/libk5crypto.so.3.1
38faa29000-38faa2a000 r--p 00029000 08:03 19399086                       /lib64/libk5crypto.so.3.1
38faa2a000-38faa2b000 rw-p 0002a000 08:03 19399086                       /lib64/libk5crypto.so.3.1
38faa2b000-38faa2c000 rw-p 00000000 00:00 0
38fac00000-38facdb000 r-xp 00000000 08:03 19399088                       /lib64/libkrb5.so.3.3
38facdb000-38faedb000 ---p 000db000 08:03 19399088                       /lib64/libkrb5.so.3.3
38faedb000-38faee5000 r--p 000db000 08:03 19399088                       /lib64/libkrb5.so.3.3
38faee5000-38faee7000 rw-p 000e5000 08:03 19399088                       /lib64/libkrb5.so.3.3
38fb000000-38fb00a000 r-xp 00000000 08:03 19399085                       /lib64/libkrb5support.so.0.1
38fb00a000-38fb209000 ---p 0000a000 08:03 19399085                       /lib64/libkrb5support.so.0.1
38fb209000-38fb20a000 r--p 00009000 08:03 19399085                       /lib64/libkrb5support.so.0.1
38fb20a000-38fb20b000 rw-p 0000a000 08:03 19399085                       /lib64/libkrb5support.so.0.1
38fc400000-38fc462000 r-xp 00000000 08:03 31985789                       /usr/lib64/libssl.so.1.0.1e
38fc462000-38fc661000 ---p 00062000 08:03 31985789                       /usr/lib64/libssl.so.1.0.1e
38fc661000-38fc665000 r--p 00061000 08:03 31985789                       /usr/lib64/libssl.so.1.0.1e
38fc665000-38fc66c000 rw-p 00065000 08:03 31985789                       /usr/lib64/libssl.so.1.0.1e
38fdc00000-38fdc19000 r-xp 00000000 08:03 31984802                       /usr/lib64/libsasl2.so.2.0.23
38fdc19000-38fde18000 ---p 00019000 08:03 31984802                       /usr/lib64/libsasl2.so.2.0.23
38fde18000-38fde19000 r--p 00018000 08:03 31984802                       /usr/lib64/libsasl2.so.2.0.23
38fde19000-38fde1a000 rw-p 00019000 08:03 31984802                       /usr/lib64/libsasl2.so.2.0.23
38fe000000-38fe00e000 r-xp 00000000 08:03 19399103                       /lib64/liblber-2.4.so.2.10.3
38fe00e000-38fe20d000 ---p 0000e000 08:03 19399103                       /lib64/liblber-2.4.so.2.10.3
38fe20d000-38fe20e000 r--p 0000d000 08:03 19399103                       /lib64/liblber-2.4.so.2.10.3
38fe20e000-38fe20f000 rw-p 0000e000 08:03 19399103                       /lib64/liblber-2.4.so.2.10.3
38fec00000-38fec4d000 r-xp 00000000 08:03 19399104                       /lib64/libldap-2.4.so.2.10.3
38fec4d000-38fee4d000 ---p 0004d000 08:03 19399104                       /lib64/libldap-2.4.so.2.10.3
38fee4d000-38fee4f000 r--p 0004d000 08:03 19399104                       /lib64/libldap-2.4.so.2.10.3
38fee4f000-38fee51000 rw-p 0004f000 08:03 19399104                       /lib64/libldap-2.4.so.2.10.3
7f4448000000-7f4448021000 rw-p 00000000 00:00 0
7f4448021000-7f444c000000 ---p 00000000 00:00 0
7f444fb6b000-7f444fb81000 r-xp 00000000 08:03 19399079                   /lib64/libgcc_s-4.4.7-20120601.so.1
7f444fb81000-7f444fd80000 ---p 00016000 08:03 19399079                   /lib64/libgcc_s-4.4.7-20120601.so.1
7f444fd80000-7f444fd81000 rw-p 00015000 08:03 19399079                   /lib64/libgcc_s-4.4.7-20120601.so.1
7f444fd81000-7f444ff68000 rw-p 00000000 00:00 0
7f444ff68000-7f444ff75000 r-xp 00000000 08:03 19398688                   /lib64/libnss_files-2.12.so
7f444ff75000-7f4450174000 ---p 0000d000 08:03 19398688                   /lib64/libnss_files-2.12.so
7f4450174000-7f4450175000 r--p 0000c000 08:03 19398688                   /lib64/libnss_files-2.12.so
7f4450175000-7f4450176000 rw-p 0000d000 08:03 19398688                   /lib64/libnss_files-2.12.so
7f4450184000-7f445903a000 rw-s 00000000 00:04 509499815                  /dev/zero (deleted)
7f445903a000-7f4459042000 r-xp 00000000 08:03 32507761                   /usr/pgsql-9.5/lib/pg_stat_statements.so
7f4459042000-7f4459241000 ---p 00008000 08:03 32507761                   /usr/pgsql-9.5/lib/pg_stat_statements.so
7f4459241000-7f4459242000 rw-p 00007000 08:03 32507761                   /usr/pgsql-9.5/lib/pg_stat_statements.so
7f4459242000-7f445f0d5000 r--p 00000000 08:03 31982260                   /usr/lib/locale/locale-archive
7f445f0d5000-7f445f0e2000 rw-p 00000000 00:00 0
7f445f0e2000-7f445f0fa000 r-xp 00000000 08:03 19399067                   /lib64/libaudit.so.1.0.0
7f445f0fa000-7f445f2f9000 ---p 00018000 08:03 19399067                   /lib64/libaudit.so.1.0.0
7f445f2f9000-7f445f2fb000 r--p 00017000 08:03 19399067                   /lib64/libaudit.so.1.0.0
7f445f2fb000-7f445f306000 rw-p 00019000 08:03 19399067                   /lib64/libaudit.so.1.0.0
7f445f306000-7f445f30a000 rw-p 00000000 00:00 0
7f445f315000-7f445f316000 rw-p 00000000 00:00 0
7f445f316000-7f445f317000 rw-s 00000000 00:10 509499818                  /dev/shm/PostgreSQL.1226764494
7f445f317000-7f445f318000 rw-s 00000000 00:04 236322817                  /SYSV0052e2c1 (deleted)
7f445f318000-7f445f319000 rw-p 00000000 00:00 0
7ffea1de2000-7ffea1df7000 rw-p 00000000 00:00 0                          [stack]
7ffea1df8000-7ffea1df9000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
< 2018-07-19 21:49:18.315 JST >LOG:  server process (PID 103681) was terminated by signal 6: Aborted
< 2018-07-19 21:49:18.315 JST >DETAIL:  Failed process was running:
        with q_data as (
          select
            (extract(epoch from now()) * 1e9)::int8 as epoch_ns,
            queryid::text as tag_queryid,
            max(ltrim(regexp_replace(query, E'[ \\t\\n\\r]+' , ' ', 'g')))::varchar(16000) as tag_query,
            sum(s.calls)::int8 as calls,
            sum(s.total_time)::double precision as total_time,
            sum(shared_blks_hit)::int8 as shared_blks_hit,
            sum(shared_blks_read)::int8 as shared_blks_read,
            sum(shared_blks_written)::int8 as shared_blks_written,
            sum(temp_blks_read)::int8 as temp_blks_read,
            sum(temp_blks_written)::int8 as temp_blks_written,
            sum(blk_read_time)::double precision as blk_read_time,
            sum(blk_write_time)::double precision as blk_write_time
          from
            public.get_stat_statements() s
          where
            calls > 5
            and total_time > 0
            and dbid = (select oid from pg_database where datname = current_database())
            and not upper(s.query) like any (array['DEALLOCATE%', 'SET %', 'RESET %', 'BEGIN%', 'BEGIN;',
              'COMMIT%', 'END%', 'ROLLBACK%', 'SHOW%'])
          group by
            queryi
< 2018-07-19 21:49:18.315 JST >LOG:  terminating any other active server processes
< 2018-07-19 21:49:18.315 JST >WARNING:  terminating connection because of crash of another server process
< 2018-07-19 21:49:18.315 JST >DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.

Thanks.

**Comment by mridude23** [comment]
Hi all,

It happened again. Anyone have any ideas?

**Comment by kmoppel** [comment]
Hi! Hmm...interesting. Haven't seen it myself before...but seems the root cause is some memory shortage / overflow: https://community.pivotal.io/s/article/Greenplum-Postmaster-Resets-with-Error-PID-terminated-by-signal-6-Aborted
In short upgrading to a newer GLIBC (thus Postgres version) could help...at least to probably give a nicer error message:) Will try to do it asap. In the meantime maybe one could try adding more RAM...

**Comment by mridude23** [comment]
Hi @kmoppel, 

I left it like that a few days and 2 days ago I increased the resources a LOT. Seems that in fact this was the issue, my bad of not doing this the first time. I was receiving mixed signals from the server, like the error above, an application doing tens of connections for no apparent reason, server going into recovery randomly so it was kind of fooling me. :)

I would say this can be closed as it seems the tunning applied is working as expected.

Thanks for pointing out the memory issue.
