### ISSUE TITLE
[question:] pg_statements report

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#95]
Hello,
I do not understand how you can graph metrics about statements during the day, because in the pg_stat_statments extension, there is no date , just the top 5000 queries...
![image](https://user-images.githubusercontent.com/4059185/43205129-f1b7dcf0-9022-11e8-90eb-ce12a0bf91ac.png)

Do you calculate something base on the influxdb collection ?
thanks

**Comment by kmoppel** [comment]
Hi! The way how all the tools do it, is to store a timestamp every time we take a snapshot out of the pg_stat_statements. Then later one can easily calculate the deltas and get the top queries.

**Comment by kmoppel** [comment]
Btw, the way to get the deltas easily on Influx (our default metrics storage engine) is to use the non_negative_derivative() function in Grafana: https://docs.influxdata.com/influxdb/v1.6/query_language/functions#non-negative-derivative

**Comment by pmpetit** [comment]
thanks
