### ISSUE TITLE
Grafana Dashboards and Datasource missing 

### ISSUE THREAD

**Issue by peterneave** [cybertec-postgresql/pgwatch2#96]
I was running pgWatch from the within a docker container (hosted on Rancer OS) and I was getting inconsistent behavior. Most of the time the datasources and dashboards failed to load in Grafana. Occasionally it all works fine.
For comparison, I was running pgWatch2 reliability on Docker on Ubuntu Host - no issue with Grafana dashboard initialization.

In the end, I had to bash into the container and run pgwatch2/bootstrap/set_up_grafana_dashboards.sh manually. I suspect that Postgres is up but Grafana has not done it's schema initialization yet.

Here is my pgWatch2 logs:
```
2018/07/27 04:27:34 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2018/07/27 04:27:39 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2018/07/27 04:27:44 ERRO InitAndTestInfluxConnection: SHOW DATABASES failed, retrying in 5s (max 3x)... Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2018/07/27 04:27:49 CRIT main: Could not initialize InfluxDB Post http://localhost:8086/query?db=pgwatch2&params=null&q=SHOW+DATABASES: dial tcp 127.0.0.1:8086: connect: connection refused
2018/07/27 04:27:51 WARN InitAndTestInfluxConnection: Database 'pgwatch2' not found! Creating with 90 retention...
```

**Comment by kmoppel** [comment]
Hi! Hmm...weird stuff. And quite difficult to pinpoint the exact issue without relevant logs...when you find time to reproduce the issue would be very nice to get the relevant logs with "cat /var/log/supervisor/grafana_dashboard_setup*.log". Currently the "set_up_grafana_dashboards.sh" script already has a endless wait loop in it to give Postgres / Grafana time to start up so no real clues...but did a blind commit on the supervisord config that can't hurt also.

**Comment by peterneave** [comment]
/var/log/supervisor/grafana_dashboard_setup*.log is practically empty. I can see that set_up_grafana_dashboards should be waiting for postgres to start up but I wonder if Grafana isn't ready.
I'm going to leave it at that, as I can just manually run set_up_grafana_dashboards.sh. Like you said - weird stuff.

**Comment by kmoppel** [comment]
@peterneave ok, thanks for the feedback! will close then:)
