### ISSUE TITLE
About table_bloat_approx.sql, Help !

### ISSUE THREAD

**Issue by hp521yu** [cybertec-postgresql/pgwatch2#98]
Test environment: database PostgreSQL9.4.6, system Centos6.5 ,Installing without Docker

Error reporting when importing "table_bloat_approx.sql"

The error message is as follows:
[postgres@pmbs_db7 ~]$psql -f /postgres/pgwatch2/pgwatch2/sql/metric_fetching_helpera/table_bloat_approx.sql pgwatch2
CREATE EXTENSION
psql:/postgres/pgwatch2/pgwatch2/sqlmetric_fetching_helpers/table_bloat_approx.sql:18: ERROR: function public.pgstattuple_approx(oid) does not exist
LINE 10:       join lateral public.pgstattuple_ approx (c.oid) on true
                            ^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
paql: /postgres/pgwatch2/pwatch2/sql/metric_fetching_helpers/table_bloat_approx.sql:20: ERROR: function public.get_table_bloat_approx() does not exist
paql: /postgres/pgwatch2/pwatch2/sql/metric_fetching_helpers/table_bloat_approx.sql:21: ERROR: function public.get_table_bloat_approx() does not exist

I have a few questions to ask, thank you very much.
1, "table_bloat_approx.sql" meaning of this file
2, PostgreSQL10 does not have this error, but 9.4.6 has an error, can this error be resolved?
3, my production environment, do not use "table_bloat_approx.sql", can continue to monitor?

--------------------------------------------------中文版-------------------------------------------------------------------------------------------------
试验环境：数据库 PostgreSQL9.4.6、系统 Centos6.5 、非docker安装

导入 “table_bloat_approx.sql” 时报错

报错信息如下：
[postgres@pmbs_db7 ~]$psql -f /postgres/pgwatch2/pgwatch2/sql/metric_fetching_helpera/table_bloat_approx.sql pgwatch2
CREATE EXTENSION
psql:/postgres/pgwatch2/pgwatch2/sqlmetric_fetching_helpers/table_bloat_approx.sql:18: ERROR: function public.pgstattuple_approx(oid) does not exist
LINE 10:       join lateral public.pgstattuple_ approx (c.oid) on true
                            ^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
paql: /postgres/pgwatch2/pwatch2/sql/metric_fetching_helpers/table_bloat_approx.sql:20: ERROR: function public.get_table_bloat_approx() does not exist
paql: /postgres/pgwatch2/pwatch2/sql/metric_fetching_helpers/table_bloat_approx.sql:21: ERROR: function public.get_table_bloat_approx() does not exist

有几个问题请教各位，非常感谢
1、“table_bloat_approx.sql” 这个文件的意义
2、PostgreSQL10没有这个报错，但是9.4.6就有报错，这个报错能否解决？
3、我的生产环境，不使用“table_bloat_approx.sql”，可以继续监控么？

**Comment by pashagolub** [comment]
Hello. 

1. This file contains function definition which monitors bloating of a database.
2. `pgstattuple_approx` function appeared in 9.5 version, so this might be a bug. We'll check this thoroughly.
3. Sure. You may disable any metric you want.

**Comment by kmoppel** [comment]
Hi! Yes, exactly as @pashagolub explained...you can just ignore this message. I changed the code also though so it wouldn't throw an error but would silently continue.
