### ISSUE TITLE
Still about the error of pgwatch2 monitoring database

### ISSUE THREAD

**Issue by hp521yu** [cybertec-postgresql/pgwatch2#99]
System version: Centos6.5 monitoring database: PostgreSQL9.4.6
There was a problem importing the "table_bloat_approx.sql" file last time

The file import error message disappears, but some error messages will always appear as shown below when the "./pgwatch2" command is executed.

The prompts are as follows (currently only two are monitored):
```
[postgres@Lpgwatch2]$./pgwatch2 
2018/08/11 15:41:05 ERRO DetectConfigurationChanges: could not read configuration_hashes from monitored host: P9_31 , err: pq: column "pending_restart" does not exist
2018/08/11 15:41:05 ERRO MetricsFetcher: Failed to get SQL for metric 'table_bloat_approx_summary', version '9.4'
2018/08/11 15:41:05 ERRO MetricsFetcher: Failed to get SQL for metric 'table_bloat_approx_summary', version '9.4'
2018/08/11 15:41:05 ERRO DetectConfigurationChanges: could not read configuration_hashes from monitored host: P9_122 , err: pq: column "pending_restart" does not exist
2018/08/11 15:46:05 ERRO DetectConfigurationChanges: could not read configuration_hashes from monitored host: P9_31 , err: pq: column "pending_restart" does not exist
2018/08/11 15:46:05 ERRO DetectConfigurationChanges: could not read configuration_hashes from monitored host: P9_122 , err: pq: column "pending_restart" does not exist
2018/08/11 15:51:05 ERRO DetectConfigurationChanges: could not read configuration_hashes from monitored host: P9_31 , err: pq: column "pending_restart" does not exist
2018/08/11 15:51:05 ERRO DetectConfigurationChanges: could not read configuration_hashes from monitored host: P9_122 , err: pq: column "pending_restart" does not exist
```

Since our production environment database (thousands) is PostgreSQL 9.4.6

We are currently unable to upgrade to version 9.5 or higher.

Please help, how to handle this error in PostgreSQL 9.4.6.

Thank you for your help

**Comment by kmoppel** [comment]
Hi! I've now made the configuration tracking (pg_settings) query backwards compatible...so the last error lines should dissapear after you update the metrics as seen from the commit.
For the first error though I'd recommend to remove the "table_bloat_approx_summary" metric from the preset config...or to create a new preset config. Nothing to fix there on code level. Cheers
